# generated by n64split
.section .rodata
.include "macros.inc"
.include "ultra64/gbi.inc"
.include "special_presets.inc"

bowser_2_seg7_texture_07000000: # 0x07000000 - 0x07000800
.incbin "levels/bowser_2/0.rgba16"

bowser_2_seg7_vertex_07000800: # 0x07000800 - 0x07000900
vertex   1176,    784,  -2837,   6612,    678,  0xFF, 0xFF, 0xFF, 0xFF
vertex   2838,   1229,  -1175,   7634,    990,  0xFF, 0xFF, 0xFF, 0xFF
vertex   2838,    784,  -1175,   7634,    678,  0xFF, 0xFF, 0xFF, 0xFF
vertex   1176,    784,   2838,   1502,    678,  0xFF, 0xFF, 0xFF, 0xFF
vertex   1176,   1229,   2838,   1502,    990,  0xFF, 0xFF, 0xFF, 0xFF
vertex  -1175,   1229,   2838,   2524,    990,  0xFF, 0xFF, 0xFF, 0xFF
vertex   2838,    784,   1176,    480,    678,  0xFF, 0xFF, 0xFF, 0xFF
vertex  -1175,    784,   2838,   2524,    678,  0xFF, 0xFF, 0xFF, 0xFF
vertex   2838,   1229,   1176,    480,    990,  0xFF, 0xFF, 0xFF, 0xFF
vertex  -2837,   1229,   1176,   3546,    990,  0xFF, 0xFF, 0xFF, 0xFF
vertex  -2837,    784,   1176,   3546,    678,  0xFF, 0xFF, 0xFF, 0xFF
vertex   2838,   1229,   1176,   8656,    990,  0xFF, 0xFF, 0xFF, 0xFF
vertex   2838,    784,   1176,   8656,    678,  0xFF, 0xFF, 0xFF, 0xFF
vertex      0,   -306,      0,   1502,    552,  0xFF, 0xFF, 0xFF, 0xFF
vertex  -1175,    784,   2838,   1246,    812,  0xFF, 0xFF, 0xFF, 0xFF
vertex  -2837,    784,   1176,   1756,    812,  0xFF, 0xFF, 0xFF, 0xFF

bowser_2_seg7_vertex_07000900: # 0x07000900 - 0x07000A00
vertex   1176,    784,  -2837,   6612,    678,  0xFF, 0xFF, 0xFF, 0xFF
vertex   1176,   1229,  -2837,   6612,    990,  0xFF, 0xFF, 0xFF, 0xFF
vertex   2838,   1229,  -1175,   7634,    990,  0xFF, 0xFF, 0xFF, 0xFF
vertex  -1175,    784,  -2837,   5590,    678,  0xFF, 0xFF, 0xFF, 0xFF
vertex  -1175,   1229,  -2837,   5590,    990,  0xFF, 0xFF, 0xFF, 0xFF
vertex  -2837,    784,  -1175,   4568,    678,  0xFF, 0xFF, 0xFF, 0xFF
vertex  -2837,   1229,  -1175,   4568,    990,  0xFF, 0xFF, 0xFF, 0xFF
vertex  -2837,    784,   1176,   3546,    678,  0xFF, 0xFF, 0xFF, 0xFF
vertex  -2837,   1229,   1176,   3546,    990,  0xFF, 0xFF, 0xFF, 0xFF
vertex  -2837,    784,   1176,   1756,    812,  0xFF, 0xFF, 0xFF, 0xFF
vertex  -2837,    784,  -1175,   2268,    812,  0xFF, 0xFF, 0xFF, 0xFF
vertex      0,   -306,      0,   2012,    552,  0xFF, 0xFF, 0xFF, 0xFF
vertex  -1175,    784,  -2837,   2778,    812,  0xFF, 0xFF, 0xFF, 0xFF
vertex      0,   -306,      0,   2524,    552,  0xFF, 0xFF, 0xFF, 0xFF
vertex   1176,    784,  -2837,   3290,    812,  0xFF, 0xFF, 0xFF, 0xFF
vertex      0,   -306,      0,   3034,    552,  0xFF, 0xFF, 0xFF, 0xFF

bowser_2_seg7_vertex_07000A00: # 0x07000A00 - 0x07000AA0
vertex   1176,    784,  -2837,   3290,    812,  0xFF, 0xFF, 0xFF, 0xFF
vertex   2838,    784,  -1175,   3800,    812,  0xFF, 0xFF, 0xFF, 0xFF
vertex      0,   -306,      0,   3546,    552,  0xFF, 0xFF, 0xFF, 0xFF
vertex   2838,    784,   1176,   4312,    812,  0xFF, 0xFF, 0xFF, 0xFF
vertex      0,   -306,      0,   4056,    552,  0xFF, 0xFF, 0xFF, 0xFF
vertex   2838,    784,   1176,    224,    812,  0xFF, 0xFF, 0xFF, 0xFF
vertex   1176,    784,   2838,    734,    812,  0xFF, 0xFF, 0xFF, 0xFF
vertex      0,   -306,      0,    480,    552,  0xFF, 0xFF, 0xFF, 0xFF
vertex  -1175,    784,   2838,   1246,    812,  0xFF, 0xFF, 0xFF, 0xFF
vertex      0,   -306,      0,    990,    552,  0xFF, 0xFF, 0xFF, 0xFF

bowser_2_seg7_vertex_07000AA0: # 0x07000AA0 - 0x07000BA0
vertex   2838,   1229,  -1175,   5298,  -4574,  0xAD, 0x10, 0x16, 0xFF
vertex   1703,   1229,    705,   3210,  -1892,  0xAD, 0x10, 0x16, 0xFF
vertex   2838,   1229,   1176,   4460,  -1222,  0xAD, 0x10, 0x16, 0xFF
vertex  -2837,   1229,  -1175,  -1782,  -4574,  0xAD, 0x10, 0x16, 0xFF
vertex   -704,   1229,  -1702,   1064,  -5326,  0xAD, 0x10, 0x16, 0xFF
vertex  -1175,   1229,  -2837,    882,  -6944,  0xAD, 0x10, 0x16, 0xFF
vertex  -2837,   1229,   1176,  -2620,  -1222,  0xAD, 0x10, 0x16, 0xFF
vertex  -1702,   1229,   -704,   -534,  -3904,  0xAD, 0x10, 0x16, 0xFF
vertex  -1702,   1229,    705,  -1036,  -1892,  0xAD, 0x10, 0x16, 0xFF
vertex    705,   1229,  -1702,   2824,  -5326,  0xAD, 0x10, 0x16, 0xFF
vertex   1176,   1229,  -2837,   3816,  -6944,  0xAD, 0x10, 0x16, 0xFF
vertex  -1175,   1229,   2838,  -1138,   1146,  0xAD, 0x10, 0x16, 0xFF
vertex   -704,   1229,   1703,   -148,   -470,  0xAD, 0x10, 0x16, 0xFF
vertex   1176,   1229,   2838,   1792,   1146,  0xAD, 0x10, 0x16, 0xFF
vertex    705,   1229,   1703,   1610,   -470,  0xAD, 0x10, 0x16, 0xFF
vertex   1703,   1229,   -704,   3714,  -3904,  0xAD, 0x10, 0x16, 0xFF

bowser_2_seg7_vertex_07000BA0: # 0x07000BA0 - 0x07000C30
vertex  -1418,   1229,    588,   3034,  -2076,  0xFD, 0x42, 0x34, 0xFF
vertex   -587,   1229,   1419,   5202,  -1178,  0xFD, 0x42, 0x34, 0xFF
vertex      0,   1229,      0,   3034,    990,  0xFD, 0x42, 0x34, 0xFF
vertex    588,   1229,   1419,   6100,    990,  0xFD, 0x42, 0x34, 0xFF
vertex   1419,   1229,    588,   5202,   3156,  0xFD, 0x42, 0x34, 0xFF
vertex  -1418,   1229,   -587,    866,  -1178,  0xFD, 0x42, 0x34, 0xFF
vertex   1419,   1229,   -587,   3034,   4054,  0xFD, 0x42, 0x34, 0xFF
vertex    588,   1229,  -1418,    866,   3156,  0xFD, 0x42, 0x34, 0xFF
vertex   -587,   1229,  -1418,      0,    990,  0xFD, 0x42, 0x34, 0xFF

bowser_2_seg7_vertex_07000C30: # 0x07000C30 - 0x07000D30
vertex   -704,   1229,   1703,      0,    850,  0xFD, 0x42, 0x34, 0xFF
vertex    705,   1229,   1703,   4568,  -1054,  0xFD, 0x42, 0x34, 0xFF
vertex    588,   1229,   1419,   3800,  -1820,  0xFD, 0x42, 0x34, 0xFF
vertex  -1702,   1229,    705,  -4630,  -1054,  0xFD, 0x42, 0x34, 0xFF
vertex  -1418,   1229,   -587,  -5450,  -5654,  0xFD, 0x42, 0x34, 0xFF
vertex  -1702,   1229,   -704,  -6534,  -5654,  0xFD, 0x42, 0x34, 0xFF
vertex   -587,   1229,  -1418,  -3862,  -9486,  0xFD, 0x42, 0x34, 0xFF
vertex   -704,   1229,  -1702,  -4628, -10252,  0xFD, 0x42, 0x34, 0xFF
vertex  -1418,   1229,    588,  -3862,  -1820,  0xFD, 0x42, 0x34, 0xFF
vertex    588,   1229,  -1418,      0, -11072,  0xFD, 0x42, 0x34, 0xFF
vertex    705,   1229,  -1702,      0, -12156,  0xFD, 0x42, 0x34, 0xFF
vertex   -587,   1229,   1419,      0,   -234,  0xFD, 0x42, 0x34, 0xFF
vertex   1703,   1229,    705,   6472,  -5652,  0xFD, 0x42, 0x34, 0xFF
vertex   1419,   1229,    588,   5388,  -5652,  0xFD, 0x42, 0x34, 0xFF
vertex   1703,   1229,   -704,   4568, -10252,  0xFD, 0x42, 0x34, 0xFF
vertex   1419,   1229,   -587,   3800,  -9486,  0xFD, 0x42, 0x34, 0xFF

glabel bowser_2_seg7_dl_07000D30 # 0x07000D30 - 0x07000E28
gsDPSetTextureImage G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, fire_09009800
gsDPLoadSync
gsDPLoadBlock 7, 0, 0, 0x3FF, 0x100
gsSPVertex bowser_2_seg7_vertex_07000800, 16, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  3,  4,  5, 0x0
gsSP1Triangle  6,  4,  3, 0x0
gsSP1Triangle  3,  5,  7, 0x0
gsSP1Triangle  6,  8,  4, 0x0
gsSP1Triangle  7,  5,  9, 0x0
gsSP1Triangle  7,  9, 10, 0x0
gsSP1Triangle  2, 11, 12, 0x0
gsSP1Triangle  2,  1, 11, 0x0
gsSP1Triangle 13, 14, 15, 0x0
gsSPVertex bowser_2_seg7_vertex_07000900, 16, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  3,  1,  0, 0x0
gsSP1Triangle  3,  4,  1, 0x0
gsSP1Triangle  5,  4,  3, 0x0
gsSP1Triangle  5,  6,  4, 0x0
gsSP1Triangle  7,  6,  5, 0x0
gsSP1Triangle  7,  8,  6, 0x0
gsSP1Triangle  9, 10, 11, 0x0
gsSP1Triangle 10, 12, 13, 0x0
gsSP1Triangle 12, 14, 15, 0x0
gsSPVertex bowser_2_seg7_vertex_07000A00, 10, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  1,  3,  4, 0x0
gsSP1Triangle  5,  6,  7, 0x0
gsSP1Triangle  6,  8,  9, 0x0
gsSPEndDisplayList

bowser_2_seg7_dl_07000E28: # 0x07000E28 - 0x07000ED0
gsDPSetTextureImage G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, fire_09003000
gsDPLoadSync
gsDPLoadBlock 7, 0, 0, 0x3FF, 0x100
gsSPVertex bowser_2_seg7_vertex_07000AA0, 16, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  3,  4,  5, 0x0
gsSP1Triangle  6,  7,  3, 0x0
gsSP1Triangle  3,  7,  4, 0x0
gsSP1Triangle  6,  8,  7, 0x0
gsSP1Triangle  5,  4,  9, 0x0
gsSP1Triangle  5,  9, 10, 0x0
gsSP1Triangle 11,  8,  6, 0x0
gsSP1Triangle 11, 12,  8, 0x0
gsSP1Triangle 11, 13, 14, 0x0
gsSP1Triangle 11, 14, 12, 0x0
gsSP1Triangle 10,  9, 15, 0x0
gsSP1Triangle  2,  1, 14, 0x0
gsSP1Triangle  0, 15,  1, 0x0
gsSP1Triangle  2, 14, 13, 0x0
gsSP1Triangle 10, 15,  0, 0x0
gsSPEndDisplayList

bowser_2_seg7_dl_07000ED0: # 0x07000ED0 - 0x07000F38
gsDPSetTextureImage G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, fire_09005800
gsDPLoadSync
gsDPLoadBlock 7, 0, 0, 0x3FF, 0x100
gsSPVertex bowser_2_seg7_vertex_07000BA0, 9, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  1,  3,  2, 0x0
gsSP1Triangle  3,  4,  2, 0x0
gsSP1Triangle  5,  0,  2, 0x0
gsSP1Triangle  6,  7,  2, 0x0
gsSP1Triangle  4,  6,  2, 0x0
gsSP1Triangle  8,  5,  2, 0x0
gsSP1Triangle  7,  8,  2, 0x0
gsSPEndDisplayList

bowser_2_seg7_dl_07000F38: # 0x07000F38 - 0x07000FE0
gsDPSetTextureImage G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, fire_09005000
gsDPLoadSync
gsDPLoadBlock 7, 0, 0, 0x3FF, 0x100
gsSPVertex bowser_2_seg7_vertex_07000C30, 16, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  3,  4,  5, 0x0
gsSP1Triangle  5,  4,  6, 0x0
gsSP1Triangle  5,  6,  7, 0x0
gsSP1Triangle  3,  8,  4, 0x0
gsSP1Triangle  7,  6,  9, 0x0
gsSP1Triangle  7,  9, 10, 0x0
gsSP1Triangle  0,  8,  3, 0x0
gsSP1Triangle  0, 11,  8, 0x0
gsSP1Triangle 12, 13,  2, 0x0
gsSP1Triangle 14, 13, 12, 0x0
gsSP1Triangle 12,  2,  1, 0x0
gsSP1Triangle  0,  2, 11, 0x0
gsSP1Triangle 10,  9, 15, 0x0
gsSP1Triangle 14, 15, 13, 0x0
gsSP1Triangle 10, 15, 14, 0x0
gsSPEndDisplayList

glabel bowser_2_seg7_dl_07000FE0 # 0x07000FE0 - 0x070010B0
gsDPPipeSync
gsSPSetOtherMode G_SETOTHERMODE_H, G_MDSFT_CYCLETYPE, 2, 0x00100000
gsSPSetOtherMode G_SETOTHERMODE_L, G_MDSFT_RENDERMODE, 29, 0xC8112078
gsSPSetOtherMode G_SETOTHERMODE_L, G_MDSFT_ZSRCSEL, 1, 0x00000000
gsDPSetFogColor 200, 50, 0, 255
gsSPFogPosition 960, 1000
gsSPSetGeometryMode G_FOG
gsDPSetCombineMode G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_COMBINED, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_COMBINED
gsSPClearGeometryMode G_LIGHTING
gsDPSetTile G_IM_FMT_RGBA, G_IM_SIZ_16b, 0, 0, G_TX_LOADTILE, 0, G_TX_WRAP | G_TX_NOMIRROR, G_TX_NOMASK, G_TX_NOLOD, G_TX_WRAP | G_TX_NOMIRROR, G_TX_NOMASK, G_TX_NOLOD
gsSPTexture -1, -1, 0, 0, 1
gsDPTileSync
gsDPSetTile G_IM_FMT_RGBA, G_IM_SIZ_16b, 8, 0, G_TX_RENDERTILE, 0, G_TX_WRAP | G_TX_NOMIRROR, 5, G_TX_NOLOD, G_TX_WRAP | G_TX_NOMIRROR, 5, G_TX_NOLOD
gsDPSetTileSize 0, 0, 0, 124, 124
gsSPDisplayList bowser_2_seg7_dl_07000D30
gsSPDisplayList bowser_2_seg7_dl_07000E28
gsSPDisplayList bowser_2_seg7_dl_07000ED0
gsSPDisplayList bowser_2_seg7_dl_07000F38
gsSPTexture -1, -1, 0, 0, 0
gsDPPipeSync
gsSPSetOtherMode G_SETOTHERMODE_H, G_MDSFT_CYCLETYPE, 2, 0x00000000
gsSPSetOtherMode G_SETOTHERMODE_L, G_MDSFT_RENDERMODE, 29, 0x00442078
gsSPClearGeometryMode G_FOG
gsDPSetCombineMode1Cycle G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsSPSetGeometryMode G_LIGHTING
gsSPEndDisplayList

bowser_2_seg7_vertex_070010B0: # 0x070010B0 - 0x070011B0
vertex   6546,   -511,   2618,   4910,    248,  0xFF, 0xFF, 0xFF, 0xFF
vertex   6480,  -3071,  -2776,   8112,    772,  0xFF, 0xFF, 0xFF, 0xFF
vertex   6480,   -511,  -2776,   8100,    232,  0xFF, 0xFF, 0xFF, 0xFF
vertex  -6545,   -511,  -2617,  17484,    232,  0xFF, 0xFF, 0xFF, 0xFF
vertex  -6545,  -3071,  -2617,  17472,    772,  0xFF, 0xFF, 0xFF, 0xFF
vertex  -6479,  -3071,   2777,  20664,    790,  0xFF, 0xFF, 0xFF, 0xFF
vertex  -6479,   -511,   2777,  20676,    248,  0xFF, 0xFF, 0xFF, 0xFF
vertex  -2776,   -511,  -6479,  14348,    220,  0xFF, 0xFF, 0xFF, 0xFF
vertex  -2617,  -3071,   6546,  23924,    800,  0xFF, 0xFF, 0xFF, 0xFF
vertex  -2617,   -511,   6546,  23930,    260,  0xFF, 0xFF, 0xFF, 0xFF
vertex  -2776,  -3071,  -6479,  14342,    762,  0xFF, 0xFF, 0xFF, 0xFF
vertex   2618,   -511,  -6545,  11236,    220,  0xFF, 0xFF, 0xFF, 0xFF
vertex   2618,  -3071,  -6545,  11240,    762,  0xFF, 0xFF, 0xFF, 0xFF
vertex  -2776,   -511,  -6479,    782,   1298,  0xFF, 0xFF, 0xFF, 0xFF
vertex   2777,   -511,   6480,  -1526,  -4090,  0xFF, 0xFF, 0xFF, 0xFF
vertex   6546,   -511,   2618,  -3092,  -2484,  0xFF, 0xFF, 0xFF, 0xFF

bowser_2_seg7_vertex_070011B0: # 0x070011B0 - 0x070012B0
vertex   6546,   -511,   2618,   4910,    248,  0xFF, 0xFF, 0xFF, 0xFF
vertex   6546,  -3071,   2618,   4924,    788,  0xFF, 0xFF, 0xFF, 0xFF
vertex   6480,  -3071,  -2776,   8112,    772,  0xFF, 0xFF, 0xFF, 0xFF
vertex   2777,   -511,   6480,   1658,    260,  0xFF, 0xFF, 0xFF, 0xFF
vertex   2777,  -3071,   6480,   1664,    800,  0xFF, 0xFF, 0xFF, 0xFF
vertex  -2617,   -511,   6546,  23930,    260,  0xFF, 0xFF, 0xFF, 0xFF
vertex  -2617,  -3071,   6546,  23924,    800,  0xFF, 0xFF, 0xFF, 0xFF
vertex   2777,  -3071,   6480,  27214,    800,  0xFF, 0xFF, 0xFF, 0xFF
vertex   2777,   -511,   6480,  27208,    260,  0xFF, 0xFF, 0xFF, 0xFF
vertex  -2776,   -511,  -6479,    782,   1298,  0xFF, 0xFF, 0xFF, 0xFF
vertex  -6545,   -511,  -2617,   2350,   -306,  0xFF, 0xFF, 0xFF, 0xFF
vertex  -6479,   -511,   2777,   2322,  -2550,  0xFF, 0xFF, 0xFF, 0xFF
vertex  -2617,   -511,   6546,    716,  -4116,  0xFF, 0xFF, 0xFF, 0xFF
vertex   2777,   -511,   6480,  -1526,  -4090,  0xFF, 0xFF, 0xFF, 0xFF
vertex   6546,   -511,   2618,  -3092,  -2484,  0xFF, 0xFF, 0xFF, 0xFF
vertex   6480,   -511,  -2776,  -3066,   -240,  0xFF, 0xFF, 0xFF, 0xFF

bowser_2_seg7_vertex_070012B0: # 0x070012B0 - 0x070012E0
vertex  -2776,   -511,  -6479,    782,   1298,  0xFF, 0xFF, 0xFF, 0xFF
vertex   6480,   -511,  -2776,  -3066,   -240,  0xFF, 0xFF, 0xFF, 0xFF
vertex   2618,   -511,  -6545,  -1460,   1326,  0xFF, 0xFF, 0xFF, 0xFF

bowser_2_seg7_vertex_070012E0: # 0x070012E0 - 0x070013E0
vertex  -3512,   -511,   -889,   -356,    984,  0xFD, 0x42, 0x34, 0xFF
vertex  -3159,   -511,   -886,   -360,    440,  0xFD, 0x42, 0x34, 0xFF
vertex  -3323,    399,  -1105,    -26,    692,  0xFD, 0x42, 0x34, 0xFF
vertex   1240,   -511,  -5279,   -356,    984,  0xFD, 0x42, 0x34, 0xFF
vertex   1593,   -511,  -5276,   -360,    440,  0xFD, 0x42, 0x34, 0xFF
vertex   1429,    399,  -5496,    -26,    692,  0xFD, 0x42, 0x34, 0xFF
vertex   1152,   -511,  -5616,    160,   1116,  0xFD, 0x42, 0x34, 0xFF
vertex   1732,   -511,  -5615,    158,    228,  0xFD, 0x42, 0x34, 0xFF
vertex   1344,   -511,  -5811,    458,    824,  0xFD, 0x42, 0x34, 0xFF
vertex  -3407,   -511,   3474,    458,    824,  0xFD, 0x42, 0x34, 0xFF
vertex  -3600,   -511,   3669,    160,   1116,  0xFD, 0x42, 0x34, 0xFF
vertex  -3322,    399,   3790,    -26,    692,  0xFD, 0x42, 0x34, 0xFF
vertex  -3511,   -511,   4006,   -356,    984,  0xFD, 0x42, 0x34, 0xFF
vertex  -3158,   -511,   4009,   -360,    440,  0xFD, 0x42, 0x34, 0xFF
vertex  -3019,   -511,   3670,    158,    228,  0xFD, 0x42, 0x34, 0xFF
vertex  -3021,   -511,  -1224,    158,    228,  0xFD, 0x42, 0x34, 0xFF

bowser_2_seg7_vertex_070013E0: # 0x070013E0 - 0x070014E0
vertex  -3021,   -511,  -1224,    158,    228,  0xFD, 0x42, 0x34, 0xFF
vertex  -3408,   -511,  -1420,    458,    824,  0xFD, 0x42, 0x34, 0xFF
vertex  -3323,    399,  -1105,    -26,    692,  0xFD, 0x42, 0x34, 0xFF
vertex  -3601,   -511,  -1226,    160,   1116,  0xFD, 0x42, 0x34, 0xFF
vertex  -3512,   -511,   -889,   -356,    984,  0xFD, 0x42, 0x34, 0xFF
vertex   4200,   -511,   -835,    160,   1116,  0xFD, 0x42, 0x34, 0xFF
vertex   4288,   -511,   -498,   -356,    984,  0xFD, 0x42, 0x34, 0xFF
vertex   4478,    399,   -715,    -26,    692,  0xFD, 0x42, 0x34, 0xFF
vertex   4392,   -511,  -1030,    458,    824,  0xFD, 0x42, 0x34, 0xFF
vertex   4642,   -511,   -495,   -360,    440,  0xFD, 0x42, 0x34, 0xFF
vertex   4780,   -511,   -834,    158,    228,  0xFD, 0x42, 0x34, 0xFF
vertex   2820,   -511,   2679,    160,   1116,  0xFD, 0x42, 0x34, 0xFF
vertex   2909,   -511,   3016,   -356,    984,  0xFD, 0x42, 0x34, 0xFF
vertex   3098,    399,   2799,    -26,    692,  0xFD, 0x42, 0x34, 0xFF
vertex   3262,   -511,   3019,   -360,    440,  0xFD, 0x42, 0x34, 0xFF
vertex   3400,   -511,   2680,    158,    228,  0xFD, 0x42, 0x34, 0xFF

bowser_2_seg7_vertex_070014E0: # 0x070014E0 - 0x070015E0
vertex   3013,   -511,   2484,    458,    824,  0xFD, 0x42, 0x34, 0xFF
vertex   2820,   -511,   2679,    160,   1116,  0xFD, 0x42, 0x34, 0xFF
vertex   3098,    399,   2799,    -26,    692,  0xFD, 0x42, 0x34, 0xFF
vertex   3400,   -511,   2680,    158,    228,  0xFD, 0x42, 0x34, 0xFF
vertex   -130,   -511,  -4068,    762,    860,  0xFD, 0x42, 0x34, 0xFF
vertex   -426,   -511,  -3769,    464,    564,  0xFD, 0x42, 0x34, 0xFF
vertex      0,   1229,  -3583,    278,    990,  0xFD, 0x42, 0x34, 0xFF
vertex   -290,   -511,  -3250,    -52,    700,  0xFD, 0x42, 0x34, 0xFF
vertex    253,   -511,  -3245,    -56,   1242,  0xFD, 0x42, 0x34, 0xFF
vertex    465,   -511,  -3767,    462,   1454,  0xFD, 0x42, 0x34, 0xFF
vertex   -126,   -511,   3113,    324,    450,  0xFD, 0x42, 0x34, 0xFF
vertex   -422,   -511,   3412,    326,    748,  0xFD, 0x42, 0x34, 0xFF
vertex      4,   1229,   3598,    632,    628,  0xFD, 0x42, 0x34, 0xFF
vertex   -286,   -511,   3931,    652,    938,  0xFD, 0x42, 0x34, 0xFF
vertex    256,   -511,   3936,    926,    670,  0xFD, 0x42, 0x34, 0xFF
vertex    469,   -511,   3415,    772,    304,  0xFD, 0x42, 0x34, 0xFF

bowser_2_seg7_vertex_070015E0: # 0x070015E0 - 0x070016A0
vertex   3453,   -511,   -484,    458,    824,  0xFD, 0x42, 0x34, 0xFF
vertex   3157,   -511,   -185,    160,   1116,  0xFD, 0x42, 0x34, 0xFF
vertex   3584,   1229,      0,    -26,    692,  0xFD, 0x42, 0x34, 0xFF
vertex   3293,   -511,    333,   -356,    984,  0xFD, 0x42, 0x34, 0xFF
vertex   3837,   -511,    338,   -360,    440,  0xFD, 0x42, 0x34, 0xFF
vertex   4049,   -511,   -183,    158,    228,  0xFD, 0x42, 0x34, 0xFF
vertex  -3714,   -511,   -484,   -516,    396,  0xFD, 0x42, 0x34, 0xFF
vertex  -4010,   -511,   -185,   -218,    692,  0xFD, 0x42, 0x34, 0xFF
vertex  -3583,   1229,      0,      0,    266,  0xFD, 0x42, 0x34, 0xFF
vertex  -3874,   -511,    333,    298,    556,  0xFD, 0x42, 0x34, 0xFF
vertex  -3118,   -511,   -183,   -216,   -198,  0xFD, 0x42, 0x34, 0xFF
vertex  -3330,   -511,    338,    302,     14,  0xFD, 0x42, 0x34, 0xFF

bowser_2_seg7_dl_070016A0: # 0x070016A0 - 0x07001788
gsDPSetTextureImage G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, bowser_2_seg7_texture_07000000
gsDPLoadSync
gsDPLoadBlock 7, 0, 0, 0x3FF, 0x100
gsSPVertex bowser_2_seg7_vertex_070010B0, 16, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  3,  4,  5, 0x0
gsSP1Triangle  3,  5,  6, 0x0
gsSP1Triangle  7,  4,  3, 0x0
gsSP1Triangle  6,  5,  8, 0x0
gsSP1Triangle  6,  8,  9, 0x0
gsSP1Triangle  7, 10,  4, 0x0
gsSP1Triangle 11, 10,  7, 0x0
gsSP1Triangle 11, 12, 10, 0x0
gsSP1Triangle  2, 12, 11, 0x0
gsSP1Triangle  2,  1, 12, 0x0
gsSP1Triangle 13, 14, 15, 0x0
gsSPVertex bowser_2_seg7_vertex_070011B0, 16, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  3,  1,  0, 0x0
gsSP1Triangle  3,  4,  1, 0x0
gsSP1Triangle  5,  6,  7, 0x0
gsSP1Triangle  5,  7,  8, 0x0
gsSP1Triangle  9, 10, 11, 0x0
gsSP1Triangle  9, 11, 12, 0x0
gsSP1Triangle  9, 12, 13, 0x0
gsSP1Triangle  9, 14, 15, 0x0
gsSPVertex bowser_2_seg7_vertex_070012B0, 3, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSPEndDisplayList

bowser_2_seg7_dl_07001788: # 0x07001788 - 0x07001930
gsDPSetTextureImage G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, fire_09005800
gsDPLoadSync
gsDPLoadBlock 7, 0, 0, 0x3FF, 0x100
gsSPVertex bowser_2_seg7_vertex_070012E0, 16, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  3,  4,  5, 0x0
gsSP1Triangle  6,  3,  5, 0x0
gsSP1Triangle  4,  7,  5, 0x0
gsSP1Triangle  7,  8,  5, 0x0
gsSP1Triangle  8,  6,  5, 0x0
gsSP1Triangle  9, 10, 11, 0x0
gsSP1Triangle 10, 12, 11, 0x0
gsSP1Triangle 12, 13, 11, 0x0
gsSP1Triangle 14,  9, 11, 0x0
gsSP1Triangle 13, 14, 11, 0x0
gsSP1Triangle  1, 15,  2, 0x0
gsSPVertex bowser_2_seg7_vertex_070013E0, 16, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  1,  3,  2, 0x0
gsSP1Triangle  3,  4,  2, 0x0
gsSP1Triangle  5,  6,  7, 0x0
gsSP1Triangle  8,  5,  7, 0x0
gsSP1Triangle  6,  9,  7, 0x0
gsSP1Triangle  9, 10,  7, 0x0
gsSP1Triangle 10,  8,  7, 0x0
gsSP1Triangle 11, 12, 13, 0x0
gsSP1Triangle 12, 14, 13, 0x0
gsSP1Triangle 14, 15, 13, 0x0
gsSPVertex bowser_2_seg7_vertex_070014E0, 16, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  3,  0,  2, 0x0
gsSP1Triangle  4,  5,  6, 0x0
gsSP1Triangle  5,  7,  6, 0x0
gsSP1Triangle  7,  8,  6, 0x0
gsSP1Triangle  8,  9,  6, 0x0
gsSP1Triangle  9,  4,  6, 0x0
gsSP1Triangle 10, 11, 12, 0x0
gsSP1Triangle 11, 13, 12, 0x0
gsSP1Triangle 13, 14, 12, 0x0
gsSP1Triangle 15, 10, 12, 0x0
gsSP1Triangle 14, 15, 12, 0x0
gsSPVertex bowser_2_seg7_vertex_070015E0, 12, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  1,  3,  2, 0x0
gsSP1Triangle  3,  4,  2, 0x0
gsSP1Triangle  4,  5,  2, 0x0
gsSP1Triangle  5,  0,  2, 0x0
gsSP1Triangle  6,  7,  8, 0x0
gsSP1Triangle  7,  9,  8, 0x0
gsSP1Triangle 10,  6,  8, 0x0
gsSP1Triangle 11, 10,  8, 0x0
gsSP1Triangle  9, 11,  8, 0x0
gsSPEndDisplayList

glabel bowser_2_seg7_dl_07001930 # 0x07001930 - 0x070019F0
gsDPPipeSync
gsSPSetOtherMode G_SETOTHERMODE_H, G_MDSFT_CYCLETYPE, 2, 0x00100000
gsSPSetOtherMode G_SETOTHERMODE_L, G_MDSFT_RENDERMODE, 29, 0xC8112078
gsSPSetOtherMode G_SETOTHERMODE_L, G_MDSFT_ZSRCSEL, 1, 0x00000000
gsDPSetFogColor 200, 50, 0, 255
gsSPFogPosition 960, 1000
gsSPSetGeometryMode G_FOG
gsDPSetCombineMode G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_COMBINED, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_COMBINED
gsSPClearGeometryMode G_LIGHTING
gsDPSetTile G_IM_FMT_RGBA, G_IM_SIZ_16b, 0, 0, G_TX_LOADTILE, 0, G_TX_WRAP | G_TX_NOMIRROR, G_TX_NOMASK, G_TX_NOLOD, G_TX_WRAP | G_TX_NOMIRROR, G_TX_NOMASK, G_TX_NOLOD
gsSPTexture -1, -1, 0, 0, 1
gsDPTileSync
gsDPSetTile G_IM_FMT_RGBA, G_IM_SIZ_16b, 8, 0, G_TX_RENDERTILE, 0, G_TX_WRAP | G_TX_NOMIRROR, 5, G_TX_NOLOD, G_TX_WRAP | G_TX_NOMIRROR, 5, G_TX_NOLOD
gsDPSetTileSize 0, 0, 0, 124, 124
gsSPDisplayList bowser_2_seg7_dl_070016A0
gsSPDisplayList bowser_2_seg7_dl_07001788
gsSPTexture -1, -1, 0, 0, 0
gsDPPipeSync
gsSPSetOtherMode G_SETOTHERMODE_H, G_MDSFT_CYCLETYPE, 2, 0x00000000
gsSPSetOtherMode G_SETOTHERMODE_L, G_MDSFT_RENDERMODE, 29, 0x00442078
gsSPClearGeometryMode G_FOG
gsDPSetCombineMode1Cycle G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsSPSetGeometryMode G_LIGHTING
gsSPEndDisplayList

glabel bowser_2_seg7_collision_lava # 0x070019F0 - 0x07001A66
# collision vertices
.hword 0x0040, 0x0008
.hword -2776, -1023, -6479
.hword -6545, -1023, -2617
.hword -6479, -1023,  2777
.hword  6480, -1023, -2776
.hword  2618, -1023, -6545
.hword -2617, -1023,  6546
.hword  6546, -1023,  2618
.hword  2777, -1023,  6480
# collision 0x01 lethal_lava
.hword 0x0001,    6
.hword    0,    1,    2
.hword    0,    3,    4
.hword    0,    2,    5
.hword    0,    6,    3
.hword    0,    7,    6
.hword    0,    5,    7
.hword 0x0041
# special objects  0x43
.hword 0x0043,    2 # add 2 special objects
special_object_10_byte /*preset*/ special_null_start, /*pos*/  0, 1229,     0, /*yaw*/ 128 # unused, probably an early way to set intial position
special_object_8_byte  /*preset*/ special_bowser,     /*pos*/ -8, 1229, -1418
.hword 0x0042

.balign 4 # 0x07001A66 - 0x07001A68

glabel bowser_2_seg7_collision_tilting_platform # 0x07001A68 - 0x07001BA0
# collision vertices
.hword 0x0040, 0x0012
.hword  1176,   784,  2838
.hword -1175,   784,  2838
.hword     0,  -306,     0
.hword  2838,   784,  1176
.hword  1176,  1229,  2838
.hword -1175,  1229,  2838
.hword     0,  1229,     0
.hword  2838,  1229,  1176
.hword -2837,  1229,  1176
.hword -2837,   784,  1176
.hword  2838,   784, -1175
.hword  2838,  1229, -1175
.hword  1176,   784, -2837
.hword  1176,  1229, -2837
.hword -1175,   784, -2837
.hword -2837,   784, -1175
.hword -1175,  1229, -2837
.hword -2837,  1229, -1175
# collision 0x00 normal
.hword 0x0000,   32
.hword    0,    1,    2
.hword    3,    0,    2
.hword    3,    4,    0
.hword    0,    5,    1
.hword    0,    4,    5
.hword    5,    4,    6
.hword    4,    7,    6
.hword    3,    7,    4
.hword    8,    5,    6
.hword    1,    5,    8
.hword    2,    1,    9
.hword    1,    8,    9
.hword   10,    3,    2
.hword   10,    7,    3
.hword    7,   11,    6
.hword   10,   11,    7
.hword   12,   10,    2
.hword   12,   11,   10
.hword   11,   13,    6
.hword   12,   13,   11
.hword   14,   12,    2
.hword   14,   13,   12
.hword   13,   16,    6
.hword   14,   16,   13
.hword   15,   14,    2
.hword   15,   16,   14
.hword   16,   17,    6
.hword   15,   17,   16
.hword    9,   15,    2
.hword    9,   17,   15
.hword   17,    8,    6
.hword    9,    8,   17
.hword 0x0041
.hword 0x0042
