#ifndef _MOVING_TEXTURE_H
#define _MOVING_TEXTURE_H

#include "types.h"

#define ROTATE_CLOCKWISE 0

enum MovingTextureIdList
{
    TEXTURE_WATER,
    TEXTURE_MIST,
    TEXTURE_JRB_WATER,
    TEXTURE_UNK_WATER,
    TEXTURE_LAVA,
    TEX_QUICKSAND_SSL,
    TEX_PYRAMID_SAND_SSL,
    TEX_YELLOW_TRI_TTC
};

extern f32 D_8032FFDC;

#endif /* _MOVING_TEXTURE_H */
