# --------------------------------------
# General Rules
# --------------------------------------

# obtain a list of segments from the *.c files in bin directory
TEXTURE_DIRS := textures/ipl3_raw

# NOTE: textures assume naming convention "texture.<encoding>.png" generates "texture.<encoding>"

IPL3_TEXTURE_FILES          := $(wildcard $(TEXTURE_DIR)/ipl3_raw/*.png)
IPL3_RAW_FILES              := $(addprefix $(BUILD_DIR)/,$(patsubst %.png,%,$(IPL3_TEXTURE_FILES)))
