# Super Mario 64 (J) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"
.include "globals.inc"

.section .text, "ax"

glabel func_8027DE30
/* 038E30 8027DE30 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 038E34 8027DE34 AFBF0014 */  sw    $ra, 0x14($sp)
/* 038E38 8027DE38 AFA40018 */  sw    $a0, 0x18($sp)
/* 038E3C 8027DE3C 0C0C9050 */  jal   osGetTime
/* 038E40 8027DE40 00000000 */   nop   
/* 038E44 8027DE44 3C0E8033 */  lui   $t6, %hi(D_8032CFB4) # $t6, 0x8033
/* 038E48 8027DE48 85CECFB4 */  lh    $t6, %lo(D_8032CFB4)($t6)
/* 038E4C 8027DE4C 8FB80018 */  lw    $t8, 0x18($sp)
/* 038E50 8027DE50 3C018034 */  lui   $at, %hi(D_8033B028)
/* 038E54 8027DE54 000E7880 */  sll   $t7, $t6, 2
/* 038E58 8027DE58 01EE7823 */  subu  $t7, $t7, $t6
/* 038E5C 8027DE5C 000F78C0 */  sll   $t7, $t7, 3
/* 038E60 8027DE60 01EE7821 */  addu  $t7, $t7, $t6
/* 038E64 8027DE64 000F78C0 */  sll   $t7, $t7, 3
/* 038E68 8027DE68 0018C8C0 */  sll   $t9, $t8, 3
/* 038E6C 8027DE6C 01F94021 */  addu  $t0, $t7, $t9
/* 038E70 8027DE70 00280821 */  addu  $at, $at, $t0
/* 038E74 8027DE74 AC22B028 */  sw    $v0, %lo(D_8033B028)($at)
/* 038E78 8027DE78 AC23B02C */  sw    $v1, -0x4fd4($at)
/* 038E7C 8027DE7C 8FA90018 */  lw    $t1, 0x18($sp)
/* 038E80 8027DE80 24010004 */  li    $at, 4
/* 038E84 8027DE84 15210010 */  bne   $t1, $at, .L8027DEC8
/* 038E88 8027DE88 00000000 */   nop   
/* 038E8C 8027DE8C 3C0A8033 */  lui   $t2, %hi(D_8032CFB4) # $t2, 0x8033
/* 038E90 8027DE90 854ACFB4 */  lh    $t2, %lo(D_8032CFB4)($t2)
/* 038E94 8027DE94 3C018033 */  lui   $at, %hi(D_8032CFB4) # $at, 0x8033
/* 038E98 8027DE98 394B0001 */  xori  $t3, $t2, 1
/* 038E9C 8027DE9C A42BCFB4 */  sh    $t3, %lo(D_8032CFB4)($at)
/* 038EA0 8027DEA0 3C0C8033 */  lui   $t4, %hi(D_8032CFB4) # $t4, 0x8033
/* 038EA4 8027DEA4 858CCFB4 */  lh    $t4, %lo(D_8032CFB4)($t4)
/* 038EA8 8027DEA8 3C018034 */  lui   $at, %hi(D_8033B020)
/* 038EAC 8027DEAC 000C6880 */  sll   $t5, $t4, 2
/* 038EB0 8027DEB0 01AC6823 */  subu  $t5, $t5, $t4
/* 038EB4 8027DEB4 000D68C0 */  sll   $t5, $t5, 3
/* 038EB8 8027DEB8 01AC6821 */  addu  $t5, $t5, $t4
/* 038EBC 8027DEBC 000D68C0 */  sll   $t5, $t5, 3
/* 038EC0 8027DEC0 002D0821 */  addu  $at, $at, $t5
/* 038EC4 8027DEC4 A420B020 */  sh    $zero, %lo(D_8033B020)($at)
.L8027DEC8:
/* 038EC8 8027DEC8 10000001 */  b     .L8027DED0
/* 038ECC 8027DECC 00000000 */   nop   
.L8027DED0:
/* 038ED0 8027DED0 8FBF0014 */  lw    $ra, 0x14($sp)
/* 038ED4 8027DED4 27BD0018 */  addiu $sp, $sp, 0x18
/* 038ED8 8027DED8 03E00008 */  jr    $ra
/* 038EDC 8027DEDC 00000000 */   nop   

glabel func_8027DEE0
/* 038EE0 8027DEE0 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 038EE4 8027DEE4 AFBF0014 */  sw    $ra, 0x14($sp)
/* 038EE8 8027DEE8 3C0E8033 */  lui   $t6, %hi(D_8032CFB4) # $t6, 0x8033
/* 038EEC 8027DEEC 85CECFB4 */  lh    $t6, %lo(D_8032CFB4)($t6)
/* 038EF0 8027DEF0 3C188034 */  lui   $t8, %hi(D_8033B020) # $t8, 0x8034
/* 038EF4 8027DEF4 2718B020 */  addiu $t8, %lo(D_8033B020) # addiu $t8, $t8, -0x4fe0
/* 038EF8 8027DEF8 000E7880 */  sll   $t7, $t6, 2
/* 038EFC 8027DEFC 01EE7823 */  subu  $t7, $t7, $t6
/* 038F00 8027DF00 000F78C0 */  sll   $t7, $t7, 3
/* 038F04 8027DF04 01EE7821 */  addu  $t7, $t7, $t6
/* 038F08 8027DF08 000F78C0 */  sll   $t7, $t7, 3
/* 038F0C 8027DF0C 01F8C821 */  addu  $t9, $t7, $t8
/* 038F10 8027DF10 AFB9001C */  sw    $t9, 0x1c($sp)
/* 038F14 8027DF14 8FA8001C */  lw    $t0, 0x1c($sp)
/* 038F18 8027DF18 85090000 */  lh    $t1, ($t0)
/* 038F1C 8027DF1C 29210008 */  slti  $at, $t1, 8
/* 038F20 8027DF20 1020000D */  beqz  $at, .L8027DF58
/* 038F24 8027DF24 00000000 */   nop   
/* 038F28 8027DF28 0C0C9050 */  jal   osGetTime
/* 038F2C 8027DF2C 00000000 */   nop   
/* 038F30 8027DF30 8FAA001C */  lw    $t2, 0x1c($sp)
/* 038F34 8027DF34 854B0000 */  lh    $t3, ($t2)
/* 038F38 8027DF38 000B60C0 */  sll   $t4, $t3, 3
/* 038F3C 8027DF3C 014C6821 */  addu  $t5, $t2, $t4
/* 038F40 8027DF40 ADA20048 */  sw    $v0, 0x48($t5)
/* 038F44 8027DF44 ADA3004C */  sw    $v1, 0x4c($t5)
/* 038F48 8027DF48 8FAE001C */  lw    $t6, 0x1c($sp)
/* 038F4C 8027DF4C 85CF0000 */  lh    $t7, ($t6)
/* 038F50 8027DF50 25F80001 */  addiu $t8, $t7, 1
/* 038F54 8027DF54 A5D80000 */  sh    $t8, ($t6)
.L8027DF58:
/* 038F58 8027DF58 10000001 */  b     .L8027DF60
/* 038F5C 8027DF5C 00000000 */   nop   
.L8027DF60:
/* 038F60 8027DF60 8FBF0014 */  lw    $ra, 0x14($sp)
/* 038F64 8027DF64 27BD0020 */  addiu $sp, $sp, 0x20
/* 038F68 8027DF68 03E00008 */  jr    $ra
/* 038F6C 8027DF6C 00000000 */   nop   

glabel func_8027DF70
/* 038F70 8027DF70 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 038F74 8027DF74 AFBF0014 */  sw    $ra, 0x14($sp)
/* 038F78 8027DF78 AFA40018 */  sw    $a0, 0x18($sp)
/* 038F7C 8027DF7C 8FAE0018 */  lw    $t6, 0x18($sp)
/* 038F80 8027DF80 15C00010 */  bnez  $t6, .L8027DFC4
/* 038F84 8027DF84 00000000 */   nop   
/* 038F88 8027DF88 3C0F8033 */  lui   $t7, %hi(D_8032CFB8) # $t7, 0x8033
/* 038F8C 8027DF8C 85EFCFB8 */  lh    $t7, %lo(D_8032CFB8)($t7)
/* 038F90 8027DF90 3C018033 */  lui   $at, %hi(D_8032CFB8) # $at, 0x8033
/* 038F94 8027DF94 39F80001 */  xori  $t8, $t7, 1
/* 038F98 8027DF98 A438CFB8 */  sh    $t8, %lo(D_8032CFB8)($at)
/* 038F9C 8027DF9C 3C198033 */  lui   $t9, %hi(D_8032CFB8) # $t9, 0x8033
/* 038FA0 8027DFA0 8739CFB8 */  lh    $t9, %lo(D_8032CFB8)($t9)
/* 038FA4 8027DFA4 3C018034 */  lui   $at, %hi(D_8033B022)
/* 038FA8 8027DFA8 00194080 */  sll   $t0, $t9, 2
/* 038FAC 8027DFAC 01194023 */  subu  $t0, $t0, $t9
/* 038FB0 8027DFB0 000840C0 */  sll   $t0, $t0, 3
/* 038FB4 8027DFB4 01194021 */  addu  $t0, $t0, $t9
/* 038FB8 8027DFB8 000840C0 */  sll   $t0, $t0, 3
/* 038FBC 8027DFBC 00280821 */  addu  $at, $at, $t0
/* 038FC0 8027DFC0 A420B022 */  sh    $zero, %lo(D_8033B022)($at)
.L8027DFC4:
/* 038FC4 8027DFC4 0C0C9050 */  jal   osGetTime
/* 038FC8 8027DFC8 00000000 */   nop   
/* 038FCC 8027DFCC 3C098033 */  lui   $t1, %hi(D_8032CFB8) # $t1, 0x8033
/* 038FD0 8027DFD0 8529CFB8 */  lh    $t1, %lo(D_8032CFB8)($t1)
/* 038FD4 8027DFD4 8FAB0018 */  lw    $t3, 0x18($sp)
/* 038FD8 8027DFD8 3C018034 */  lui   $at, %hi(D_8033B050)
/* 038FDC 8027DFDC 00095080 */  sll   $t2, $t1, 2
/* 038FE0 8027DFE0 01495023 */  subu  $t2, $t2, $t1
/* 038FE4 8027DFE4 000A50C0 */  sll   $t2, $t2, 3
/* 038FE8 8027DFE8 01495021 */  addu  $t2, $t2, $t1
/* 038FEC 8027DFEC 000A50C0 */  sll   $t2, $t2, 3
/* 038FF0 8027DFF0 000B60C0 */  sll   $t4, $t3, 3
/* 038FF4 8027DFF4 014C6821 */  addu  $t5, $t2, $t4
/* 038FF8 8027DFF8 002D0821 */  addu  $at, $at, $t5
/* 038FFC 8027DFFC AC22B050 */  sw    $v0, %lo(D_8033B050)($at)
/* 039000 8027E000 AC23B054 */  sw    $v1, -0x4fac($at)
/* 039004 8027E004 10000001 */  b     .L8027E00C
/* 039008 8027E008 00000000 */   nop   
.L8027E00C:
/* 03900C 8027E00C 8FBF0014 */  lw    $ra, 0x14($sp)
/* 039010 8027E010 27BD0018 */  addiu $sp, $sp, 0x18
/* 039014 8027E014 03E00008 */  jr    $ra
/* 039018 8027E018 00000000 */   nop   

glabel func_8027E01C
/* 03901C 8027E01C 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 039020 8027E020 AFBF0014 */  sw    $ra, 0x14($sp)
/* 039024 8027E024 3C0E8033 */  lui   $t6, %hi(D_8032CFB8) # $t6, 0x8033
/* 039028 8027E028 85CECFB8 */  lh    $t6, %lo(D_8032CFB8)($t6)
/* 03902C 8027E02C 3C188034 */  lui   $t8, %hi(D_8033B020) # $t8, 0x8034
/* 039030 8027E030 2718B020 */  addiu $t8, %lo(D_8033B020) # addiu $t8, $t8, -0x4fe0
/* 039034 8027E034 000E7880 */  sll   $t7, $t6, 2
/* 039038 8027E038 01EE7823 */  subu  $t7, $t7, $t6
/* 03903C 8027E03C 000F78C0 */  sll   $t7, $t7, 3
/* 039040 8027E040 01EE7821 */  addu  $t7, $t7, $t6
/* 039044 8027E044 000F78C0 */  sll   $t7, $t7, 3
/* 039048 8027E048 01F8C821 */  addu  $t9, $t7, $t8
/* 03904C 8027E04C AFB9001C */  sw    $t9, 0x1c($sp)
/* 039050 8027E050 8FA8001C */  lw    $t0, 0x1c($sp)
/* 039054 8027E054 85090002 */  lh    $t1, 2($t0)
/* 039058 8027E058 29210008 */  slti  $at, $t1, 8
/* 03905C 8027E05C 1020000D */  beqz  $at, .L8027E094
/* 039060 8027E060 00000000 */   nop   
/* 039064 8027E064 0C0C9050 */  jal   osGetTime
/* 039068 8027E068 00000000 */   nop   
/* 03906C 8027E06C 8FAA001C */  lw    $t2, 0x1c($sp)
/* 039070 8027E070 854B0002 */  lh    $t3, 2($t2)
/* 039074 8027E074 000B60C0 */  sll   $t4, $t3, 3
/* 039078 8027E078 014C6821 */  addu  $t5, $t2, $t4
/* 03907C 8027E07C ADA20088 */  sw    $v0, 0x88($t5)
/* 039080 8027E080 ADA3008C */  sw    $v1, 0x8c($t5)
/* 039084 8027E084 8FAE001C */  lw    $t6, 0x1c($sp)
/* 039088 8027E088 85CF0002 */  lh    $t7, 2($t6)
/* 03908C 8027E08C 25F80001 */  addiu $t8, $t7, 1
/* 039090 8027E090 A5D80002 */  sh    $t8, 2($t6)
.L8027E094:
/* 039094 8027E094 10000001 */  b     .L8027E09C
/* 039098 8027E098 00000000 */   nop   
.L8027E09C:
/* 03909C 8027E09C 8FBF0014 */  lw    $ra, 0x14($sp)
/* 0390A0 8027E0A0 27BD0020 */  addiu $sp, $sp, 0x20
/* 0390A4 8027E0A4 03E00008 */  jr    $ra
/* 0390A8 8027E0A8 00000000 */   nop   

glabel func_8027E0AC
/* 0390AC 8027E0AC 27BDFFA8 */  addiu $sp, $sp, -0x58
/* 0390B0 8027E0B0 AFBF0014 */  sw    $ra, 0x14($sp)
/* 0390B4 8027E0B4 AFA40058 */  sw    $a0, 0x58($sp)
/* 0390B8 8027E0B8 AFA5005C */  sw    $a1, 0x5c($sp)
/* 0390BC 8027E0BC AFA60060 */  sw    $a2, 0x60($sp)
/* 0390C0 8027E0C0 AFA70064 */  sw    $a3, 0x64($sp)
/* 0390C4 8027E0C4 8FAE0060 */  lw    $t6, 0x60($sp)
/* 0390C8 8027E0C8 8FAF0064 */  lw    $t7, 0x64($sp)
/* 0390CC 8027E0CC 8FB80058 */  lw    $t8, 0x58($sp)
/* 0390D0 8027E0D0 8FB9005C */  lw    $t9, 0x5c($sp)
/* 0390D4 8027E0D4 01D84023 */  subu  $t0, $t6, $t8
/* 0390D8 8027E0D8 01F9082B */  sltu  $at, $t7, $t9
/* 0390DC 8027E0DC 01014023 */  subu  $t0, $t0, $at
/* 0390E0 8027E0E0 01F94823 */  subu  $t1, $t7, $t9
/* 0390E4 8027E0E4 AFA90054 */  sw    $t1, 0x54($sp)
/* 0390E8 8027E0E8 1D000009 */  bgtz  $t0, .L8027E110
/* 0390EC 8027E0EC AFA80050 */   sw    $t0, 0x50($sp)
/* 0390F0 8027E0F0 05000003 */  bltz  $t0, .L8027E100
/* 0390F4 8027E0F4 00000000 */   nop   
/* 0390F8 8027E0F8 10000005 */  b     .L8027E110
/* 0390FC 8027E0FC 00000000 */   nop   
.L8027E100:
/* 039100 8027E100 240A0000 */  li    $t2, 0
/* 039104 8027E104 240B0000 */  li    $t3, 0
/* 039108 8027E108 AFAB0054 */  sw    $t3, 0x54($sp)
/* 03910C 8027E10C AFAA0050 */  sw    $t2, 0x50($sp)
.L8027E110:
/* 039110 8027E110 8FAC0068 */  lw    $t4, 0x68($sp)
/* 039114 8027E114 8FAD006C */  lw    $t5, 0x6c($sp)
/* 039118 8027E118 8FAE0058 */  lw    $t6, 0x58($sp)
/* 03911C 8027E11C 8FAF005C */  lw    $t7, 0x5c($sp)
/* 039120 8027E120 018EC023 */  subu  $t8, $t4, $t6
/* 039124 8027E124 01AF082B */  sltu  $at, $t5, $t7
/* 039128 8027E128 0301C023 */  subu  $t8, $t8, $at
/* 03912C 8027E12C 01AFC823 */  subu  $t9, $t5, $t7
/* 039130 8027E130 AFB9004C */  sw    $t9, 0x4c($sp)
/* 039134 8027E134 1F000009 */  bgtz  $t8, .L8027E15C
/* 039138 8027E138 AFB80048 */   sw    $t8, 0x48($sp)
/* 03913C 8027E13C 07000003 */  bltz  $t8, .L8027E14C
/* 039140 8027E140 00000000 */   nop   
/* 039144 8027E144 10000005 */  b     .L8027E15C
/* 039148 8027E148 00000000 */   nop   
.L8027E14C:
/* 03914C 8027E14C 24080000 */  li    $t0, 0
/* 039150 8027E150 24090000 */  li    $t1, 0
/* 039154 8027E154 AFA9004C */  sw    $t1, 0x4c($sp)
/* 039158 8027E158 AFA80048 */  sw    $t0, 0x48($sp)
.L8027E15C:
/* 03915C 8027E15C 3C07000F */  lui   $a3, (0x000F4240 >> 16) # lui $a3, 0xf
/* 039160 8027E160 34E74240 */  ori   $a3, (0x000F4240 & 0xFFFF) # ori $a3, $a3, 0x4240
/* 039164 8027E164 8FA40050 */  lw    $a0, 0x50($sp)
/* 039168 8027E168 8FA50054 */  lw    $a1, 0x54($sp)
/* 03916C 8027E16C 0C0C8CCA */  jal   __ll_mul
/* 039170 8027E170 24060000 */   li    $a2, 0
/* 039174 8027E174 AFA20018 */  sw    $v0, 0x18($sp)
/* 039178 8027E178 AFA3001C */  sw    $v1, 0x1c($sp)
/* 03917C 8027E17C 3C068033 */  lui   $a2, %hi(D_80334800) # $a2, 0x8033
/* 039180 8027E180 3C078033 */  lui   $a3, %hi(D_80334804) # $a3, 0x8033
/* 039184 8027E184 8CE74804 */  lw    $a3, %lo(D_80334804)($a3)
/* 039188 8027E188 8CC64800 */  lw    $a2, %lo(D_80334800)($a2)
/* 03918C 8027E18C 8FA5001C */  lw    $a1, 0x1c($sp)
/* 039190 8027E190 0C0C8C8A */  jal   __ull_div
/* 039194 8027E194 8FA40018 */   lw    $a0, 0x18($sp)
/* 039198 8027E198 AFA20020 */  sw    $v0, 0x20($sp)
/* 03919C 8027E19C AFA30024 */  sw    $v1, 0x24($sp)
/* 0391A0 8027E1A0 8FA50024 */  lw    $a1, 0x24($sp)
/* 0391A4 8027E1A4 8FA40020 */  lw    $a0, 0x20($sp)
/* 0391A8 8027E1A8 24060000 */  li    $a2, 0
/* 0391AC 8027E1AC 0C0C8CCA */  jal   __ll_mul
/* 0391B0 8027E1B0 24070003 */   li    $a3, 3
/* 0391B4 8027E1B4 AFA20028 */  sw    $v0, 0x28($sp)
/* 0391B8 8027E1B8 AFA3002C */  sw    $v1, 0x2c($sp)
/* 0391BC 8027E1BC 8FA5002C */  lw    $a1, 0x2c($sp)
/* 0391C0 8027E1C0 8FA40028 */  lw    $a0, 0x28($sp)
/* 0391C4 8027E1C4 24060000 */  li    $a2, 0
/* 0391C8 8027E1C8 0C0C8C8A */  jal   __ull_div
/* 0391CC 8027E1CC 240703E8 */   li    $a3, 1000
/* 0391D0 8027E1D0 246B001E */  addiu $t3, $v1, 0x1e
/* 0391D4 8027E1D4 2D61001E */  sltiu $at, $t3, 0x1e
/* 0391D8 8027E1D8 01606025 */  move  $t4, $t3
/* 0391DC 8027E1DC AFAC0044 */  sw    $t4, 0x44($sp)
/* 0391E0 8027E1E0 00415021 */  addu  $t2, $v0, $at
/* 0391E4 8027E1E4 3C07000F */  lui   $a3, (0x000F4240 >> 16) # lui $a3, 0xf
/* 0391E8 8027E1E8 34E74240 */  ori   $a3, (0x000F4240 & 0xFFFF) # ori $a3, $a3, 0x4240
/* 0391EC 8027E1EC 8FA40048 */  lw    $a0, 0x48($sp)
/* 0391F0 8027E1F0 8FA5004C */  lw    $a1, 0x4c($sp)
/* 0391F4 8027E1F4 0C0C8CCA */  jal   __ll_mul
/* 0391F8 8027E1F8 24060000 */   li    $a2, 0
/* 0391FC 8027E1FC AFA20018 */  sw    $v0, 0x18($sp)
/* 039200 8027E200 AFA3001C */  sw    $v1, 0x1c($sp)
/* 039204 8027E204 3C068033 */  lui   $a2, %hi(D_80334800) # $a2, 0x8033
/* 039208 8027E208 3C078033 */  lui   $a3, %hi(D_80334804) # $a3, 0x8033
/* 03920C 8027E20C 8CE74804 */  lw    $a3, %lo(D_80334804)($a3)
/* 039210 8027E210 8CC64800 */  lw    $a2, %lo(D_80334800)($a2)
/* 039214 8027E214 8FA5001C */  lw    $a1, 0x1c($sp)
/* 039218 8027E218 0C0C8C8A */  jal   __ull_div
/* 03921C 8027E21C 8FA40018 */   lw    $a0, 0x18($sp)
/* 039220 8027E220 AFA20020 */  sw    $v0, 0x20($sp)
/* 039224 8027E224 AFA30024 */  sw    $v1, 0x24($sp)
/* 039228 8027E228 8FA50024 */  lw    $a1, 0x24($sp)
/* 03922C 8027E22C 8FA40020 */  lw    $a0, 0x20($sp)
/* 039230 8027E230 24060000 */  li    $a2, 0
/* 039234 8027E234 0C0C8CCA */  jal   __ll_mul
/* 039238 8027E238 24070003 */   li    $a3, 3
/* 03923C 8027E23C AFA20028 */  sw    $v0, 0x28($sp)
/* 039240 8027E240 AFA3002C */  sw    $v1, 0x2c($sp)
/* 039244 8027E244 8FA5002C */  lw    $a1, 0x2c($sp)
/* 039248 8027E248 8FA40028 */  lw    $a0, 0x28($sp)
/* 03924C 8027E24C 24060000 */  li    $a2, 0
/* 039250 8027E250 0C0C8C8A */  jal   __ull_div
/* 039254 8027E254 240703E8 */   li    $a3, 1000
/* 039258 8027E258 246F001E */  addiu $t7, $v1, 0x1e
/* 03925C 8027E25C 2DE1001E */  sltiu $at, $t7, 0x1e
/* 039260 8027E260 01E06825 */  move  $t5, $t7
/* 039264 8027E264 AFAD0040 */  sw    $t5, 0x40($sp)
/* 039268 8027E268 00417021 */  addu  $t6, $v0, $at
/* 03926C 8027E26C 8FB80044 */  lw    $t8, 0x44($sp)
/* 039270 8027E270 2B010140 */  slti  $at, $t8, 0x140
/* 039274 8027E274 14200005 */  bnez  $at, .L8027E28C
/* 039278 8027E278 00000000 */   nop   
/* 03927C 8027E27C 24080000 */  li    $t0, 0
/* 039280 8027E280 2409013F */  li    $t1, 319
/* 039284 8027E284 AFA90064 */  sw    $t1, 0x64($sp)
/* 039288 8027E288 AFA80060 */  sw    $t0, 0x60($sp)
.L8027E28C:
/* 03928C 8027E28C 8FB90040 */  lw    $t9, 0x40($sp)
/* 039290 8027E290 2B210140 */  slti  $at, $t9, 0x140
/* 039294 8027E294 14200005 */  bnez  $at, .L8027E2AC
/* 039298 8027E298 00000000 */   nop   
/* 03929C 8027E29C 240A0000 */  li    $t2, 0
/* 0392A0 8027E2A0 240B013F */  li    $t3, 319
/* 0392A4 8027E2A4 AFAB006C */  sw    $t3, 0x6c($sp)
/* 0392A8 8027E2A8 AFAA0068 */  sw    $t2, 0x68($sp)
.L8027E2AC:
/* 0392AC 8027E2AC 8FAC0044 */  lw    $t4, 0x44($sp)
/* 0392B0 8027E2B0 8FAE0040 */  lw    $t6, 0x40($sp)
/* 0392B4 8027E2B4 018E082A */  slt   $at, $t4, $t6
/* 0392B8 8027E2B8 10200035 */  beqz  $at, .L8027E390
/* 0392BC 8027E2BC 00000000 */   nop   
/* 0392C0 8027E2C0 3C0F8034 */  lui   $t7, %hi(gDisplayListHead) # $t7, 0x8034
/* 0392C4 8027E2C4 8DEF9CFC */  lw    $t7, %lo(gDisplayListHead)($t7)
/* 0392C8 8027E2C8 3C018034 */  lui   $at, %hi(gDisplayListHead) # $at, 0x8034
/* 0392CC 8027E2CC 25ED0008 */  addiu $t5, $t7, 8
/* 0392D0 8027E2D0 AC2D9CFC */  sw    $t5, %lo(gDisplayListHead)($at)
/* 0392D4 8027E2D4 AFAF003C */  sw    $t7, 0x3c($sp)
/* 0392D8 8027E2D8 8FA8003C */  lw    $t0, 0x3c($sp)
/* 0392DC 8027E2DC 3C18E700 */  lui   $t8, 0xe700
/* 0392E0 8027E2E0 AD180000 */  sw    $t8, ($t0)
/* 0392E4 8027E2E4 8FA9003C */  lw    $t1, 0x3c($sp)
/* 0392E8 8027E2E8 AD200004 */  sw    $zero, 4($t1)
/* 0392EC 8027E2EC 3C198034 */  lui   $t9, %hi(gDisplayListHead) # $t9, 0x8034
/* 0392F0 8027E2F0 8F399CFC */  lw    $t9, %lo(gDisplayListHead)($t9)
/* 0392F4 8027E2F4 3C018034 */  lui   $at, %hi(gDisplayListHead) # $at, 0x8034
/* 0392F8 8027E2F8 272A0008 */  addiu $t2, $t9, 8
/* 0392FC 8027E2FC AC2A9CFC */  sw    $t2, %lo(gDisplayListHead)($at)
/* 039300 8027E300 AFB90038 */  sw    $t9, 0x38($sp)
/* 039304 8027E304 8FAC0038 */  lw    $t4, 0x38($sp)
/* 039308 8027E308 3C0BF700 */  lui   $t3, 0xf700
/* 03930C 8027E30C AD8B0000 */  sw    $t3, ($t4)
/* 039310 8027E310 97AE0076 */  lhu   $t6, 0x76($sp)
/* 039314 8027E314 8FB80038 */  lw    $t8, 0x38($sp)
/* 039318 8027E318 000E7C00 */  sll   $t7, $t6, 0x10
/* 03931C 8027E31C 01EE6825 */  or    $t5, $t7, $t6
/* 039320 8027E320 AF0D0004 */  sw    $t5, 4($t8)
/* 039324 8027E324 3C088034 */  lui   $t0, %hi(gDisplayListHead) # $t0, 0x8034
/* 039328 8027E328 8D089CFC */  lw    $t0, %lo(gDisplayListHead)($t0)
/* 03932C 8027E32C 3C018034 */  lui   $at, %hi(gDisplayListHead) # $at, 0x8034
/* 039330 8027E330 25090008 */  addiu $t1, $t0, 8
/* 039334 8027E334 AC299CFC */  sw    $t1, %lo(gDisplayListHead)($at)
/* 039338 8027E338 AFA80034 */  sw    $t0, 0x34($sp)
/* 03933C 8027E33C 8FB90040 */  lw    $t9, 0x40($sp)
/* 039340 8027E340 87AF0072 */  lh    $t7, 0x72($sp)
/* 039344 8027E344 8FA90034 */  lw    $t1, 0x34($sp)
/* 039348 8027E348 332A03FF */  andi  $t2, $t9, 0x3ff
/* 03934C 8027E34C 25EE0002 */  addiu $t6, $t7, 2
/* 039350 8027E350 31CD03FF */  andi  $t5, $t6, 0x3ff
/* 039354 8027E354 000A5B80 */  sll   $t3, $t2, 0xe
/* 039358 8027E358 3C01F600 */  lui   $at, 0xf600
/* 03935C 8027E35C 01616025 */  or    $t4, $t3, $at
/* 039360 8027E360 000DC080 */  sll   $t8, $t5, 2
/* 039364 8027E364 01984025 */  or    $t0, $t4, $t8
/* 039368 8027E368 AD280000 */  sw    $t0, ($t1)
/* 03936C 8027E36C 8FB90044 */  lw    $t9, 0x44($sp)
/* 039370 8027E370 87AF0072 */  lh    $t7, 0x72($sp)
/* 039374 8027E374 8FB80034 */  lw    $t8, 0x34($sp)
/* 039378 8027E378 332A03FF */  andi  $t2, $t9, 0x3ff
/* 03937C 8027E37C 31EE03FF */  andi  $t6, $t7, 0x3ff
/* 039380 8027E380 000E6880 */  sll   $t5, $t6, 2
/* 039384 8027E384 000A5B80 */  sll   $t3, $t2, 0xe
/* 039388 8027E388 016D6025 */  or    $t4, $t3, $t5
/* 03938C 8027E38C AF0C0004 */  sw    $t4, 4($t8)
.L8027E390:
/* 039390 8027E390 10000001 */  b     .L8027E398
/* 039394 8027E394 00000000 */   nop   
.L8027E398:
/* 039398 8027E398 8FBF0014 */  lw    $ra, 0x14($sp)
/* 03939C 8027E39C 27BD0058 */  addiu $sp, $sp, 0x58
/* 0393A0 8027E3A0 03E00008 */  jr    $ra
/* 0393A4 8027E3A4 00000000 */   nop   

glabel func_8027E3A8
/* 0393A8 8027E3A8 27BDFFD0 */  addiu $sp, $sp, -0x30
/* 0393AC 8027E3AC 3C0E8034 */  lui   $t6, %hi(gDisplayListHead) # $t6, 0x8034
/* 0393B0 8027E3B0 8DCE9CFC */  lw    $t6, %lo(gDisplayListHead)($t6)
/* 0393B4 8027E3B4 3C018034 */  lui   $at, %hi(gDisplayListHead) # $at, 0x8034
/* 0393B8 8027E3B8 25CF0008 */  addiu $t7, $t6, 8
/* 0393BC 8027E3BC AC2F9CFC */  sw    $t7, %lo(gDisplayListHead)($at)
/* 0393C0 8027E3C0 AFAE002C */  sw    $t6, 0x2c($sp)
/* 0393C4 8027E3C4 8FB9002C */  lw    $t9, 0x2c($sp)
/* 0393C8 8027E3C8 3C18E700 */  lui   $t8, 0xe700
/* 0393CC 8027E3CC AF380000 */  sw    $t8, ($t9)
/* 0393D0 8027E3D0 8FA8002C */  lw    $t0, 0x2c($sp)
/* 0393D4 8027E3D4 AD000004 */  sw    $zero, 4($t0)
/* 0393D8 8027E3D8 3C098034 */  lui   $t1, %hi(gDisplayListHead) # $t1, 0x8034
/* 0393DC 8027E3DC 8D299CFC */  lw    $t1, %lo(gDisplayListHead)($t1)
/* 0393E0 8027E3E0 3C018034 */  lui   $at, %hi(gDisplayListHead) # $at, 0x8034
/* 0393E4 8027E3E4 252A0008 */  addiu $t2, $t1, 8
/* 0393E8 8027E3E8 AC2A9CFC */  sw    $t2, %lo(gDisplayListHead)($at)
/* 0393EC 8027E3EC AFA90028 */  sw    $t1, 0x28($sp)
/* 0393F0 8027E3F0 8FAC0028 */  lw    $t4, 0x28($sp)
/* 0393F4 8027E3F4 3C0BF700 */  lui   $t3, 0xf700
/* 0393F8 8027E3F8 AD8B0000 */  sw    $t3, ($t4)
/* 0393FC 8027E3FC 8FAE0028 */  lw    $t6, 0x28($sp)
/* 039400 8027E400 3C0D2ABF */  lui   $t5, (0x2ABF2ABF >> 16) # lui $t5, 0x2abf
/* 039404 8027E404 35AD2ABF */  ori   $t5, (0x2ABF2ABF & 0xFFFF) # ori $t5, $t5, 0x2abf
/* 039408 8027E408 ADCD0004 */  sw    $t5, 4($t6)
/* 03940C 8027E40C 3C0F8034 */  lui   $t7, %hi(gDisplayListHead) # $t7, 0x8034
/* 039410 8027E410 8DEF9CFC */  lw    $t7, %lo(gDisplayListHead)($t7)
/* 039414 8027E414 3C018034 */  lui   $at, %hi(gDisplayListHead) # $at, 0x8034
/* 039418 8027E418 25F80008 */  addiu $t8, $t7, 8
/* 03941C 8027E41C AC389CFC */  sw    $t8, %lo(gDisplayListHead)($at)
/* 039420 8027E420 AFAF0024 */  sw    $t7, 0x24($sp)
/* 039424 8027E424 8FA80024 */  lw    $t0, 0x24($sp)
/* 039428 8027E428 3C19F613 */  lui   $t9, (0xF613C378 >> 16) # lui $t9, 0xf613
/* 03942C 8027E42C 3739C378 */  ori   $t9, (0xF613C378 & 0xFFFF) # ori $t9, $t9, 0xc378
/* 039430 8027E430 AD190000 */  sw    $t9, ($t0)
/* 039434 8027E434 8FAA0024 */  lw    $t2, 0x24($sp)
/* 039438 8027E438 3C090007 */  lui   $t1, (0x00078370 >> 16) # lui $t1, 7
/* 03943C 8027E43C 35298370 */  ori   $t1, (0x00078370 & 0xFFFF) # ori $t1, $t1, 0x8370
/* 039440 8027E440 AD490004 */  sw    $t1, 4($t2)
/* 039444 8027E444 3C0B8034 */  lui   $t3, %hi(gDisplayListHead) # $t3, 0x8034
/* 039448 8027E448 8D6B9CFC */  lw    $t3, %lo(gDisplayListHead)($t3)
/* 03944C 8027E44C 3C018034 */  lui   $at, %hi(gDisplayListHead) # $at, 0x8034
/* 039450 8027E450 256C0008 */  addiu $t4, $t3, 8
/* 039454 8027E454 AC2C9CFC */  sw    $t4, %lo(gDisplayListHead)($at)
/* 039458 8027E458 AFAB0020 */  sw    $t3, 0x20($sp)
/* 03945C 8027E45C 8FAE0020 */  lw    $t6, 0x20($sp)
/* 039460 8027E460 3C0DE700 */  lui   $t5, 0xe700
/* 039464 8027E464 ADCD0000 */  sw    $t5, ($t6)
/* 039468 8027E468 8FAF0020 */  lw    $t7, 0x20($sp)
/* 03946C 8027E46C ADE00004 */  sw    $zero, 4($t7)
/* 039470 8027E470 3C188034 */  lui   $t8, %hi(gDisplayListHead) # $t8, 0x8034
/* 039474 8027E474 8F189CFC */  lw    $t8, %lo(gDisplayListHead)($t8)
/* 039478 8027E478 3C018034 */  lui   $at, %hi(gDisplayListHead) # $at, 0x8034
/* 03947C 8027E47C 27190008 */  addiu $t9, $t8, 8
/* 039480 8027E480 AC399CFC */  sw    $t9, %lo(gDisplayListHead)($at)
/* 039484 8027E484 AFB8001C */  sw    $t8, 0x1c($sp)
/* 039488 8027E488 8FA9001C */  lw    $t1, 0x1c($sp)
/* 03948C 8027E48C 3C08F700 */  lui   $t0, 0xf700
/* 039490 8027E490 AD280000 */  sw    $t0, ($t1)
/* 039494 8027E494 8FAB001C */  lw    $t3, 0x1c($sp)
/* 039498 8027E498 3C0AFFCB */  lui   $t2, (0xFFCBFFCB >> 16) # lui $t2, 0xffcb
/* 03949C 8027E49C 354AFFCB */  ori   $t2, (0xFFCBFFCB & 0xFFFF) # ori $t2, $t2, 0xffcb
/* 0394A0 8027E4A0 AD6A0004 */  sw    $t2, 4($t3)
/* 0394A4 8027E4A4 3C0C8034 */  lui   $t4, %hi(gDisplayListHead) # $t4, 0x8034
/* 0394A8 8027E4A8 8D8C9CFC */  lw    $t4, %lo(gDisplayListHead)($t4)
/* 0394AC 8027E4AC 3C018034 */  lui   $at, %hi(gDisplayListHead) # $at, 0x8034
/* 0394B0 8027E4B0 258D0008 */  addiu $t5, $t4, 8
/* 0394B4 8027E4B4 AC2D9CFC */  sw    $t5, %lo(gDisplayListHead)($at)
/* 0394B8 8027E4B8 AFAC0018 */  sw    $t4, 0x18($sp)
/* 0394BC 8027E4BC 8FAF0018 */  lw    $t7, 0x18($sp)
/* 0394C0 8027E4C0 3C0EF620 */  lui   $t6, (0xF6200378 >> 16) # lui $t6, 0xf620
/* 0394C4 8027E4C4 35CE0378 */  ori   $t6, (0xF6200378 & 0xFFFF) # ori $t6, $t6, 0x378
/* 0394C8 8027E4C8 ADEE0000 */  sw    $t6, ($t7)
/* 0394CC 8027E4CC 8FB90018 */  lw    $t9, 0x18($sp)
/* 0394D0 8027E4D0 3C180013 */  lui   $t8, (0x0013C370 >> 16) # lui $t8, 0x13
/* 0394D4 8027E4D4 3718C370 */  ori   $t8, (0x0013C370 & 0xFFFF) # ori $t8, $t8, 0xc370
/* 0394D8 8027E4D8 AF380004 */  sw    $t8, 4($t9)
/* 0394DC 8027E4DC 3C088034 */  lui   $t0, %hi(gDisplayListHead) # $t0, 0x8034
/* 0394E0 8027E4E0 8D089CFC */  lw    $t0, %lo(gDisplayListHead)($t0)
/* 0394E4 8027E4E4 3C018034 */  lui   $at, %hi(gDisplayListHead) # $at, 0x8034
/* 0394E8 8027E4E8 25090008 */  addiu $t1, $t0, 8
/* 0394EC 8027E4EC AC299CFC */  sw    $t1, %lo(gDisplayListHead)($at)
/* 0394F0 8027E4F0 AFA80014 */  sw    $t0, 0x14($sp)
/* 0394F4 8027E4F4 8FAB0014 */  lw    $t3, 0x14($sp)
/* 0394F8 8027E4F8 3C0AE700 */  lui   $t2, 0xe700
/* 0394FC 8027E4FC AD6A0000 */  sw    $t2, ($t3)
/* 039500 8027E500 8FAC0014 */  lw    $t4, 0x14($sp)
/* 039504 8027E504 AD800004 */  sw    $zero, 4($t4)
/* 039508 8027E508 3C0D8034 */  lui   $t5, %hi(gDisplayListHead) # $t5, 0x8034
/* 03950C 8027E50C 8DAD9CFC */  lw    $t5, %lo(gDisplayListHead)($t5)
/* 039510 8027E510 3C018034 */  lui   $at, %hi(gDisplayListHead) # $at, 0x8034
/* 039514 8027E514 25AE0008 */  addiu $t6, $t5, 8
/* 039518 8027E518 AC2E9CFC */  sw    $t6, %lo(gDisplayListHead)($at)
/* 03951C 8027E51C AFAD0010 */  sw    $t5, 0x10($sp)
/* 039520 8027E520 8FB80010 */  lw    $t8, 0x10($sp)
/* 039524 8027E524 3C0FF700 */  lui   $t7, 0xf700
/* 039528 8027E528 AF0F0000 */  sw    $t7, ($t8)
/* 03952C 8027E52C 8FA80010 */  lw    $t0, 0x10($sp)
/* 039530 8027E530 3C19FBCB */  lui   $t9, (0xFBCBFBCB >> 16) # lui $t9, 0xfbcb
/* 039534 8027E534 3739FBCB */  ori   $t9, (0xFBCBFBCB & 0xFFFF) # ori $t9, $t9, 0xfbcb
/* 039538 8027E538 AD190004 */  sw    $t9, 4($t0)
/* 03953C 8027E53C 3C098034 */  lui   $t1, %hi(gDisplayListHead) # $t1, 0x8034
/* 039540 8027E540 8D299CFC */  lw    $t1, %lo(gDisplayListHead)($t1)
/* 039544 8027E544 3C018034 */  lui   $at, %hi(gDisplayListHead) # $at, 0x8034
/* 039548 8027E548 252A0008 */  addiu $t2, $t1, 8
/* 03954C 8027E54C AC2A9CFC */  sw    $t2, %lo(gDisplayListHead)($at)
/* 039550 8027E550 AFA9000C */  sw    $t1, 0xc($sp)
/* 039554 8027E554 8FAC000C */  lw    $t4, 0xc($sp)
/* 039558 8027E558 3C0BF62C */  lui   $t3, (0xF62C4378 >> 16) # lui $t3, 0xf62c
/* 03955C 8027E55C 356B4378 */  ori   $t3, (0xF62C4378 & 0xFFFF) # ori $t3, $t3, 0x4378
/* 039560 8027E560 AD8B0000 */  sw    $t3, ($t4)
/* 039564 8027E564 8FAE000C */  lw    $t6, 0xc($sp)
/* 039568 8027E568 3C0D0020 */  lui   $t5, (0x00200370 >> 16) # lui $t5, 0x20
/* 03956C 8027E56C 35AD0370 */  ori   $t5, (0x00200370 & 0xFFFF) # ori $t5, $t5, 0x370
/* 039570 8027E570 ADCD0004 */  sw    $t5, 4($t6)
/* 039574 8027E574 3C0F8034 */  lui   $t7, %hi(gDisplayListHead) # $t7, 0x8034
/* 039578 8027E578 8DEF9CFC */  lw    $t7, %lo(gDisplayListHead)($t7)
/* 03957C 8027E57C 3C018034 */  lui   $at, %hi(gDisplayListHead) # $at, 0x8034
/* 039580 8027E580 25F80008 */  addiu $t8, $t7, 8
/* 039584 8027E584 AC389CFC */  sw    $t8, %lo(gDisplayListHead)($at)
/* 039588 8027E588 AFAF0008 */  sw    $t7, 8($sp)
/* 03958C 8027E58C 8FA80008 */  lw    $t0, 8($sp)
/* 039590 8027E590 3C19E700 */  lui   $t9, 0xe700
/* 039594 8027E594 AD190000 */  sw    $t9, ($t0)
/* 039598 8027E598 8FA90008 */  lw    $t1, 8($sp)
/* 03959C 8027E59C AD200004 */  sw    $zero, 4($t1)
/* 0395A0 8027E5A0 3C0A8034 */  lui   $t2, %hi(gDisplayListHead) # $t2, 0x8034
/* 0395A4 8027E5A4 8D4A9CFC */  lw    $t2, %lo(gDisplayListHead)($t2)
/* 0395A8 8027E5A8 3C018034 */  lui   $at, %hi(gDisplayListHead) # $at, 0x8034
/* 0395AC 8027E5AC 254B0008 */  addiu $t3, $t2, 8
/* 0395B0 8027E5B0 AC2B9CFC */  sw    $t3, %lo(gDisplayListHead)($at)
/* 0395B4 8027E5B4 AFAA0004 */  sw    $t2, 4($sp)
/* 0395B8 8027E5B8 8FAD0004 */  lw    $t5, 4($sp)
/* 0395BC 8027E5BC 3C0CF700 */  lui   $t4, 0xf700
/* 0395C0 8027E5C0 ADAC0000 */  sw    $t4, ($t5)
/* 0395C4 8027E5C4 8FAF0004 */  lw    $t7, 4($sp)
/* 0395C8 8027E5C8 3C0EF94B */  lui   $t6, (0xF94BF94B >> 16) # lui $t6, 0xf94b
/* 0395CC 8027E5CC 35CEF94B */  ori   $t6, (0xF94BF94B & 0xFFFF) # ori $t6, $t6, 0xf94b
/* 0395D0 8027E5D0 ADEE0004 */  sw    $t6, 4($t7)
/* 0395D4 8027E5D4 3C188034 */  lui   $t8, %hi(gDisplayListHead) # $t8, 0x8034
/* 0395D8 8027E5D8 8F189CFC */  lw    $t8, %lo(gDisplayListHead)($t8)
/* 0395DC 8027E5DC 3C018034 */  lui   $at, %hi(gDisplayListHead) # $at, 0x8034
/* 0395E0 8027E5E0 27190008 */  addiu $t9, $t8, 8
/* 0395E4 8027E5E4 AC399CFC */  sw    $t9, %lo(gDisplayListHead)($at)
/* 0395E8 8027E5E8 AFB80000 */  sw    $t8, ($sp)
/* 0395EC 8027E5EC 8FA90000 */  lw    $t1, ($sp)
/* 0395F0 8027E5F0 3C08F638 */  lui   $t0, (0xF6388378 >> 16) # lui $t0, 0xf638
/* 0395F4 8027E5F4 35088378 */  ori   $t0, (0xF6388378 & 0xFFFF) # ori $t0, $t0, 0x8378
/* 0395F8 8027E5F8 AD280000 */  sw    $t0, ($t1)
/* 0395FC 8027E5FC 8FAB0000 */  lw    $t3, ($sp)
/* 039600 8027E600 3C0A002C */  lui   $t2, (0x002C4370 >> 16) # lui $t2, 0x2c
/* 039604 8027E604 354A4370 */  ori   $t2, (0x002C4370 & 0xFFFF) # ori $t2, $t2, 0x4370
/* 039608 8027E608 AD6A0004 */  sw    $t2, 4($t3)
/* 03960C 8027E60C 10000001 */  b     .L8027E614
/* 039610 8027E610 00000000 */   nop   
.L8027E614:
/* 039614 8027E614 03E00008 */  jr    $ra
/* 039618 8027E618 27BD0030 */   addiu $sp, $sp, 0x30

glabel func_8027E61C
/* 03961C 8027E61C 27BDFFC0 */  addiu $sp, $sp, -0x40
/* 039620 8027E620 AFBF0024 */  sw    $ra, 0x24($sp)
/* 039624 8027E624 3C0E8033 */  lui   $t6, %hi(D_8032CFB4) # $t6, 0x8033
/* 039628 8027E628 85CECFB4 */  lh    $t6, %lo(D_8032CFB4)($t6)
/* 03962C 8027E62C 3C198034 */  lui   $t9, %hi(D_8033B020) # $t9, 0x8034
/* 039630 8027E630 2739B020 */  addiu $t9, %lo(D_8033B020) # addiu $t9, $t9, -0x4fe0
/* 039634 8027E634 39CF0001 */  xori  $t7, $t6, 1
/* 039638 8027E638 000FC080 */  sll   $t8, $t7, 2
/* 03963C 8027E63C 030FC023 */  subu  $t8, $t8, $t7
/* 039640 8027E640 0018C0C0 */  sll   $t8, $t8, 3
/* 039644 8027E644 030FC021 */  addu  $t8, $t8, $t7
/* 039648 8027E648 0018C0C0 */  sll   $t8, $t8, 3
/* 03964C 8027E64C 03194021 */  addu  $t0, $t8, $t9
/* 039650 8027E650 AFA80038 */  sw    $t0, 0x38($sp)
/* 039654 8027E654 3C068033 */  lui   $a2, %hi(D_80334800) # $a2, 0x8033
/* 039658 8027E658 3C078033 */  lui   $a3, %hi(D_80334804) # $a3, 0x8033
/* 03965C 8027E65C 8CE74804 */  lw    $a3, %lo(D_80334804)($a3)
/* 039660 8027E660 8CC64800 */  lw    $a2, %lo(D_80334800)($a2)
/* 039664 8027E664 24040000 */  li    $a0, 0
/* 039668 8027E668 0C0C8CCA */  jal   __ll_mul
/* 03966C 8027E66C 24054031 */   li    $a1, 16433
/* 039670 8027E670 AFA20028 */  sw    $v0, 0x28($sp)
/* 039674 8027E674 AFA3002C */  sw    $v1, 0x2c($sp)
/* 039678 8027E678 3C07000F */  lui   $a3, (0x000F4240 >> 16) # lui $a3, 0xf
/* 03967C 8027E67C 34E74240 */  ori   $a3, (0x000F4240 & 0xFFFF) # ori $a3, $a3, 0x4240
/* 039680 8027E680 8FA5002C */  lw    $a1, 0x2c($sp)
/* 039684 8027E684 8FA40028 */  lw    $a0, 0x28($sp)
/* 039688 8027E688 0C0C8C8A */  jal   __ull_div
/* 03968C 8027E68C 24060000 */   li    $a2, 0
/* 039690 8027E690 8FA90038 */  lw    $t1, 0x38($sp)
/* 039694 8027E694 8D2A0048 */  lw    $t2, 0x48($t1)
/* 039698 8027E698 8D2B004C */  lw    $t3, 0x4c($t1)
/* 03969C 8027E69C 01426023 */  subu  $t4, $t2, $v0
/* 0396A0 8027E6A0 0163082B */  sltu  $at, $t3, $v1
/* 0396A4 8027E6A4 01816023 */  subu  $t4, $t4, $at
/* 0396A8 8027E6A8 01636823 */  subu  $t5, $t3, $v1
/* 0396AC 8027E6AC AFAD0034 */  sw    $t5, 0x34($sp)
/* 0396B0 8027E6B0 AFAC0030 */  sw    $t4, 0x30($sp)
/* 0396B4 8027E6B4 8FAE0038 */  lw    $t6, 0x38($sp)
/* 0396B8 8027E6B8 240F00D4 */  li    $t7, 212
/* 0396BC 8027E6BC 3408FFCB */  li    $t0, 65483
/* 0396C0 8027E6C0 8DD80010 */  lw    $t8, 0x10($t6)
/* 0396C4 8027E6C4 8DD90014 */  lw    $t9, 0x14($t6)
/* 0396C8 8027E6C8 8DC60008 */  lw    $a2, 8($t6)
/* 0396CC 8027E6CC 8DC7000C */  lw    $a3, 0xc($t6)
/* 0396D0 8027E6D0 AFA8001C */  sw    $t0, 0x1c($sp)
/* 0396D4 8027E6D4 AFAF0018 */  sw    $t7, 0x18($sp)
/* 0396D8 8027E6D8 8FA40030 */  lw    $a0, 0x30($sp)
/* 0396DC 8027E6DC 8FA50034 */  lw    $a1, 0x34($sp)
/* 0396E0 8027E6E0 AFB80010 */  sw    $t8, 0x10($sp)
/* 0396E4 8027E6E4 0C09F82B */  jal   func_8027E0AC
/* 0396E8 8027E6E8 AFB90014 */   sw    $t9, 0x14($sp)
/* 0396EC 8027E6EC 8FA90038 */  lw    $t1, 0x38($sp)
/* 0396F0 8027E6F0 240C00D4 */  li    $t4, 212
/* 0396F4 8027E6F4 340DFBCB */  li    $t5, 64459
/* 0396F8 8027E6F8 8D2A0018 */  lw    $t2, 0x18($t1)
/* 0396FC 8027E6FC 8D2B001C */  lw    $t3, 0x1c($t1)
/* 039700 8027E700 8D260010 */  lw    $a2, 0x10($t1)
/* 039704 8027E704 8D270014 */  lw    $a3, 0x14($t1)
/* 039708 8027E708 AFAD001C */  sw    $t5, 0x1c($sp)
/* 03970C 8027E70C AFAC0018 */  sw    $t4, 0x18($sp)
/* 039710 8027E710 8FA40030 */  lw    $a0, 0x30($sp)
/* 039714 8027E714 8FA50034 */  lw    $a1, 0x34($sp)
/* 039718 8027E718 AFAA0010 */  sw    $t2, 0x10($sp)
/* 03971C 8027E71C 0C09F82B */  jal   func_8027E0AC
/* 039720 8027E720 AFAB0014 */   sw    $t3, 0x14($sp)
/* 039724 8027E724 8FAE0038 */  lw    $t6, 0x38($sp)
/* 039728 8027E728 240F00D4 */  li    $t7, 212
/* 03972C 8027E72C 24082E39 */  li    $t0, 11833
/* 039730 8027E730 8DD80020 */  lw    $t8, 0x20($t6)
/* 039734 8027E734 8DD90024 */  lw    $t9, 0x24($t6)
/* 039738 8027E738 8DC60018 */  lw    $a2, 0x18($t6)
/* 03973C 8027E73C 8DC7001C */  lw    $a3, 0x1c($t6)
/* 039740 8027E740 AFA8001C */  sw    $t0, 0x1c($sp)
/* 039744 8027E744 AFAF0018 */  sw    $t7, 0x18($sp)
/* 039748 8027E748 8FA40030 */  lw    $a0, 0x30($sp)
/* 03974C 8027E74C 8FA50034 */  lw    $a1, 0x34($sp)
/* 039750 8027E750 AFB80010 */  sw    $t8, 0x10($sp)
/* 039754 8027E754 0C09F82B */  jal   func_8027E0AC
/* 039758 8027E758 AFB90014 */   sw    $t9, 0x14($sp)
/* 03975C 8027E75C 8FA90038 */  lw    $t1, 0x38($sp)
/* 039760 8027E760 852A0000 */  lh    $t2, ($t1)
/* 039764 8027E764 314BFFFE */  andi  $t3, $t2, 0xfffe
/* 039768 8027E768 A52B0000 */  sh    $t3, ($t1)
/* 03976C 8027E76C 8FAC0038 */  lw    $t4, 0x38($sp)
/* 039770 8027E770 AFA0003C */  sw    $zero, 0x3c($sp)
/* 039774 8027E774 858D0000 */  lh    $t5, ($t4)
/* 039778 8027E778 19A0001A */  blez  $t5, .L8027E7E4
/* 03977C 8027E77C 00000000 */   nop   
.L8027E780:
/* 039780 8027E780 8FB8003C */  lw    $t8, 0x3c($sp)
/* 039784 8027E784 8FAE0038 */  lw    $t6, 0x38($sp)
/* 039788 8027E788 240A00D4 */  li    $t2, 212
/* 03978C 8027E78C 0018C8C0 */  sll   $t9, $t8, 3
/* 039790 8027E790 01D97821 */  addu  $t7, $t6, $t9
/* 039794 8027E794 8DE80050 */  lw    $t0, 0x50($t7)
/* 039798 8027E798 8DE90054 */  lw    $t1, 0x54($t7)
/* 03979C 8027E79C 8DE60048 */  lw    $a2, 0x48($t7)
/* 0397A0 8027E7A0 8DE7004C */  lw    $a3, 0x4c($t7)
/* 0397A4 8027E7A4 340BF94B */  li    $t3, 63819
/* 0397A8 8027E7A8 AFAB001C */  sw    $t3, 0x1c($sp)
/* 0397AC 8027E7AC AFAA0018 */  sw    $t2, 0x18($sp)
/* 0397B0 8027E7B0 8FA40030 */  lw    $a0, 0x30($sp)
/* 0397B4 8027E7B4 8FA50034 */  lw    $a1, 0x34($sp)
/* 0397B8 8027E7B8 AFA80010 */  sw    $t0, 0x10($sp)
/* 0397BC 8027E7BC 0C09F82B */  jal   func_8027E0AC
/* 0397C0 8027E7C0 AFA90014 */   sw    $t1, 0x14($sp)
/* 0397C4 8027E7C4 8FAC003C */  lw    $t4, 0x3c($sp)
/* 0397C8 8027E7C8 8FB80038 */  lw    $t8, 0x38($sp)
/* 0397CC 8027E7CC 258D0002 */  addiu $t5, $t4, 2
/* 0397D0 8027E7D0 AFAD003C */  sw    $t5, 0x3c($sp)
/* 0397D4 8027E7D4 870E0000 */  lh    $t6, ($t8)
/* 0397D8 8027E7D8 01AE082A */  slt   $at, $t5, $t6
/* 0397DC 8027E7DC 1420FFE8 */  bnez  $at, .L8027E780
/* 0397E0 8027E7E0 00000000 */   nop   
.L8027E7E4:
/* 0397E4 8027E7E4 8FB90038 */  lw    $t9, 0x38($sp)
/* 0397E8 8027E7E8 240F00D8 */  li    $t7, 216
/* 0397EC 8027E7EC 340AFFCB */  li    $t2, 65483
/* 0397F0 8027E7F0 8F280038 */  lw    $t0, 0x38($t9)
/* 0397F4 8027E7F4 8F29003C */  lw    $t1, 0x3c($t9)
/* 0397F8 8027E7F8 8F260030 */  lw    $a2, 0x30($t9)
/* 0397FC 8027E7FC 8F270034 */  lw    $a3, 0x34($t9)
/* 039800 8027E800 AFAA001C */  sw    $t2, 0x1c($sp)
/* 039804 8027E804 AFAF0018 */  sw    $t7, 0x18($sp)
/* 039808 8027E808 8FA40030 */  lw    $a0, 0x30($sp)
/* 03980C 8027E80C 8FA50034 */  lw    $a1, 0x34($sp)
/* 039810 8027E810 AFA80010 */  sw    $t0, 0x10($sp)
/* 039814 8027E814 0C09F82B */  jal   func_8027E0AC
/* 039818 8027E818 AFA90014 */   sw    $t1, 0x14($sp)
/* 03981C 8027E81C 8FAB0038 */  lw    $t3, 0x38($sp)
/* 039820 8027E820 241800D8 */  li    $t8, 216
/* 039824 8027E824 340EFBCB */  li    $t6, 64459
/* 039828 8027E828 8D6C0040 */  lw    $t4, 0x40($t3)
/* 03982C 8027E82C 8D6D0044 */  lw    $t5, 0x44($t3)
/* 039830 8027E830 8D660038 */  lw    $a2, 0x38($t3)
/* 039834 8027E834 8D67003C */  lw    $a3, 0x3c($t3)
/* 039838 8027E838 AFAE001C */  sw    $t6, 0x1c($sp)
/* 03983C 8027E83C AFB80018 */  sw    $t8, 0x18($sp)
/* 039840 8027E840 8FA40030 */  lw    $a0, 0x30($sp)
/* 039844 8027E844 8FA50034 */  lw    $a1, 0x34($sp)
/* 039848 8027E848 AFAC0010 */  sw    $t4, 0x10($sp)
/* 03984C 8027E84C 0C09F82B */  jal   func_8027E0AC
/* 039850 8027E850 AFAD0014 */   sw    $t5, 0x14($sp)
/* 039854 8027E854 8FB90038 */  lw    $t9, 0x38($sp)
/* 039858 8027E858 87280002 */  lh    $t0, 2($t9)
/* 03985C 8027E85C 3109FFFE */  andi  $t1, $t0, 0xfffe
/* 039860 8027E860 A7290002 */  sh    $t1, 2($t9)
/* 039864 8027E864 8FAF0038 */  lw    $t7, 0x38($sp)
/* 039868 8027E868 AFA0003C */  sw    $zero, 0x3c($sp)
/* 03986C 8027E86C 85EA0002 */  lh    $t2, 2($t7)
/* 039870 8027E870 1940001A */  blez  $t2, .L8027E8DC
/* 039874 8027E874 00000000 */   nop   
.L8027E878:
/* 039878 8027E878 8FAC003C */  lw    $t4, 0x3c($sp)
/* 03987C 8027E87C 8FAB0038 */  lw    $t3, 0x38($sp)
/* 039880 8027E880 240800D8 */  li    $t0, 216
/* 039884 8027E884 000C68C0 */  sll   $t5, $t4, 3
/* 039888 8027E888 016DC021 */  addu  $t8, $t3, $t5
/* 03988C 8027E88C 8F0E0090 */  lw    $t6, 0x90($t8)
/* 039890 8027E890 8F0F0094 */  lw    $t7, 0x94($t8)
/* 039894 8027E894 8F060088 */  lw    $a2, 0x88($t8)
/* 039898 8027E898 8F07008C */  lw    $a3, 0x8c($t8)
/* 03989C 8027E89C 3409F94B */  li    $t1, 63819
/* 0398A0 8027E8A0 AFA9001C */  sw    $t1, 0x1c($sp)
/* 0398A4 8027E8A4 AFA80018 */  sw    $t0, 0x18($sp)
/* 0398A8 8027E8A8 8FA40030 */  lw    $a0, 0x30($sp)
/* 0398AC 8027E8AC 8FA50034 */  lw    $a1, 0x34($sp)
/* 0398B0 8027E8B0 AFAE0010 */  sw    $t6, 0x10($sp)
/* 0398B4 8027E8B4 0C09F82B */  jal   func_8027E0AC
/* 0398B8 8027E8B8 AFAF0014 */   sw    $t7, 0x14($sp)
/* 0398BC 8027E8BC 8FB9003C */  lw    $t9, 0x3c($sp)
/* 0398C0 8027E8C0 8FAC0038 */  lw    $t4, 0x38($sp)
/* 0398C4 8027E8C4 272A0002 */  addiu $t2, $t9, 2
/* 0398C8 8027E8C8 AFAA003C */  sw    $t2, 0x3c($sp)
/* 0398CC 8027E8CC 858B0002 */  lh    $t3, 2($t4)
/* 0398D0 8027E8D0 014B082A */  slt   $at, $t2, $t3
/* 0398D4 8027E8D4 1420FFE8 */  bnez  $at, .L8027E878
/* 0398D8 8027E8D8 00000000 */   nop   
.L8027E8DC:
/* 0398DC 8027E8DC 0C09F8EA */  jal   func_8027E3A8
/* 0398E0 8027E8E0 00000000 */   nop   
/* 0398E4 8027E8E4 10000001 */  b     .L8027E8EC
/* 0398E8 8027E8E8 00000000 */   nop   
.L8027E8EC:
/* 0398EC 8027E8EC 8FBF0024 */  lw    $ra, 0x24($sp)
/* 0398F0 8027E8F0 27BD0040 */  addiu $sp, $sp, 0x40
/* 0398F4 8027E8F4 03E00008 */  jr    $ra
/* 0398F8 8027E8F8 00000000 */   nop   

glabel func_8027E8FC
/* 0398FC 8027E8FC 27BDFF78 */  addiu $sp, $sp, -0x88
/* 039900 8027E900 AFBF0024 */  sw    $ra, 0x24($sp)
/* 039904 8027E904 3C0E8033 */  lui   $t6, %hi(D_8032CFB4) # $t6, 0x8033
/* 039908 8027E908 85CECFB4 */  lh    $t6, %lo(D_8032CFB4)($t6)
/* 03990C 8027E90C 3C198034 */  lui   $t9, %hi(D_8033B020) # $t9, 0x8034
/* 039910 8027E910 2739B020 */  addiu $t9, %lo(D_8033B020) # addiu $t9, $t9, -0x4fe0
/* 039914 8027E914 39CF0001 */  xori  $t7, $t6, 1
/* 039918 8027E918 000FC080 */  sll   $t8, $t7, 2
/* 03991C 8027E91C 030FC023 */  subu  $t8, $t8, $t7
/* 039920 8027E920 0018C0C0 */  sll   $t8, $t8, 3
/* 039924 8027E924 030FC021 */  addu  $t8, $t8, $t7
/* 039928 8027E928 0018C0C0 */  sll   $t8, $t8, 3
/* 03992C 8027E92C 03194021 */  addu  $t0, $t8, $t9
/* 039930 8027E930 AFA80080 */  sw    $t0, 0x80($sp)
/* 039934 8027E934 8FA90080 */  lw    $t1, 0x80($sp)
/* 039938 8027E938 8D2A0008 */  lw    $t2, 8($t1)
/* 03993C 8027E93C 8D2C0048 */  lw    $t4, 0x48($t1)
/* 039940 8027E940 8D2B000C */  lw    $t3, 0xc($t1)
/* 039944 8027E944 8D2D004C */  lw    $t5, 0x4c($t1)
/* 039948 8027E948 018A082B */  sltu  $at, $t4, $t2
/* 03994C 8027E94C 1420000A */  bnez  $at, .L8027E978
/* 039950 8027E950 00000000 */   nop   
/* 039954 8027E954 014C082B */  sltu  $at, $t2, $t4
/* 039958 8027E958 14200004 */  bnez  $at, .L8027E96C
/* 03995C 8027E95C 00000000 */   nop   
/* 039960 8027E960 01AB082B */  sltu  $at, $t5, $t3
/* 039964 8027E964 14200004 */  bnez  $at, .L8027E978
/* 039968 8027E968 00000000 */   nop   
.L8027E96C:
/* 03996C 8027E96C AFAA0078 */  sw    $t2, 0x78($sp)
/* 039970 8027E970 10000006 */  b     .L8027E98C
/* 039974 8027E974 AFAB007C */   sw    $t3, 0x7c($sp)
.L8027E978:
/* 039978 8027E978 8FAE0080 */  lw    $t6, 0x80($sp)
/* 03997C 8027E97C 8DD80048 */  lw    $t8, 0x48($t6)
/* 039980 8027E980 8DD9004C */  lw    $t9, 0x4c($t6)
/* 039984 8027E984 AFB80078 */  sw    $t8, 0x78($sp)
/* 039988 8027E988 AFB9007C */  sw    $t9, 0x7c($sp)
.L8027E98C:
/* 03998C 8027E98C 8FAF0080 */  lw    $t7, 0x80($sp)
/* 039990 8027E990 8FAC0078 */  lw    $t4, 0x78($sp)
/* 039994 8027E994 8FAD007C */  lw    $t5, 0x7c($sp)
/* 039998 8027E998 8DE80010 */  lw    $t0, 0x10($t7)
/* 03999C 8027E99C 8DE90014 */  lw    $t1, 0x14($t7)
/* 0399A0 8027E9A0 010C5023 */  subu  $t2, $t0, $t4
/* 0399A4 8027E9A4 012D082B */  sltu  $at, $t1, $t5
/* 0399A8 8027E9A8 01415023 */  subu  $t2, $t2, $at
/* 0399AC 8027E9AC 012D5823 */  subu  $t3, $t1, $t5
/* 0399B0 8027E9B0 AFAB0074 */  sw    $t3, 0x74($sp)
/* 0399B4 8027E9B4 AFAA0070 */  sw    $t2, 0x70($sp)
/* 0399B8 8027E9B8 8FAE0080 */  lw    $t6, 0x80($sp)
/* 0399BC 8027E9BC 8DD80018 */  lw    $t8, 0x18($t6)
/* 0399C0 8027E9C0 8DD9001C */  lw    $t9, 0x1c($t6)
/* 0399C4 8027E9C4 8DC80010 */  lw    $t0, 0x10($t6)
/* 0399C8 8027E9C8 8DC90014 */  lw    $t1, 0x14($t6)
/* 0399CC 8027E9CC 03086023 */  subu  $t4, $t8, $t0
/* 0399D0 8027E9D0 0329082B */  sltu  $at, $t9, $t1
/* 0399D4 8027E9D4 01816023 */  subu  $t4, $t4, $at
/* 0399D8 8027E9D8 03296823 */  subu  $t5, $t9, $t1
/* 0399DC 8027E9DC AFAD006C */  sw    $t5, 0x6c($sp)
/* 0399E0 8027E9E0 AFAC0068 */  sw    $t4, 0x68($sp)
/* 0399E4 8027E9E4 240A0000 */  li    $t2, 0
/* 0399E8 8027E9E8 240B0000 */  li    $t3, 0
/* 0399EC 8027E9EC AFAB0064 */  sw    $t3, 0x64($sp)
/* 0399F0 8027E9F0 AFAA0060 */  sw    $t2, 0x60($sp)
/* 0399F4 8027E9F4 8FAF0080 */  lw    $t7, 0x80($sp)
/* 0399F8 8027E9F8 01E0C025 */  move  $t8, $t7
/* 0399FC 8027E9FC 8DEE0038 */  lw    $t6, 0x38($t7)
/* 039A00 8027EA00 8F080030 */  lw    $t0, 0x30($t8)
/* 039A04 8027EA04 8F090034 */  lw    $t1, 0x34($t8)
/* 039A08 8027EA08 8DEF003C */  lw    $t7, 0x3c($t7)
/* 039A0C 8027EA0C 01C86023 */  subu  $t4, $t6, $t0
/* 039A10 8027EA10 01E9082B */  sltu  $at, $t7, $t1
/* 039A14 8027EA14 01816023 */  subu  $t4, $t4, $at
/* 039A18 8027EA18 01E96823 */  subu  $t5, $t7, $t1
/* 039A1C 8027EA1C AFAD005C */  sw    $t5, 0x5c($sp)
/* 039A20 8027EA20 AFAC0058 */  sw    $t4, 0x58($sp)
/* 039A24 8027EA24 8FB90080 */  lw    $t9, 0x80($sp)
/* 039A28 8027EA28 8F2A0040 */  lw    $t2, 0x40($t9)
/* 039A2C 8027EA2C 8F2B0044 */  lw    $t3, 0x44($t9)
/* 039A30 8027EA30 8F380030 */  lw    $t8, 0x30($t9)
/* 039A34 8027EA34 8F390034 */  lw    $t9, 0x34($t9)
/* 039A38 8027EA38 01587023 */  subu  $t6, $t2, $t8
/* 039A3C 8027EA3C 0179082B */  sltu  $at, $t3, $t9
/* 039A40 8027EA40 01C17023 */  subu  $t6, $t6, $at
/* 039A44 8027EA44 01797823 */  subu  $t7, $t3, $t9
/* 039A48 8027EA48 AFAF0054 */  sw    $t7, 0x54($sp)
/* 039A4C 8027EA4C AFAE0050 */  sw    $t6, 0x50($sp)
/* 039A50 8027EA50 24080000 */  li    $t0, 0
/* 039A54 8027EA54 24090000 */  li    $t1, 0
/* 039A58 8027EA58 AFA9004C */  sw    $t1, 0x4c($sp)
/* 039A5C 8027EA5C AFA80048 */  sw    $t0, 0x48($sp)
/* 039A60 8027EA60 8FAC0080 */  lw    $t4, 0x80($sp)
/* 039A64 8027EA64 858D0000 */  lh    $t5, ($t4)
/* 039A68 8027EA68 31AAFFFE */  andi  $t2, $t5, 0xfffe
/* 039A6C 8027EA6C A58A0000 */  sh    $t2, ($t4)
/* 039A70 8027EA70 8FAB0080 */  lw    $t3, 0x80($sp)
/* 039A74 8027EA74 AFA00084 */  sw    $zero, 0x84($sp)
/* 039A78 8027EA78 85780000 */  lh    $t8, ($t3)
/* 039A7C 8027EA7C 1B000061 */  blez  $t8, .L8027EC04
/* 039A80 8027EA80 00000000 */   nop   
.L8027EA84:
/* 039A84 8027EA84 8FAE0084 */  lw    $t6, 0x84($sp)
/* 039A88 8027EA88 8FB90080 */  lw    $t9, 0x80($sp)
/* 039A8C 8027EA8C 000E78C0 */  sll   $t7, $t6, 3
/* 039A90 8027EA90 032F4021 */  addu  $t0, $t9, $t7
/* 039A94 8027EA94 8D0A0050 */  lw    $t2, 0x50($t0)
/* 039A98 8027EA98 8D0B0054 */  lw    $t3, 0x54($t0)
/* 039A9C 8027EA9C 8D0C0048 */  lw    $t4, 0x48($t0)
/* 039AA0 8027EAA0 8D0D004C */  lw    $t5, 0x4c($t0)
/* 039AA4 8027EAA4 014CC023 */  subu  $t8, $t2, $t4
/* 039AA8 8027EAA8 016D082B */  sltu  $at, $t3, $t5
/* 039AAC 8027EAAC 0301C023 */  subu  $t8, $t8, $at
/* 039AB0 8027EAB0 016DC823 */  subu  $t9, $t3, $t5
/* 039AB4 8027EAB4 AFB90044 */  sw    $t9, 0x44($sp)
/* 039AB8 8027EAB8 AFB80040 */  sw    $t8, 0x40($sp)
/* 039ABC 8027EABC 27A90060 */  addiu $t1, $sp, 0x60
/* 039AC0 8027EAC0 AFA9003C */  sw    $t1, 0x3c($sp)
/* 039AC4 8027EAC4 8D2F0004 */  lw    $t7, 4($t1)
/* 039AC8 8027EAC8 8D2E0000 */  lw    $t6, ($t1)
/* 039ACC 8027EACC 01205025 */  move  $t2, $t1
/* 039AD0 8027EAD0 8FA90044 */  lw    $t1, 0x44($sp)
/* 039AD4 8027EAD4 8FA80040 */  lw    $t0, 0x40($sp)
/* 039AD8 8027EAD8 01E96821 */  addu  $t5, $t7, $t1
/* 039ADC 8027EADC 01A9082B */  sltu  $at, $t5, $t1
/* 039AE0 8027EAE0 002E6021 */  addu  $t4, $at, $t6
/* 039AE4 8027EAE4 01886021 */  addu  $t4, $t4, $t0
/* 039AE8 8027EAE8 AD4C0000 */  sw    $t4, ($t2)
/* 039AEC 8027EAEC AD4D0004 */  sw    $t5, 4($t2)
/* 039AF0 8027EAF0 8FB80084 */  lw    $t8, 0x84($sp)
/* 039AF4 8027EAF4 8FAB0080 */  lw    $t3, 0x80($sp)
/* 039AF8 8027EAF8 0018C8C0 */  sll   $t9, $t8, 3
/* 039AFC 8027EAFC 01797021 */  addu  $t6, $t3, $t9
/* 039B00 8027EB00 8DC80048 */  lw    $t0, 0x48($t6)
/* 039B04 8027EB04 8D6C0010 */  lw    $t4, 0x10($t3)
/* 039B08 8027EB08 8DC9004C */  lw    $t1, 0x4c($t6)
/* 039B0C 8027EB0C 8D6D0014 */  lw    $t5, 0x14($t3)
/* 039B10 8027EB10 0188082B */  sltu  $at, $t4, $t0
/* 039B14 8027EB14 14200015 */  bnez  $at, .L8027EB6C
/* 039B18 8027EB18 00000000 */   nop   
/* 039B1C 8027EB1C 010C082B */  sltu  $at, $t0, $t4
/* 039B20 8027EB20 14200004 */  bnez  $at, .L8027EB34
/* 039B24 8027EB24 00000000 */   nop   
/* 039B28 8027EB28 012D082B */  sltu  $at, $t1, $t5
/* 039B2C 8027EB2C 1020000F */  beqz  $at, .L8027EB6C
/* 039B30 8027EB30 00000000 */   nop   
.L8027EB34:
/* 039B34 8027EB34 27AF0070 */  addiu $t7, $sp, 0x70
/* 039B38 8027EB38 AFAF0038 */  sw    $t7, 0x38($sp)
/* 039B3C 8027EB3C 8DEB0004 */  lw    $t3, 4($t7)
/* 039B40 8027EB40 8DEA0000 */  lw    $t2, ($t7)
/* 039B44 8027EB44 8FB80040 */  lw    $t8, 0x40($sp)
/* 039B48 8027EB48 8FB90044 */  lw    $t9, 0x44($sp)
/* 039B4C 8027EB4C 01E04025 */  move  $t0, $t7
/* 039B50 8027EB50 01587023 */  subu  $t6, $t2, $t8
/* 039B54 8027EB54 0179082B */  sltu  $at, $t3, $t9
/* 039B58 8027EB58 01C17023 */  subu  $t6, $t6, $at
/* 039B5C 8027EB5C 01797823 */  subu  $t7, $t3, $t9
/* 039B60 8027EB60 AD0F0004 */  sw    $t7, 4($t0)
/* 039B64 8027EB64 1000001F */  b     .L8027EBE4
/* 039B68 8027EB68 AD0E0000 */   sw    $t6, ($t0)
.L8027EB6C:
/* 039B6C 8027EB6C 8FAC0084 */  lw    $t4, 0x84($sp)
/* 039B70 8027EB70 8FA90080 */  lw    $t1, 0x80($sp)
/* 039B74 8027EB74 000C68C0 */  sll   $t5, $t4, 3
/* 039B78 8027EB78 012D5021 */  addu  $t2, $t1, $t5
/* 039B7C 8027EB7C 8D580048 */  lw    $t8, 0x48($t2)
/* 039B80 8027EB80 8D2E0018 */  lw    $t6, 0x18($t1)
/* 039B84 8027EB84 8D59004C */  lw    $t9, 0x4c($t2)
/* 039B88 8027EB88 8D2F001C */  lw    $t7, 0x1c($t1)
/* 039B8C 8027EB8C 01D8082B */  sltu  $at, $t6, $t8
/* 039B90 8027EB90 14200014 */  bnez  $at, .L8027EBE4
/* 039B94 8027EB94 00000000 */   nop   
/* 039B98 8027EB98 030E082B */  sltu  $at, $t8, $t6
/* 039B9C 8027EB9C 14200004 */  bnez  $at, .L8027EBB0
/* 039BA0 8027EBA0 00000000 */   nop   
/* 039BA4 8027EBA4 032F082B */  sltu  $at, $t9, $t7
/* 039BA8 8027EBA8 1020000E */  beqz  $at, .L8027EBE4
/* 039BAC 8027EBAC 00000000 */   nop   
.L8027EBB0:
/* 039BB0 8027EBB0 27AB0068 */  addiu $t3, $sp, 0x68
/* 039BB4 8027EBB4 AFAB0034 */  sw    $t3, 0x34($sp)
/* 039BB8 8027EBB8 8D690004 */  lw    $t1, 4($t3)
/* 039BBC 8027EBBC 8D680000 */  lw    $t0, ($t3)
/* 039BC0 8027EBC0 8FAC0040 */  lw    $t4, 0x40($sp)
/* 039BC4 8027EBC4 8FAD0044 */  lw    $t5, 0x44($sp)
/* 039BC8 8027EBC8 0160C025 */  move  $t8, $t3
/* 039BCC 8027EBCC 010C5023 */  subu  $t2, $t0, $t4
/* 039BD0 8027EBD0 012D082B */  sltu  $at, $t1, $t5
/* 039BD4 8027EBD4 01415023 */  subu  $t2, $t2, $at
/* 039BD8 8027EBD8 012D5823 */  subu  $t3, $t1, $t5
/* 039BDC 8027EBDC AF0B0004 */  sw    $t3, 4($t8)
/* 039BE0 8027EBE0 AF0A0000 */  sw    $t2, ($t8)
.L8027EBE4:
/* 039BE4 8027EBE4 8FB90084 */  lw    $t9, 0x84($sp)
/* 039BE8 8027EBE8 8FAF0080 */  lw    $t7, 0x80($sp)
/* 039BEC 8027EBEC 272E0002 */  addiu $t6, $t9, 2
/* 039BF0 8027EBF0 AFAE0084 */  sw    $t6, 0x84($sp)
/* 039BF4 8027EBF4 85E80000 */  lh    $t0, ($t7)
/* 039BF8 8027EBF8 01C8082A */  slt   $at, $t6, $t0
/* 039BFC 8027EBFC 1420FFA1 */  bnez  $at, .L8027EA84
/* 039C00 8027EC00 00000000 */   nop   
.L8027EC04:
/* 039C04 8027EC04 8FA90080 */  lw    $t1, 0x80($sp)
/* 039C08 8027EC08 852C0000 */  lh    $t4, ($t1)
/* 039C0C 8027EC0C 318DFFFE */  andi  $t5, $t4, 0xfffe
/* 039C10 8027EC10 A52D0000 */  sh    $t5, ($t1)
/* 039C14 8027EC14 8FAA0080 */  lw    $t2, 0x80($sp)
/* 039C18 8027EC18 AFA00084 */  sw    $zero, 0x84($sp)
/* 039C1C 8027EC1C 854B0000 */  lh    $t3, ($t2)
/* 039C20 8027EC20 1960001F */  blez  $t3, .L8027ECA0
/* 039C24 8027EC24 00000000 */   nop   
.L8027EC28:
/* 039C28 8027EC28 8FAF0084 */  lw    $t7, 0x84($sp)
/* 039C2C 8027EC2C 8FB90080 */  lw    $t9, 0x80($sp)
/* 039C30 8027EC30 27B80048 */  addiu $t8, $sp, 0x48
/* 039C34 8027EC34 000F70C0 */  sll   $t6, $t7, 3
/* 039C38 8027EC38 AFB80030 */  sw    $t8, 0x30($sp)
/* 039C3C 8027EC3C 032E4021 */  addu  $t0, $t9, $t6
/* 039C40 8027EC40 8D0D0094 */  lw    $t5, 0x94($t0)
/* 039C44 8027EC44 8D0B008C */  lw    $t3, 0x8c($t0)
/* 039C48 8027EC48 8D0C0090 */  lw    $t4, 0x90($t0)
/* 039C4C 8027EC4C 8D0A0088 */  lw    $t2, 0x88($t0)
/* 039C50 8027EC50 8F090004 */  lw    $t1, 4($t8)
/* 039C54 8027EC54 01AB082B */  sltu  $at, $t5, $t3
/* 039C58 8027EC58 01AB7823 */  subu  $t7, $t5, $t3
/* 039C5C 8027EC5C 018A7023 */  subu  $t6, $t4, $t2
/* 039C60 8027EC60 8F080000 */  lw    $t0, ($t8)
/* 039C64 8027EC64 01C17023 */  subu  $t6, $t6, $at
/* 039C68 8027EC68 01E96821 */  addu  $t5, $t7, $t1
/* 039C6C 8027EC6C 01A9082B */  sltu  $at, $t5, $t1
/* 039C70 8027EC70 002E6021 */  addu  $t4, $at, $t6
/* 039C74 8027EC74 01886021 */  addu  $t4, $t4, $t0
/* 039C78 8027EC78 AF0C0000 */  sw    $t4, ($t8)
/* 039C7C 8027EC7C AF0D0004 */  sw    $t5, 4($t8)
/* 039C80 8027EC80 8FB90084 */  lw    $t9, 0x84($sp)
/* 039C84 8027EC84 8FAB0080 */  lw    $t3, 0x80($sp)
/* 039C88 8027EC88 272A0002 */  addiu $t2, $t9, 2
/* 039C8C 8027EC8C AFAA0084 */  sw    $t2, 0x84($sp)
/* 039C90 8027EC90 856E0000 */  lh    $t6, ($t3)
/* 039C94 8027EC94 014E082A */  slt   $at, $t2, $t6
/* 039C98 8027EC98 1420FFE3 */  bnez  $at, .L8027EC28
/* 039C9C 8027EC9C 00000000 */   nop   
.L8027ECA0:
/* 039CA0 8027ECA0 24080000 */  li    $t0, 0
/* 039CA4 8027ECA4 24090000 */  li    $t1, 0
/* 039CA8 8027ECA8 AFA9007C */  sw    $t1, 0x7c($sp)
/* 039CAC 8027ECAC AFA80078 */  sw    $t0, 0x78($sp)
/* 039CB0 8027ECB0 8FAD007C */  lw    $t5, 0x7c($sp)
/* 039CB4 8027ECB4 8FB90064 */  lw    $t9, 0x64($sp)
/* 039CB8 8027ECB8 8FAC0078 */  lw    $t4, 0x78($sp)
/* 039CBC 8027ECBC 8FB80060 */  lw    $t8, 0x60($sp)
/* 039CC0 8027ECC0 01B95821 */  addu  $t3, $t5, $t9
/* 039CC4 8027ECC4 0179082B */  sltu  $at, $t3, $t9
/* 039CC8 8027ECC8 002C5021 */  addu  $t2, $at, $t4
/* 039CCC 8027ECCC 240F00D4 */  li    $t7, 212
/* 039CD0 8027ECD0 340EF94B */  li    $t6, 63819
/* 039CD4 8027ECD4 01585021 */  addu  $t2, $t2, $t8
/* 039CD8 8027ECD8 AFAA0010 */  sw    $t2, 0x10($sp)
/* 039CDC 8027ECDC AFAE001C */  sw    $t6, 0x1c($sp)
/* 039CE0 8027ECE0 AFAF0018 */  sw    $t7, 0x18($sp)
/* 039CE4 8027ECE4 AFAB0014 */  sw    $t3, 0x14($sp)
/* 039CE8 8027ECE8 24040000 */  li    $a0, 0
/* 039CEC 8027ECEC 24050000 */  li    $a1, 0
/* 039CF0 8027ECF0 01A03825 */  move  $a3, $t5
/* 039CF4 8027ECF4 0C09F82B */  jal   func_8027E0AC
/* 039CF8 8027ECF8 01803025 */   move  $a2, $t4
/* 039CFC 8027ECFC 27A80078 */  addiu $t0, $sp, 0x78
/* 039D00 8027ED00 AFA8002C */  sw    $t0, 0x2c($sp)
/* 039D04 8027ED04 8D0D0004 */  lw    $t5, 4($t0)
/* 039D08 8027ED08 8FB90064 */  lw    $t9, 0x64($sp)
/* 039D0C 8027ED0C 8D0C0000 */  lw    $t4, ($t0)
/* 039D10 8027ED10 8FB80060 */  lw    $t8, 0x60($sp)
/* 039D14 8027ED14 01B95821 */  addu  $t3, $t5, $t9
/* 039D18 8027ED18 0179082B */  sltu  $at, $t3, $t9
/* 039D1C 8027ED1C 002C5021 */  addu  $t2, $at, $t4
/* 039D20 8027ED20 01585021 */  addu  $t2, $t2, $t8
/* 039D24 8027ED24 AD0A0000 */  sw    $t2, ($t0)
/* 039D28 8027ED28 AD0B0004 */  sw    $t3, 4($t0)
/* 039D2C 8027ED2C 8FAF007C */  lw    $t7, 0x7c($sp)
/* 039D30 8027ED30 8FAD0074 */  lw    $t5, 0x74($sp)
/* 039D34 8027ED34 8FAE0078 */  lw    $t6, 0x78($sp)
/* 039D38 8027ED38 8FAC0070 */  lw    $t4, 0x70($sp)
/* 039D3C 8027ED3C 01EDC821 */  addu  $t9, $t7, $t5
/* 039D40 8027ED40 032D082B */  sltu  $at, $t9, $t5
/* 039D44 8027ED44 002EC021 */  addu  $t8, $at, $t6
/* 039D48 8027ED48 240900D4 */  li    $t1, 212
/* 039D4C 8027ED4C 340AFFCB */  li    $t2, 65483
/* 039D50 8027ED50 030CC021 */  addu  $t8, $t8, $t4
/* 039D54 8027ED54 AFB80010 */  sw    $t8, 0x10($sp)
/* 039D58 8027ED58 AFAA001C */  sw    $t2, 0x1c($sp)
/* 039D5C 8027ED5C AFA90018 */  sw    $t1, 0x18($sp)
/* 039D60 8027ED60 AFB90014 */  sw    $t9, 0x14($sp)
/* 039D64 8027ED64 24040000 */  li    $a0, 0
/* 039D68 8027ED68 24050000 */  li    $a1, 0
/* 039D6C 8027ED6C 01E03825 */  move  $a3, $t7
/* 039D70 8027ED70 0C09F82B */  jal   func_8027E0AC
/* 039D74 8027ED74 01C03025 */   move  $a2, $t6
/* 039D78 8027ED78 27AB0078 */  addiu $t3, $sp, 0x78
/* 039D7C 8027ED7C AFAB0028 */  sw    $t3, 0x28($sp)
/* 039D80 8027ED80 8D690004 */  lw    $t1, 4($t3)
/* 039D84 8027ED84 8FAF0074 */  lw    $t7, 0x74($sp)
/* 039D88 8027ED88 8D680000 */  lw    $t0, ($t3)
/* 039D8C 8027ED8C 8FAE0070 */  lw    $t6, 0x70($sp)
/* 039D90 8027ED90 012F6821 */  addu  $t5, $t1, $t7
/* 039D94 8027ED94 01AF082B */  sltu  $at, $t5, $t7
/* 039D98 8027ED98 00286021 */  addu  $t4, $at, $t0
/* 039D9C 8027ED9C 018E6021 */  addu  $t4, $t4, $t6
/* 039DA0 8027EDA0 AD6C0000 */  sw    $t4, ($t3)
/* 039DA4 8027EDA4 AD6D0004 */  sw    $t5, 4($t3)
/* 039DA8 8027EDA8 8FB9007C */  lw    $t9, 0x7c($sp)
/* 039DAC 8027EDAC 8FAB006C */  lw    $t3, 0x6c($sp)
/* 039DB0 8027EDB0 8FB80078 */  lw    $t8, 0x78($sp)
/* 039DB4 8027EDB4 8FAA0068 */  lw    $t2, 0x68($sp)
/* 039DB8 8027EDB8 032B4821 */  addu  $t1, $t9, $t3
/* 039DBC 8027EDBC 012B082B */  sltu  $at, $t1, $t3
/* 039DC0 8027EDC0 00384021 */  addu  $t0, $at, $t8
/* 039DC4 8027EDC4 240E00D4 */  li    $t6, 212
/* 039DC8 8027EDC8 340FFBCB */  li    $t7, 64459
/* 039DCC 8027EDCC 010A4021 */  addu  $t0, $t0, $t2
/* 039DD0 8027EDD0 AFA80010 */  sw    $t0, 0x10($sp)
/* 039DD4 8027EDD4 AFAF001C */  sw    $t7, 0x1c($sp)
/* 039DD8 8027EDD8 AFAE0018 */  sw    $t6, 0x18($sp)
/* 039DDC 8027EDDC AFA90014 */  sw    $t1, 0x14($sp)
/* 039DE0 8027EDE0 24040000 */  li    $a0, 0
/* 039DE4 8027EDE4 24050000 */  li    $a1, 0
/* 039DE8 8027EDE8 03203825 */  move  $a3, $t9
/* 039DEC 8027EDEC 0C09F82B */  jal   func_8027E0AC
/* 039DF0 8027EDF0 03003025 */   move  $a2, $t8
/* 039DF4 8027EDF4 8FAC0050 */  lw    $t4, 0x50($sp)
/* 039DF8 8027EDF8 8FAD0054 */  lw    $t5, 0x54($sp)
/* 039DFC 8027EDFC 241800D8 */  li    $t8, 216
/* 039E00 8027EE00 3419FBCB */  li    $t9, 64459
/* 039E04 8027EE04 AFB9001C */  sw    $t9, 0x1c($sp)
/* 039E08 8027EE08 AFB80018 */  sw    $t8, 0x18($sp)
/* 039E0C 8027EE0C 24040000 */  li    $a0, 0
/* 039E10 8027EE10 24050000 */  li    $a1, 0
/* 039E14 8027EE14 24060000 */  li    $a2, 0
/* 039E18 8027EE18 24070000 */  li    $a3, 0
/* 039E1C 8027EE1C AFAC0010 */  sw    $t4, 0x10($sp)
/* 039E20 8027EE20 0C09F82B */  jal   func_8027E0AC
/* 039E24 8027EE24 AFAD0014 */   sw    $t5, 0x14($sp)
/* 039E28 8027EE28 8FAA0058 */  lw    $t2, 0x58($sp)
/* 039E2C 8027EE2C 8FAB005C */  lw    $t3, 0x5c($sp)
/* 039E30 8027EE30 240800D8 */  li    $t0, 216
/* 039E34 8027EE34 3409FFCB */  li    $t1, 65483
/* 039E38 8027EE38 AFA9001C */  sw    $t1, 0x1c($sp)
/* 039E3C 8027EE3C AFA80018 */  sw    $t0, 0x18($sp)
/* 039E40 8027EE40 24040000 */  li    $a0, 0
/* 039E44 8027EE44 24050000 */  li    $a1, 0
/* 039E48 8027EE48 24060000 */  li    $a2, 0
/* 039E4C 8027EE4C 24070000 */  li    $a3, 0
/* 039E50 8027EE50 AFAA0010 */  sw    $t2, 0x10($sp)
/* 039E54 8027EE54 0C09F82B */  jal   func_8027E0AC
/* 039E58 8027EE58 AFAB0014 */   sw    $t3, 0x14($sp)
/* 039E5C 8027EE5C 8FAE0048 */  lw    $t6, 0x48($sp)
/* 039E60 8027EE60 8FAF004C */  lw    $t7, 0x4c($sp)
/* 039E64 8027EE64 240C00D8 */  li    $t4, 216
/* 039E68 8027EE68 340DF94B */  li    $t5, 63819
/* 039E6C 8027EE6C AFAD001C */  sw    $t5, 0x1c($sp)
/* 039E70 8027EE70 AFAC0018 */  sw    $t4, 0x18($sp)
/* 039E74 8027EE74 24040000 */  li    $a0, 0
/* 039E78 8027EE78 24050000 */  li    $a1, 0
/* 039E7C 8027EE7C 24060000 */  li    $a2, 0
/* 039E80 8027EE80 24070000 */  li    $a3, 0
/* 039E84 8027EE84 AFAE0010 */  sw    $t6, 0x10($sp)
/* 039E88 8027EE88 0C09F82B */  jal   func_8027E0AC
/* 039E8C 8027EE8C AFAF0014 */   sw    $t7, 0x14($sp)
/* 039E90 8027EE90 0C09F8EA */  jal   func_8027E3A8
/* 039E94 8027EE94 00000000 */   nop   
/* 039E98 8027EE98 10000001 */  b     .L8027EEA0
/* 039E9C 8027EE9C 00000000 */   nop   
.L8027EEA0:
/* 039EA0 8027EEA0 8FBF0024 */  lw    $ra, 0x24($sp)
/* 039EA4 8027EEA4 27BD0088 */  addiu $sp, $sp, 0x88
/* 039EA8 8027EEA8 03E00008 */  jr    $ra
/* 039EAC 8027EEAC 00000000 */   nop   

glabel func_8027EEB0
/* 039EB0 8027EEB0 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 039EB4 8027EEB4 AFBF0014 */  sw    $ra, 0x14($sp)
/* 039EB8 8027EEB8 3C0E8033 */  lui   $t6, %hi(gPlayer1Controller) # $t6, 0x8033
/* 039EBC 8027EEBC 8DCEC6A4 */  lw    $t6, %lo(gPlayer1Controller)($t6)
/* 039EC0 8027EEC0 95CF0012 */  lhu   $t7, 0x12($t6)
/* 039EC4 8027EEC4 31F80020 */  andi  $t8, $t7, 0x20
/* 039EC8 8027EEC8 13000006 */  beqz  $t8, .L8027EEE4
/* 039ECC 8027EECC 00000000 */   nop   
/* 039ED0 8027EED0 3C198033 */  lui   $t9, %hi(D_8032CFB0) # $t9, 0x8033
/* 039ED4 8027EED4 8739CFB0 */  lh    $t9, %lo(D_8032CFB0)($t9)
/* 039ED8 8027EED8 3C018033 */  lui   $at, %hi(D_8032CFB0) # $at, 0x8033
/* 039EDC 8027EEDC 3B280001 */  xori  $t0, $t9, 1
/* 039EE0 8027EEE0 A428CFB0 */  sh    $t0, %lo(D_8032CFB0)($at)
.L8027EEE4:
/* 039EE4 8027EEE4 3C098033 */  lui   $t1, %hi(D_8032CFB0) # $t1, 0x8033
/* 039EE8 8027EEE8 8529CFB0 */  lh    $t1, %lo(D_8032CFB0)($t1)
/* 039EEC 8027EEEC 15200005 */  bnez  $t1, .L8027EF04
/* 039EF0 8027EEF0 00000000 */   nop   
/* 039EF4 8027EEF4 0C09FA3F */  jal   func_8027E8FC
/* 039EF8 8027EEF8 00000000 */   nop   
/* 039EFC 8027EEFC 10000003 */  b     .L8027EF0C
/* 039F00 8027EF00 00000000 */   nop   
.L8027EF04:
/* 039F04 8027EF04 0C09F987 */  jal   func_8027E61C
/* 039F08 8027EF08 00000000 */   nop   
.L8027EF0C:
/* 039F0C 8027EF0C 10000001 */  b     .L8027EF14
/* 039F10 8027EF10 00000000 */   nop   
.L8027EF14:
/* 039F14 8027EF14 8FBF0014 */  lw    $ra, 0x14($sp)
/* 039F18 8027EF18 27BD0018 */  addiu $sp, $sp, 0x18
/* 039F1C 8027EF1C 03E00008 */  jr    $ra
/* 039F20 8027EF20 00000000 */   nop   

/* 039F24 8027EF24 00000000 */  nop   
/* 039F28 8027EF28 00000000 */  nop   
/* 039F2C 8027EF2C 00000000 */  nop   
