# Super Mario 64 (J) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"
.include "globals.inc"

.section .text, "ax"

glabel func_801780A0
/* 226870 801780A0 3C01801C */  lui   $at, %hi(D_801B9B24) # $at, 0x801c
/* 226874 801780A4 AC209B24 */  sw    $zero, %lo(D_801B9B24)($at)
/* 226878 801780A8 3C01801C */  lui   $at, %hi(D_801B9B20) # $at, 0x801c
/* 22687C 801780AC AC209B20 */  sw    $zero, %lo(D_801B9B20)($at)
/* 226880 801780B0 03E00008 */  jr    $ra
/* 226884 801780B4 00000000 */   nop   

/* 226888 801780B8 03E00008 */  jr    $ra
/* 22688C 801780BC 00000000 */   nop   

glabel func_801780C0
/* 226890 801780C0 3C0E801C */  lui   $t6, %hi(D_801B9B24) # $t6, 0x801c
/* 226894 801780C4 8DCE9B24 */  lw    $t6, %lo(D_801B9B24)($t6)
/* 226898 801780C8 3C18801C */  lui   $t8, %hi(D_801B9B20) # $t8, 0x801c
/* 22689C 801780CC 8F189B20 */  lw    $t8, %lo(D_801B9B20)($t8)
/* 2268A0 801780D0 01C07827 */  not   $t7, $t6
/* 2268A4 801780D4 03E00008 */  jr    $ra
/* 2268A8 801780D8 01F81024 */   and   $v0, $t7, $t8

/* 2268AC 801780DC 03E00008 */  jr    $ra
/* 2268B0 801780E0 00000000 */   nop   

/* 2268B4 801780E4 03E00008 */  jr    $ra
/* 2268B8 801780E8 00000000 */   nop   

glabel func_801780EC
/* 2268BC 801780EC 3C0E801C */  lui   $t6, %hi(D_801B9B20) # $t6, 0x801c
/* 2268C0 801780F0 8DCE9B20 */  lw    $t6, %lo(D_801B9B20)($t6)
/* 2268C4 801780F4 3C01801C */  lui   $at, %hi(D_801B9B24) # $at, 0x801c
/* 2268C8 801780F8 AC2E9B24 */  sw    $t6, %lo(D_801B9B24)($at)
/* 2268CC 801780FC 3C01801C */  lui   $at, %hi(D_801B9B20) # $at, 0x801c
/* 2268D0 80178100 AC209B20 */  sw    $zero, %lo(D_801B9B20)($at)
/* 2268D4 80178104 03E00008 */  jr    $ra
/* 2268D8 80178108 00000000 */   nop   

/* 2268DC 8017810C 03E00008 */  jr    $ra
/* 2268E0 80178110 00000000 */   nop   

glabel func_80178114
/* 2268E4 80178114 3C0E801C */  lui   $t6, %hi(D_801B9B20) # $t6, 0x801c
/* 2268E8 80178118 8DCE9B20 */  lw    $t6, %lo(D_801B9B20)($t6)
/* 2268EC 8017811C 3C01801C */  lui   $at, %hi(D_801B9B20) # $at, 0x801c
/* 2268F0 80178120 01C47825 */  or    $t7, $t6, $a0
/* 2268F4 80178124 AC2F9B20 */  sw    $t7, %lo(D_801B9B20)($at)
/* 2268F8 80178128 03E00008 */  jr    $ra
/* 2268FC 8017812C 00000000 */   nop   

/* 226900 80178130 03E00008 */  jr    $ra
/* 226904 80178134 00000000 */   nop   

/* 226908 80178138 00000000 */  nop   
/* 22690C 8017813C 00000000 */  nop   
