# Super Mario 64 (J) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"
.include "globals.inc"

.section .text, "ax"

glabel Geo18_8016F670
/* 21DDA0 8016F5D0 27BDFFB0 */  addiu $sp, $sp, -0x50
/* 21DDA4 8016F5D4 AFBF0014 */  sw    $ra, 0x14($sp)
/* 21DDA8 8016F5D8 AFA40050 */  sw    $a0, 0x50($sp)
/* 21DDAC 8016F5DC AFA50054 */  sw    $a1, 0x54($sp)
/* 21DDB0 8016F5E0 AFA60058 */  sw    $a2, 0x58($sp)
/* 21DDB4 8016F5E4 8FAE0054 */  lw    $t6, 0x54($sp)
/* 21DDB8 8016F5E8 AFAE004C */  sw    $t6, 0x4c($sp)
/* 21DDBC 8016F5EC AFA00048 */  sw    $zero, 0x48($sp)
/* 21DDC0 8016F5F0 AFA00044 */  sw    $zero, 0x44($sp)
/* 21DDC4 8016F5F4 3C040701 */  lui   $a0, %hi(D_0700C790) # $a0, 0x701
/* 21DDC8 8016F5F8 0C09DE68 */  jal   segmented_to_virtual
/* 21DDCC 8016F5FC 2484C790 */   addiu $a0, %lo(D_0700C790) # addiu $a0, $a0, -0x3870
/* 21DDD0 8016F600 AFA2003C */  sw    $v0, 0x3c($sp)
/* 21DDD4 8016F604 3C040701 */  lui   $a0, %hi(D_0700C880) # $a0, 0x701
/* 21DDD8 8016F608 0C09DE68 */  jal   segmented_to_virtual
/* 21DDDC 8016F60C 2484C880 */   addiu $a0, %lo(D_0700C880) # addiu $a0, $a0, -0x3780
/* 21DDE0 8016F610 AFA20038 */  sw    $v0, 0x38($sp)
/* 21DDE4 8016F614 8FAF0050 */  lw    $t7, 0x50($sp)
/* 21DDE8 8016F618 24010001 */  li    $at, 1
/* 21DDEC 8016F61C 11E10004 */  beq   $t7, $at, .L8016F630
/* 21DDF0 8016F620 00000000 */   nop   
/* 21DDF4 8016F624 3C01801C */  lui   $at, %hi(D_801B9858) # $at, 0x801c
/* 21DDF8 8016F628 100000A6 */  b     .L8016F8C4
/* 21DDFC 8016F62C A4209858 */   sh    $zero, %lo(D_801B9858)($at)
.L8016F630:
/* 21DE00 8016F630 8FB80050 */  lw    $t8, 0x50($sp)
/* 21DE04 8016F634 24010001 */  li    $at, 1
/* 21DE08 8016F638 170100A2 */  bne   $t8, $at, .L8016F8C4
/* 21DE0C 8016F63C 00000000 */   nop   
/* 21DE10 8016F640 8FB9004C */  lw    $t9, 0x4c($sp)
/* 21DE14 8016F644 87280002 */  lh    $t0, 2($t9)
/* 21DE18 8016F648 310900FF */  andi  $t1, $t0, 0xff
/* 21DE1C 8016F64C 352A0100 */  ori   $t2, $t1, 0x100
/* 21DE20 8016F650 A72A0002 */  sh    $t2, 2($t9)
/* 21DE24 8016F654 0C09E25F */  jal   alloc_display_list
/* 21DE28 8016F658 24040040 */   li    $a0, 64
/* 21DE2C 8016F65C AFA20040 */  sw    $v0, 0x40($sp)
/* 21DE30 8016F660 0C09E25F */  jal   alloc_display_list
/* 21DE34 8016F664 24040020 */   li    $a0, 32
/* 21DE38 8016F668 AFA20048 */  sw    $v0, 0x48($sp)
/* 21DE3C 8016F66C 8FAB0048 */  lw    $t3, 0x48($sp)
/* 21DE40 8016F670 AFAB0044 */  sw    $t3, 0x44($sp)
/* 21DE44 8016F674 3C0C801C */  lui   $t4, %hi(D_801B9858) # $t4, 0x801c
/* 21DE48 8016F678 858C9858 */  lh    $t4, %lo(D_801B9858)($t4)
/* 21DE4C 8016F67C 05800020 */  bltz  $t4, .L8016F700
/* 21DE50 8016F680 00000000 */   nop   
/* 21DE54 8016F684 29810014 */  slti  $at, $t4, 0x14
/* 21DE58 8016F688 1020001D */  beqz  $at, .L8016F700
/* 21DE5C 8016F68C 00000000 */   nop   
/* 21DE60 8016F690 3C0E801C */  lui   $t6, %hi(D_801B9858) # $t6, 0x801c
/* 21DE64 8016F694 85CE9858 */  lh    $t6, %lo(D_801B9858)($t6)
/* 21DE68 8016F698 8FAD003C */  lw    $t5, 0x3c($sp)
/* 21DE6C 8016F69C 000E7880 */  sll   $t7, $t6, 2
/* 21DE70 8016F6A0 01EE7823 */  subu  $t7, $t7, $t6
/* 21DE74 8016F6A4 000FC080 */  sll   $t8, $t7, 2
/* 21DE78 8016F6A8 01B84021 */  addu  $t0, $t5, $t8
/* 21DE7C 8016F6AC C5040000 */  lwc1  $f4, ($t0)
/* 21DE80 8016F6B0 E7A40034 */  swc1  $f4, 0x34($sp)
/* 21DE84 8016F6B4 3C0A801C */  lui   $t2, %hi(D_801B9858) # $t2, 0x801c
/* 21DE88 8016F6B8 854A9858 */  lh    $t2, %lo(D_801B9858)($t2)
/* 21DE8C 8016F6BC 8FA9003C */  lw    $t1, 0x3c($sp)
/* 21DE90 8016F6C0 000AC880 */  sll   $t9, $t2, 2
/* 21DE94 8016F6C4 032AC823 */  subu  $t9, $t9, $t2
/* 21DE98 8016F6C8 00195880 */  sll   $t3, $t9, 2
/* 21DE9C 8016F6CC 012B6021 */  addu  $t4, $t1, $t3
/* 21DEA0 8016F6D0 C5860004 */  lwc1  $f6, 4($t4)
/* 21DEA4 8016F6D4 E7A60030 */  swc1  $f6, 0x30($sp)
/* 21DEA8 8016F6D8 3C0F801C */  lui   $t7, %hi(D_801B9858) # $t7, 0x801c
/* 21DEAC 8016F6DC 85EF9858 */  lh    $t7, %lo(D_801B9858)($t7)
/* 21DEB0 8016F6E0 8FAE003C */  lw    $t6, 0x3c($sp)
/* 21DEB4 8016F6E4 000F6880 */  sll   $t5, $t7, 2
/* 21DEB8 8016F6E8 01AF6823 */  subu  $t5, $t5, $t7
/* 21DEBC 8016F6EC 000DC080 */  sll   $t8, $t5, 2
/* 21DEC0 8016F6F0 01D84021 */  addu  $t0, $t6, $t8
/* 21DEC4 8016F6F4 C5080008 */  lwc1  $f8, 8($t0)
/* 21DEC8 8016F6F8 10000042 */  b     .L8016F804
/* 21DECC 8016F6FC E7A8002C */   swc1  $f8, 0x2c($sp)
.L8016F700:
/* 21DED0 8016F700 3C0A801C */  lui   $t2, %hi(D_801B9858) # $t2, 0x801c
/* 21DED4 8016F704 854A9858 */  lh    $t2, %lo(D_801B9858)($t2)
/* 21DED8 8016F708 29410014 */  slti  $at, $t2, 0x14
/* 21DEDC 8016F70C 14200010 */  bnez  $at, .L8016F750
/* 21DEE0 8016F710 00000000 */   nop   
/* 21DEE4 8016F714 2941004B */  slti  $at, $t2, 0x4b
/* 21DEE8 8016F718 1020000D */  beqz  $at, .L8016F750
/* 21DEEC 8016F71C 00000000 */   nop   
/* 21DEF0 8016F720 3C013F80 */  li    $at, 0x3F800000 # 1.000000
/* 21DEF4 8016F724 44815000 */  mtc1  $at, $f10
/* 21DEF8 8016F728 00000000 */  nop   
/* 21DEFC 8016F72C E7AA0034 */  swc1  $f10, 0x34($sp)
/* 21DF00 8016F730 3C013F80 */  li    $at, 0x3F800000 # 1.000000
/* 21DF04 8016F734 44818000 */  mtc1  $at, $f16
/* 21DF08 8016F738 00000000 */  nop   
/* 21DF0C 8016F73C E7B00030 */  swc1  $f16, 0x30($sp)
/* 21DF10 8016F740 3C013F80 */  li    $at, 0x3F800000 # 1.000000
/* 21DF14 8016F744 44819000 */  mtc1  $at, $f18
/* 21DF18 8016F748 1000002E */  b     .L8016F804
/* 21DF1C 8016F74C E7B2002C */   swc1  $f18, 0x2c($sp)
.L8016F750:
/* 21DF20 8016F750 3C19801C */  lui   $t9, %hi(D_801B9858) # $t9, 0x801c
/* 21DF24 8016F754 87399858 */  lh    $t9, %lo(D_801B9858)($t9)
/* 21DF28 8016F758 2B21004B */  slti  $at, $t9, 0x4b
/* 21DF2C 8016F75C 14200020 */  bnez  $at, .L8016F7E0
/* 21DF30 8016F760 00000000 */   nop   
/* 21DF34 8016F764 2B21005B */  slti  $at, $t9, 0x5b
/* 21DF38 8016F768 1020001D */  beqz  $at, .L8016F7E0
/* 21DF3C 8016F76C 00000000 */   nop   
/* 21DF40 8016F770 3C0B801C */  lui    $t3, %hi(D_801B9858) # 0.000000
/* 21DF44 8016F774 856B9858 */  lh    $t3, %lo(D_801B9858)($t3)
/* 21DF48 8016F778 8FA90038 */  lw    $t1, 0x38($sp)
/* 21DF4C 8016F77C 000B6080 */  sll   $t4, $t3, 2
/* 21DF50 8016F780 018B6023 */  subu  $t4, $t4, $t3
/* 21DF54 8016F784 000C7880 */  sll   $t7, $t4, 2
/* 21DF58 8016F788 012F6821 */  addu  $t5, $t1, $t7
/* 21DF5C 8016F78C C5A4FC7C */  lwc1  $f4, -0x384($t5)
/* 21DF60 8016F790 E7A40034 */  swc1  $f4, 0x34($sp)
/* 21DF64 8016F794 3C18801C */  lui    $t8, %hi(D_801B9858) # 0.000000
/* 21DF68 8016F798 87189858 */  lh    $t8, %lo(D_801B9858)($t8)
/* 21DF6C 8016F79C 8FAE0038 */  lw    $t6, 0x38($sp)
/* 21DF70 8016F7A0 00184080 */  sll   $t0, $t8, 2
/* 21DF74 8016F7A4 01184023 */  subu  $t0, $t0, $t8
/* 21DF78 8016F7A8 00085080 */  sll   $t2, $t0, 2
/* 21DF7C 8016F7AC 01CAC821 */  addu  $t9, $t6, $t2
/* 21DF80 8016F7B0 C726FC80 */  lwc1  $f6, -0x380($t9)
/* 21DF84 8016F7B4 E7A60030 */  swc1  $f6, 0x30($sp)
/* 21DF88 8016F7B8 3C0C801C */  lui    $t4, %hi(D_801B9858) # 0.000000
/* 21DF8C 8016F7BC 858C9858 */  lh    $t4, %lo(D_801B9858)($t4)
/* 21DF90 8016F7C0 8FAB0038 */  lw    $t3, 0x38($sp)
/* 21DF94 8016F7C4 000C4880 */  sll   $t1, $t4, 2
/* 21DF98 8016F7C8 012C4823 */  subu  $t1, $t1, $t4
/* 21DF9C 8016F7CC 00097880 */  sll   $t7, $t1, 2
/* 21DFA0 8016F7D0 016F6821 */  addu  $t5, $t3, $t7
/* 21DFA4 8016F7D4 C5A8FC84 */  lwc1  $f8, -0x37c($t5)
/* 21DFA8 8016F7D8 1000000A */  b     .L8016F804
/* 21DFAC 8016F7DC E7A8002C */   swc1  $f8, 0x2c($sp)
.L8016F7E0:
/* 21DFB0 8016F7E0 44805000 */  mtc1  $zero, $f10
/* 21DFB4 8016F7E4 00000000 */  nop   
/* 21DFB8 8016F7E8 E7AA0034 */  swc1  $f10, 0x34($sp)
/* 21DFBC 8016F7EC 44808000 */  mtc1  $zero, $f16
/* 21DFC0 8016F7F0 00000000 */  nop   
/* 21DFC4 8016F7F4 E7B00030 */  swc1  $f16, 0x30($sp)
/* 21DFC8 8016F7F8 44809000 */  mtc1  $zero, $f18
/* 21DFCC 8016F7FC 00000000 */  nop   
/* 21DFD0 8016F800 E7B2002C */  swc1  $f18, 0x2c($sp)
.L8016F804:
/* 21DFD4 8016F804 8FA40040 */  lw    $a0, 0x40($sp)
/* 21DFD8 8016F808 8FA50034 */  lw    $a1, 0x34($sp)
/* 21DFDC 8016F80C 8FA60030 */  lw    $a2, 0x30($sp)
/* 21DFE0 8016F810 0C0C927D */  jal   guScale
/* 21DFE4 8016F814 8FA7002C */   lw    $a3, 0x2c($sp)
/* 21DFE8 8016F818 8FB80044 */  lw    $t8, 0x44($sp)
/* 21DFEC 8016F81C 27080008 */  addiu $t0, $t8, 8
/* 21DFF0 8016F820 AFA80044 */  sw    $t0, 0x44($sp)
/* 21DFF4 8016F824 AFB80028 */  sw    $t8, 0x28($sp)
/* 21DFF8 8016F828 8FAA0028 */  lw    $t2, 0x28($sp)
/* 21DFFC 8016F82C 3C0E0104 */  lui   $t6, (0x01040040 >> 16) # lui $t6, 0x104
/* 21E000 8016F830 35CE0040 */  ori   $t6, (0x01040040 & 0xFFFF) # ori $t6, $t6, 0x40
/* 21E004 8016F834 AD4E0000 */  sw    $t6, ($t2)
/* 21E008 8016F838 8FB90040 */  lw    $t9, 0x40($sp)
/* 21E00C 8016F83C 8FAC0028 */  lw    $t4, 0x28($sp)
/* 21E010 8016F840 AD990004 */  sw    $t9, 4($t4)
/* 21E014 8016F844 8FA90044 */  lw    $t1, 0x44($sp)
/* 21E018 8016F848 252B0008 */  addiu $t3, $t1, 8
/* 21E01C 8016F84C AFAB0044 */  sw    $t3, 0x44($sp)
/* 21E020 8016F850 AFA90024 */  sw    $t1, 0x24($sp)
/* 21E024 8016F854 8FAD0024 */  lw    $t5, 0x24($sp)
/* 21E028 8016F858 3C0F0600 */  lui   $t7, 0x600
/* 21E02C 8016F85C ADAF0000 */  sw    $t7, ($t5)
/* 21E030 8016F860 8FA80024 */  lw    $t0, 0x24($sp)
/* 21E034 8016F864 3C180701 */  lui   $t8, %hi(D_0700B3A0) # $t8, 0x701
/* 21E038 8016F868 2718B3A0 */  addiu $t8, %lo(D_0700B3A0) # addiu $t8, $t8, -0x4c60
/* 21E03C 8016F86C AD180004 */  sw    $t8, 4($t0)
/* 21E040 8016F870 8FAE0044 */  lw    $t6, 0x44($sp)
/* 21E044 8016F874 25CA0008 */  addiu $t2, $t6, 8
/* 21E048 8016F878 AFAA0044 */  sw    $t2, 0x44($sp)
/* 21E04C 8016F87C AFAE0020 */  sw    $t6, 0x20($sp)
/* 21E050 8016F880 8FAC0020 */  lw    $t4, 0x20($sp)
/* 21E054 8016F884 3C19BD00 */  lui   $t9, 0xbd00
/* 21E058 8016F888 AD990000 */  sw    $t9, ($t4)
/* 21E05C 8016F88C 8FA90020 */  lw    $t1, 0x20($sp)
/* 21E060 8016F890 AD200004 */  sw    $zero, 4($t1)
/* 21E064 8016F894 8FAB0044 */  lw    $t3, 0x44($sp)
/* 21E068 8016F898 AFAB001C */  sw    $t3, 0x1c($sp)
/* 21E06C 8016F89C 8FAD001C */  lw    $t5, 0x1c($sp)
/* 21E070 8016F8A0 3C0FB800 */  lui   $t7, 0xb800
/* 21E074 8016F8A4 ADAF0000 */  sw    $t7, ($t5)
/* 21E078 8016F8A8 8FB8001C */  lw    $t8, 0x1c($sp)
/* 21E07C 8016F8AC AF000004 */  sw    $zero, 4($t8)
/* 21E080 8016F8B0 3C08801C */  lui   $t0, %hi(D_801B9858) # $t0, 0x801c
/* 21E084 8016F8B4 85089858 */  lh    $t0, %lo(D_801B9858)($t0)
/* 21E088 8016F8B8 3C01801C */  lui   $at, %hi(D_801B9858) # $at, 0x801c
/* 21E08C 8016F8BC 250E0001 */  addiu $t6, $t0, 1
/* 21E090 8016F8C0 A42E9858 */  sh    $t6, %lo(D_801B9858)($at)
.L8016F8C4:
/* 21E094 8016F8C4 10000003 */  b     .L8016F8D4
/* 21E098 8016F8C8 8FA20048 */   lw    $v0, 0x48($sp)
/* 21E09C 8016F8CC 10000001 */  b     .L8016F8D4
/* 21E0A0 8016F8D0 00000000 */   nop   
.L8016F8D4:
/* 21E0A4 8016F8D4 8FBF0014 */  lw    $ra, 0x14($sp)
/* 21E0A8 8016F8D8 27BD0050 */  addiu $sp, $sp, 0x50
/* 21E0AC 8016F8DC 03E00008 */  jr    $ra
/* 21E0B0 8016F8E0 00000000 */   nop   

glabel Geo18_8016F984
/* 21E0B4 8016F8E4 27BDFFC0 */  addiu $sp, $sp, -0x40
/* 21E0B8 8016F8E8 AFBF0014 */  sw    $ra, 0x14($sp)
/* 21E0BC 8016F8EC AFA40040 */  sw    $a0, 0x40($sp)
/* 21E0C0 8016F8F0 AFA50044 */  sw    $a1, 0x44($sp)
/* 21E0C4 8016F8F4 AFA60048 */  sw    $a2, 0x48($sp)
/* 21E0C8 8016F8F8 8FAE0044 */  lw    $t6, 0x44($sp)
/* 21E0CC 8016F8FC AFAE003C */  sw    $t6, 0x3c($sp)
/* 21E0D0 8016F900 AFA00038 */  sw    $zero, 0x38($sp)
/* 21E0D4 8016F904 AFA00034 */  sw    $zero, 0x34($sp)
/* 21E0D8 8016F908 8FAF0040 */  lw    $t7, 0x40($sp)
/* 21E0DC 8016F90C 24010001 */  li    $at, 1
/* 21E0E0 8016F910 11E10004 */  beq   $t7, $at, .L8016F924
/* 21E0E4 8016F914 00000000 */   nop   
/* 21E0E8 8016F918 3C01801C */  lui   $at, %hi(D_801B985C) # $at, 0x801c
/* 21E0EC 8016F91C 10000074 */  b     .L8016FAF0
/* 21E0F0 8016F920 AC20985C */   sw    $zero, %lo(D_801B985C)($at)
.L8016F924:
/* 21E0F4 8016F924 8FB80040 */  lw    $t8, 0x40($sp)
/* 21E0F8 8016F928 24010001 */  li    $at, 1
/* 21E0FC 8016F92C 17010070 */  bne   $t8, $at, .L8016FAF0
/* 21E100 8016F930 00000000 */   nop   
/* 21E104 8016F934 0C09E25F */  jal   alloc_display_list
/* 21E108 8016F938 24040028 */   li    $a0, 40
/* 21E10C 8016F93C AFA20038 */  sw    $v0, 0x38($sp)
/* 21E110 8016F940 8FB90038 */  lw    $t9, 0x38($sp)
/* 21E114 8016F944 AFB90034 */  sw    $t9, 0x34($sp)
/* 21E118 8016F948 8FA80034 */  lw    $t0, 0x34($sp)
/* 21E11C 8016F94C 25090008 */  addiu $t1, $t0, 8
/* 21E120 8016F950 AFA90034 */  sw    $t1, 0x34($sp)
/* 21E124 8016F954 AFA80030 */  sw    $t0, 0x30($sp)
/* 21E128 8016F958 8FAB0030 */  lw    $t3, 0x30($sp)
/* 21E12C 8016F95C 3C0A0600 */  lui   $t2, 0x600
/* 21E130 8016F960 AD6A0000 */  sw    $t2, ($t3)
/* 21E134 8016F964 8FAD0030 */  lw    $t5, 0x30($sp)
/* 21E138 8016F968 3C0C0201 */  lui   $t4, %hi(D_02014660) # $t4, 0x201
/* 21E13C 8016F96C 258C4660 */  addiu $t4, %lo(D_02014660) # addiu $t4, $t4, 0x4660
/* 21E140 8016F970 ADAC0004 */  sw    $t4, 4($t5)
/* 21E144 8016F974 8FAE0034 */  lw    $t6, 0x34($sp)
/* 21E148 8016F978 25CF0008 */  addiu $t7, $t6, 8
/* 21E14C 8016F97C AFAF0034 */  sw    $t7, 0x34($sp)
/* 21E150 8016F980 AFAE002C */  sw    $t6, 0x2c($sp)
/* 21E154 8016F984 8FB9002C */  lw    $t9, 0x2c($sp)
/* 21E158 8016F988 3C18FB00 */  lui   $t8, 0xfb00
/* 21E15C 8016F98C AF380000 */  sw    $t8, ($t9)
/* 21E160 8016F990 3C08801C */  lui   $t0, %hi(D_801B985C) # $t0, 0x801c
/* 21E164 8016F994 8D08985C */  lw    $t0, %lo(D_801B985C)($t0)
/* 21E168 8016F998 8FAB002C */  lw    $t3, 0x2c($sp)
/* 21E16C 8016F99C 2401FF00 */  li    $at, -256
/* 21E170 8016F9A0 310900FF */  andi  $t1, $t0, 0xff
/* 21E174 8016F9A4 01215025 */  or    $t2, $t1, $at
/* 21E178 8016F9A8 AD6A0004 */  sw    $t2, 4($t3)
/* 21E17C 8016F9AC 3C0C801C */  lui   $t4, %hi(D_801B985C) # $t4, 0x801c
/* 21E180 8016F9B0 8D8C985C */  lw    $t4, %lo(D_801B985C)($t4)
/* 21E184 8016F9B4 240100FF */  li    $at, 255
/* 21E188 8016F9B8 15810016 */  bne   $t4, $at, .L8016FA14
/* 21E18C 8016F9BC 00000000 */   nop   
/* 21E190 8016F9C0 10000001 */  b     .L8016F9C8
/* 21E194 8016F9C4 00000000 */   nop   
.L8016F9C8:
/* 21E198 8016F9C8 8FAD003C */  lw    $t5, 0x3c($sp)
/* 21E19C 8016F9CC 85AE0002 */  lh    $t6, 2($t5)
/* 21E1A0 8016F9D0 31CF00FF */  andi  $t7, $t6, 0xff
/* 21E1A4 8016F9D4 35F80100 */  ori   $t8, $t7, 0x100
/* 21E1A8 8016F9D8 A5B80002 */  sh    $t8, 2($t5)
/* 21E1AC 8016F9DC 8FB90034 */  lw    $t9, 0x34($sp)
/* 21E1B0 8016F9E0 27280008 */  addiu $t0, $t9, 8
/* 21E1B4 8016F9E4 AFA80034 */  sw    $t0, 0x34($sp)
/* 21E1B8 8016F9E8 AFB90028 */  sw    $t9, 0x28($sp)
/* 21E1BC 8016F9EC 8FAA0028 */  lw    $t2, 0x28($sp)
/* 21E1C0 8016F9F0 3C09B900 */  lui   $t1, (0xB900031D >> 16) # lui $t1, 0xb900
/* 21E1C4 8016F9F4 3529031D */  ori   $t1, (0xB900031D & 0xFFFF) # ori $t1, $t1, 0x31d
/* 21E1C8 8016F9F8 AD490000 */  sw    $t1, ($t2)
/* 21E1CC 8016F9FC 8FAC0028 */  lw    $t4, 0x28($sp)
/* 21E1D0 8016FA00 3C0B0055 */  lui   $t3, (0x00552048 >> 16) # lui $t3, 0x55
/* 21E1D4 8016FA04 356B2048 */  ori   $t3, (0x00552048 & 0xFFFF) # ori $t3, $t3, 0x2048
/* 21E1D8 8016FA08 AD8B0004 */  sw    $t3, 4($t4)
/* 21E1DC 8016FA0C 10000014 */  b     .L8016FA60
/* 21E1E0 8016FA10 00000000 */   nop   
.L8016FA14:
/* 21E1E4 8016FA14 8FAE003C */  lw    $t6, 0x3c($sp)
/* 21E1E8 8016FA18 85CF0002 */  lh    $t7, 2($t6)
/* 21E1EC 8016FA1C 31F800FF */  andi  $t8, $t7, 0xff
/* 21E1F0 8016FA20 370D0500 */  ori   $t5, $t8, 0x500
/* 21E1F4 8016FA24 A5CD0002 */  sh    $t5, 2($t6)
/* 21E1F8 8016FA28 8FB90034 */  lw    $t9, 0x34($sp)
/* 21E1FC 8016FA2C 27280008 */  addiu $t0, $t9, 8
/* 21E200 8016FA30 AFA80034 */  sw    $t0, 0x34($sp)
/* 21E204 8016FA34 AFB90024 */  sw    $t9, 0x24($sp)
/* 21E208 8016FA38 8FAA0024 */  lw    $t2, 0x24($sp)
/* 21E20C 8016FA3C 3C09B900 */  lui   $t1, (0xB900031D >> 16) # lui $t1, 0xb900
/* 21E210 8016FA40 3529031D */  ori   $t1, (0xB900031D & 0xFFFF) # ori $t1, $t1, 0x31d
/* 21E214 8016FA44 AD490000 */  sw    $t1, ($t2)
/* 21E218 8016FA48 8FAC0024 */  lw    $t4, 0x24($sp)
/* 21E21C 8016FA4C 3C0B0050 */  lui   $t3, (0x005041C8 >> 16) # lui $t3, 0x50
/* 21E220 8016FA50 356B41C8 */  ori   $t3, (0x005041C8 & 0xFFFF) # ori $t3, $t3, 0x41c8
/* 21E224 8016FA54 AD8B0004 */  sw    $t3, 4($t4)
/* 21E228 8016FA58 10000001 */  b     .L8016FA60
/* 21E22C 8016FA5C 00000000 */   nop   
.L8016FA60:
/* 21E230 8016FA60 8FAF0034 */  lw    $t7, 0x34($sp)
/* 21E234 8016FA64 25F80008 */  addiu $t8, $t7, 8
/* 21E238 8016FA68 AFB80034 */  sw    $t8, 0x34($sp)
/* 21E23C 8016FA6C AFAF0020 */  sw    $t7, 0x20($sp)
/* 21E240 8016FA70 8FAE0020 */  lw    $t6, 0x20($sp)
/* 21E244 8016FA74 3C0D0600 */  lui   $t5, 0x600
/* 21E248 8016FA78 ADCD0000 */  sw    $t5, ($t6)
/* 21E24C 8016FA7C 8FA80020 */  lw    $t0, 0x20($sp)
/* 21E250 8016FA80 3C190701 */  lui   $t9, %hi(D_0700C6A0) # $t9, 0x701
/* 21E254 8016FA84 2739C6A0 */  addiu $t9, %lo(D_0700C6A0) # addiu $t9, $t9, -0x3960
/* 21E258 8016FA88 AD190004 */  sw    $t9, 4($t0)
/* 21E25C 8016FA8C 8FA90034 */  lw    $t1, 0x34($sp)
/* 21E260 8016FA90 AFA9001C */  sw    $t1, 0x1c($sp)
/* 21E264 8016FA94 8FAB001C */  lw    $t3, 0x1c($sp)
/* 21E268 8016FA98 3C0AB800 */  lui   $t2, 0xb800
/* 21E26C 8016FA9C AD6A0000 */  sw    $t2, ($t3)
/* 21E270 8016FAA0 8FAC001C */  lw    $t4, 0x1c($sp)
/* 21E274 8016FAA4 AD800004 */  sw    $zero, 4($t4)
/* 21E278 8016FAA8 3C0F801C */  lui   $t7, %hi(D_801B9858) # $t7, 0x801c
/* 21E27C 8016FAAC 85EF9858 */  lh    $t7, %lo(D_801B9858)($t7)
/* 21E280 8016FAB0 29E10013 */  slti  $at, $t7, 0x13
/* 21E284 8016FAB4 1420000E */  bnez  $at, .L8016FAF0
/* 21E288 8016FAB8 00000000 */   nop   
/* 21E28C 8016FABC 3C18801C */  lui   $t8, %hi(D_801B985C) # $t8, 0x801c
/* 21E290 8016FAC0 8F18985C */  lw    $t8, %lo(D_801B985C)($t8)
/* 21E294 8016FAC4 3C01801C */  lui   $at, %hi(D_801B985C) # $at, 0x801c
/* 21E298 8016FAC8 270D001A */  addiu $t5, $t8, 0x1a
/* 21E29C 8016FACC AC2D985C */  sw    $t5, %lo(D_801B985C)($at)
/* 21E2A0 8016FAD0 3C0E801C */  lui   $t6, %hi(D_801B985C) # $t6, 0x801c
/* 21E2A4 8016FAD4 8DCE985C */  lw    $t6, %lo(D_801B985C)($t6)
/* 21E2A8 8016FAD8 29C10100 */  slti  $at, $t6, 0x100
/* 21E2AC 8016FADC 14200004 */  bnez  $at, .L8016FAF0
/* 21E2B0 8016FAE0 00000000 */   nop   
/* 21E2B4 8016FAE4 241900FF */  li    $t9, 255
/* 21E2B8 8016FAE8 3C01801C */  lui   $at, %hi(D_801B985C) # $at, 0x801c
/* 21E2BC 8016FAEC AC39985C */  sw    $t9, %lo(D_801B985C)($at)
.L8016FAF0:
/* 21E2C0 8016FAF0 10000003 */  b     .L8016FB00
/* 21E2C4 8016FAF4 8FA20038 */   lw    $v0, 0x38($sp)
/* 21E2C8 8016FAF8 10000001 */  b     .L8016FB00
/* 21E2CC 8016FAFC 00000000 */   nop   
.L8016FB00:
/* 21E2D0 8016FB00 8FBF0014 */  lw    $ra, 0x14($sp)
/* 21E2D4 8016FB04 27BD0040 */  addiu $sp, $sp, 0x40
/* 21E2D8 8016FB08 03E00008 */  jr    $ra
/* 21E2DC 8016FB0C 00000000 */   nop   

glabel func_8016FB10
/* 21E2E0 8016FB10 27BDFFA0 */  addiu $sp, $sp, -0x60
/* 21E2E4 8016FB14 AFBF0014 */  sw    $ra, 0x14($sp)
/* 21E2E8 8016FB18 AFA40060 */  sw    $a0, 0x60($sp)
/* 21E2EC 8016FB1C AFA50064 */  sw    $a1, 0x64($sp)
/* 21E2F0 8016FB20 0C09E25F */  jal   alloc_display_list
/* 21E2F4 8016FB24 24040040 */   li    $a0, 64
/* 21E2F8 8016FB28 AFA2005C */  sw    $v0, 0x5c($sp)
/* 21E2FC 8016FB2C 0C09E25F */  jal   alloc_display_list
/* 21E300 8016FB30 24040120 */   li    $a0, 288
/* 21E304 8016FB34 AFA20058 */  sw    $v0, 0x58($sp)
/* 21E308 8016FB38 8FAE0058 */  lw    $t6, 0x58($sp)
/* 21E30C 8016FB3C AFAE0054 */  sw    $t6, 0x54($sp)
/* 21E310 8016FB40 8FAF0064 */  lw    $t7, 0x64($sp)
/* 21E314 8016FB44 8FB80060 */  lw    $t8, 0x60($sp)
/* 21E318 8016FB48 3C04801A */  lui   $a0, %hi(D_801A7BA0)
/* 21E31C 8016FB4C 01F8C821 */  addu  $t9, $t7, $t8
/* 21E320 8016FB50 83280000 */  lb    $t0, ($t9)
/* 21E324 8016FB54 00084880 */  sll   $t1, $t0, 2
/* 21E328 8016FB58 00892021 */  addu  $a0, $a0, $t1
/* 21E32C 8016FB5C 0C09DE68 */  jal   segmented_to_virtual
/* 21E330 8016FB60 8C847BA0 */   lw    $a0, %lo(D_801A7BA0)($a0)
/* 21E334 8016FB64 AFA20050 */  sw    $v0, 0x50($sp)
/* 21E338 8016FB68 8FAA0060 */  lw    $t2, 0x60($sp)
/* 21E33C 8016FB6C 3C05801A */  lui   $a1, %hi(D_801A7B40)
/* 21E340 8016FB70 3C06801A */  lui   $a2, %hi(D_801A7B70)
/* 21E344 8016FB74 000A5880 */  sll   $t3, $t2, 2
/* 21E348 8016FB78 00AB2821 */  addu  $a1, $a1, $t3
/* 21E34C 8016FB7C 00CB3021 */  addu  $a2, $a2, $t3
/* 21E350 8016FB80 8CC67B70 */  lw    $a2, %lo(D_801A7B70)($a2)
/* 21E354 8016FB84 8CA57B40 */  lw    $a1, %lo(D_801A7B40)($a1)
/* 21E358 8016FB88 8FA4005C */  lw    $a0, 0x5c($sp)
/* 21E35C 8016FB8C 0C0C91D6 */  jal   func_80324758
/* 21E360 8016FB90 24070000 */   li    $a3, 0
/* 21E364 8016FB94 8FAC0054 */  lw    $t4, 0x54($sp)
/* 21E368 8016FB98 258D0008 */  addiu $t5, $t4, 8
/* 21E36C 8016FB9C AFAD0054 */  sw    $t5, 0x54($sp)
/* 21E370 8016FBA0 AFAC0048 */  sw    $t4, 0x48($sp)
/* 21E374 8016FBA4 8FAF0048 */  lw    $t7, 0x48($sp)
/* 21E378 8016FBA8 3C0E0106 */  lui   $t6, (0x01060040 >> 16) # lui $t6, 0x106
/* 21E37C 8016FBAC 35CE0040 */  ori   $t6, (0x01060040 & 0xFFFF) # ori $t6, $t6, 0x40
/* 21E380 8016FBB0 ADEE0000 */  sw    $t6, ($t7)
/* 21E384 8016FBB4 8FB8005C */  lw    $t8, 0x5c($sp)
/* 21E388 8016FBB8 8FB90048 */  lw    $t9, 0x48($sp)
/* 21E38C 8016FBBC AF380004 */  sw    $t8, 4($t9)
/* 21E390 8016FBC0 8FA80054 */  lw    $t0, 0x54($sp)
/* 21E394 8016FBC4 25090008 */  addiu $t1, $t0, 8
/* 21E398 8016FBC8 AFA90054 */  sw    $t1, 0x54($sp)
/* 21E39C 8016FBCC AFA80044 */  sw    $t0, 0x44($sp)
/* 21E3A0 8016FBD0 8FAB0044 */  lw    $t3, 0x44($sp)
/* 21E3A4 8016FBD4 3C0A0600 */  lui   $t2, 0x600
/* 21E3A8 8016FBD8 AD6A0000 */  sw    $t2, ($t3)
/* 21E3AC 8016FBDC 8FAD0044 */  lw    $t5, 0x44($sp)
/* 21E3B0 8016FBE0 3C0C0A00 */  lui   $t4, %hi(D_0A000118) # $t4, 0xa00
/* 21E3B4 8016FBE4 258C0118 */  addiu $t4, %lo(D_0A000118) # addiu $t4, $t4, 0x118
/* 21E3B8 8016FBE8 ADAC0004 */  sw    $t4, 4($t5)
/* 21E3BC 8016FBEC AFA0004C */  sw    $zero, 0x4c($sp)
.L8016FBF0:
/* 21E3C0 8016FBF0 8FAE0054 */  lw    $t6, 0x54($sp)
/* 21E3C4 8016FBF4 25CF0008 */  addiu $t7, $t6, 8
/* 21E3C8 8016FBF8 AFAF0054 */  sw    $t7, 0x54($sp)
/* 21E3CC 8016FBFC AFAE0040 */  sw    $t6, 0x40($sp)
/* 21E3D0 8016FC00 8FB90040 */  lw    $t9, 0x40($sp)
/* 21E3D4 8016FC04 3C18FD10 */  lui   $t8, 0xfd10
/* 21E3D8 8016FC08 AF380000 */  sw    $t8, ($t9)
/* 21E3DC 8016FC0C 8FA9004C */  lw    $t1, 0x4c($sp)
/* 21E3E0 8016FC10 8FA80050 */  lw    $t0, 0x50($sp)
/* 21E3E4 8016FC14 8FAD0040 */  lw    $t5, 0x40($sp)
/* 21E3E8 8016FC18 00095080 */  sll   $t2, $t1, 2
/* 21E3EC 8016FC1C 010A5821 */  addu  $t3, $t0, $t2
/* 21E3F0 8016FC20 8D6C0000 */  lw    $t4, ($t3)
/* 21E3F4 8016FC24 ADAC0004 */  sw    $t4, 4($t5)
/* 21E3F8 8016FC28 8FAE0054 */  lw    $t6, 0x54($sp)
/* 21E3FC 8016FC2C 25CF0008 */  addiu $t7, $t6, 8
/* 21E400 8016FC30 AFAF0054 */  sw    $t7, 0x54($sp)
/* 21E404 8016FC34 AFAE003C */  sw    $t6, 0x3c($sp)
/* 21E408 8016FC38 8FB9003C */  lw    $t9, 0x3c($sp)
/* 21E40C 8016FC3C 3C18F510 */  lui   $t8, 0xf510
/* 21E410 8016FC40 AF380000 */  sw    $t8, ($t9)
/* 21E414 8016FC44 8FA8003C */  lw    $t0, 0x3c($sp)
/* 21E418 8016FC48 3C090709 */  lui   $t1, (0x07098270 >> 16) # lui $t1, 0x709
/* 21E41C 8016FC4C 35298270 */  ori   $t1, (0x07098270 & 0xFFFF) # ori $t1, $t1, 0x8270
/* 21E420 8016FC50 AD090004 */  sw    $t1, 4($t0)
/* 21E424 8016FC54 8FAA0054 */  lw    $t2, 0x54($sp)
/* 21E428 8016FC58 254B0008 */  addiu $t3, $t2, 8
/* 21E42C 8016FC5C AFAB0054 */  sw    $t3, 0x54($sp)
/* 21E430 8016FC60 AFAA0038 */  sw    $t2, 0x38($sp)
/* 21E434 8016FC64 8FAD0038 */  lw    $t5, 0x38($sp)
/* 21E438 8016FC68 3C0CE600 */  lui   $t4, 0xe600
/* 21E43C 8016FC6C ADAC0000 */  sw    $t4, ($t5)
/* 21E440 8016FC70 8FAE0038 */  lw    $t6, 0x38($sp)
/* 21E444 8016FC74 ADC00004 */  sw    $zero, 4($t6)
/* 21E448 8016FC78 8FAF0054 */  lw    $t7, 0x54($sp)
/* 21E44C 8016FC7C 25F80008 */  addiu $t8, $t7, 8
/* 21E450 8016FC80 AFB80054 */  sw    $t8, 0x54($sp)
/* 21E454 8016FC84 AFAF0034 */  sw    $t7, 0x34($sp)
/* 21E458 8016FC88 8FA90034 */  lw    $t1, 0x34($sp)
/* 21E45C 8016FC8C 3C19F300 */  lui   $t9, 0xf300
/* 21E460 8016FC90 AD390000 */  sw    $t9, ($t1)
/* 21E464 8016FC94 8FAA0034 */  lw    $t2, 0x34($sp)
/* 21E468 8016FC98 3C080763 */  lui   $t0, (0x0763F067 >> 16) # lui $t0, 0x763
/* 21E46C 8016FC9C 3508F067 */  ori   $t0, (0x0763F067 & 0xFFFF) # ori $t0, $t0, 0xf067
/* 21E470 8016FCA0 AD480004 */  sw    $t0, 4($t2)
/* 21E474 8016FCA4 8FAB0054 */  lw    $t3, 0x54($sp)
/* 21E478 8016FCA8 256C0008 */  addiu $t4, $t3, 8
/* 21E47C 8016FCAC AFAC0054 */  sw    $t4, 0x54($sp)
/* 21E480 8016FCB0 AFAB0030 */  sw    $t3, 0x30($sp)
/* 21E484 8016FCB4 8FAE0030 */  lw    $t6, 0x30($sp)
/* 21E488 8016FCB8 3C0DE700 */  lui   $t5, 0xe700
/* 21E48C 8016FCBC ADCD0000 */  sw    $t5, ($t6)
/* 21E490 8016FCC0 8FAF0030 */  lw    $t7, 0x30($sp)
/* 21E494 8016FCC4 ADE00004 */  sw    $zero, 4($t7)
/* 21E498 8016FCC8 8FB80054 */  lw    $t8, 0x54($sp)
/* 21E49C 8016FCCC 27190008 */  addiu $t9, $t8, 8
/* 21E4A0 8016FCD0 AFB90054 */  sw    $t9, 0x54($sp)
/* 21E4A4 8016FCD4 AFB8002C */  sw    $t8, 0x2c($sp)
/* 21E4A8 8016FCD8 8FA8002C */  lw    $t0, 0x2c($sp)
/* 21E4AC 8016FCDC 3C09F510 */  lui   $t1, (0xF5102800 >> 16) # lui $t1, 0xf510
/* 21E4B0 8016FCE0 35292800 */  ori   $t1, (0xF5102800 & 0xFFFF) # ori $t1, $t1, 0x2800
/* 21E4B4 8016FCE4 AD090000 */  sw    $t1, ($t0)
/* 21E4B8 8016FCE8 8FAB002C */  lw    $t3, 0x2c($sp)
/* 21E4BC 8016FCEC 3C0A0009 */  lui   $t2, (0x00098270 >> 16) # lui $t2, 9
/* 21E4C0 8016FCF0 354A8270 */  ori   $t2, (0x00098270 & 0xFFFF) # ori $t2, $t2, 0x8270
/* 21E4C4 8016FCF4 AD6A0004 */  sw    $t2, 4($t3)
/* 21E4C8 8016FCF8 8FAC0054 */  lw    $t4, 0x54($sp)
/* 21E4CC 8016FCFC 258D0008 */  addiu $t5, $t4, 8
/* 21E4D0 8016FD00 AFAD0054 */  sw    $t5, 0x54($sp)
/* 21E4D4 8016FD04 AFAC0028 */  sw    $t4, 0x28($sp)
/* 21E4D8 8016FD08 8FAF0028 */  lw    $t7, 0x28($sp)
/* 21E4DC 8016FD0C 3C0EF200 */  lui   $t6, 0xf200
/* 21E4E0 8016FD10 ADEE0000 */  sw    $t6, ($t7)
/* 21E4E4 8016FD14 8FB90028 */  lw    $t9, 0x28($sp)
/* 21E4E8 8016FD18 3C180013 */  lui   $t8, (0x0013C04C >> 16) # lui $t8, 0x13
/* 21E4EC 8016FD1C 3718C04C */  ori   $t8, (0x0013C04C & 0xFFFF) # ori $t8, $t8, 0xc04c
/* 21E4F0 8016FD20 AF380004 */  sw    $t8, 4($t9)
/* 21E4F4 8016FD24 8FA90054 */  lw    $t1, 0x54($sp)
/* 21E4F8 8016FD28 25280008 */  addiu $t0, $t1, 8
/* 21E4FC 8016FD2C AFA80054 */  sw    $t0, 0x54($sp)
/* 21E500 8016FD30 AFA90024 */  sw    $t1, 0x24($sp)
/* 21E504 8016FD34 8FAB0024 */  lw    $t3, 0x24($sp)
/* 21E508 8016FD38 3C0A0600 */  lui   $t2, 0x600
/* 21E50C 8016FD3C AD6A0000 */  sw    $t2, ($t3)
/* 21E510 8016FD40 8FAC004C */  lw    $t4, 0x4c($sp)
/* 21E514 8016FD44 3C0E801A */  lui   $t6, %hi(D_801A7B30)
/* 21E518 8016FD48 8FAF0024 */  lw    $t7, 0x24($sp)
/* 21E51C 8016FD4C 000C6880 */  sll   $t5, $t4, 2
/* 21E520 8016FD50 01CD7021 */  addu  $t6, $t6, $t5
/* 21E524 8016FD54 8DCE7B30 */  lw    $t6, %lo(D_801A7B30)($t6)
/* 21E528 8016FD58 ADEE0004 */  sw    $t6, 4($t7)
/* 21E52C 8016FD5C 8FB8004C */  lw    $t8, 0x4c($sp)
/* 21E530 8016FD60 27190001 */  addiu $t9, $t8, 1
/* 21E534 8016FD64 2B210004 */  slti  $at, $t9, 4
/* 21E538 8016FD68 1420FFA1 */  bnez  $at, .L8016FBF0
/* 21E53C 8016FD6C AFB9004C */   sw    $t9, 0x4c($sp)
/* 21E540 8016FD70 8FA90054 */  lw    $t1, 0x54($sp)
/* 21E544 8016FD74 25280008 */  addiu $t0, $t1, 8
/* 21E548 8016FD78 AFA80054 */  sw    $t0, 0x54($sp)
/* 21E54C 8016FD7C AFA90020 */  sw    $t1, 0x20($sp)
/* 21E550 8016FD80 8FAB0020 */  lw    $t3, 0x20($sp)
/* 21E554 8016FD84 3C0ABD00 */  lui   $t2, 0xbd00
/* 21E558 8016FD88 AD6A0000 */  sw    $t2, ($t3)
/* 21E55C 8016FD8C 8FAC0020 */  lw    $t4, 0x20($sp)
/* 21E560 8016FD90 AD800004 */  sw    $zero, 4($t4)
/* 21E564 8016FD94 8FAD0054 */  lw    $t5, 0x54($sp)
/* 21E568 8016FD98 AFAD001C */  sw    $t5, 0x1c($sp)
/* 21E56C 8016FD9C 8FAF001C */  lw    $t7, 0x1c($sp)
/* 21E570 8016FDA0 3C0EB800 */  lui   $t6, 0xb800
/* 21E574 8016FDA4 ADEE0000 */  sw    $t6, ($t7)
/* 21E578 8016FDA8 8FB8001C */  lw    $t8, 0x1c($sp)
/* 21E57C 8016FDAC AF000004 */  sw    $zero, 4($t8)
/* 21E580 8016FDB0 10000003 */  b     .L8016FDC0
/* 21E584 8016FDB4 8FA20058 */   lw    $v0, 0x58($sp)
/* 21E588 8016FDB8 10000001 */  b     .L8016FDC0
/* 21E58C 8016FDBC 00000000 */   nop   
.L8016FDC0:
/* 21E590 8016FDC0 8FBF0014 */  lw    $ra, 0x14($sp)
/* 21E594 8016FDC4 27BD0060 */  addiu $sp, $sp, 0x60
/* 21E598 8016FDC8 03E00008 */  jr    $ra
/* 21E59C 8016FDCC 00000000 */   nop   

glabel Geo18_8016FE70
/* 21E5A0 8016FDD0 27BDFFB8 */  addiu $sp, $sp, -0x48
/* 21E5A4 8016FDD4 AFBF0014 */  sw    $ra, 0x14($sp)
/* 21E5A8 8016FDD8 AFA40048 */  sw    $a0, 0x48($sp)
/* 21E5AC 8016FDDC AFA5004C */  sw    $a1, 0x4c($sp)
/* 21E5B0 8016FDE0 AFA60050 */  sw    $a2, 0x50($sp)
/* 21E5B4 8016FDE4 8FAE004C */  lw    $t6, 0x4c($sp)
/* 21E5B8 8016FDE8 AFAE0044 */  sw    $t6, 0x44($sp)
/* 21E5BC 8016FDEC 8FAF0044 */  lw    $t7, 0x44($sp)
/* 21E5C0 8016FDF0 8DF80018 */  lw    $t8, 0x18($t7)
/* 21E5C4 8016FDF4 331900FF */  andi  $t9, $t8, 0xff
/* 21E5C8 8016FDF8 AFB90040 */  sw    $t9, 0x40($sp)
/* 21E5CC 8016FDFC 8FA80040 */  lw    $t0, 0x40($sp)
/* 21E5D0 8016FE00 3C0A801A */  lui   $t2, %hi(D_801A7BB4)
/* 21E5D4 8016FE04 00084880 */  sll   $t1, $t0, 2
/* 21E5D8 8016FE08 01495021 */  addu  $t2, $t2, $t1
/* 21E5DC 8016FE0C 8D4A7BB4 */  lw    $t2, %lo(D_801A7BB4)($t2)
/* 21E5E0 8016FE10 AFAA003C */  sw    $t2, 0x3c($sp)
/* 21E5E4 8016FE14 AFA00038 */  sw    $zero, 0x38($sp)
/* 21E5E8 8016FE18 AFA00034 */  sw    $zero, 0x34($sp)
/* 21E5EC 8016FE1C 8FAB0048 */  lw    $t3, 0x48($sp)
/* 21E5F0 8016FE20 24010001 */  li    $at, 1
/* 21E5F4 8016FE24 15610045 */  bne   $t3, $at, .L8016FF3C
/* 21E5F8 8016FE28 00000000 */   nop   
/* 21E5FC 8016FE2C 0C09E25F */  jal   alloc_display_list
/* 21E600 8016FE30 24040080 */   li    $a0, 128
/* 21E604 8016FE34 AFA20038 */  sw    $v0, 0x38($sp)
/* 21E608 8016FE38 8FAC0038 */  lw    $t4, 0x38($sp)
/* 21E60C 8016FE3C AFAC0034 */  sw    $t4, 0x34($sp)
/* 21E610 8016FE40 8FAD0044 */  lw    $t5, 0x44($sp)
/* 21E614 8016FE44 85AE0002 */  lh    $t6, 2($t5)
/* 21E618 8016FE48 31CF00FF */  andi  $t7, $t6, 0xff
/* 21E61C 8016FE4C 35F80100 */  ori   $t8, $t7, 0x100
/* 21E620 8016FE50 A5B80002 */  sh    $t8, 2($t5)
/* 21E624 8016FE54 8FB90034 */  lw    $t9, 0x34($sp)
/* 21E628 8016FE58 27280008 */  addiu $t0, $t9, 8
/* 21E62C 8016FE5C AFA80034 */  sw    $t0, 0x34($sp)
/* 21E630 8016FE60 AFB9002C */  sw    $t9, 0x2c($sp)
/* 21E634 8016FE64 8FAA002C */  lw    $t2, 0x2c($sp)
/* 21E638 8016FE68 3C090600 */  lui   $t1, 0x600
/* 21E63C 8016FE6C AD490000 */  sw    $t1, ($t2)
/* 21E640 8016FE70 8FAC002C */  lw    $t4, 0x2c($sp)
/* 21E644 8016FE74 3C0B0201 */  lui   $t3, %hi(D_02014660) # $t3, 0x201
/* 21E648 8016FE78 256B4660 */  addiu $t3, %lo(D_02014660) # addiu $t3, $t3, 0x4660
/* 21E64C 8016FE7C AD8B0004 */  sw    $t3, 4($t4)
/* 21E650 8016FE80 8FAE0034 */  lw    $t6, 0x34($sp)
/* 21E654 8016FE84 25CF0008 */  addiu $t7, $t6, 8
/* 21E658 8016FE88 AFAF0034 */  sw    $t7, 0x34($sp)
/* 21E65C 8016FE8C AFAE0028 */  sw    $t6, 0x28($sp)
/* 21E660 8016FE90 8FAD0028 */  lw    $t5, 0x28($sp)
/* 21E664 8016FE94 3C180600 */  lui   $t8, 0x600
/* 21E668 8016FE98 ADB80000 */  sw    $t8, ($t5)
/* 21E66C 8016FE9C 8FA80028 */  lw    $t0, 0x28($sp)
/* 21E670 8016FEA0 3C190A00 */  lui   $t9, %hi(D_0A000100) # $t9, 0xa00
/* 21E674 8016FEA4 27390100 */  addiu $t9, %lo(D_0A000100) # addiu $t9, $t9, 0x100
/* 21E678 8016FEA8 AD190004 */  sw    $t9, 4($t0)
/* 21E67C 8016FEAC AFA00030 */  sw    $zero, 0x30($sp)
.L8016FEB0:
/* 21E680 8016FEB0 8FA90034 */  lw    $t1, 0x34($sp)
/* 21E684 8016FEB4 252A0008 */  addiu $t2, $t1, 8
/* 21E688 8016FEB8 AFAA0034 */  sw    $t2, 0x34($sp)
/* 21E68C 8016FEBC AFA90024 */  sw    $t1, 0x24($sp)
/* 21E690 8016FEC0 8FAC0024 */  lw    $t4, 0x24($sp)
/* 21E694 8016FEC4 3C0B0600 */  lui   $t3, 0x600
/* 21E698 8016FEC8 AD8B0000 */  sw    $t3, ($t4)
/* 21E69C 8016FECC 8FA40030 */  lw    $a0, 0x30($sp)
/* 21E6A0 8016FED0 0C05BEC4 */  jal   func_8016FB10
/* 21E6A4 8016FED4 8FA5003C */   lw    $a1, 0x3c($sp)
/* 21E6A8 8016FED8 8FAE0024 */  lw    $t6, 0x24($sp)
/* 21E6AC 8016FEDC ADC20004 */  sw    $v0, 4($t6)
/* 21E6B0 8016FEE0 8FAF0030 */  lw    $t7, 0x30($sp)
/* 21E6B4 8016FEE4 25F80001 */  addiu $t8, $t7, 1
/* 21E6B8 8016FEE8 2B01000C */  slti  $at, $t8, 0xc
/* 21E6BC 8016FEEC 1420FFF0 */  bnez  $at, .L8016FEB0
/* 21E6C0 8016FEF0 AFB80030 */   sw    $t8, 0x30($sp)
/* 21E6C4 8016FEF4 8FAD0034 */  lw    $t5, 0x34($sp)
/* 21E6C8 8016FEF8 25B90008 */  addiu $t9, $t5, 8
/* 21E6CC 8016FEFC AFB90034 */  sw    $t9, 0x34($sp)
/* 21E6D0 8016FF00 AFAD0020 */  sw    $t5, 0x20($sp)
/* 21E6D4 8016FF04 8FA90020 */  lw    $t1, 0x20($sp)
/* 21E6D8 8016FF08 3C080600 */  lui   $t0, 0x600
/* 21E6DC 8016FF0C AD280000 */  sw    $t0, ($t1)
/* 21E6E0 8016FF10 8FAB0020 */  lw    $t3, 0x20($sp)
/* 21E6E4 8016FF14 3C0A0A00 */  lui   $t2, %hi(D_0A000190) # $t2, 0xa00
/* 21E6E8 8016FF18 254A0190 */  addiu $t2, %lo(D_0A000190) # addiu $t2, $t2, 0x190
/* 21E6EC 8016FF1C AD6A0004 */  sw    $t2, 4($t3)
/* 21E6F0 8016FF20 8FAC0034 */  lw    $t4, 0x34($sp)
/* 21E6F4 8016FF24 AFAC001C */  sw    $t4, 0x1c($sp)
/* 21E6F8 8016FF28 8FAF001C */  lw    $t7, 0x1c($sp)
/* 21E6FC 8016FF2C 3C0EB800 */  lui   $t6, 0xb800
/* 21E700 8016FF30 ADEE0000 */  sw    $t6, ($t7)
/* 21E704 8016FF34 8FB8001C */  lw    $t8, 0x1c($sp)
/* 21E708 8016FF38 AF000004 */  sw    $zero, 4($t8)
.L8016FF3C:
/* 21E70C 8016FF3C 10000003 */  b     .L8016FF4C
/* 21E710 8016FF40 8FA20038 */   lw    $v0, 0x38($sp)
/* 21E714 8016FF44 10000001 */  b     .L8016FF4C
/* 21E718 8016FF48 00000000 */   nop   
.L8016FF4C:
/* 21E71C 8016FF4C 8FBF0014 */  lw    $ra, 0x14($sp)
/* 21E720 8016FF50 27BD0048 */  addiu $sp, $sp, 0x48
/* 21E724 8016FF54 03E00008 */  jr    $ra
/* 21E728 8016FF58 00000000 */   nop   

glabel Geo18_8016FFFC
/* 21E72C 8016FF5C 27BDFFC0 */  addiu $sp, $sp, -0x40
/* 21E730 8016FF60 AFBF0014 */  sw    $ra, 0x14($sp)
/* 21E734 8016FF64 AFA40040 */  sw    $a0, 0x40($sp)
/* 21E738 8016FF68 AFA50044 */  sw    $a1, 0x44($sp)
/* 21E73C 8016FF6C AFA60048 */  sw    $a2, 0x48($sp)
/* 21E740 8016FF70 8FAE0044 */  lw    $t6, 0x44($sp)
/* 21E744 8016FF74 AFAE003C */  sw    $t6, 0x3c($sp)
/* 21E748 8016FF78 AFA00038 */  sw    $zero, 0x38($sp)
/* 21E74C 8016FF7C AFA00034 */  sw    $zero, 0x34($sp)
/* 21E750 8016FF80 8FAF0040 */  lw    $t7, 0x40($sp)
/* 21E754 8016FF84 24010001 */  li    $at, 1
/* 21E758 8016FF88 11E10013 */  beq   $t7, $at, .L8016FFD8
/* 21E75C 8016FF8C 00000000 */   nop   
/* 21E760 8016FF90 3C01801C */  lui   $at, %hi(D_801B9850) # $at, 0x801c
/* 21E764 8016FF94 AC209850 */  sw    $zero, %lo(D_801B9850)($at)
/* 21E768 8016FF98 2418FFFE */  li    $t8, -2
/* 21E76C 8016FF9C 3C01801C */  lui   $at, %hi(D_801B9854) # $at, 0x801c
/* 21E770 8016FFA0 AC389854 */  sw    $t8, %lo(D_801B9854)($at)
/* 21E774 8016FFA4 AFA0002C */  sw    $zero, 0x2c($sp)
.L8016FFA8:
/* 21E778 8016FFA8 8FA8002C */  lw    $t0, 0x2c($sp)
/* 21E77C 8016FFAC 3C01801A */  lui   $at, %hi(D_801A7BB8)
/* 21E780 8016FFB0 24190001 */  li    $t9, 1
/* 21E784 8016FFB4 00280821 */  addu  $at, $at, $t0
/* 21E788 8016FFB8 A0397BB8 */  sb    $t9, %lo(D_801A7BB8)($at)
/* 21E78C 8016FFBC 8FA9002C */  lw    $t1, 0x2c($sp)
/* 21E790 8016FFC0 252A0001 */  addiu $t2, $t1, 1
/* 21E794 8016FFC4 2941000C */  slti  $at, $t2, 0xc
/* 21E798 8016FFC8 1420FFF7 */  bnez  $at, .L8016FFA8
/* 21E79C 8016FFCC AFAA002C */   sw    $t2, 0x2c($sp)
/* 21E7A0 8016FFD0 1000007A */  b     .L801701BC
/* 21E7A4 8016FFD4 00000000 */   nop   
.L8016FFD8:
/* 21E7A8 8016FFD8 0C09E25F */  jal   alloc_display_list
/* 21E7AC 8016FFDC 24040080 */   li    $a0, 128
/* 21E7B0 8016FFE0 AFA20038 */  sw    $v0, 0x38($sp)
/* 21E7B4 8016FFE4 8FAB0038 */  lw    $t3, 0x38($sp)
/* 21E7B8 8016FFE8 AFAB0034 */  sw    $t3, 0x34($sp)
/* 21E7BC 8016FFEC 3C0C801C */  lui   $t4, %hi(D_801B9854) # $t4, 0x801c
/* 21E7C0 8016FFF0 8D8C9854 */  lw    $t4, %lo(D_801B9854)($t4)
/* 21E7C4 8016FFF4 2401FFFE */  li    $at, -2
/* 21E7C8 8016FFF8 1581000F */  bne   $t4, $at, .L80170038
/* 21E7CC 8016FFFC 00000000 */   nop   
/* 21E7D0 80170000 3C0D801C */  lui   $t5, %hi(D_801B9850) # $t5, 0x801c
/* 21E7D4 80170004 8DAD9850 */  lw    $t5, %lo(D_801B9850)($t5)
/* 21E7D8 80170008 240100B4 */  li    $at, 180
/* 21E7DC 8017000C 15A10008 */  bne   $t5, $at, .L80170030
/* 21E7E0 80170010 00000000 */   nop   
/* 21E7E4 80170014 3C0E801C */  lui   $t6, %hi(D_801B9854) # $t6, 0x801c
/* 21E7E8 80170018 8DCE9854 */  lw    $t6, %lo(D_801B9854)($t6)
/* 21E7EC 8017001C 3C01801C */  lui   $at, %hi(D_801B9854) # $at, 0x801c
/* 21E7F0 80170020 25CF0001 */  addiu $t7, $t6, 1
/* 21E7F4 80170024 AC2F9854 */  sw    $t7, %lo(D_801B9854)($at)
/* 21E7F8 80170028 3C01801C */  lui   $at, %hi(D_801B9850) # $at, 0x801c
/* 21E7FC 8017002C AC209850 */  sw    $zero, %lo(D_801B9850)($at)
.L80170030:
/* 21E800 80170030 10000018 */  b     .L80170094
/* 21E804 80170034 00000000 */   nop   
.L80170038:
/* 21E808 80170038 3C18801C */  lui   $t8, %hi(D_801B9854) # $t8, 0x801c
/* 21E80C 8017003C 8F189854 */  lw    $t8, %lo(D_801B9854)($t8)
/* 21E810 80170040 2401000B */  li    $at, 11
/* 21E814 80170044 13010013 */  beq   $t8, $at, .L80170094
/* 21E818 80170048 00000000 */   nop   
/* 21E81C 8017004C 3C19801C */  lui   $t9, %hi(D_801B9850) # $t9, 0x801c
/* 21E820 80170050 8F399850 */  lw    $t9, %lo(D_801B9850)($t9)
/* 21E824 80170054 33280001 */  andi  $t0, $t9, 1
/* 21E828 80170058 1500000E */  bnez  $t0, .L80170094
/* 21E82C 8017005C 00000000 */   nop   
/* 21E830 80170060 3C09801C */  lui   $t1, %hi(D_801B9854) # $t1, 0x801c
/* 21E834 80170064 8D299854 */  lw    $t1, %lo(D_801B9854)($t1)
/* 21E838 80170068 3C01801C */  lui   $at, %hi(D_801B9854) # $at, 0x801c
/* 21E83C 8017006C 252A0001 */  addiu $t2, $t1, 1
/* 21E840 80170070 AC2A9854 */  sw    $t2, %lo(D_801B9854)($at)
/* 21E844 80170074 3C0B801C */  lui   $t3, %hi(D_801B9854) # $t3, 0x801c
/* 21E848 80170078 8D6B9854 */  lw    $t3, %lo(D_801B9854)($t3)
/* 21E84C 8017007C 3C0C801A */  lui   $t4, %hi(D_801A7BC4)
/* 21E850 80170080 3C01801A */  lui   $at, %hi(D_801A7BB8)
/* 21E854 80170084 018B6021 */  addu  $t4, $t4, $t3
/* 21E858 80170088 818C7BC4 */  lb    $t4, %lo(D_801A7BC4)($t4)
/* 21E85C 8017008C 002C0821 */  addu  $at, $at, $t4
/* 21E860 80170090 A0207BB8 */  sb    $zero, %lo(D_801A7BB8)($at)
.L80170094:
/* 21E864 80170094 3C0D801C */  lui   $t5, %hi(D_801B9854) # $t5, 0x801c
/* 21E868 80170098 8DAD9854 */  lw    $t5, %lo(D_801B9854)($t5)
/* 21E86C 8017009C 2401000B */  li    $at, 11
/* 21E870 801700A0 11A10006 */  beq   $t5, $at, .L801700BC
/* 21E874 801700A4 00000000 */   nop   
/* 21E878 801700A8 3C0E801C */  lui   $t6, %hi(D_801B9850) # $t6, 0x801c
/* 21E87C 801700AC 8DCE9850 */  lw    $t6, %lo(D_801B9850)($t6)
/* 21E880 801700B0 3C01801C */  lui   $at, %hi(D_801B9850) # $at, 0x801c
/* 21E884 801700B4 25CF0001 */  addiu $t7, $t6, 1
/* 21E888 801700B8 AC2F9850 */  sw    $t7, %lo(D_801B9850)($at)
.L801700BC:
/* 21E88C 801700BC 8FB8003C */  lw    $t8, 0x3c($sp)
/* 21E890 801700C0 87190002 */  lh    $t9, 2($t8)
/* 21E894 801700C4 332800FF */  andi  $t0, $t9, 0xff
/* 21E898 801700C8 35090100 */  ori   $t1, $t0, 0x100
/* 21E89C 801700CC A7090002 */  sh    $t1, 2($t8)
/* 21E8A0 801700D0 8FAA0034 */  lw    $t2, 0x34($sp)
/* 21E8A4 801700D4 254B0008 */  addiu $t3, $t2, 8
/* 21E8A8 801700D8 AFAB0034 */  sw    $t3, 0x34($sp)
/* 21E8AC 801700DC AFAA0028 */  sw    $t2, 0x28($sp)
/* 21E8B0 801700E0 8FAD0028 */  lw    $t5, 0x28($sp)
/* 21E8B4 801700E4 3C0C0600 */  lui   $t4, 0x600
/* 21E8B8 801700E8 ADAC0000 */  sw    $t4, ($t5)
/* 21E8BC 801700EC 8FAF0028 */  lw    $t7, 0x28($sp)
/* 21E8C0 801700F0 3C0E0201 */  lui   $t6, %hi(D_02014660) # $t6, 0x201
/* 21E8C4 801700F4 25CE4660 */  addiu $t6, %lo(D_02014660) # addiu $t6, $t6, 0x4660
/* 21E8C8 801700F8 ADEE0004 */  sw    $t6, 4($t7)
/* 21E8CC 801700FC 8FB90034 */  lw    $t9, 0x34($sp)
/* 21E8D0 80170100 27280008 */  addiu $t0, $t9, 8
/* 21E8D4 80170104 AFA80034 */  sw    $t0, 0x34($sp)
/* 21E8D8 80170108 AFB90024 */  sw    $t9, 0x24($sp)
/* 21E8DC 8017010C 8FB80024 */  lw    $t8, 0x24($sp)
/* 21E8E0 80170110 3C090600 */  lui   $t1, 0x600
/* 21E8E4 80170114 AF090000 */  sw    $t1, ($t8)
/* 21E8E8 80170118 8FAB0024 */  lw    $t3, 0x24($sp)
/* 21E8EC 8017011C 3C0A0A00 */  lui   $t2, %hi(D_0A000100) # $t2, 0xa00
/* 21E8F0 80170120 254A0100 */  addiu $t2, %lo(D_0A000100) # addiu $t2, $t2, 0x100
/* 21E8F4 80170124 AD6A0004 */  sw    $t2, 4($t3)
/* 21E8F8 80170128 AFA00030 */  sw    $zero, 0x30($sp)
.L8017012C:
/* 21E8FC 8017012C 8FAC0034 */  lw    $t4, 0x34($sp)
/* 21E900 80170130 258D0008 */  addiu $t5, $t4, 8
/* 21E904 80170134 AFAD0034 */  sw    $t5, 0x34($sp)
/* 21E908 80170138 AFAC0020 */  sw    $t4, 0x20($sp)
/* 21E90C 8017013C 8FAF0020 */  lw    $t7, 0x20($sp)
/* 21E910 80170140 3C0E0600 */  lui   $t6, 0x600
/* 21E914 80170144 ADEE0000 */  sw    $t6, ($t7)
/* 21E918 80170148 3C05801A */  lui   $a1, %hi(D_801A7BB8) # $a1, 0x801a
/* 21E91C 8017014C 24A57BB8 */  addiu $a1, %lo(D_801A7BB8) # addiu $a1, $a1, 0x7bb8
/* 21E920 80170150 0C05BEC4 */  jal   func_8016FB10
/* 21E924 80170154 8FA40030 */   lw    $a0, 0x30($sp)
/* 21E928 80170158 8FB90020 */  lw    $t9, 0x20($sp)
/* 21E92C 8017015C AF220004 */  sw    $v0, 4($t9)
/* 21E930 80170160 8FA80030 */  lw    $t0, 0x30($sp)
/* 21E934 80170164 25090001 */  addiu $t1, $t0, 1
/* 21E938 80170168 2921000C */  slti  $at, $t1, 0xc
/* 21E93C 8017016C 1420FFEF */  bnez  $at, .L8017012C
/* 21E940 80170170 AFA90030 */   sw    $t1, 0x30($sp)
/* 21E944 80170174 8FB80034 */  lw    $t8, 0x34($sp)
/* 21E948 80170178 270A0008 */  addiu $t2, $t8, 8
/* 21E94C 8017017C AFAA0034 */  sw    $t2, 0x34($sp)
/* 21E950 80170180 AFB8001C */  sw    $t8, 0x1c($sp)
/* 21E954 80170184 8FAC001C */  lw    $t4, 0x1c($sp)
/* 21E958 80170188 3C0B0600 */  lui   $t3, 0x600
/* 21E95C 8017018C AD8B0000 */  sw    $t3, ($t4)
/* 21E960 80170190 8FAE001C */  lw    $t6, 0x1c($sp)
/* 21E964 80170194 3C0D0A00 */  lui   $t5, %hi(D_0A000190) # $t5, 0xa00
/* 21E968 80170198 25AD0190 */  addiu $t5, %lo(D_0A000190) # addiu $t5, $t5, 0x190
/* 21E96C 8017019C ADCD0004 */  sw    $t5, 4($t6)
/* 21E970 801701A0 8FAF0034 */  lw    $t7, 0x34($sp)
/* 21E974 801701A4 AFAF0018 */  sw    $t7, 0x18($sp)
/* 21E978 801701A8 8FA80018 */  lw    $t0, 0x18($sp)
/* 21E97C 801701AC 3C19B800 */  lui   $t9, 0xb800
/* 21E980 801701B0 AD190000 */  sw    $t9, ($t0)
/* 21E984 801701B4 8FA90018 */  lw    $t1, 0x18($sp)
/* 21E988 801701B8 AD200004 */  sw    $zero, 4($t1)
.L801701BC:
/* 21E98C 801701BC 10000003 */  b     .L801701CC
/* 21E990 801701C0 8FA20038 */   lw    $v0, 0x38($sp)
/* 21E994 801701C4 10000001 */  b     .L801701CC
/* 21E998 801701C8 00000000 */   nop   
.L801701CC:
/* 21E99C 801701CC 8FBF0014 */  lw    $ra, 0x14($sp)
/* 21E9A0 801701D0 27BD0040 */  addiu $sp, $sp, 0x40
/* 21E9A4 801701D4 03E00008 */  jr    $ra
/* 21E9A8 801701D8 00000000 */   nop   

/* 21E9AC 801701DC 00000000 */  nop  
