# Super Mario 64 (J) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"
.include "globals.inc"

.section .text, "ax"

glabel menu
/* 21D7D0 8016F000 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 21D7D4 8016F004 AFBF0014 */  sw    $ra, 0x14($sp)
/* 21D7D8 8016F008 AFA40018 */  sw    $a0, 0x18($sp)
/* 21D7DC 8016F00C 3C018033 */  lui   $at, %hi(gDemoInputs) # $at, 0x8033
/* 21D7E0 8016F010 AC20C6B0 */  sw    $zero, %lo(gDemoInputs)($at)
/* 21D7E4 8016F014 8FAE0018 */  lw    $t6, 0x18($sp)
/* 21D7E8 8016F018 15C0003B */  bnez  $t6, .L8016F108
/* 21D7EC 8016F01C 00000000 */   nop   
/* 21D7F0 8016F020 3C0F8033 */  li    $t7, 0x80330000 # 0.000000
/* 21D7F4 8016F024 8DEFC6A4 */  lw    $t7, %lo(gPlayer1Controller)($t7)
/* 21D7F8 8016F028 95F80010 */  lhu   $t8, 0x10($t7)
/* 21D7FC 8016F02C 17000034 */  bnez  $t8, .L8016F100
/* 21D800 8016F030 00000000 */   nop   
/* 21D804 8016F034 C5E4000C */  lwc1  $f4, 0xc($t7)
/* 21D808 8016F038 44803000 */  mtc1  $zero, $f6
/* 21D80C 8016F03C 00000000 */  nop   
/* 21D810 8016F040 46062032 */  c.eq.s $f4, $f6
/* 21D814 8016F044 00000000 */  nop   
/* 21D818 8016F048 4500002D */  bc1f  .L8016F100
/* 21D81C 8016F04C 00000000 */   nop   
/* 21D820 8016F050 3C19801A */  lui   $t9, %hi(D_801A7AF0) # $t9, 0x801a
/* 21D824 8016F054 97397AF0 */  lhu   $t9, %lo(D_801A7AF0)($t9)
/* 21D828 8016F058 3C01801A */  lui   $at, %hi(D_801A7AF0) # $at, 0x801a
/* 21D82C 8016F05C 27280001 */  addiu $t0, $t9, 1
/* 21D830 8016F060 A4287AF0 */  sh    $t0, %lo(D_801A7AF0)($at)
/* 21D834 8016F064 24010320 */  li    $at, 800
/* 21D838 8016F068 3109FFFF */  andi  $t1, $t0, 0xffff
/* 21D83C 8016F06C 15210022 */  bne   $t1, $at, .L8016F0F8
/* 21D840 8016F070 00000000 */   nop   
/* 21D844 8016F074 3C048034 */  lui   $a0, %hi(D_80339D20) # $a0, 0x8034
/* 21D848 8016F078 3C058033 */  lui   $a1, %hi(D_8032C6B4) # $a1, 0x8033
/* 21D84C 8016F07C 94A5C6B4 */  lhu   $a1, %lo(D_8032C6B4)($a1)
/* 21D850 8016F080 0C09E2B5 */  jal   SetMarioAnimation
/* 21D854 8016F084 24849D20 */   addiu $a0, %lo(D_80339D20) # addiu $a0, $a0, -0x62e0
/* 21D858 8016F088 3C0A8033 */  lui   $t2, %hi(D_8032C6B4) # $t2, 0x8033
/* 21D85C 8016F08C 954AC6B4 */  lhu   $t2, %lo(D_8032C6B4)($t2)
/* 21D860 8016F090 3C0D8034 */  lui   $t5, %hi(D_80339D20) # $t5, 0x8034
/* 21D864 8016F094 8DAD9D20 */  lw    $t5, %lo(D_80339D20)($t5)
/* 21D868 8016F098 3C018033 */  lui   $at, %hi(D_8032C6B4) # $at, 0x8033
/* 21D86C 8016F09C 254B0001 */  addiu $t3, $t2, 1
/* 21D870 8016F0A0 A42BC6B4 */  sh    $t3, %lo(D_8032C6B4)($at)
/* 21D874 8016F0A4 8DAE0000 */  lw    $t6, ($t5)
/* 21D878 8016F0A8 316CFFFF */  andi  $t4, $t3, 0xffff
/* 21D87C 8016F0AC 158E0003 */  bne   $t4, $t6, .L8016F0BC
/* 21D880 8016F0B0 00000000 */   nop   
/* 21D884 8016F0B4 3C018033 */  lui   $at, %hi(D_8032C6B4) # $at, 0x8033
/* 21D888 8016F0B8 A420C6B4 */  sh    $zero, %lo(D_8032C6B4)($at)
.L8016F0BC:
/* 21D88C 8016F0BC 3C188034 */  lui   $t8, %hi(D_80339D28) # $t8, 0x8034
/* 21D890 8016F0C0 8F189D28 */  lw    $t8, %lo(D_80339D28)($t8)
/* 21D894 8016F0C4 3C018033 */  lui   $at, %hi(gDemoInputs) # $at, 0x8033
/* 21D898 8016F0C8 270F0004 */  addiu $t7, $t8, 4
/* 21D89C 8016F0CC AC2FC6B0 */  sw    $t7, %lo(gDemoInputs)($at)
/* 21D8A0 8016F0D0 3C198034 */  lui   $t9, %hi(D_80339D28) # $t9, 0x8034
/* 21D8A4 8016F0D4 8F399D28 */  lw    $t9, %lo(D_80339D28)($t9)
/* 21D8A8 8016F0D8 83280000 */  lb    $t0, ($t9)
/* 21D8AC 8016F0DC AFA80018 */  sw    $t0, 0x18($sp)
/* 21D8B0 8016F0E0 24090001 */  li    $t1, 1
/* 21D8B4 8016F0E4 3C018033 */  lui   $at, %hi(gCurrSaveFileNum) # $at, 0x8033
/* 21D8B8 8016F0E8 A429CE94 */  sh    $t1, %lo(gCurrSaveFileNum)($at)
/* 21D8BC 8016F0EC 240A0001 */  li    $t2, 1
/* 21D8C0 8016F0F0 3C018034 */  lui   $at, %hi(D_8033A758) # $at, 0x8034
/* 21D8C4 8016F0F4 A42AA758 */  sh    $t2, %lo(D_8033A758)($at)
.L8016F0F8:
/* 21D8C8 8016F0F8 10000003 */  b     .L8016F108
/* 21D8CC 8016F0FC 00000000 */   nop   
.L8016F100:
/* 21D8D0 8016F100 3C01801A */  lui   $at, %hi(D_801A7AF0) # $at, 0x801a
/* 21D8D4 8016F104 A4207AF0 */  sh    $zero, %lo(D_801A7AF0)($at)
.L8016F108:
/* 21D8D8 8016F108 10000003 */  b     .L8016F118
/* 21D8DC 8016F10C 8FA20018 */   lw    $v0, 0x18($sp)
/* 21D8E0 8016F110 10000001 */  b     .L8016F118
/* 21D8E4 8016F114 00000000 */   nop   
.L8016F118:
/* 21D8E8 8016F118 8FBF0014 */  lw    $ra, 0x14($sp)
/* 21D8EC 8016F11C 27BD0018 */  addiu $sp, $sp, 0x18
/* 21D8F0 8016F120 03E00008 */  jr    $ra
/* 21D8F4 8016F124 00000000 */   nop   

glabel func_8016F128
/* 21D8F8 8016F128 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 21D8FC 8016F12C AFBF0014 */  sw    $ra, 0x14($sp)
/* 21D900 8016F130 AFA0001C */  sw    $zero, 0x1c($sp)
/* 21D904 8016F134 3C0E8033 */  lui   $t6, %hi(gPlayer1Controller) # $t6, 0x8033
/* 21D908 8016F138 8DCEC6A4 */  lw    $t6, %lo(gPlayer1Controller)($t6)
/* 21D90C 8016F13C 95CF0012 */  lhu   $t7, 0x12($t6)
/* 21D910 8016F140 31F88000 */  andi  $t8, $t7, 0x8000
/* 21D914 8016F144 13000008 */  beqz  $t8, .L8016F168
/* 21D918 8016F148 00000000 */   nop   
/* 21D91C 8016F14C 3C198033 */  lui   $t9, %hi(D_8032CE98) # $t9, 0x8033
/* 21D920 8016F150 8739CE98 */  lh    $t9, %lo(D_8032CE98)($t9)
/* 21D924 8016F154 3C018033 */  lui   $at, %hi(D_8032CE98) # $at, 0x8033
/* 21D928 8016F158 24090001 */  li    $t1, 1
/* 21D92C 8016F15C 27280001 */  addiu $t0, $t9, 1
/* 21D930 8016F160 A428CE98 */  sh    $t0, %lo(D_8032CE98)($at)
/* 21D934 8016F164 AFA9001C */  sw    $t1, 0x1c($sp)
.L8016F168:
/* 21D938 8016F168 3C0A8033 */  lui   $t2, %hi(gPlayer1Controller) # $t2, 0x8033
/* 21D93C 8016F16C 8D4AC6A4 */  lw    $t2, %lo(gPlayer1Controller)($t2)
/* 21D940 8016F170 954B0012 */  lhu   $t3, 0x12($t2)
/* 21D944 8016F174 316C4000 */  andi  $t4, $t3, 0x4000
/* 21D948 8016F178 11800008 */  beqz  $t4, .L8016F19C
/* 21D94C 8016F17C 00000000 */   nop   
/* 21D950 8016F180 3C0D8033 */  lui   $t5, %hi(D_8032CE98) # $t5, 0x8033
/* 21D954 8016F184 85ADCE98 */  lh    $t5, %lo(D_8032CE98)($t5)
/* 21D958 8016F188 3C018033 */  lui   $at, %hi(D_8032CE98) # $at, 0x8033
/* 21D95C 8016F18C 240F0001 */  li    $t7, 1
/* 21D960 8016F190 25AEFFFF */  addiu $t6, $t5, -1
/* 21D964 8016F194 A42ECE98 */  sh    $t6, %lo(D_8032CE98)($at)
/* 21D968 8016F198 AFAF001C */  sw    $t7, 0x1c($sp)
.L8016F19C:
/* 21D96C 8016F19C 3C188033 */  lui   $t8, %hi(gPlayer1Controller) # $t8, 0x8033
/* 21D970 8016F1A0 8F18C6A4 */  lw    $t8, %lo(gPlayer1Controller)($t8)
/* 21D974 8016F1A4 97190012 */  lhu   $t9, 0x12($t8)
/* 21D978 8016F1A8 33280800 */  andi  $t0, $t9, 0x800
/* 21D97C 8016F1AC 11000008 */  beqz  $t0, .L8016F1D0
/* 21D980 8016F1B0 00000000 */   nop   
/* 21D984 8016F1B4 3C098033 */  lui   $t1, %hi(D_8032CE98) # $t1, 0x8033
/* 21D988 8016F1B8 8529CE98 */  lh    $t1, %lo(D_8032CE98)($t1)
/* 21D98C 8016F1BC 3C018033 */  lui   $at, %hi(D_8032CE98) # $at, 0x8033
/* 21D990 8016F1C0 240B0001 */  li    $t3, 1
/* 21D994 8016F1C4 252AFFFF */  addiu $t2, $t1, -1
/* 21D998 8016F1C8 A42ACE98 */  sh    $t2, %lo(D_8032CE98)($at)
/* 21D99C 8016F1CC AFAB001C */  sw    $t3, 0x1c($sp)
.L8016F1D0:
/* 21D9A0 8016F1D0 3C0C8033 */  lui   $t4, %hi(gPlayer1Controller) # $t4, 0x8033
/* 21D9A4 8016F1D4 8D8CC6A4 */  lw    $t4, %lo(gPlayer1Controller)($t4)
/* 21D9A8 8016F1D8 958D0012 */  lhu   $t5, 0x12($t4)
/* 21D9AC 8016F1DC 31AE0400 */  andi  $t6, $t5, 0x400
/* 21D9B0 8016F1E0 11C00008 */  beqz  $t6, .L8016F204
/* 21D9B4 8016F1E4 00000000 */   nop   
/* 21D9B8 8016F1E8 3C0F8033 */  lui   $t7, %hi(D_8032CE98) # $t7, 0x8033
/* 21D9BC 8016F1EC 85EFCE98 */  lh    $t7, %lo(D_8032CE98)($t7)
/* 21D9C0 8016F1F0 3C018033 */  lui   $at, %hi(D_8032CE98) # $at, 0x8033
/* 21D9C4 8016F1F4 24190001 */  li    $t9, 1
/* 21D9C8 8016F1F8 25F80001 */  addiu $t8, $t7, 1
/* 21D9CC 8016F1FC A438CE98 */  sh    $t8, %lo(D_8032CE98)($at)
/* 21D9D0 8016F200 AFB9001C */  sw    $t9, 0x1c($sp)
.L8016F204:
/* 21D9D4 8016F204 3C088033 */  lui   $t0, %hi(gPlayer1Controller) # $t0, 0x8033
/* 21D9D8 8016F208 8D08C6A4 */  lw    $t0, %lo(gPlayer1Controller)($t0)
/* 21D9DC 8016F20C 95090012 */  lhu   $t1, 0x12($t0)
/* 21D9E0 8016F210 312A0200 */  andi  $t2, $t1, 0x200
/* 21D9E4 8016F214 11400008 */  beqz  $t2, .L8016F238
/* 21D9E8 8016F218 00000000 */   nop   
/* 21D9EC 8016F21C 3C0B8033 */  lui   $t3, %hi(D_8032CE98) # $t3, 0x8033
/* 21D9F0 8016F220 856BCE98 */  lh    $t3, %lo(D_8032CE98)($t3)
/* 21D9F4 8016F224 3C018033 */  lui   $at, %hi(D_8032CE98) # $at, 0x8033
/* 21D9F8 8016F228 240D0001 */  li    $t5, 1
/* 21D9FC 8016F22C 256CFFF6 */  addiu $t4, $t3, -0xa
/* 21DA00 8016F230 A42CCE98 */  sh    $t4, %lo(D_8032CE98)($at)
/* 21DA04 8016F234 AFAD001C */  sw    $t5, 0x1c($sp)
.L8016F238:
/* 21DA08 8016F238 3C0E8033 */  lui   $t6, %hi(gPlayer1Controller) # $t6, 0x8033
/* 21DA0C 8016F23C 8DCEC6A4 */  lw    $t6, %lo(gPlayer1Controller)($t6)
/* 21DA10 8016F240 95CF0012 */  lhu   $t7, 0x12($t6)
/* 21DA14 8016F244 31F80100 */  andi  $t8, $t7, 0x100
/* 21DA18 8016F248 13000008 */  beqz  $t8, .L8016F26C
/* 21DA1C 8016F24C 00000000 */   nop   
/* 21DA20 8016F250 3C198033 */  lui   $t9, %hi(D_8032CE98) # $t9, 0x8033
/* 21DA24 8016F254 8739CE98 */  lh    $t9, %lo(D_8032CE98)($t9)
/* 21DA28 8016F258 3C018033 */  lui   $at, %hi(D_8032CE98) # $at, 0x8033
/* 21DA2C 8016F25C 24090001 */  li    $t1, 1
/* 21DA30 8016F260 2728000A */  addiu $t0, $t9, 0xa
/* 21DA34 8016F264 A428CE98 */  sh    $t0, %lo(D_8032CE98)($at)
/* 21DA38 8016F268 AFA9001C */  sw    $t1, 0x1c($sp)
.L8016F26C:
/* 21DA3C 8016F26C 8FAA001C */  lw    $t2, 0x1c($sp)
/* 21DA40 8016F270 11400006 */  beqz  $t2, .L8016F28C
/* 21DA44 8016F274 00000000 */   nop   
/* 21DA48 8016F278 3C04302B */  lui   $a0, (0x302B0081 >> 16) # lui $a0, 0x302b
/* 21DA4C 8016F27C 3C058033 */  lui   $a1, %hi(D_803320E0) # $a1, 0x8033
/* 21DA50 8016F280 24A520E0 */  addiu $a1, %lo(D_803320E0) # addiu $a1, $a1, 0x20e0
/* 21DA54 8016F284 0C0C771E */  jal   SetSound
/* 21DA58 8016F288 34840081 */   ori   $a0, (0x302B0081 & 0xFFFF) # ori $a0, $a0, 0x81
.L8016F28C:
/* 21DA5C 8016F28C 3C0B8033 */  lui   $t3, %hi(D_8032CE98) # $t3, 0x8033
/* 21DA60 8016F290 856BCE98 */  lh    $t3, %lo(D_8032CE98)($t3)
/* 21DA64 8016F294 29610027 */  slti  $at, $t3, 0x27
/* 21DA68 8016F298 14200004 */  bnez  $at, .L8016F2AC
/* 21DA6C 8016F29C 00000000 */   nop   
/* 21DA70 8016F2A0 240C0001 */  li    $t4, 1
/* 21DA74 8016F2A4 3C018033 */  lui   $at, %hi(D_8032CE98) # $at, 0x8033
/* 21DA78 8016F2A8 A42CCE98 */  sh    $t4, %lo(D_8032CE98)($at)
.L8016F2AC:
/* 21DA7C 8016F2AC 3C0D8033 */  lui   $t5, %hi(D_8032CE98) # $t5, 0x8033
/* 21DA80 8016F2B0 85ADCE98 */  lh    $t5, %lo(D_8032CE98)($t5)
/* 21DA84 8016F2B4 1DA00004 */  bgtz  $t5, .L8016F2C8
/* 21DA88 8016F2B8 00000000 */   nop   
/* 21DA8C 8016F2BC 240E0026 */  li    $t6, 38
/* 21DA90 8016F2C0 3C018033 */  lui   $at, %hi(D_8032CE98) # $at, 0x8033
/* 21DA94 8016F2C4 A42ECE98 */  sh    $t6, %lo(D_8032CE98)($at)
.L8016F2C8:
/* 21DA98 8016F2C8 240F0004 */  li    $t7, 4
/* 21DA9C 8016F2CC 3C018033 */  lui   $at, %hi(gCurrSaveFileNum) # $at, 0x8033
/* 21DAA0 8016F2D0 A42FCE94 */  sh    $t7, %lo(gCurrSaveFileNum)($at)
/* 21DAA4 8016F2D4 24180006 */  li    $t8, 6
/* 21DAA8 8016F2D8 3C018034 */  lui   $at, %hi(D_8033A758) # $at, 0x8034
/* 21DAAC 8016F2DC A438A758 */  sh    $t8, %lo(D_8033A758)($at)
/* 21DAB0 8016F2E0 3C06801A */  lui   $a2, %hi(D_801A7B00) # $a2, 0x801a
/* 21DAB4 8016F2E4 24C67B00 */  addiu $a2, %lo(D_801A7B00) # addiu $a2, $a2, 0x7b00
/* 21DAB8 8016F2E8 240400A0 */  li    $a0, 160
/* 21DABC 8016F2EC 0C0B56F8 */  jal   PrintXY
/* 21DAC0 8016F2F0 24050050 */   li    $a1, 80
/* 21DAC4 8016F2F4 3C06801A */  lui   $a2, %hi(D_801A7B10) # $a2, 0x801a
/* 21DAC8 8016F2F8 24C67B10 */  addiu $a2, %lo(D_801A7B10) # addiu $a2, $a2, 0x7b10
/* 21DACC 8016F2FC 240400A0 */  li    $a0, 160
/* 21DAD0 8016F300 0C0B56F8 */  jal   PrintXY
/* 21DAD4 8016F304 2405001E */   li    $a1, 30
/* 21DAD8 8016F308 3C06801A */  lui   $a2, %hi(D_801A7B24) # $a2, 0x801a
/* 21DADC 8016F30C 3C078033 */  lui   $a3, %hi(D_8032CE98) # $a3, 0x8033
/* 21DAE0 8016F310 84E7CE98 */  lh    $a3, %lo(D_8032CE98)($a3)
/* 21DAE4 8016F314 24C67B24 */  addiu $a2, %lo(D_801A7B24) # addiu $a2, $a2, 0x7b24
/* 21DAE8 8016F318 24040028 */  li    $a0, 40
/* 21DAEC 8016F31C 0C0B55FE */  jal   PrintInt
/* 21DAF0 8016F320 2405003C */   li    $a1, 60
/* 21DAF4 8016F324 3C198033 */  lui   $t9, %hi(D_8032CE98) # $t9, 0x8033
/* 21DAF8 8016F328 8739CE98 */  lh    $t9, %lo(D_8032CE98)($t9)
/* 21DAFC 8016F32C 3C0A801A */  lui   $t2, %hi(D_801A76F0) # $t2, 0x801a
/* 21DB00 8016F330 254A76F0 */  addiu $t2, %lo(D_801A76F0) # addiu $t2, $t2, 0x76f0
/* 21DB04 8016F334 00194100 */  sll   $t0, $t9, 4
/* 21DB08 8016F338 2509FFF0 */  addiu $t1, $t0, -0x10
/* 21DB0C 8016F33C 012A3021 */  addu  $a2, $t1, $t2
/* 21DB10 8016F340 24040050 */  li    $a0, 80
/* 21DB14 8016F344 0C0B569D */  jal   PrintStr
/* 21DB18 8016F348 2405003C */   li    $a1, 60
/* 21DB1C 8016F34C 3C0B8033 */  lui   $t3, %hi(gPlayer1Controller) # $t3, 0x8033
/* 21DB20 8016F350 8D6BC6A4 */  lw    $t3, %lo(gPlayer1Controller)($t3)
/* 21DB24 8016F354 956C0012 */  lhu   $t4, 0x12($t3)
/* 21DB28 8016F358 318D1000 */  andi  $t5, $t4, 0x1000
/* 21DB2C 8016F35C 11A00013 */  beqz  $t5, .L8016F3AC
/* 21DB30 8016F360 00000000 */   nop   
/* 21DB34 8016F364 3C0E8033 */  lui   $t6, %hi(gPlayer1Controller) # $t6, 0x8033
/* 21DB38 8016F368 8DCEC6A4 */  lw    $t6, %lo(gPlayer1Controller)($t6)
/* 21DB3C 8016F36C 24013003 */  li    $at, 12291
/* 21DB40 8016F370 95CF0010 */  lhu   $t7, 0x10($t6)
/* 21DB44 8016F374 15E10005 */  bne   $t7, $at, .L8016F38C
/* 21DB48 8016F378 00000000 */   nop   
/* 21DB4C 8016F37C 3C018033 */  lui   $at, %hi(D_8032C64C) # $at, 0x8033
/* 21DB50 8016F380 A020C64C */  sb    $zero, %lo(D_8032C64C)($at)
/* 21DB54 8016F384 1000000D */  b     .L8016F3BC
/* 21DB58 8016F388 2402FFFF */   li    $v0, -1
.L8016F38C:
/* 21DB5C 8016F38C 3C04701E */  lui   $a0, (0x701EFF81 >> 16) # lui $a0, 0x701e
/* 21DB60 8016F390 3C058033 */  lui   $a1, %hi(D_803320E0) # $a1, 0x8033
/* 21DB64 8016F394 24A520E0 */  addiu $a1, %lo(D_803320E0) # addiu $a1, $a1, 0x20e0
/* 21DB68 8016F398 0C0C771E */  jal   SetSound
/* 21DB6C 8016F39C 3484FF81 */   ori   $a0, (0x701EFF81 & 0xFFFF) # ori $a0, $a0, 0xff81
/* 21DB70 8016F3A0 3C028033 */  lui   $v0, %hi(D_8032CE98) # $v0, 0x8033
/* 21DB74 8016F3A4 10000005 */  b     .L8016F3BC
/* 21DB78 8016F3A8 8442CE98 */   lh    $v0, %lo(D_8032CE98)($v0)
.L8016F3AC:
/* 21DB7C 8016F3AC 10000003 */  b     .L8016F3BC
/* 21DB80 8016F3B0 00001025 */   move  $v0, $zero
/* 21DB84 8016F3B4 10000001 */  b     .L8016F3BC
/* 21DB88 8016F3B8 00000000 */   nop   
.L8016F3BC:
/* 21DB8C 8016F3BC 8FBF0014 */  lw    $ra, 0x14($sp)
/* 21DB90 8016F3C0 27BD0020 */  addiu $sp, $sp, 0x20
/* 21DB94 8016F3C4 03E00008 */  jr    $ra
/* 21DB98 8016F3C8 00000000 */   nop   

glabel func_8016F3CC
/* 21DB9C 8016F3CC 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 21DBA0 8016F3D0 AFBF0014 */  sw    $ra, 0x14($sp)
/* 21DBA4 8016F3D4 AFA0001C */  sw    $zero, 0x1c($sp)
/* 21DBA8 8016F3D8 0C09E8C0 */  jal   IntroPrintText
/* 21DBAC 8016F3DC 00000000 */   nop   
/* 21DBB0 8016F3E0 3C0E8033 */  lui   $t6, %hi(gPlayer1Controller) # $t6, 0x8033
/* 21DBB4 8016F3E4 8DCEC6A4 */  lw    $t6, %lo(gPlayer1Controller)($t6)
/* 21DBB8 8016F3E8 95CF0012 */  lhu   $t7, 0x12($t6)
/* 21DBBC 8016F3EC 31F81000 */  andi  $t8, $t7, 0x1000
/* 21DBC0 8016F3F0 1300000A */  beqz  $t8, .L8016F41C
/* 21DBC4 8016F3F4 00000000 */   nop   
/* 21DBC8 8016F3F8 3C04701E */  lui   $a0, (0x701EFF81 >> 16) # lui $a0, 0x701e
/* 21DBCC 8016F3FC 3C058033 */  lui   $a1, %hi(D_803320E0) # $a1, 0x8033
/* 21DBD0 8016F400 24A520E0 */  addiu $a1, %lo(D_803320E0) # addiu $a1, $a1, 0x20e0
/* 21DBD4 8016F404 0C0C771E */  jal   SetSound
/* 21DBD8 8016F408 3484FF81 */   ori   $a0, (0x701EFF81 & 0xFFFF) # ori $a0, $a0, 0xff81
/* 21DBDC 8016F40C 3C198033 */  lui   $t9, %hi(D_8032C64C) # $t9, 0x8033
/* 21DBE0 8016F410 8339C64C */  lb    $t9, %lo(D_8032C64C)($t9)
/* 21DBE4 8016F414 27280064 */  addiu $t0, $t9, 0x64
/* 21DBE8 8016F418 AFA8001C */  sw    $t0, 0x1c($sp)
.L8016F41C:
/* 21DBEC 8016F41C 0C05BC00 */  jal   menu
/* 21DBF0 8016F420 8FA4001C */   lw    $a0, 0x1c($sp)
/* 21DBF4 8016F424 10000003 */  b     .L8016F434
/* 21DBF8 8016F428 00000000 */   nop   
/* 21DBFC 8016F42C 10000001 */  b     .L8016F434
/* 21DC00 8016F430 00000000 */   nop   
.L8016F434:
/* 21DC04 8016F434 8FBF0014 */  lw    $ra, 0x14($sp)
/* 21DC08 8016F438 27BD0020 */  addiu $sp, $sp, 0x20
/* 21DC0C 8016F43C 03E00008 */  jr    $ra
/* 21DC10 8016F440 00000000 */   nop   

glabel func_8016F444
/* 21DC14 8016F444 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 21DC18 8016F448 AFBF0014 */  sw    $ra, 0x14($sp)
/* 21DC1C 8016F44C AFA0001C */  sw    $zero, 0x1c($sp)
/* 21DC20 8016F450 0C09E8C0 */  jal   IntroPrintText
/* 21DC24 8016F454 00000000 */   nop   
/* 21DC28 8016F458 3C0E8033 */  lui   $t6, %hi(gPlayer1Controller) # $t6, 0x8033
/* 21DC2C 8016F45C 8DCEC6A4 */  lw    $t6, %lo(gPlayer1Controller)($t6)
/* 21DC30 8016F460 95CF0012 */  lhu   $t7, 0x12($t6)
/* 21DC34 8016F464 31F81000 */  andi  $t8, $t7, 0x1000
/* 21DC38 8016F468 1300000A */  beqz  $t8, .L8016F494
/* 21DC3C 8016F46C 00000000 */   nop   
/* 21DC40 8016F470 3C04701E */  lui   $a0, (0x701EFF81 >> 16) # lui $a0, 0x701e
/* 21DC44 8016F474 3C058033 */  lui   $a1, %hi(D_803320E0) # $a1, 0x8033
/* 21DC48 8016F478 24A520E0 */  addiu $a1, %lo(D_803320E0) # addiu $a1, $a1, 0x20e0
/* 21DC4C 8016F47C 0C0C771E */  jal   SetSound
/* 21DC50 8016F480 3484FF81 */   ori   $a0, (0x701EFF81 & 0xFFFF) # ori $a0, $a0, 0xff81
/* 21DC54 8016F484 3C198033 */  lui   $t9, %hi(D_8032C64C) # $t9, 0x8033
/* 21DC58 8016F488 8339C64C */  lb    $t9, %lo(D_8032C64C)($t9)
/* 21DC5C 8016F48C 27280064 */  addiu $t0, $t9, 0x64
/* 21DC60 8016F490 AFA8001C */  sw    $t0, 0x1c($sp)
.L8016F494:
/* 21DC64 8016F494 0C05BC00 */  jal   menu
/* 21DC68 8016F498 8FA4001C */   lw    $a0, 0x1c($sp)
/* 21DC6C 8016F49C 10000003 */  b     .L8016F4AC
/* 21DC70 8016F4A0 00000000 */   nop   
/* 21DC74 8016F4A4 10000001 */  b     .L8016F4AC
/* 21DC78 8016F4A8 00000000 */   nop   
.L8016F4AC:
/* 21DC7C 8016F4AC 8FBF0014 */  lw    $ra, 0x14($sp)
/* 21DC80 8016F4B0 27BD0020 */  addiu $sp, $sp, 0x20
/* 21DC84 8016F4B4 03E00008 */  jr    $ra
/* 21DC88 8016F4B8 00000000 */   nop   

glabel func_8016F4BC
/* 21DC8C 8016F4BC 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 21DC90 8016F4C0 AFBF0014 */  sw    $ra, 0x14($sp)
/* 21DC94 8016F4C4 00002025 */  move  $a0, $zero
/* 21DC98 8016F4C8 00002825 */  move  $a1, $zero
/* 21DC9C 8016F4CC 0C092452 */  jal   func_80249148
/* 21DCA0 8016F4D0 00003025 */   move  $a2, $zero
/* 21DCA4 8016F4D4 3C047014 */  lui   $a0, (0x70140081 >> 16) # lui $a0, 0x7014
/* 21DCA8 8016F4D8 3C058033 */  lui   $a1, %hi(D_803320E0) # $a1, 0x8033
/* 21DCAC 8016F4DC 24A520E0 */  addiu $a1, %lo(D_803320E0) # addiu $a1, $a1, 0x20e0
/* 21DCB0 8016F4E0 0C0C771E */  jal   SetSound
/* 21DCB4 8016F4E4 34840081 */   ori   $a0, (0x70140081 & 0xFFFF) # ori $a0, $a0, 0x81
/* 21DCB8 8016F4E8 10000003 */  b     .L8016F4F8
/* 21DCBC 8016F4EC 24020001 */   li    $v0, 1
/* 21DCC0 8016F4F0 10000001 */  b     .L8016F4F8
/* 21DCC4 8016F4F4 00000000 */   nop   
.L8016F4F8:
/* 21DCC8 8016F4F8 8FBF0014 */  lw    $ra, 0x14($sp)
/* 21DCCC 8016F4FC 27BD0018 */  addiu $sp, $sp, 0x18
/* 21DCD0 8016F500 03E00008 */  jr    $ra
/* 21DCD4 8016F504 00000000 */   nop   

glabel LevelProc_8016F508
/* 21DCD8 8016F508 27BDFFD8 */  addiu $sp, $sp, -0x28
/* 21DCDC 8016F50C AFBF001C */  sw    $ra, 0x1c($sp)
/* 21DCE0 8016F510 AFA40028 */  sw    $a0, 0x28($sp)
/* 21DCE4 8016F514 AFA5002C */  sw    $a1, 0x2c($sp)
/* 21DCE8 8016F518 AFB00018 */  sw    $s0, 0x18($sp)
/* 21DCEC 8016F51C 87B0002A */  lh    $s0, 0x2a($sp)
/* 21DCF0 8016F520 1200000C */  beqz  $s0, .L8016F554
/* 21DCF4 8016F524 00000000 */   nop   
/* 21DCF8 8016F528 24010001 */  li    $at, 1
/* 21DCFC 8016F52C 1201000E */  beq   $s0, $at, .L8016F568
/* 21DD00 8016F530 00000000 */   nop   
/* 21DD04 8016F534 24010002 */  li    $at, 2
/* 21DD08 8016F538 12010010 */  beq   $s0, $at, .L8016F57C
/* 21DD0C 8016F53C 00000000 */   nop   
/* 21DD10 8016F540 24010003 */  li    $at, 3
/* 21DD14 8016F544 12010012 */  beq   $s0, $at, .L8016F590
/* 21DD18 8016F548 00000000 */   nop   
/* 21DD1C 8016F54C 10000015 */  b     .L8016F5A4
/* 21DD20 8016F550 00000000 */   nop   
.L8016F554:
/* 21DD24 8016F554 0C05BD2F */  jal   func_8016F4BC
/* 21DD28 8016F558 00000000 */   nop   
/* 21DD2C 8016F55C AFA20024 */  sw    $v0, 0x24($sp)
/* 21DD30 8016F560 10000010 */  b     .L8016F5A4
/* 21DD34 8016F564 00000000 */   nop   
.L8016F568:
/* 21DD38 8016F568 0C05BCF3 */  jal   func_8016F3CC
/* 21DD3C 8016F56C 00000000 */   nop   
/* 21DD40 8016F570 AFA20024 */  sw    $v0, 0x24($sp)
/* 21DD44 8016F574 1000000B */  b     .L8016F5A4
/* 21DD48 8016F578 00000000 */   nop   
.L8016F57C:
/* 21DD4C 8016F57C 0C05BD11 */  jal   func_8016F444
/* 21DD50 8016F580 00000000 */   nop   
/* 21DD54 8016F584 AFA20024 */  sw    $v0, 0x24($sp)
/* 21DD58 8016F588 10000006 */  b     .L8016F5A4
/* 21DD5C 8016F58C 00000000 */   nop   
.L8016F590:
/* 21DD60 8016F590 0C05BC4A */  jal   func_8016F128
/* 21DD64 8016F594 00000000 */   nop   
/* 21DD68 8016F598 AFA20024 */  sw    $v0, 0x24($sp)
/* 21DD6C 8016F59C 10000001 */  b     .L8016F5A4
/* 21DD70 8016F5A0 00000000 */   nop   
.L8016F5A4:
/* 21DD74 8016F5A4 10000003 */  b     .L8016F5B4
/* 21DD78 8016F5A8 8FA20024 */   lw    $v0, 0x24($sp)
/* 21DD7C 8016F5AC 10000001 */  b     .L8016F5B4
/* 21DD80 8016F5B0 00000000 */   nop   
.L8016F5B4:
/* 21DD84 8016F5B4 8FBF001C */  lw    $ra, 0x1c($sp)
/* 21DD88 8016F5B8 8FB00018 */  lw    $s0, 0x18($sp)
/* 21DD8C 8016F5BC 27BD0028 */  addiu $sp, $sp, 0x28
/* 21DD90 8016F5C0 03E00008 */  jr    $ra
/* 21DD94 8016F5C4 00000000 */   nop   

/* 21DD98 8016F5C8 00000000 */  nop   
/* 21DD9C 8016F5CC 00000000 */  nop   
