# Super Mario 64 (J) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax"

glabel func_8029BFF0
/* 056FF0 8029BFF0 03E00008 */  jr    $ra
/* 056FF4 8029BFF4 00000000 */   nop   

/* 056FF8 8029BFF8 03E00008 */  jr    $ra
/* 056FFC 8029BFFC 00000000 */   nop   

glabel func_8029C000
/* 057000 8029C000 27BDFFF8 */  addiu $sp, $sp, -8
/* 057004 8029C004 AFA00004 */  sw    $zero, 4($sp)
/* 057008 8029C008 3C0E8036 */  lui   $t6, %hi(gCurrentObject) # $t6, 0x8036
/* 05700C 8029C00C 3C0F8036 */  lui   $t7, %hi(gMarioObject) # $t7, 0x8036
/* 057010 8029C010 8DEFFDE8 */  lw    $t7, %lo(gMarioObject)($t7)
/* 057014 8029C014 8DCEFDF0 */  lw    $t6, %lo(gCurrentObject)($t6)
/* 057018 8029C018 11CF0004 */  beq   $t6, $t7, .L8029C02C
/* 05701C 8029C01C 00000000 */   nop   
/* 057020 8029C020 8FB80004 */  lw    $t8, 4($sp)
/* 057024 8029C024 27190001 */  addiu $t9, $t8, 1
/* 057028 8029C028 AFB90004 */  sw    $t9, 4($sp)
.L8029C02C:
/* 05702C 8029C02C 8FA80004 */  lw    $t0, 4($sp)
/* 057030 8029C030 3C018034 */  lui   $at, %hi(D_80339E48)
/* 057034 8029C034 3C0A8036 */  lui   $t2, %hi(gCurrentObject) # $t2, 0x8036
/* 057038 8029C038 00084880 */  sll   $t1, $t0, 2
/* 05703C 8029C03C 01284823 */  subu  $t1, $t1, $t0
/* 057040 8029C040 000948C0 */  sll   $t1, $t1, 3
/* 057044 8029C044 01284821 */  addu  $t1, $t1, $t0
/* 057048 8029C048 000948C0 */  sll   $t1, $t1, 3
/* 05704C 8029C04C 00290821 */  addu  $at, $at, $t1
/* 057050 8029C050 C4249E48 */  lwc1  $f4, %lo(D_80339E48)($at)
/* 057054 8029C054 8D4AFDF0 */  lw    $t2, %lo(gCurrentObject)($t2)
/* 057058 8029C058 E54400AC */  swc1  $f4, 0xac($t2)
/* 05705C 8029C05C 8FAB0004 */  lw    $t3, 4($sp)
/* 057060 8029C060 3C018034 */  lui   $at, %hi(D_80339E4C)
/* 057064 8029C064 3C0D8036 */  lui   $t5, %hi(gCurrentObject) # $t5, 0x8036
/* 057068 8029C068 000B6080 */  sll   $t4, $t3, 2
/* 05706C 8029C06C 018B6023 */  subu  $t4, $t4, $t3
/* 057070 8029C070 000C60C0 */  sll   $t4, $t4, 3
/* 057074 8029C074 018B6021 */  addu  $t4, $t4, $t3
/* 057078 8029C078 000C60C0 */  sll   $t4, $t4, 3
/* 05707C 8029C07C 002C0821 */  addu  $at, $at, $t4
/* 057080 8029C080 C4269E4C */  lwc1  $f6, %lo(D_80339E4C)($at)
/* 057084 8029C084 8DADFDF0 */  lw    $t5, %lo(gCurrentObject)($t5)
/* 057088 8029C088 E5A600B0 */  swc1  $f6, 0xb0($t5)
/* 05708C 8029C08C 8FAE0004 */  lw    $t6, 4($sp)
/* 057090 8029C090 3C018034 */  lui   $at, %hi(D_80339E50)
/* 057094 8029C094 3C188036 */  lui   $t8, %hi(gCurrentObject) # $t8, 0x8036
/* 057098 8029C098 000E7880 */  sll   $t7, $t6, 2
/* 05709C 8029C09C 01EE7823 */  subu  $t7, $t7, $t6
/* 0570A0 8029C0A0 000F78C0 */  sll   $t7, $t7, 3
/* 0570A4 8029C0A4 01EE7821 */  addu  $t7, $t7, $t6
/* 0570A8 8029C0A8 000F78C0 */  sll   $t7, $t7, 3
/* 0570AC 8029C0AC 002F0821 */  addu  $at, $at, $t7
/* 0570B0 8029C0B0 C4289E50 */  lwc1  $f8, %lo(D_80339E50)($at)
/* 0570B4 8029C0B4 8F18FDF0 */  lw    $t8, %lo(gCurrentObject)($t8)
/* 0570B8 8029C0B8 E70800B4 */  swc1  $f8, 0xb4($t8)
/* 0570BC 8029C0BC 8FB90004 */  lw    $t9, 4($sp)
/* 0570C0 8029C0C0 3C018034 */  lui   $at, %hi(D_80339E3C)
/* 0570C4 8029C0C4 3C098036 */  lui   $t1, %hi(gCurrentObject) # $t1, 0x8036
/* 0570C8 8029C0C8 00194080 */  sll   $t0, $t9, 2
/* 0570CC 8029C0CC 01194023 */  subu  $t0, $t0, $t9
/* 0570D0 8029C0D0 000840C0 */  sll   $t0, $t0, 3
/* 0570D4 8029C0D4 01194021 */  addu  $t0, $t0, $t9
/* 0570D8 8029C0D8 000840C0 */  sll   $t0, $t0, 3
/* 0570DC 8029C0DC 00280821 */  addu  $at, $at, $t0
/* 0570E0 8029C0E0 C42A9E3C */  lwc1  $f10, %lo(D_80339E3C)($at)
/* 0570E4 8029C0E4 8D29FDF0 */  lw    $t1, %lo(gCurrentObject)($t1)
/* 0570E8 8029C0E8 E52A00A0 */  swc1  $f10, 0xa0($t1)
/* 0570EC 8029C0EC 8FAA0004 */  lw    $t2, 4($sp)
/* 0570F0 8029C0F0 3C018034 */  lui   $at, %hi(D_80339E40)
/* 0570F4 8029C0F4 3C0C8036 */  lui   $t4, %hi(gCurrentObject) # $t4, 0x8036
/* 0570F8 8029C0F8 000A5880 */  sll   $t3, $t2, 2
/* 0570FC 8029C0FC 016A5823 */  subu  $t3, $t3, $t2
/* 057100 8029C100 000B58C0 */  sll   $t3, $t3, 3
/* 057104 8029C104 016A5821 */  addu  $t3, $t3, $t2
/* 057108 8029C108 000B58C0 */  sll   $t3, $t3, 3
/* 05710C 8029C10C 002B0821 */  addu  $at, $at, $t3
/* 057110 8029C110 C4309E40 */  lwc1  $f16, %lo(D_80339E40)($at)
/* 057114 8029C114 8D8CFDF0 */  lw    $t4, %lo(gCurrentObject)($t4)
/* 057118 8029C118 E59000A4 */  swc1  $f16, 0xa4($t4)
/* 05711C 8029C11C 8FAD0004 */  lw    $t5, 4($sp)
/* 057120 8029C120 3C018034 */  lui   $at, %hi(D_80339E44)
/* 057124 8029C124 3C0F8036 */  lui   $t7, %hi(gCurrentObject) # $t7, 0x8036
/* 057128 8029C128 000D7080 */  sll   $t6, $t5, 2
/* 05712C 8029C12C 01CD7023 */  subu  $t6, $t6, $t5
/* 057130 8029C130 000E70C0 */  sll   $t6, $t6, 3
/* 057134 8029C134 01CD7021 */  addu  $t6, $t6, $t5
/* 057138 8029C138 000E70C0 */  sll   $t6, $t6, 3
/* 05713C 8029C13C 002E0821 */  addu  $at, $at, $t6
/* 057140 8029C140 C4329E44 */  lwc1  $f18, %lo(D_80339E44)($at)
/* 057144 8029C144 8DEFFDF0 */  lw    $t7, %lo(gCurrentObject)($t7)
/* 057148 8029C148 E5F200A8 */  swc1  $f18, 0xa8($t7)
/* 05714C 8029C14C 3C188036 */  lui   $t8, %hi(gCurrentObject) # $t8, 0x8036
/* 057150 8029C150 8F18FDF0 */  lw    $t8, %lo(gCurrentObject)($t8)
/* 057154 8029C154 8719001A */  lh    $t9, 0x1a($t8)
/* 057158 8029C158 AF1900C4 */  sw    $t9, 0xc4($t8)
/* 05715C 8029C15C 3C088036 */  lui   $t0, %hi(gCurrentObject) # $t0, 0x8036
/* 057160 8029C160 8D08FDF0 */  lw    $t0, %lo(gCurrentObject)($t0)
/* 057164 8029C164 8509001C */  lh    $t1, 0x1c($t0)
/* 057168 8029C168 AD0900C8 */  sw    $t1, 0xc8($t0)
/* 05716C 8029C16C 3C0A8036 */  lui   $t2, %hi(gCurrentObject) # $t2, 0x8036
/* 057170 8029C170 8D4AFDF0 */  lw    $t2, %lo(gCurrentObject)($t2)
/* 057174 8029C174 854B001E */  lh    $t3, 0x1e($t2)
/* 057178 8029C178 AD4B00CC */  sw    $t3, 0xcc($t2)
/* 05717C 8029C17C 3C0C8036 */  lui   $t4, %hi(gCurrentObject) # $t4, 0x8036
/* 057180 8029C180 8D8CFDF0 */  lw    $t4, %lo(gCurrentObject)($t4)
/* 057184 8029C184 858D001A */  lh    $t5, 0x1a($t4)
/* 057188 8029C188 AD8D00D0 */  sw    $t5, 0xd0($t4)
/* 05718C 8029C18C 3C0E8036 */  lui   $t6, %hi(gCurrentObject) # $t6, 0x8036
/* 057190 8029C190 8DCEFDF0 */  lw    $t6, %lo(gCurrentObject)($t6)
/* 057194 8029C194 85CF001C */  lh    $t7, 0x1c($t6)
/* 057198 8029C198 ADCF00D4 */  sw    $t7, 0xd4($t6)
/* 05719C 8029C19C 3C198036 */  lui   $t9, %hi(gCurrentObject) # $t9, 0x8036
/* 0571A0 8029C1A0 8F39FDF0 */  lw    $t9, %lo(gCurrentObject)($t9)
/* 0571A4 8029C1A4 8738001E */  lh    $t8, 0x1e($t9)
/* 0571A8 8029C1A8 AF3800D8 */  sw    $t8, 0xd8($t9)
/* 0571AC 8029C1AC 8FA90004 */  lw    $t1, 4($sp)
/* 0571B0 8029C1B0 3C0B8034 */  lui   $t3, %hi(D_80339E32)
/* 0571B4 8029C1B4 3C0A8036 */  lui   $t2, %hi(gCurrentObject) # $t2, 0x8036
/* 0571B8 8029C1B8 00094080 */  sll   $t0, $t1, 2
/* 0571BC 8029C1BC 01094023 */  subu  $t0, $t0, $t1
/* 0571C0 8029C1C0 000840C0 */  sll   $t0, $t0, 3
/* 0571C4 8029C1C4 01094021 */  addu  $t0, $t0, $t1
/* 0571C8 8029C1C8 000840C0 */  sll   $t0, $t0, 3
/* 0571CC 8029C1CC 01685821 */  addu  $t3, $t3, $t0
/* 0571D0 8029C1D0 856B9E32 */  lh    $t3, %lo(D_80339E32)($t3)
/* 0571D4 8029C1D4 8D4AFDF0 */  lw    $t2, %lo(gCurrentObject)($t2)
/* 0571D8 8029C1D8 AD4B0114 */  sw    $t3, 0x114($t2)
/* 0571DC 8029C1DC 8FAD0004 */  lw    $t5, 4($sp)
/* 0571E0 8029C1E0 3C0F8034 */  lui   $t7, %hi(D_80339E34)
/* 0571E4 8029C1E4 3C0E8036 */  lui   $t6, %hi(gCurrentObject) # $t6, 0x8036
/* 0571E8 8029C1E8 000D6080 */  sll   $t4, $t5, 2
/* 0571EC 8029C1EC 018D6023 */  subu  $t4, $t4, $t5
/* 0571F0 8029C1F0 000C60C0 */  sll   $t4, $t4, 3
/* 0571F4 8029C1F4 018D6021 */  addu  $t4, $t4, $t5
/* 0571F8 8029C1F8 000C60C0 */  sll   $t4, $t4, 3
/* 0571FC 8029C1FC 01EC7821 */  addu  $t7, $t7, $t4
/* 057200 8029C200 85EF9E34 */  lh    $t7, %lo(D_80339E34)($t7)
/* 057204 8029C204 8DCEFDF0 */  lw    $t6, %lo(gCurrentObject)($t6)
/* 057208 8029C208 ADCF0118 */  sw    $t7, 0x118($t6)
/* 05720C 8029C20C 8FB80004 */  lw    $t8, 4($sp)
/* 057210 8029C210 3C098034 */  lui   $t1, %hi(D_80339E36)
/* 057214 8029C214 3C088036 */  lui   $t0, %hi(gCurrentObject) # $t0, 0x8036
/* 057218 8029C218 0018C880 */  sll   $t9, $t8, 2
/* 05721C 8029C21C 0338C823 */  subu  $t9, $t9, $t8
/* 057220 8029C220 0019C8C0 */  sll   $t9, $t9, 3
/* 057224 8029C224 0338C821 */  addu  $t9, $t9, $t8
/* 057228 8029C228 0019C8C0 */  sll   $t9, $t9, 3
/* 05722C 8029C22C 01394821 */  addu  $t1, $t1, $t9
/* 057230 8029C230 85299E36 */  lh    $t1, %lo(D_80339E36)($t1)
/* 057234 8029C234 8D08FDF0 */  lw    $t0, %lo(gCurrentObject)($t0)
/* 057238 8029C238 AD09011C */  sw    $t1, 0x11c($t0)
/* 05723C 8029C23C 10000001 */  b     .L8029C244
/* 057240 8029C240 00000000 */   nop   
.L8029C244:
/* 057244 8029C244 03E00008 */  jr    $ra
/* 057248 8029C248 27BD0008 */   addiu $sp, $sp, 8

glabel func_8029C24C
/* 05724C 8029C24C 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 057250 8029C250 AFBF0014 */  sw    $ra, 0x14($sp)
/* 057254 8029C254 AFA40020 */  sw    $a0, 0x20($sp)
/* 057258 8029C258 AFA50024 */  sw    $a1, 0x24($sp)
/* 05725C 8029C25C AFA60028 */  sw    $a2, 0x28($sp)
/* 057260 8029C260 3C0E8036 */  lui   $t6, %hi(gCurrentObject) # $t6, 0x8036
/* 057264 8029C264 8DCEFDF0 */  lw    $t6, %lo(gCurrentObject)($t6)
/* 057268 8029C268 8FB80020 */  lw    $t8, 0x20($sp)
/* 05726C 8029C26C 8DCF00E0 */  lw    $t7, 0xe0($t6)
/* 057270 8029C270 01F8C824 */  and   $t9, $t7, $t8
/* 057274 8029C274 17200012 */  bnez  $t9, .L8029C2C0
/* 057278 8029C278 00000000 */   nop   
/* 05727C 8029C27C 3C088036 */  lui   $t0, %hi(gCurrentObject) # $t0, 0x8036
/* 057280 8029C280 8D08FDF0 */  lw    $t0, %lo(gCurrentObject)($t0)
/* 057284 8029C284 8FAA0020 */  lw    $t2, 0x20($sp)
/* 057288 8029C288 8D0900E0 */  lw    $t1, 0xe0($t0)
/* 05728C 8029C28C 012A5825 */  or    $t3, $t1, $t2
/* 057290 8029C290 AD0B00E0 */  sw    $t3, 0xe0($t0)
/* 057294 8029C294 3C048036 */  lui   $a0, %hi(gCurrentObject) # $a0, 0x8036
/* 057298 8029C298 8C84FDF0 */  lw    $a0, %lo(gCurrentObject)($a0)
/* 05729C 8029C29C 00002825 */  move  $a1, $zero
/* 0572A0 8029C2A0 87A60026 */  lh    $a2, 0x26($sp)
/* 0572A4 8029C2A4 0C0A7969 */  jal   func_8029E5A4
/* 0572A8 8029C2A8 8FA70028 */   lw    $a3, 0x28($sp)
/* 0572AC 8029C2AC AFA2001C */  sw    $v0, 0x1c($sp)
/* 0572B0 8029C2B0 3C058036 */  lui   $a1, %hi(gCurrentObject) # $a1, 0x8036
/* 0572B4 8029C2B4 8CA5FDF0 */  lw    $a1, %lo(gCurrentObject)($a1)
/* 0572B8 8029C2B8 0C0A7A59 */  jal   CopyObjParams
/* 0572BC 8029C2BC 8FA4001C */   lw    $a0, 0x1c($sp)
.L8029C2C0:
/* 0572C0 8029C2C0 10000001 */  b     .L8029C2C8
/* 0572C4 8029C2C4 00000000 */   nop   
.L8029C2C8:
/* 0572C8 8029C2C8 8FBF0014 */  lw    $ra, 0x14($sp)
/* 0572CC 8029C2CC 27BD0020 */  addiu $sp, $sp, 0x20
/* 0572D0 8029C2D0 03E00008 */  jr    $ra
/* 0572D4 8029C2D4 00000000 */   nop   

glabel BehMarioLoop2
/* 0572D8 8029C2D8 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 0572DC 8029C2DC AFBF0014 */  sw    $ra, 0x14($sp)
/* 0572E0 8029C2E0 AFA0001C */  sw    $zero, 0x1c($sp)
/* 0572E4 8029C2E4 3C048036 */  lui   $a0, %hi(gCurrentObject) # $a0, 0x8036
/* 0572E8 8029C2E8 0C095181 */  jal   func_80254604
/* 0572EC 8029C2EC 8C84FDF0 */   lw    $a0, %lo(gCurrentObject)($a0)
/* 0572F0 8029C2F0 AFA2001C */  sw    $v0, 0x1c($sp)
/* 0572F4 8029C2F4 3C0F8036 */  lui   $t7, %hi(gCurrentObject) # $t7, 0x8036
/* 0572F8 8029C2F8 8DEFFDF0 */  lw    $t7, %lo(gCurrentObject)($t7)
/* 0572FC 8029C2FC 8FAE001C */  lw    $t6, 0x1c($sp)
/* 057300 8029C300 ADEE00F4 */  sw    $t6, 0xf4($t7)
/* 057304 8029C304 0C0A7000 */  jal   func_8029C000
/* 057308 8029C308 00000000 */   nop   
/* 05730C 8029C30C AFA00018 */  sw    $zero, 0x18($sp)
/* 057310 8029C310 8FB80018 */  lw    $t8, 0x18($sp)
/* 057314 8029C314 3C088033 */  lui   $t0, %hi(D_8032EF6C)
/* 057318 8029C318 0018C900 */  sll   $t9, $t8, 4
/* 05731C 8029C31C 01194021 */  addu  $t0, $t0, $t9
/* 057320 8029C320 8D08EF6C */  lw    $t0, %lo(D_8032EF6C)($t0)
/* 057324 8029C324 1100001D */  beqz  $t0, .L8029C39C
/* 057328 8029C328 00000000 */   nop   
.L8029C32C:
/* 05732C 8029C32C 8FA90018 */  lw    $t1, 0x18($sp)
/* 057330 8029C330 3C0B8033 */  lui   $t3, %hi(D_8032EF6C)
/* 057334 8029C334 8FAC001C */  lw    $t4, 0x1c($sp)
/* 057338 8029C338 00095100 */  sll   $t2, $t1, 4
/* 05733C 8029C33C 016A5821 */  addu  $t3, $t3, $t2
/* 057340 8029C340 8D6BEF6C */  lw    $t3, %lo(D_8032EF6C)($t3)
/* 057344 8029C344 016C6824 */  and   $t5, $t3, $t4
/* 057348 8029C348 11A0000A */  beqz  $t5, .L8029C374
/* 05734C 8029C34C 00000000 */   nop   
/* 057350 8029C350 8FAE0018 */  lw    $t6, 0x18($sp)
/* 057354 8029C354 3C188033 */  lui   $t8, %hi(D_8032EF6C) # $t8, 0x8033
/* 057358 8029C358 2718EF6C */  addiu $t8, %lo(D_8032EF6C) # addiu $t8, $t8, -0x1094
/* 05735C 8029C35C 000E7900 */  sll   $t7, $t6, 4
/* 057360 8029C360 01F8C821 */  addu  $t9, $t7, $t8
/* 057364 8029C364 8F240004 */  lw    $a0, 4($t9)
/* 057368 8029C368 93250008 */  lbu   $a1, 8($t9)
/* 05736C 8029C36C 0C0A7093 */  jal   func_8029C24C
/* 057370 8029C370 8F26000C */   lw    $a2, 0xc($t9)
.L8029C374:
/* 057374 8029C374 8FA80018 */  lw    $t0, 0x18($sp)
/* 057378 8029C378 25090001 */  addiu $t1, $t0, 1
/* 05737C 8029C37C AFA90018 */  sw    $t1, 0x18($sp)
/* 057380 8029C380 8FAA0018 */  lw    $t2, 0x18($sp)
/* 057384 8029C384 3C0C8033 */  lui   $t4, %hi(D_8032EF6C)
/* 057388 8029C388 000A5900 */  sll   $t3, $t2, 4
/* 05738C 8029C38C 018B6021 */  addu  $t4, $t4, $t3
/* 057390 8029C390 8D8CEF6C */  lw    $t4, %lo(D_8032EF6C)($t4)
/* 057394 8029C394 1580FFE5 */  bnez  $t4, .L8029C32C
/* 057398 8029C398 00000000 */   nop   
.L8029C39C:
/* 05739C 8029C39C 10000001 */  b     .L8029C3A4
/* 0573A0 8029C3A0 00000000 */   nop   
.L8029C3A4:
/* 0573A4 8029C3A4 8FBF0014 */  lw    $ra, 0x14($sp)
/* 0573A8 8029C3A8 27BD0020 */  addiu $sp, $sp, 0x20
/* 0573AC 8029C3AC 03E00008 */  jr    $ra
/* 0573B0 8029C3B0 00000000 */   nop   

glabel func_8029C3B4
/* 0573B4 8029C3B4 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 0573B8 8029C3B8 AFBF0014 */  sw    $ra, 0x14($sp)
/* 0573BC 8029C3BC AFA40020 */  sw    $a0, 0x20($sp)
/* 0573C0 8029C3C0 AFA50024 */  sw    $a1, 0x24($sp)
/* 0573C4 8029C3C4 AFA0001C */  sw    $zero, 0x1c($sp)
/* 0573C8 8029C3C8 8FAE0020 */  lw    $t6, 0x20($sp)
/* 0573CC 8029C3CC 8FAF0024 */  lw    $t7, 0x24($sp)
/* 0573D0 8029C3D0 11CF0015 */  beq   $t6, $t7, .L8029C428
/* 0573D4 8029C3D4 00000000 */   nop   
.L8029C3D8:
/* 0573D8 8029C3D8 8FB80024 */  lw    $t8, 0x24($sp)
/* 0573DC 8029C3DC 3C018036 */  lui   $at, %hi(gCurrentObject) # $at, 0x8036
/* 0573E0 8029C3E0 AC38FDF0 */  sw    $t8, %lo(gCurrentObject)($at)
/* 0573E4 8029C3E4 3C198036 */  lui   $t9, %hi(gCurrentObject) # $t9, 0x8036
/* 0573E8 8029C3E8 8F39FDF0 */  lw    $t9, %lo(gCurrentObject)($t9)
/* 0573EC 8029C3EC 87280002 */  lh    $t0, 2($t9)
/* 0573F0 8029C3F0 35090020 */  ori   $t1, $t0, 0x20
/* 0573F4 8029C3F4 A7290002 */  sh    $t1, 2($t9)
/* 0573F8 8029C3F8 0C0E1700 */  jal   cur_object_exec_behavior
/* 0573FC 8029C3FC 00000000 */   nop   
/* 057400 8029C400 8FAA0024 */  lw    $t2, 0x24($sp)
/* 057404 8029C404 8D4B0060 */  lw    $t3, 0x60($t2)
/* 057408 8029C408 AFAB0024 */  sw    $t3, 0x24($sp)
/* 05740C 8029C40C 8FAC001C */  lw    $t4, 0x1c($sp)
/* 057410 8029C410 258D0001 */  addiu $t5, $t4, 1
/* 057414 8029C414 AFAD001C */  sw    $t5, 0x1c($sp)
/* 057418 8029C418 8FAE0020 */  lw    $t6, 0x20($sp)
/* 05741C 8029C41C 8FAF0024 */  lw    $t7, 0x24($sp)
/* 057420 8029C420 15CFFFED */  bne   $t6, $t7, .L8029C3D8
/* 057424 8029C424 00000000 */   nop   
.L8029C428:
/* 057428 8029C428 10000003 */  b     .L8029C438
/* 05742C 8029C42C 8FA2001C */   lw    $v0, 0x1c($sp)
/* 057430 8029C430 10000001 */  b     .L8029C438
/* 057434 8029C434 00000000 */   nop   
.L8029C438:
/* 057438 8029C438 8FBF0014 */  lw    $ra, 0x14($sp)
/* 05743C 8029C43C 27BD0020 */  addiu $sp, $sp, 0x20
/* 057440 8029C440 03E00008 */  jr    $ra
/* 057444 8029C444 00000000 */   nop   

glabel func_8029C448
/* 057448 8029C448 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 05744C 8029C44C AFBF0014 */  sw    $ra, 0x14($sp)
/* 057450 8029C450 AFA40020 */  sw    $a0, 0x20($sp)
/* 057454 8029C454 AFA50024 */  sw    $a1, 0x24($sp)
/* 057458 8029C458 AFA0001C */  sw    $zero, 0x1c($sp)
/* 05745C 8029C45C 8FAE0020 */  lw    $t6, 0x20($sp)
/* 057460 8029C460 8FAF0024 */  lw    $t7, 0x24($sp)
/* 057464 8029C464 11CF0048 */  beq   $t6, $t7, .L8029C588
/* 057468 8029C468 00000000 */   nop   
.L8029C46C:
/* 05746C 8029C46C 8FB80024 */  lw    $t8, 0x24($sp)
/* 057470 8029C470 3C018036 */  lui   $at, %hi(gCurrentObject) # $at, 0x8036
/* 057474 8029C474 AC38FDF0 */  sw    $t8, %lo(gCurrentObject)($at)
/* 057478 8029C478 AFA00018 */  sw    $zero, 0x18($sp)
/* 05747C 8029C47C 3C198034 */  lui   $t9, %hi(D_8033C110) # $t9, 0x8034
/* 057480 8029C480 8F39C110 */  lw    $t9, %lo(D_8033C110)($t9)
/* 057484 8029C484 33280010 */  andi  $t0, $t9, 0x10
/* 057488 8029C488 15000023 */  bnez  $t0, .L8029C518
/* 05748C 8029C48C 00000000 */   nop   
/* 057490 8029C490 3C098036 */  lui   $t1, %hi(gCurrentObject) # $t1, 0x8036
/* 057494 8029C494 3C0A8036 */  lui   $t2, %hi(gMarioObject) # $t2, 0x8036
/* 057498 8029C498 8D4AFDE8 */  lw    $t2, %lo(gMarioObject)($t2)
/* 05749C 8029C49C 8D29FDF0 */  lw    $t1, %lo(gCurrentObject)($t1)
/* 0574A0 8029C4A0 152A0008 */  bne   $t1, $t2, .L8029C4C4
/* 0574A4 8029C4A4 00000000 */   nop   
/* 0574A8 8029C4A8 3C0B8034 */  lui   $t3, %hi(D_8033C110) # $t3, 0x8034
/* 0574AC 8029C4AC 8D6BC110 */  lw    $t3, %lo(D_8033C110)($t3)
/* 0574B0 8029C4B0 316C0008 */  andi  $t4, $t3, 8
/* 0574B4 8029C4B4 15800003 */  bnez  $t4, .L8029C4C4
/* 0574B8 8029C4B8 00000000 */   nop   
/* 0574BC 8029C4BC 240D0001 */  li    $t5, 1
/* 0574C0 8029C4C0 AFAD0018 */  sw    $t5, 0x18($sp)
.L8029C4C4:
/* 0574C4 8029C4C4 3C0E8036 */  lui   $t6, %hi(gCurrentObject) # $t6, 0x8036
/* 0574C8 8029C4C8 8DCEFDF0 */  lw    $t6, %lo(gCurrentObject)($t6)
/* 0574CC 8029C4CC 8DCF0130 */  lw    $t7, 0x130($t6)
/* 0574D0 8029C4D0 31F80804 */  andi  $t8, $t7, 0x804
/* 0574D4 8029C4D4 13000008 */  beqz  $t8, .L8029C4F8
/* 0574D8 8029C4D8 00000000 */   nop   
/* 0574DC 8029C4DC 3C198034 */  lui   $t9, %hi(D_8033C110) # $t9, 0x8034
/* 0574E0 8029C4E0 8F39C110 */  lw    $t9, %lo(D_8033C110)($t9)
/* 0574E4 8029C4E4 33280008 */  andi  $t0, $t9, 8
/* 0574E8 8029C4E8 15000003 */  bnez  $t0, .L8029C4F8
/* 0574EC 8029C4EC 00000000 */   nop   
/* 0574F0 8029C4F0 24090001 */  li    $t1, 1
/* 0574F4 8029C4F4 AFA90018 */  sw    $t1, 0x18($sp)
.L8029C4F8:
/* 0574F8 8029C4F8 3C0A8036 */  lui   $t2, %hi(gCurrentObject) # $t2, 0x8036
/* 0574FC 8029C4FC 8D4AFDF0 */  lw    $t2, %lo(gCurrentObject)($t2)
/* 057500 8029C500 854B0074 */  lh    $t3, 0x74($t2)
/* 057504 8029C504 316C0030 */  andi  $t4, $t3, 0x30
/* 057508 8029C508 11800003 */  beqz  $t4, .L8029C518
/* 05750C 8029C50C 00000000 */   nop   
/* 057510 8029C510 240D0001 */  li    $t5, 1
/* 057514 8029C514 AFAD0018 */  sw    $t5, 0x18($sp)
.L8029C518:
/* 057518 8029C518 8FAE0018 */  lw    $t6, 0x18($sp)
/* 05751C 8029C51C 11C0000A */  beqz  $t6, .L8029C548
/* 057520 8029C520 00000000 */   nop   
/* 057524 8029C524 3C0F8036 */  lui   $t7, %hi(gCurrentObject) # $t7, 0x8036
/* 057528 8029C528 8DEFFDF0 */  lw    $t7, %lo(gCurrentObject)($t7)
/* 05752C 8029C52C 85F80002 */  lh    $t8, 2($t7)
/* 057530 8029C530 37190020 */  ori   $t9, $t8, 0x20
/* 057534 8029C534 A5F90002 */  sh    $t9, 2($t7)
/* 057538 8029C538 0C0E1700 */  jal   cur_object_exec_behavior
/* 05753C 8029C53C 00000000 */   nop   
/* 057540 8029C540 10000007 */  b     .L8029C560
/* 057544 8029C544 00000000 */   nop   
.L8029C548:
/* 057548 8029C548 3C088036 */  lui   $t0, %hi(gCurrentObject) # $t0, 0x8036
/* 05754C 8029C54C 8D08FDF0 */  lw    $t0, %lo(gCurrentObject)($t0)
/* 057550 8029C550 2401FFDF */  li    $at, -33
/* 057554 8029C554 85090002 */  lh    $t1, 2($t0)
/* 057558 8029C558 01215024 */  and   $t2, $t1, $at
/* 05755C 8029C55C A50A0002 */  sh    $t2, 2($t0)
.L8029C560:
/* 057560 8029C560 8FAB0024 */  lw    $t3, 0x24($sp)
/* 057564 8029C564 8D6C0060 */  lw    $t4, 0x60($t3)
/* 057568 8029C568 AFAC0024 */  sw    $t4, 0x24($sp)
/* 05756C 8029C56C 8FAD001C */  lw    $t5, 0x1c($sp)
/* 057570 8029C570 25AE0001 */  addiu $t6, $t5, 1
/* 057574 8029C574 AFAE001C */  sw    $t6, 0x1c($sp)
/* 057578 8029C578 8FB80020 */  lw    $t8, 0x20($sp)
/* 05757C 8029C57C 8FB90024 */  lw    $t9, 0x24($sp)
/* 057580 8029C580 1719FFBA */  bne   $t8, $t9, .L8029C46C
/* 057584 8029C584 00000000 */   nop   
.L8029C588:
/* 057588 8029C588 10000003 */  b     .L8029C598
/* 05758C 8029C58C 8FA2001C */   lw    $v0, 0x1c($sp)
/* 057590 8029C590 10000001 */  b     .L8029C598
/* 057594 8029C594 00000000 */   nop   
.L8029C598:
/* 057598 8029C598 8FBF0014 */  lw    $ra, 0x14($sp)
/* 05759C 8029C59C 27BD0020 */  addiu $sp, $sp, 0x20
/* 0575A0 8029C5A0 03E00008 */  jr    $ra
/* 0575A4 8029C5A4 00000000 */   nop   

glabel func_8029C5A8
/* 0575A8 8029C5A8 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 0575AC 8029C5AC AFBF0014 */  sw    $ra, 0x14($sp)
/* 0575B0 8029C5B0 AFA40020 */  sw    $a0, 0x20($sp)
/* 0575B4 8029C5B4 8FAE0020 */  lw    $t6, 0x20($sp)
/* 0575B8 8029C5B8 8DCF0060 */  lw    $t7, 0x60($t6)
/* 0575BC 8029C5BC AFAF0018 */  sw    $t7, 0x18($sp)
/* 0575C0 8029C5C0 3C188034 */  lui   $t8, %hi(D_8033C110) # $t8, 0x8034
/* 0575C4 8029C5C4 8F18C110 */  lw    $t8, %lo(D_8033C110)($t8)
/* 0575C8 8029C5C8 33190040 */  andi  $t9, $t8, 0x40
/* 0575CC 8029C5CC 17200006 */  bnez  $t9, .L8029C5E8
/* 0575D0 8029C5D0 00000000 */   nop   
/* 0575D4 8029C5D4 8FA40020 */  lw    $a0, 0x20($sp)
/* 0575D8 8029C5D8 0C0A70ED */  jal   func_8029C3B4
/* 0575DC 8029C5DC 8FA50018 */   lw    $a1, 0x18($sp)
/* 0575E0 8029C5E0 10000005 */  b     .L8029C5F8
/* 0575E4 8029C5E4 AFA2001C */   sw    $v0, 0x1c($sp)
.L8029C5E8:
/* 0575E8 8029C5E8 8FA40020 */  lw    $a0, 0x20($sp)
/* 0575EC 8029C5EC 0C0A7112 */  jal   func_8029C448
/* 0575F0 8029C5F0 8FA50018 */   lw    $a1, 0x18($sp)
/* 0575F4 8029C5F4 AFA2001C */  sw    $v0, 0x1c($sp)
.L8029C5F8:
/* 0575F8 8029C5F8 10000003 */  b     .L8029C608
/* 0575FC 8029C5FC 8FA2001C */   lw    $v0, 0x1c($sp)
/* 057600 8029C600 10000001 */  b     .L8029C608
/* 057604 8029C604 00000000 */   nop   
.L8029C608:
/* 057608 8029C608 8FBF0014 */  lw    $ra, 0x14($sp)
/* 05760C 8029C60C 27BD0020 */  addiu $sp, $sp, 0x20
/* 057610 8029C610 03E00008 */  jr    $ra
/* 057614 8029C614 00000000 */   nop   

glabel func_8029C618
/* 057618 8029C618 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 05761C 8029C61C AFBF0014 */  sw    $ra, 0x14($sp)
/* 057620 8029C620 AFA40020 */  sw    $a0, 0x20($sp)
/* 057624 8029C624 8FAE0020 */  lw    $t6, 0x20($sp)
/* 057628 8029C628 8DCF0060 */  lw    $t7, 0x60($t6)
/* 05762C 8029C62C AFAF001C */  sw    $t7, 0x1c($sp)
/* 057630 8029C630 8FB80020 */  lw    $t8, 0x20($sp)
/* 057634 8029C634 8FB9001C */  lw    $t9, 0x1c($sp)
/* 057638 8029C638 1319001F */  beq   $t8, $t9, .L8029C6B8
/* 05763C 8029C63C 00000000 */   nop   
.L8029C640:
/* 057640 8029C640 8FA8001C */  lw    $t0, 0x1c($sp)
/* 057644 8029C644 3C018036 */  lui   $at, %hi(gCurrentObject) # $at, 0x8036
/* 057648 8029C648 AC28FDF0 */  sw    $t0, %lo(gCurrentObject)($at)
/* 05764C 8029C64C 8FA9001C */  lw    $t1, 0x1c($sp)
/* 057650 8029C650 8D2A0060 */  lw    $t2, 0x60($t1)
/* 057654 8029C654 AFAA001C */  sw    $t2, 0x1c($sp)
/* 057658 8029C658 3C0B8036 */  lui   $t3, %hi(gCurrentObject) # $t3, 0x8036
/* 05765C 8029C65C 8D6BFDF0 */  lw    $t3, %lo(gCurrentObject)($t3)
/* 057660 8029C660 24010001 */  li    $at, 1
/* 057664 8029C664 856C0074 */  lh    $t4, 0x74($t3)
/* 057668 8029C668 318D0001 */  andi  $t5, $t4, 1
/* 05766C 8029C66C 11A1000E */  beq   $t5, $at, .L8029C6A8
/* 057670 8029C670 00000000 */   nop   
/* 057674 8029C674 3C0E8036 */  lui   $t6, %hi(gCurrentObject) # $t6, 0x8036
/* 057678 8029C678 8DCEFDF0 */  lw    $t6, %lo(gCurrentObject)($t6)
/* 05767C 8029C67C 8DCF008C */  lw    $t7, 0x8c($t6)
/* 057680 8029C680 31F84000 */  andi  $t8, $t7, 0x4000
/* 057684 8029C684 17000005 */  bnez  $t8, .L8029C69C
/* 057688 8029C688 00000000 */   nop   
/* 05768C 8029C68C 3C048036 */  lui   $a0, %hi(gCurrentObject) # $a0, 0x8036
/* 057690 8029C690 8C84FDF0 */  lw    $a0, %lo(gCurrentObject)($a0)
/* 057694 8029C694 0C0A71B6 */  jal   func_8029C6D8
/* 057698 8029C698 240500FF */   li    $a1, 255
.L8029C69C:
/* 05769C 8029C69C 3C048036 */  lui   $a0, %hi(gCurrentObject) # $a0, 0x8036
/* 0576A0 8029C6A0 0C0B2422 */  jal   func_802C9088
/* 0576A4 8029C6A4 8C84FDF0 */   lw    $a0, %lo(gCurrentObject)($a0)
.L8029C6A8:
/* 0576A8 8029C6A8 8FB90020 */  lw    $t9, 0x20($sp)
/* 0576AC 8029C6AC 8FA8001C */  lw    $t0, 0x1c($sp)
/* 0576B0 8029C6B0 1728FFE3 */  bne   $t9, $t0, .L8029C640
/* 0576B4 8029C6B4 00000000 */   nop   
.L8029C6B8:
/* 0576B8 8029C6B8 10000003 */  b     .L8029C6C8
/* 0576BC 8029C6BC 00001025 */   move  $v0, $zero
/* 0576C0 8029C6C0 10000001 */  b     .L8029C6C8
/* 0576C4 8029C6C4 00000000 */   nop   
.L8029C6C8:
/* 0576C8 8029C6C8 8FBF0014 */  lw    $ra, 0x14($sp)
/* 0576CC 8029C6CC 27BD0020 */  addiu $sp, $sp, 0x20
/* 0576D0 8029C6D0 03E00008 */  jr    $ra
/* 0576D4 8029C6D4 00000000 */   nop   

glabel func_8029C6D8
/* 0576D8 8029C6D8 27BDFFF0 */  addiu $sp, $sp, -0x10
/* 0576DC 8029C6DC 30A500FF */  andi  $a1, $a1, 0xff
/* 0576E0 8029C6E0 848601F6 */  lh    $a2, 0x1f6($a0)
/* 0576E4 8029C6E4 24010001 */  li    $at, 1
/* 0576E8 8029C6E8 10C10006 */  beq   $a2, $at, .L8029C704
/* 0576EC 8029C6EC 00000000 */   nop   
/* 0576F0 8029C6F0 24010002 */  li    $at, 2
/* 0576F4 8029C6F4 10C1000C */  beq   $a2, $at, .L8029C728
/* 0576F8 8029C6F8 00000000 */   nop   
/* 0576FC 8029C6FC 10000013 */  b     .L8029C74C
/* 057700 8029C700 00000000 */   nop   
.L8029C704:
/* 057704 8029C704 8C8E025C */  lw    $t6, 0x25c($a0)
/* 057708 8029C708 AFAE000C */  sw    $t6, 0xc($sp)
/* 05770C 8029C70C 8FAF000C */  lw    $t7, 0xc($sp)
/* 057710 8029C710 0005CA00 */  sll   $t9, $a1, 8
/* 057714 8029C714 8DF80000 */  lw    $t8, ($t7)
/* 057718 8029C718 03194025 */  or    $t0, $t8, $t9
/* 05771C 8029C71C ADE80000 */  sw    $t0, ($t7)
/* 057720 8029C720 1000000A */  b     .L8029C74C
/* 057724 8029C724 00000000 */   nop   
.L8029C728:
/* 057728 8029C728 8C89025C */  lw    $t1, 0x25c($a0)
/* 05772C 8029C72C AFA90008 */  sw    $t1, 8($sp)
/* 057730 8029C730 8FAA0008 */  lw    $t2, 8($sp)
/* 057734 8029C734 00056200 */  sll   $t4, $a1, 8
/* 057738 8029C738 954B0000 */  lhu   $t3, ($t2)
/* 05773C 8029C73C 016C6825 */  or    $t5, $t3, $t4
/* 057740 8029C740 A54D0000 */  sh    $t5, ($t2)
/* 057744 8029C744 10000001 */  b     .L8029C74C
/* 057748 8029C748 00000000 */   nop   
.L8029C74C:
/* 05774C 8029C74C 10000001 */  b     .L8029C754
/* 057750 8029C750 00000000 */   nop   
.L8029C754:
/* 057754 8029C754 03E00008 */  jr    $ra
/* 057758 8029C758 27BD0010 */   addiu $sp, $sp, 0x10

glabel func_8029C75C
/* 05775C 8029C75C 27BDFFD8 */  addiu $sp, $sp, -0x28
/* 057760 8029C760 AFBF0014 */  sw    $ra, 0x14($sp)
/* 057764 8029C764 AFA40028 */  sw    $a0, 0x28($sp)
/* 057768 8029C768 AFA5002C */  sw    $a1, 0x2c($sp)
/* 05776C 8029C76C 3C0E8034 */  lui   $t6, %hi(D_8033B870) # $t6, 0x8034
/* 057770 8029C770 25CEB870 */  addiu $t6, %lo(D_8033B870) # addiu $t6, $t6, -0x4790
/* 057774 8029C774 3C018036 */  lui   $at, %hi(D_8035FD78) # $at, 0x8036
/* 057778 8029C778 AC2EFD78 */  sw    $t6, %lo(D_8035FD78)($at)
/* 05777C 8029C77C AFA00018 */  sw    $zero, 0x18($sp)
.L8029C780:
/* 057780 8029C780 8FAF0018 */  lw    $t7, 0x18($sp)
/* 057784 8029C784 3C198036 */  lui   $t9, %hi(D_8035FD78) # $t9, 0x8036
/* 057788 8029C788 8F39FD78 */  lw    $t9, %lo(D_8035FD78)($t9)
/* 05778C 8029C78C 000FC080 */  sll   $t8, $t7, 2
/* 057790 8029C790 030FC023 */  subu  $t8, $t8, $t7
/* 057794 8029C794 0018C080 */  sll   $t8, $t8, 2
/* 057798 8029C798 030FC021 */  addu  $t8, $t8, $t7
/* 05779C 8029C79C 0018C0C0 */  sll   $t8, $t8, 3
/* 0577A0 8029C7A0 03194021 */  addu  $t0, $t8, $t9
/* 0577A4 8029C7A4 AFA8001C */  sw    $t0, 0x1c($sp)
/* 0577A8 8029C7A8 8FA9001C */  lw    $t1, 0x1c($sp)
/* 0577AC 8029C7AC 8D2A0060 */  lw    $t2, 0x60($t1)
/* 0577B0 8029C7B0 AFAA0020 */  sw    $t2, 0x20($sp)
/* 0577B4 8029C7B4 8FAB0020 */  lw    $t3, 0x20($sp)
/* 0577B8 8029C7B8 8FAC001C */  lw    $t4, 0x1c($sp)
/* 0577BC 8029C7BC 116C0011 */  beq   $t3, $t4, .L8029C804
/* 0577C0 8029C7C0 00000000 */   nop   
.L8029C7C4:
/* 0577C4 8029C7C4 8FAD0020 */  lw    $t5, 0x20($sp)
/* 0577C8 8029C7C8 AFAD0024 */  sw    $t5, 0x24($sp)
/* 0577CC 8029C7CC 8FAE0020 */  lw    $t6, 0x20($sp)
/* 0577D0 8029C7D0 8DCF0060 */  lw    $t7, 0x60($t6)
/* 0577D4 8029C7D4 AFAF0020 */  sw    $t7, 0x20($sp)
/* 0577D8 8029C7D8 8FB80024 */  lw    $t8, 0x24($sp)
/* 0577DC 8029C7DC 8FA8002C */  lw    $t0, 0x2c($sp)
/* 0577E0 8029C7E0 83190019 */  lb    $t9, 0x19($t8)
/* 0577E4 8029C7E4 17280003 */  bne   $t9, $t0, .L8029C7F4
/* 0577E8 8029C7E8 00000000 */   nop   
/* 0577EC 8029C7EC 0C0B2422 */  jal   func_802C9088
/* 0577F0 8029C7F0 8FA40024 */   lw    $a0, 0x24($sp)
.L8029C7F4:
/* 0577F4 8029C7F4 8FA90020 */  lw    $t1, 0x20($sp)
/* 0577F8 8029C7F8 8FAA001C */  lw    $t2, 0x1c($sp)
/* 0577FC 8029C7FC 152AFFF1 */  bne   $t1, $t2, .L8029C7C4
/* 057800 8029C800 00000000 */   nop   
.L8029C804:
/* 057804 8029C804 8FAB0018 */  lw    $t3, 0x18($sp)
/* 057808 8029C808 256C0001 */  addiu $t4, $t3, 1
/* 05780C 8029C80C 2981000D */  slti  $at, $t4, 0xd
/* 057810 8029C810 1420FFDB */  bnez  $at, .L8029C780
/* 057814 8029C814 AFAC0018 */   sw    $t4, 0x18($sp)
/* 057818 8029C818 10000001 */  b     .L8029C820
/* 05781C 8029C81C 00000000 */   nop   
.L8029C820:
/* 057820 8029C820 8FBF0014 */  lw    $ra, 0x14($sp)
/* 057824 8029C824 27BD0028 */  addiu $sp, $sp, 0x28
/* 057828 8029C828 03E00008 */  jr    $ra
/* 05782C 8029C82C 00000000 */   nop   

glabel func_8029C830
/* 057830 8029C830 27BDFFD8 */  addiu $sp, $sp, -0x28
/* 057834 8029C834 AFBF0014 */  sw    $ra, 0x14($sp)
/* 057838 8029C838 AFA40028 */  sw    $a0, 0x28($sp)
/* 05783C 8029C83C AFA5002C */  sw    $a1, 0x2c($sp)
/* 057840 8029C840 3C0E8034 */  lui   $t6, %hi(D_8033B870) # $t6, 0x8034
/* 057844 8029C844 25CEB870 */  addiu $t6, %lo(D_8033B870) # addiu $t6, $t6, -0x4790
/* 057848 8029C848 3C018036 */  lui   $at, %hi(D_8035FD78) # $at, 0x8036
/* 05784C 8029C84C AC2EFD78 */  sw    $t6, %lo(D_8035FD78)($at)
/* 057850 8029C850 3C018034 */  lui   $at, %hi(D_8033C110) # $at, 0x8034
/* 057854 8029C854 AC20C110 */  sw    $zero, %lo(D_8033C110)($at)
/* 057858 8029C858 3C018036 */  lui   $at, %hi(D_8035FEF2) # $at, 0x8036
/* 05785C 8029C85C A420FEF2 */  sh    $zero, %lo(D_8035FEF2)($at)
/* 057860 8029C860 3C018036 */  lui   $at, %hi(D_8035FEF4) # $at, 0x8036
/* 057864 8029C864 A420FEF4 */  sh    $zero, %lo(D_8035FEF4)($at)
/* 057868 8029C868 3C0F8034 */  lui   $t7, %hi(D_8033A75A) # $t7, 0x8034
/* 05786C 8029C86C 85EFA75A */  lh    $t7, %lo(D_8033A75A)($t7)
/* 057870 8029C870 24010002 */  li    $at, 2
/* 057874 8029C874 15E10006 */  bne   $t7, $at, .L8029C890
/* 057878 8029C878 00000000 */   nop   
/* 05787C 8029C87C 3C188036 */  lui   $t8, %hi(D_8035FEEC) # $t8, 0x8036
/* 057880 8029C880 8718FEEC */  lh    $t8, %lo(D_8035FEEC)($t8)
/* 057884 8029C884 3C018036 */  lui   $at, %hi(D_8035FEEC) # $at, 0x8036
/* 057888 8029C888 37190001 */  ori   $t9, $t8, 1
/* 05788C 8029C88C A439FEEC */  sh    $t9, %lo(D_8035FEEC)($at)
.L8029C890:
/* 057890 8029C890 8FA8002C */  lw    $t0, 0x2c($sp)
/* 057894 8029C894 11000068 */  beqz  $t0, .L8029CA38
/* 057898 8029C898 00000000 */   nop   
.L8029C89C:
/* 05789C 8029C89C 8FA9002C */  lw    $t1, 0x2c($sp)
/* 0578A0 8029C8A0 8D2A0010 */  lw    $t2, 0x10($t1)
/* 0578A4 8029C8A4 314BFFFF */  andi  $t3, $t2, 0xffff
/* 0578A8 8029C8A8 A7AB001A */  sh    $t3, 0x1a($sp)
/* 0578AC 8029C8AC 8FAC002C */  lw    $t4, 0x2c($sp)
/* 0578B0 8029C8B0 0C09DE68 */  jal   segmented_to_virtual
/* 0578B4 8029C8B4 8D840014 */   lw    $a0, 0x14($t4)
/* 0578B8 8029C8B8 AFA2001C */  sw    $v0, 0x1c($sp)
/* 0578BC 8029C8BC 8FAD002C */  lw    $t5, 0x2c($sp)
/* 0578C0 8029C8C0 3401FF00 */  li    $at, 65280
/* 0578C4 8029C8C4 8DAE0010 */  lw    $t6, 0x10($t5)
/* 0578C8 8029C8C8 31CFFF00 */  andi  $t7, $t6, 0xff00
/* 0578CC 8029C8CC 11E10054 */  beq   $t7, $at, .L8029CA20
/* 0578D0 8029C8D0 00000000 */   nop   
/* 0578D4 8029C8D4 0C0B2509 */  jal   func_802C9424
/* 0578D8 8029C8D8 8FA4001C */   lw    $a0, 0x1c($sp)
/* 0578DC 8029C8DC AFA20024 */  sw    $v0, 0x24($sp)
/* 0578E0 8029C8E0 8FB8002C */  lw    $t8, 0x2c($sp)
/* 0578E4 8029C8E4 8FA80024 */  lw    $t0, 0x24($sp)
/* 0578E8 8029C8E8 8F190010 */  lw    $t9, 0x10($t8)
/* 0578EC 8029C8EC AD190188 */  sw    $t9, 0x188($t0)
/* 0578F0 8029C8F0 8FA9002C */  lw    $t1, 0x2c($sp)
/* 0578F4 8029C8F4 8FAD0024 */  lw    $t5, 0x24($sp)
/* 0578F8 8029C8F8 8D2A0010 */  lw    $t2, 0x10($t1)
/* 0578FC 8029C8FC 000A5C02 */  srl   $t3, $t2, 0x10
/* 057900 8029C900 316C00FF */  andi  $t4, $t3, 0xff
/* 057904 8029C904 ADAC0144 */  sw    $t4, 0x144($t5)
/* 057908 8029C908 8FAE001C */  lw    $t6, 0x1c($sp)
/* 05790C 8029C90C 8FAF0024 */  lw    $t7, 0x24($sp)
/* 057910 8029C910 ADEE020C */  sw    $t6, 0x20c($t7)
/* 057914 8029C914 8FB80024 */  lw    $t8, 0x24($sp)
/* 057918 8029C918 AF0001C8 */  sw    $zero, 0x1c8($t8)
/* 05791C 8029C91C 8FA80024 */  lw    $t0, 0x24($sp)
/* 057920 8029C920 24190001 */  li    $t9, 1
/* 057924 8029C924 A51901F6 */  sh    $t9, 0x1f6($t0)
/* 057928 8029C928 8FA9002C */  lw    $t1, 0x2c($sp)
/* 05792C 8029C92C 8FAB0024 */  lw    $t3, 0x24($sp)
/* 057930 8029C930 252A0010 */  addiu $t2, $t1, 0x10
/* 057934 8029C934 AD6A025C */  sw    $t2, 0x25c($t3)
/* 057938 8029C938 8FAC002C */  lw    $t4, 0x2c($sp)
/* 05793C 8029C93C 8D8D0010 */  lw    $t5, 0x10($t4)
/* 057940 8029C940 31AE0001 */  andi  $t6, $t5, 1
/* 057944 8029C944 11C00006 */  beqz  $t6, .L8029C960
/* 057948 8029C948 00000000 */   nop   
/* 05794C 8029C94C 8FAF0024 */  lw    $t7, 0x24($sp)
/* 057950 8029C950 3C018036 */  lui   $at, %hi(gMarioObject) # $at, 0x8036
/* 057954 8029C954 AC2FFDE8 */  sw    $t7, %lo(gMarioObject)($at)
/* 057958 8029C958 0C0DF04E */  jal   func_8037C138
/* 05795C 8029C95C 8FA40024 */   lw    $a0, 0x24($sp)
.L8029C960:
/* 057960 8029C960 8FA40024 */  lw    $a0, 0x24($sp)
/* 057964 8029C964 0C0DF147 */  jal   func_8037C51C
/* 057968 8029C968 8FA5002C */   lw    $a1, 0x2c($sp)
/* 05796C 8029C96C 8FB8002C */  lw    $t8, 0x2c($sp)
/* 057970 8029C970 8FA80024 */  lw    $t0, 0x24($sp)
/* 057974 8029C974 87190000 */  lh    $t9, ($t8)
/* 057978 8029C978 44992000 */  mtc1  $t9, $f4
/* 05797C 8029C97C 00000000 */  nop   
/* 057980 8029C980 468021A0 */  cvt.s.w $f6, $f4
/* 057984 8029C984 E50600A0 */  swc1  $f6, 0xa0($t0)
/* 057988 8029C988 8FA9002C */  lw    $t1, 0x2c($sp)
/* 05798C 8029C98C 8FAB0024 */  lw    $t3, 0x24($sp)
/* 057990 8029C990 852A0002 */  lh    $t2, 2($t1)
/* 057994 8029C994 448A4000 */  mtc1  $t2, $f8
/* 057998 8029C998 00000000 */  nop   
/* 05799C 8029C99C 468042A0 */  cvt.s.w $f10, $f8
/* 0579A0 8029C9A0 E56A00A4 */  swc1  $f10, 0xa4($t3)
/* 0579A4 8029C9A4 8FAC002C */  lw    $t4, 0x2c($sp)
/* 0579A8 8029C9A8 8FAE0024 */  lw    $t6, 0x24($sp)
/* 0579AC 8029C9AC 858D0004 */  lh    $t5, 4($t4)
/* 0579B0 8029C9B0 448D8000 */  mtc1  $t5, $f16
/* 0579B4 8029C9B4 00000000 */  nop   
/* 0579B8 8029C9B8 468084A0 */  cvt.s.w $f18, $f16
/* 0579BC 8029C9BC E5D200A8 */  swc1  $f18, 0xa8($t6)
/* 0579C0 8029C9C0 8FAF002C */  lw    $t7, 0x2c($sp)
/* 0579C4 8029C9C4 8FB90024 */  lw    $t9, 0x24($sp)
/* 0579C8 8029C9C8 85F80006 */  lh    $t8, 6($t7)
/* 0579CC 8029C9CC AF3800D0 */  sw    $t8, 0xd0($t9)
/* 0579D0 8029C9D0 8FA8002C */  lw    $t0, 0x2c($sp)
/* 0579D4 8029C9D4 8FAA0024 */  lw    $t2, 0x24($sp)
/* 0579D8 8029C9D8 85090008 */  lh    $t1, 8($t0)
/* 0579DC 8029C9DC AD4900D4 */  sw    $t1, 0xd4($t2)
/* 0579E0 8029C9E0 8FAB002C */  lw    $t3, 0x2c($sp)
/* 0579E4 8029C9E4 8FAD0024 */  lw    $t5, 0x24($sp)
/* 0579E8 8029C9E8 856C000A */  lh    $t4, 0xa($t3)
/* 0579EC 8029C9EC ADAC00D8 */  sw    $t4, 0xd8($t5)
/* 0579F0 8029C9F0 8FAE002C */  lw    $t6, 0x2c($sp)
/* 0579F4 8029C9F4 8FB80024 */  lw    $t8, 0x24($sp)
/* 0579F8 8029C9F8 85CF0006 */  lh    $t7, 6($t6)
/* 0579FC 8029C9FC AF0F00C4 */  sw    $t7, 0xc4($t8)
/* 057A00 8029CA00 8FB9002C */  lw    $t9, 0x2c($sp)
/* 057A04 8029CA04 8FA90024 */  lw    $t1, 0x24($sp)
/* 057A08 8029CA08 87280008 */  lh    $t0, 8($t9)
/* 057A0C 8029CA0C AD2800C8 */  sw    $t0, 0xc8($t1)
/* 057A10 8029CA10 8FAA002C */  lw    $t2, 0x2c($sp)
/* 057A14 8029CA14 8FAC0024 */  lw    $t4, 0x24($sp)
/* 057A18 8029CA18 854B000A */  lh    $t3, 0xa($t2)
/* 057A1C 8029CA1C AD8B00CC */  sw    $t3, 0xcc($t4)
.L8029CA20:
/* 057A20 8029CA20 8FAD002C */  lw    $t5, 0x2c($sp)
/* 057A24 8029CA24 8DAE001C */  lw    $t6, 0x1c($t5)
/* 057A28 8029CA28 AFAE002C */  sw    $t6, 0x2c($sp)
/* 057A2C 8029CA2C 8FAF002C */  lw    $t7, 0x2c($sp)
/* 057A30 8029CA30 15E0FF9A */  bnez  $t7, .L8029C89C
/* 057A34 8029CA34 00000000 */   nop   
.L8029CA38:
/* 057A38 8029CA38 10000001 */  b     .L8029CA40
/* 057A3C 8029CA3C 00000000 */   nop   
.L8029CA40:
/* 057A40 8029CA40 8FBF0014 */  lw    $ra, 0x14($sp)
/* 057A44 8029CA44 27BD0028 */  addiu $sp, $sp, 0x28
/* 057A48 8029CA48 03E00008 */  jr    $ra
/* 057A4C 8029CA4C 00000000 */   nop   

glabel func_8029CA50
/* 057A50 8029CA50 03E00008 */  jr    $ra
/* 057A54 8029CA54 00000000 */   nop   

/* 057A58 8029CA58 03E00008 */  jr    $ra
/* 057A5C 8029CA5C 00000000 */   nop   

glabel func_8029CA60
/* 057A60 8029CA60 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 057A64 8029CA64 AFBF0014 */  sw    $ra, 0x14($sp)
/* 057A68 8029CA68 3C018036 */  lui   $at, %hi(D_8035FEE6) # $at, 0x8036
/* 057A6C 8029CA6C A420FEE6 */  sh    $zero, %lo(D_8035FEE6)($at)
/* 057A70 8029CA70 3C018034 */  lui   $at, %hi(D_8033C110) # $at, 0x8034
/* 057A74 8029CA74 AC20C110 */  sw    $zero, %lo(D_8033C110)($at)
/* 057A78 8029CA78 3C018036 */  lui   $at, %hi(gMarioObject) # $at, 0x8036
/* 057A7C 8029CA7C AC20FDE8 */  sw    $zero, %lo(gMarioObject)($at)
/* 057A80 8029CA80 3C018036 */  lui   $at, %hi(D_8035FEE0) # $at, 0x8036
/* 057A84 8029CA84 A420FEE0 */  sh    $zero, %lo(D_8035FEE0)($at)
/* 057A88 8029CA88 AFA0001C */  sw    $zero, 0x1c($sp)
.L8029CA8C:
/* 057A8C 8029CA8C 8FAE001C */  lw    $t6, 0x1c($sp)
/* 057A90 8029CA90 3C018036 */  lui   $at, %hi(D_8035FE68)
/* 057A94 8029CA94 000E7840 */  sll   $t7, $t6, 1
/* 057A98 8029CA98 002F0821 */  addu  $at, $at, $t7
/* 057A9C 8029CA9C A020FE68 */  sb    $zero, %lo(D_8035FE68)($at)
/* 057AA0 8029CAA0 8FB8001C */  lw    $t8, 0x1c($sp)
/* 057AA4 8029CAA4 3C018036 */  lui   $at, %hi(D_8035FE69)
/* 057AA8 8029CAA8 0018C840 */  sll   $t9, $t8, 1
/* 057AAC 8029CAAC 00390821 */  addu  $at, $at, $t9
/* 057AB0 8029CAB0 A020FE69 */  sb    $zero, %lo(D_8035FE69)($at)
/* 057AB4 8029CAB4 8FA8001C */  lw    $t0, 0x1c($sp)
/* 057AB8 8029CAB8 25090001 */  addiu $t1, $t0, 1
/* 057ABC 8029CABC 2921003C */  slti  $at, $t1, 0x3c
/* 057AC0 8029CAC0 1420FFF2 */  bnez  $at, .L8029CA8C
/* 057AC4 8029CAC4 AFA9001C */   sw    $t1, 0x1c($sp)
/* 057AC8 8029CAC8 0C0B2833 */  jal   func_802CA0CC
/* 057ACC 8029CACC 00000000 */   nop   
/* 057AD0 8029CAD0 0C0B23B6 */  jal   func_802C8ED8
/* 057AD4 8029CAD4 00000000 */   nop   
/* 057AD8 8029CAD8 3C048034 */  lui   $a0, %hi(D_8033B870) # $a0, 0x8034
/* 057ADC 8029CADC 0C0B23D7 */  jal   func_802C8F5C
/* 057AE0 8029CAE0 2484B870 */   addiu $a0, %lo(D_8033B870) # addiu $a0, $a0, -0x4790
/* 057AE4 8029CAE4 0C0E16FC */  jal   func_80385BF0
/* 057AE8 8029CAE8 00000000 */   nop   
/* 057AEC 8029CAEC 0C0A7294 */  jal   func_8029CA50
/* 057AF0 8029CAF0 00000000 */   nop   
/* 057AF4 8029CAF4 AFA0001C */  sw    $zero, 0x1c($sp)
.L8029CAF8:
/* 057AF8 8029CAF8 8FAA001C */  lw    $t2, 0x1c($sp)
/* 057AFC 8029CAFC 3C018034 */  lui   $at, %hi(D_8033C18C)
/* 057B00 8029CB00 000A5880 */  sll   $t3, $t2, 2
/* 057B04 8029CB04 016A5821 */  addu  $t3, $t3, $t2
/* 057B08 8029CB08 000B5880 */  sll   $t3, $t3, 2
/* 057B0C 8029CB0C 016A5823 */  subu  $t3, $t3, $t2
/* 057B10 8029CB10 000B5940 */  sll   $t3, $t3, 5
/* 057B14 8029CB14 002B0821 */  addu  $at, $at, $t3
/* 057B18 8029CB18 A420C18C */  sh    $zero, %lo(D_8033C18C)($at)
/* 057B1C 8029CB1C 8FAC001C */  lw    $t4, 0x1c($sp)
/* 057B20 8029CB20 3C0E8034 */  lui   $t6, %hi(D_8033C118) # $t6, 0x8034
/* 057B24 8029CB24 25CEC118 */  addiu $t6, %lo(D_8033C118) # addiu $t6, $t6, -0x3ee8
/* 057B28 8029CB28 000C6880 */  sll   $t5, $t4, 2
/* 057B2C 8029CB2C 01AC6821 */  addu  $t5, $t5, $t4
/* 057B30 8029CB30 000D6880 */  sll   $t5, $t5, 2
/* 057B34 8029CB34 01AC6823 */  subu  $t5, $t5, $t4
/* 057B38 8029CB38 000D6940 */  sll   $t5, $t5, 5
/* 057B3C 8029CB3C 0C0DF0F4 */  jal   func_8037C3D0
/* 057B40 8029CB40 01AE2021 */   addu  $a0, $t5, $t6
/* 057B44 8029CB44 8FAF001C */  lw    $t7, 0x1c($sp)
/* 057B48 8029CB48 25F80001 */  addiu $t8, $t7, 1
/* 057B4C 8029CB4C 2B0100F0 */  slti  $at, $t8, 0xf0
/* 057B50 8029CB50 1420FFE9 */  bnez  $at, .L8029CAF8
/* 057B54 8029CB54 AFB8001C */   sw    $t8, 0x1c($sp)
/* 057B58 8029CB58 24040800 */  li    $a0, 2048
/* 057B5C 8029CB5C 0C09E17A */  jal   func_802785E8
/* 057B60 8029CB60 00002825 */   move  $a1, $zero
/* 057B64 8029CB64 3C018036 */  lui   $at, %hi(D_8035FE0C) # $at, 0x8036
/* 057B68 8029CB68 AC22FE0C */  sw    $v0, %lo(D_8035FE0C)($at)
/* 057B6C 8029CB6C 3C198034 */  lui   $t9, %hi(D_8033B870) # $t9, 0x8034
/* 057B70 8029CB70 2739B870 */  addiu $t9, %lo(D_8033B870) # addiu $t9, $t9, -0x4790
/* 057B74 8029CB74 3C018036 */  lui   $at, %hi(D_8035FD78) # $at, 0x8036
/* 057B78 8029CB78 AC39FD78 */  sw    $t9, %lo(D_8035FD78)($at)
/* 057B7C 8029CB7C 0C0E0D69 */  jal   func_803835A4
/* 057B80 8029CB80 00000000 */   nop   
/* 057B84 8029CB84 10000001 */  b     .L8029CB8C
/* 057B88 8029CB88 00000000 */   nop   
.L8029CB8C:
/* 057B8C 8029CB8C 8FBF0014 */  lw    $ra, 0x14($sp)
/* 057B90 8029CB90 27BD0020 */  addiu $sp, $sp, 0x20
/* 057B94 8029CB94 03E00008 */  jr    $ra
/* 057B98 8029CB98 00000000 */   nop   

glabel func_8029CB9C
/* 057B9C 8029CB9C 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 057BA0 8029CBA0 AFBF0014 */  sw    $ra, 0x14($sp)
/* 057BA4 8029CBA4 3C048036 */  lui   $a0, %hi(D_8035FD78) # $a0, 0x8036
/* 057BA8 8029CBA8 8C84FD78 */  lw    $a0, %lo(D_8035FD78)($a0)
/* 057BAC 8029CBAC 0C0A716A */  jal   func_8029C5A8
/* 057BB0 8029CBB0 24840478 */   addiu $a0, $a0, 0x478
/* 057BB4 8029CBB4 3C018034 */  lui   $at, %hi(D_8033BF00) # $at, 0x8034
/* 057BB8 8029CBB8 AC22BF00 */  sw    $v0, %lo(D_8033BF00)($at)
/* 057BBC 8029CBBC 3C048036 */  lui   $a0, %hi(D_8035FD78) # $a0, 0x8036
/* 057BC0 8029CBC0 8C84FD78 */  lw    $a0, %lo(D_8035FD78)($a0)
/* 057BC4 8029CBC4 0C0A716A */  jal   func_8029C5A8
/* 057BC8 8029CBC8 248403A8 */   addiu $a0, $a0, 0x3a8
/* 057BCC 8029CBCC 3C018034 */  lui   $at, %hi(D_8033BF00) # $at, 0x8034
/* 057BD0 8029CBD0 AC22BF00 */  sw    $v0, %lo(D_8033BF00)($at)
/* 057BD4 8029CBD4 10000001 */  b     .L8029CBDC
/* 057BD8 8029CBD8 00000000 */   nop   
.L8029CBDC:
/* 057BDC 8029CBDC 8FBF0014 */  lw    $ra, 0x14($sp)
/* 057BE0 8029CBE0 27BD0018 */  addiu $sp, $sp, 0x18
/* 057BE4 8029CBE4 03E00008 */  jr    $ra
/* 057BE8 8029CBE8 00000000 */   nop   

glabel func_8029CBEC
/* 057BEC 8029CBEC 27BDFFD0 */  addiu $sp, $sp, -0x30
/* 057BF0 8029CBF0 AFBF001C */  sw    $ra, 0x1c($sp)
/* 057BF4 8029CBF4 AFB00018 */  sw    $s0, 0x18($sp)
/* 057BF8 8029CBF8 240E0002 */  li    $t6, 2
/* 057BFC 8029CBFC AFAE0024 */  sw    $t6, 0x24($sp)
/* 057C00 8029CC00 8FAF0024 */  lw    $t7, 0x24($sp)
/* 057C04 8029CC04 3C188033 */  lui   $t8, %hi(D_8032EF60)
/* 057C08 8029CC08 2401FFFF */  li    $at, -1
/* 057C0C 8029CC0C 030FC021 */  addu  $t8, $t8, $t7
/* 057C10 8029CC10 8318EF60 */  lb    $t8, %lo(D_8032EF60)($t8)
/* 057C14 8029CC14 1301001B */  beq   $t8, $at, .L8029CC84
/* 057C18 8029CC18 AFB80028 */   sw    $t8, 0x28($sp)
.L8029CC1C:
/* 057C1C 8029CC1C 8FB90028 */  lw    $t9, 0x28($sp)
/* 057C20 8029CC20 3C098036 */  lui   $t1, %hi(D_8035FD78) # $t1, 0x8036
/* 057C24 8029CC24 8D29FD78 */  lw    $t1, %lo(D_8035FD78)($t1)
/* 057C28 8029CC28 00194080 */  sll   $t0, $t9, 2
/* 057C2C 8029CC2C 01194023 */  subu  $t0, $t0, $t9
/* 057C30 8029CC30 00084080 */  sll   $t0, $t0, 2
/* 057C34 8029CC34 01194021 */  addu  $t0, $t0, $t9
/* 057C38 8029CC38 000840C0 */  sll   $t0, $t0, 3
/* 057C3C 8029CC3C 0C0A716A */  jal   func_8029C5A8
/* 057C40 8029CC40 01092021 */   addu  $a0, $t0, $t1
/* 057C44 8029CC44 3C0A8034 */  lui   $t2, %hi(D_8033BF00) # $t2, 0x8034
/* 057C48 8029CC48 8D4ABF00 */  lw    $t2, %lo(D_8033BF00)($t2)
/* 057C4C 8029CC4C 00408025 */  move  $s0, $v0
/* 057C50 8029CC50 3C018034 */  lui   $at, %hi(D_8033BF00) # $at, 0x8034
/* 057C54 8029CC54 01505821 */  addu  $t3, $t2, $s0
/* 057C58 8029CC58 AC2BBF00 */  sw    $t3, %lo(D_8033BF00)($at)
/* 057C5C 8029CC5C 8FAC0024 */  lw    $t4, 0x24($sp)
/* 057C60 8029CC60 258D0001 */  addiu $t5, $t4, 1
/* 057C64 8029CC64 AFAD0024 */  sw    $t5, 0x24($sp)
/* 057C68 8029CC68 8FAE0024 */  lw    $t6, 0x24($sp)
/* 057C6C 8029CC6C 3C0F8033 */  lui   $t7, %hi(D_8032EF60)
/* 057C70 8029CC70 2401FFFF */  li    $at, -1
/* 057C74 8029CC74 01EE7821 */  addu  $t7, $t7, $t6
/* 057C78 8029CC78 81EFEF60 */  lb    $t7, %lo(D_8032EF60)($t7)
/* 057C7C 8029CC7C 15E1FFE7 */  bne   $t7, $at, .L8029CC1C
/* 057C80 8029CC80 AFAF0028 */   sw    $t7, 0x28($sp)
.L8029CC84:
/* 057C84 8029CC84 10000001 */  b     .L8029CC8C
/* 057C88 8029CC88 00000000 */   nop   
.L8029CC8C:
/* 057C8C 8029CC8C 8FBF001C */  lw    $ra, 0x1c($sp)
/* 057C90 8029CC90 8FB00018 */  lw    $s0, 0x18($sp)
/* 057C94 8029CC94 27BD0030 */  addiu $sp, $sp, 0x30
/* 057C98 8029CC98 03E00008 */  jr    $ra
/* 057C9C 8029CC9C 00000000 */   nop   

glabel func_8029CCA0
/* 057CA0 8029CCA0 27BDFFD8 */  addiu $sp, $sp, -0x28
/* 057CA4 8029CCA4 AFBF0014 */  sw    $ra, 0x14($sp)
/* 057CA8 8029CCA8 AFA0001C */  sw    $zero, 0x1c($sp)
/* 057CAC 8029CCAC 8FAE001C */  lw    $t6, 0x1c($sp)
/* 057CB0 8029CCB0 3C0F8033 */  lui   $t7, %hi(D_8032EF60)
/* 057CB4 8029CCB4 2401FFFF */  li    $at, -1
/* 057CB8 8029CCB8 01EE7821 */  addu  $t7, $t7, $t6
/* 057CBC 8029CCBC 81EFEF60 */  lb    $t7, %lo(D_8032EF60)($t7)
/* 057CC0 8029CCC0 11E10015 */  beq   $t7, $at, .L8029CD18
/* 057CC4 8029CCC4 AFAF0020 */   sw    $t7, 0x20($sp)
.L8029CCC8:
/* 057CC8 8029CCC8 8FB80020 */  lw    $t8, 0x20($sp)
/* 057CCC 8029CCCC 3C088036 */  lui   $t0, %hi(D_8035FD78) # $t0, 0x8036
/* 057CD0 8029CCD0 8D08FD78 */  lw    $t0, %lo(D_8035FD78)($t0)
/* 057CD4 8029CCD4 0018C880 */  sll   $t9, $t8, 2
/* 057CD8 8029CCD8 0338C823 */  subu  $t9, $t9, $t8
/* 057CDC 8029CCDC 0019C880 */  sll   $t9, $t9, 2
/* 057CE0 8029CCE0 0338C821 */  addu  $t9, $t9, $t8
/* 057CE4 8029CCE4 0019C8C0 */  sll   $t9, $t9, 3
/* 057CE8 8029CCE8 0C0A7186 */  jal   func_8029C618
/* 057CEC 8029CCEC 03282021 */   addu  $a0, $t9, $t0
/* 057CF0 8029CCF0 8FA9001C */  lw    $t1, 0x1c($sp)
/* 057CF4 8029CCF4 252A0001 */  addiu $t2, $t1, 1
/* 057CF8 8029CCF8 AFAA001C */  sw    $t2, 0x1c($sp)
/* 057CFC 8029CCFC 8FAB001C */  lw    $t3, 0x1c($sp)
/* 057D00 8029CD00 3C0C8033 */  lui   $t4, %hi(D_8032EF60)
/* 057D04 8029CD04 2401FFFF */  li    $at, -1
/* 057D08 8029CD08 018B6021 */  addu  $t4, $t4, $t3
/* 057D0C 8029CD0C 818CEF60 */  lb    $t4, %lo(D_8032EF60)($t4)
/* 057D10 8029CD10 1581FFED */  bne   $t4, $at, .L8029CCC8
/* 057D14 8029CD14 AFAC0020 */   sw    $t4, 0x20($sp)
.L8029CD18:
/* 057D18 8029CD18 3C0D8034 */  lui   $t5, %hi(D_8033C110) # $t5, 0x8034
/* 057D1C 8029CD1C 8DADC110 */  lw    $t5, %lo(D_8033C110)($t5)
/* 057D20 8029CD20 2401FFFE */  li    $at, -2
/* 057D24 8029CD24 01A17024 */  and   $t6, $t5, $at
/* 057D28 8029CD28 3C018034 */  lui   $at, %hi(D_8033C110) # $at, 0x8034
/* 057D2C 8029CD2C AC2EC110 */  sw    $t6, %lo(D_8033C110)($at)
/* 057D30 8029CD30 10000001 */  b     .L8029CD38
/* 057D34 8029CD34 00000000 */   nop   
.L8029CD38:
/* 057D38 8029CD38 8FBF0014 */  lw    $ra, 0x14($sp)
/* 057D3C 8029CD3C 27BD0028 */  addiu $sp, $sp, 0x28
/* 057D40 8029CD40 03E00008 */  jr    $ra
/* 057D44 8029CD44 00000000 */   nop   

glabel Unknown8029CD48
/* 057D48 8029CD48 27BDFFC0 */  addiu $sp, $sp, -0x40
/* 057D4C 8029CD4C AFBF0014 */  sw    $ra, 0x14($sp)
/* 057D50 8029CD50 AFA40040 */  sw    $a0, 0x40($sp)
/* 057D54 8029CD54 AFA50044 */  sw    $a1, 0x44($sp)
/* 057D58 8029CD58 8FAF0044 */  lw    $t7, 0x44($sp)
/* 057D5C 8029CD5C 8FAE0040 */  lw    $t6, 0x40($sp)
/* 057D60 8029CD60 000FC0C0 */  sll   $t8, $t7, 3
/* 057D64 8029CD64 01D8C821 */  addu  $t9, $t6, $t8
/* 057D68 8029CD68 8F280000 */  lw    $t0, ($t9)
/* 057D6C 8029CD6C 8F290004 */  lw    $t1, 4($t9)
/* 057D70 8029CD70 8F2AFFF8 */  lw    $t2, -8($t9)
/* 057D74 8029CD74 8F2BFFFC */  lw    $t3, -4($t9)
/* 057D78 8029CD78 010A2023 */  subu  $a0, $t0, $t2
/* 057D7C 8029CD7C 012B082B */  sltu  $at, $t1, $t3
/* 057D80 8029CD80 00812023 */  subu  $a0, $a0, $at
/* 057D84 8029CD84 0C0C90DD */  jal   func_80324374
/* 057D88 8029CD88 012B2823 */   subu  $a1, $t1, $t3
/* 057D8C 8029CD8C F7A00030 */  sdc1  $f0, 0x30($sp)
/* 057D90 8029CD90 D7A40030 */  ldc1  $f4, 0x30($sp)
/* 057D94 8029CD94 44803800 */  mtc1  $zero, $f7
/* 057D98 8029CD98 44803000 */  mtc1  $zero, $f6
/* 057D9C 8029CD9C 00000000 */  nop   
/* 057DA0 8029CDA0 4626203C */  c.lt.d $f4, $f6
/* 057DA4 8029CDA4 00000000 */  nop   
/* 057DA8 8029CDA8 45000005 */  bc1f  .L8029CDC0
/* 057DAC 8029CDAC 00000000 */   nop   
/* 057DB0 8029CDB0 44804800 */  mtc1  $zero, $f9
/* 057DB4 8029CDB4 44804000 */  mtc1  $zero, $f8
/* 057DB8 8029CDB8 00000000 */  nop   
/* 057DBC 8029CDBC F7A80030 */  sdc1  $f8, 0x30($sp)
.L8029CDC0:
/* 057DC0 8029CDC0 0C0C9082 */  jal   func_80324208
/* 057DC4 8029CDC4 D7AC0030 */   ldc1  $f12, 0x30($sp)
/* 057DC8 8029CDC8 AFA20018 */  sw    $v0, 0x18($sp)
/* 057DCC 8029CDCC AFA3001C */  sw    $v1, 0x1c($sp)
/* 057DD0 8029CDD0 3C07000F */  lui   $a3, (0x000F4240 >> 16) # lui $a3, 0xf
/* 057DD4 8029CDD4 34E74240 */  ori   $a3, (0x000F4240 & 0xFFFF) # ori $a3, $a3, 0x4240
/* 057DD8 8029CDD8 8FA5001C */  lw    $a1, 0x1c($sp)
/* 057DDC 8029CDDC 8FA40018 */  lw    $a0, 0x18($sp)
/* 057DE0 8029CDE0 0C0C8CCA */  jal   __ll_mul
/* 057DE4 8029CDE4 24060000 */   li    $a2, 0
/* 057DE8 8029CDE8 AFA20020 */  sw    $v0, 0x20($sp)
/* 057DEC 8029CDEC AFA30024 */  sw    $v1, 0x24($sp)
/* 057DF0 8029CDF0 3C068033 */  lui   $a2, %hi(D_80334800) # $a2, 0x8033
/* 057DF4 8029CDF4 3C078033 */  lui   $a3, %hi(D_80334804) # $a3, 0x8033
/* 057DF8 8029CDF8 8CE74804 */  lw    $a3, %lo(D_80334804)($a3)
/* 057DFC 8029CDFC 8CC64800 */  lw    $a2, %lo(D_80334800)($a2)
/* 057E00 8029CE00 8FA50024 */  lw    $a1, 0x24($sp)
/* 057E04 8029CE04 0C0C8C8A */  jal   __ull_div
/* 057E08 8029CE08 8FA40020 */   lw    $a0, 0x20($sp)
/* 057E0C 8029CE0C AFA20028 */  sw    $v0, 0x28($sp)
/* 057E10 8029CE10 AFA3002C */  sw    $v1, 0x2c($sp)
/* 057E14 8029CE14 8FA5002C */  lw    $a1, 0x2c($sp)
/* 057E18 8029CE18 0C0C90DD */  jal   func_80324374
/* 057E1C 8029CE1C 8FA40028 */   lw    $a0, 0x28($sp)
/* 057E20 8029CE20 3C018033 */  lui   $at, %hi(D_80336600)
/* 057E24 8029CE24 D42A6600 */  ldc1  $f10, %lo(D_80336600)($at)
/* 057E28 8029CE28 3C018033 */  lui    $at, %hi(D_80336608)
/* 057E2C 8029CE2C D4326608 */  ldc1  $f18, %lo(D_80336608)($at)
/* 057E30 8029CE30 462A0403 */  div.d $f16, $f0, $f10
/* 057E34 8029CE34 240D0001 */  li    $t5, 1
/* 057E38 8029CE38 46328102 */  mul.d $f4, $f16, $f18
/* 057E3C 8029CE3C 444CF800 */  cfc1  $t4, $31
/* 057E40 8029CE40 44CDF800 */  ctc1  $t5, $31
/* 057E44 8029CE44 00000000 */  nop   
/* 057E48 8029CE48 462021A4 */  cvt.w.d $f6, $f4
/* 057E4C 8029CE4C 444DF800 */  cfc1  $t5, $31
/* 057E50 8029CE50 00000000 */  nop   
/* 057E54 8029CE54 31A10004 */  andi  $at, $t5, 4
/* 057E58 8029CE58 31AD0078 */  andi  $t5, $t5, 0x78
/* 057E5C 8029CE5C 11A00015 */  beqz  $t5, .L8029CEB4
/* 057E60 8029CE60 00000000 */   nop   
/* 057E64 8029CE64 3C0141E0 */  li    $at, 0x41E00000 # 28.000000
/* 057E68 8029CE68 44813800 */  mtc1  $at, $f7
/* 057E6C 8029CE6C 44803000 */  mtc1  $zero, $f6
/* 057E70 8029CE70 240D0001 */  li    $t5, 1
/* 057E74 8029CE74 46262181 */  sub.d $f6, $f4, $f6
/* 057E78 8029CE78 44CDF800 */  ctc1  $t5, $31
/* 057E7C 8029CE7C 00000000 */  nop   
/* 057E80 8029CE80 462031A4 */  cvt.w.d $f6, $f6
/* 057E84 8029CE84 444DF800 */  cfc1  $t5, $31
/* 057E88 8029CE88 00000000 */  nop   
/* 057E8C 8029CE8C 31A10004 */  andi  $at, $t5, 4
/* 057E90 8029CE90 31AD0078 */  andi  $t5, $t5, 0x78
/* 057E94 8029CE94 15A00005 */  bnez  $t5, .L8029CEAC
/* 057E98 8029CE98 00000000 */   nop   
/* 057E9C 8029CE9C 440D3000 */  mfc1  $t5, $f6
/* 057EA0 8029CEA0 3C018000 */  lui   $at, 0x8000
/* 057EA4 8029CEA4 10000007 */  b     .L8029CEC4
/* 057EA8 8029CEA8 01A16825 */   or    $t5, $t5, $at
.L8029CEAC:
/* 057EAC 8029CEAC 10000005 */  b     .L8029CEC4
/* 057EB0 8029CEB0 240DFFFF */   li    $t5, -1
.L8029CEB4:
/* 057EB4 8029CEB4 440D3000 */  mfc1  $t5, $f6
/* 057EB8 8029CEB8 00000000 */  nop   
/* 057EBC 8029CEBC 05A0FFFB */  bltz  $t5, .L8029CEAC
/* 057EC0 8029CEC0 00000000 */   nop   
.L8029CEC4:
/* 057EC4 8029CEC4 44CCF800 */  ctc1  $t4, $31
/* 057EC8 8029CEC8 A7AD003E */  sh    $t5, 0x3e($sp)
/* 057ECC 8029CECC 00000000 */  nop   
/* 057ED0 8029CED0 97AF003E */  lhu   $t7, 0x3e($sp)
/* 057ED4 8029CED4 29E103E8 */  slti  $at, $t7, 0x3e8
/* 057ED8 8029CED8 14200003 */  bnez  $at, .L8029CEE8
/* 057EDC 8029CEDC 00000000 */   nop   
/* 057EE0 8029CEE0 240E03E7 */  li    $t6, 999
/* 057EE4 8029CEE4 A7AE003E */  sh    $t6, 0x3e($sp)
.L8029CEE8:
/* 057EE8 8029CEE8 10000003 */  b     .L8029CEF8
/* 057EEC 8029CEEC 97A2003E */   lhu   $v0, 0x3e($sp)
/* 057EF0 8029CEF0 10000001 */  b     .L8029CEF8
/* 057EF4 8029CEF4 00000000 */   nop   
.L8029CEF8:
/* 057EF8 8029CEF8 8FBF0014 */  lw    $ra, 0x14($sp)
/* 057EFC 8029CEFC 27BD0040 */  addiu $sp, $sp, 0x40
/* 057F00 8029CF00 03E00008 */  jr    $ra
/* 057F04 8029CF04 00000000 */   nop   

glabel func_8029CF08
/* 057F08 8029CF08 27BDFEF8 */  addiu $sp, $sp, -0x108
/* 057F0C 8029CF0C AFBF0014 */  sw    $ra, 0x14($sp)
/* 057F10 8029CF10 AFA40108 */  sw    $a0, 0x108($sp)
/* 057F14 8029CF14 0C0B2634 */  jal   func_802C98D0
/* 057F18 8029CF18 00000000 */   nop   
/* 057F1C 8029CF1C 27AE0018 */  addiu $t6, $sp, 0x18
/* 057F20 8029CF20 ADC20000 */  sw    $v0, ($t6)
/* 057F24 8029CF24 ADC30004 */  sw    $v1, 4($t6)
/* 057F28 8029CF28 3C0F8034 */  lui   $t7, %hi(D_8033C110) # $t7, 0x8034
/* 057F2C 8029CF2C 8DEFC110 */  lw    $t7, %lo(D_8033C110)($t7)
/* 057F30 8029CF30 2401FFDF */  li    $at, -33
/* 057F34 8029CF34 01E1C024 */  and   $t8, $t7, $at
/* 057F38 8029CF38 3C018034 */  lui   $at, %hi(D_8033C110) # $at, 0x8034
/* 057F3C 8029CF3C AC38C110 */  sw    $t8, %lo(D_8033C110)($at)
/* 057F40 8029CF40 3C018036 */  lui   $at, %hi(D_8035FEEE) # $at, 0x8036
/* 057F44 8029CF44 A420FEEE */  sh    $zero, %lo(D_8035FEEE)($at)
/* 057F48 8029CF48 3C018036 */  lui   $at, %hi(D_8035FEF0) # $at, 0x8036
/* 057F4C 8029CF4C A420FEF0 */  sh    $zero, %lo(D_8035FEF0)($at)
/* 057F50 8029CF50 3C018036 */  lui   $at, %hi(D_8035FE10) # $at, 0x8036
/* 057F54 8029CF54 A420FE10 */  sh    $zero, %lo(D_8035FE10)($at)
/* 057F58 8029CF58 0C0B2850 */  jal   func_802CA140
/* 057F5C 8029CF5C 00000000 */   nop   
/* 057F60 8029CF60 0C0B2974 */  jal   func_802CA5D0
/* 057F64 8029CF64 00000000 */   nop   
/* 057F68 8029CF68 3C198034 */  lui   $t9, %hi(D_8033B870) # $t9, 0x8034
/* 057F6C 8029CF6C 2739B870 */  addiu $t9, %lo(D_8033B870) # addiu $t9, $t9, -0x4790
/* 057F70 8029CF70 3C018036 */  lui   $at, %hi(D_8035FD78) # $at, 0x8036
/* 057F74 8029CF74 AC39FD78 */  sw    $t9, %lo(D_8035FD78)($at)
/* 057F78 8029CF78 27A80018 */  addiu $t0, $sp, 0x18
/* 057F7C 8029CF7C 8D040000 */  lw    $a0, ($t0)
/* 057F80 8029CF80 0C0B2640 */  jal   func_802C9900
/* 057F84 8029CF84 8D050004 */   lw    $a1, 4($t0)
/* 057F88 8029CF88 27A90018 */  addiu $t1, $sp, 0x18
/* 057F8C 8029CF8C AD220008 */  sw    $v0, 8($t1)
/* 057F90 8029CF90 AD23000C */  sw    $v1, 0xc($t1)
/* 057F94 8029CF94 0C0E0D69 */  jal   func_803835A4
/* 057F98 8029CF98 00000000 */   nop   
/* 057F9C 8029CF9C 27AA0018 */  addiu $t2, $sp, 0x18
/* 057FA0 8029CFA0 8D440000 */  lw    $a0, ($t2)
/* 057FA4 8029CFA4 0C0B2640 */  jal   func_802C9900
/* 057FA8 8029CFA8 8D450004 */   lw    $a1, 4($t2)
/* 057FAC 8029CFAC 27AB0018 */  addiu $t3, $sp, 0x18
/* 057FB0 8029CFB0 AD620010 */  sw    $v0, 0x10($t3)
/* 057FB4 8029CFB4 AD630014 */  sw    $v1, 0x14($t3)
/* 057FB8 8029CFB8 0C0A72E7 */  jal   func_8029CB9C
/* 057FBC 8029CFBC 00000000 */   nop   
/* 057FC0 8029CFC0 0C0B20FC */  jal   apply_mario_platform_displacement
/* 057FC4 8029CFC4 00000000 */   nop   
/* 057FC8 8029CFC8 27AC0018 */  addiu $t4, $sp, 0x18
/* 057FCC 8029CFCC 8D840000 */  lw    $a0, ($t4)
/* 057FD0 8029CFD0 0C0B2640 */  jal   func_802C9900
/* 057FD4 8029CFD4 8D850004 */   lw    $a1, 4($t4)
/* 057FD8 8029CFD8 27AD0018 */  addiu $t5, $sp, 0x18
/* 057FDC 8029CFDC ADA20018 */  sw    $v0, 0x18($t5)
/* 057FE0 8029CFE0 ADA3001C */  sw    $v1, 0x1c($t5)
/* 057FE4 8029CFE4 0C0B2311 */  jal   func_802C8C44
/* 057FE8 8029CFE8 00000000 */   nop   
/* 057FEC 8029CFEC 27AE0018 */  addiu $t6, $sp, 0x18
/* 057FF0 8029CFF0 8DC40000 */  lw    $a0, ($t6)
/* 057FF4 8029CFF4 0C0B2640 */  jal   func_802C9900
/* 057FF8 8029CFF8 8DC50004 */   lw    $a1, 4($t6)
/* 057FFC 8029CFFC 27AF0018 */  addiu $t7, $sp, 0x18
/* 058000 8029D000 ADE20020 */  sw    $v0, 0x20($t7)
/* 058004 8029D004 ADE30024 */  sw    $v1, 0x24($t7)
/* 058008 8029D008 0C0A72FB */  jal   func_8029CBEC
/* 05800C 8029D00C 00000000 */   nop   
/* 058010 8029D010 27B80018 */  addiu $t8, $sp, 0x18
/* 058014 8029D014 8F040000 */  lw    $a0, ($t8)
/* 058018 8029D018 0C0B2640 */  jal   func_802C9900
/* 05801C 8029D01C 8F050004 */   lw    $a1, 4($t8)
/* 058020 8029D020 27B90018 */  addiu $t9, $sp, 0x18
/* 058024 8029D024 AF220028 */  sw    $v0, 0x28($t9)
/* 058028 8029D028 AF23002C */  sw    $v1, 0x2c($t9)
/* 05802C 8029D02C 0C0A7328 */  jal   func_8029CCA0
/* 058030 8029D030 00000000 */   nop   
/* 058034 8029D034 27A80018 */  addiu $t0, $sp, 0x18
/* 058038 8029D038 8D040000 */  lw    $a0, ($t0)
/* 05803C 8029D03C 0C0B2640 */  jal   func_802C9900
/* 058040 8029D040 8D050004 */   lw    $a1, 4($t0)
/* 058044 8029D044 27A90018 */  addiu $t1, $sp, 0x18
/* 058048 8029D048 AD220030 */  sw    $v0, 0x30($t1)
/* 05804C 8029D04C AD230034 */  sw    $v1, 0x34($t1)
/* 058050 8029D050 0C0B1FC8 */  jal   update_mario_platform
/* 058054 8029D054 00000000 */   nop   
/* 058058 8029D058 27AA0018 */  addiu $t2, $sp, 0x18
/* 05805C 8029D05C 8D440000 */  lw    $a0, ($t2)
/* 058060 8029D060 0C0B2640 */  jal   func_802C9900
/* 058064 8029D064 8D450004 */   lw    $a1, 4($t2)
/* 058068 8029D068 27AB0018 */  addiu $t3, $sp, 0x18
/* 05806C 8029D06C AD620038 */  sw    $v0, 0x38($t3)
/* 058070 8029D070 AD63003C */  sw    $v1, 0x3c($t3)
/* 058074 8029D074 27AE0018 */  addiu $t6, $sp, 0x18
/* 058078 8029D078 240C0000 */  li    $t4, 0
/* 05807C 8029D07C 240D0000 */  li    $t5, 0
/* 058080 8029D080 ADCD0004 */  sw    $t5, 4($t6)
/* 058084 8029D084 ADCC0000 */  sw    $t4, ($t6)
/* 058088 8029D088 0C0B2978 */  jal   func_802CA5E0
/* 05808C 8029D08C 00000000 */   nop   
/* 058090 8029D090 3C0F8034 */  lui   $t7, %hi(D_8033C110) # $t7, 0x8034
/* 058094 8029D094 8DEFC110 */  lw    $t7, %lo(D_8033C110)($t7)
/* 058098 8029D098 31F80002 */  andi  $t8, $t7, 2
/* 05809C 8029D09C 13000007 */  beqz  $t8, .L8029D0BC
/* 0580A0 8029D0A0 00000000 */   nop   
/* 0580A4 8029D0A4 3C198034 */  lui   $t9, %hi(D_8033C110) # $t9, 0x8034
/* 0580A8 8029D0A8 8F39C110 */  lw    $t9, %lo(D_8033C110)($t9)
/* 0580AC 8029D0AC 3C018034 */  lui   $at, %hi(D_8033C110) # $at, 0x8034
/* 0580B0 8029D0B0 37280040 */  ori   $t0, $t9, 0x40
/* 0580B4 8029D0B4 10000007 */  b     .L8029D0D4
/* 0580B8 8029D0B8 AC28C110 */   sw    $t0, %lo(D_8033C110)($at)
.L8029D0BC:
/* 0580BC 8029D0BC 3C098034 */  lui   $t1, %hi(D_8033C110) # $t1, 0x8034
/* 0580C0 8029D0C0 8D29C110 */  lw    $t1, %lo(D_8033C110)($t1)
/* 0580C4 8029D0C4 2401FFBF */  li    $at, -65
/* 0580C8 8029D0C8 01215024 */  and   $t2, $t1, $at
/* 0580CC 8029D0CC 3C018034 */  lui   $at, %hi(D_8033C110) # $at, 0x8034
/* 0580D0 8029D0D0 AC2AC110 */  sw    $t2, %lo(D_8033C110)($at)
.L8029D0D4:
/* 0580D4 8029D0D4 3C0B8034 */  lui   $t3, %hi(D_8033BF00) # $t3, 0x8034
/* 0580D8 8029D0D8 8D6BBF00 */  lw    $t3, %lo(D_8033BF00)($t3)
/* 0580DC 8029D0DC 3C018036 */  lui   $at, %hi(D_8035FDF8) # $at, 0x8036
/* 0580E0 8029D0E0 A42BFDF8 */  sh    $t3, %lo(D_8035FDF8)($at)
/* 0580E4 8029D0E4 10000001 */  b     .L8029D0EC
/* 0580E8 8029D0E8 00000000 */   nop   
.L8029D0EC:
/* 0580EC 8029D0EC 8FBF0014 */  lw    $ra, 0x14($sp)
/* 0580F0 8029D0F0 27BD0108 */  addiu $sp, $sp, 0x108
/* 0580F4 8029D0F4 03E00008 */  jr    $ra
/* 0580F8 8029D0F8 00000000 */   nop   

/* 0580FC 8029D0FC 00000000 */  nop   
