# Super Mario 64 (J) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.section .header, "a"
.byte  0x80, 0x37, 0x12, 0x40 # PI BSD Domain 1 register
.word  0x0000000F # clock rate setting
.word  0x80246000 # entry point
.word  0x00001444 # release
.word  0x4EAA3D0E # checksum1
.word  0x74757C24 # checksum2
.word  0x00000000 # unknown
.word  0x00000000 # unknown
.ascii "SUPER MARIO 64      " # ROM name: 20 bytes
.word  0x00000000 # unknown
.word  0x0000004E # cartridge
.ascii "SM"       # cartridge ID
.ascii "J"        # country
.byte  0x00       # version
