# Super Mario 64 (J) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"
.include "globals.inc"

.section .text, "ax" 

glabel func_802D1730
/* 08C730 802D1730 00063400 */  sll   $a2, $a2, 0x10
/* 08C734 802D1734 00073C00 */  sll   $a3, $a3, 0x10
/* 08C738 802D1738 00073C03 */  sra   $a3, $a3, 0x10
/* 08C73C 802D173C 00063403 */  sra   $a2, $a2, 0x10
/* 08C740 802D1740 00057100 */  sll   $t6, $a1, 4
/* 08C744 802D1744 008E7821 */  addu  $t7, $a0, $t6
/* 08C748 802D1748 A5E60000 */  sh    $a2, ($t7)
/* 08C74C 802D174C 0005C100 */  sll   $t8, $a1, 4
/* 08C750 802D1750 0098C821 */  addu  $t9, $a0, $t8
/* 08C754 802D1754 A7270002 */  sh    $a3, 2($t9)
/* 08C758 802D1758 87A80012 */  lh    $t0, 0x12($sp)
/* 08C75C 802D175C 00054900 */  sll   $t1, $a1, 4
/* 08C760 802D1760 00895021 */  addu  $t2, $a0, $t1
/* 08C764 802D1764 A5480004 */  sh    $t0, 4($t2)
/* 08C768 802D1768 00055900 */  sll   $t3, $a1, 4
/* 08C76C 802D176C 008B6021 */  addu  $t4, $a0, $t3
/* 08C770 802D1770 A5800006 */  sh    $zero, 6($t4)
/* 08C774 802D1774 87AD0016 */  lh    $t5, 0x16($sp)
/* 08C778 802D1778 00057100 */  sll   $t6, $a1, 4
/* 08C77C 802D177C 008E7821 */  addu  $t7, $a0, $t6
/* 08C780 802D1780 A5ED0008 */  sh    $t5, 8($t7)
/* 08C784 802D1784 87B8001A */  lh    $t8, 0x1a($sp)
/* 08C788 802D1788 0005C900 */  sll   $t9, $a1, 4
/* 08C78C 802D178C 00994821 */  addu  $t1, $a0, $t9
/* 08C790 802D1790 A538000A */  sh    $t8, 0xa($t1)
/* 08C794 802D1794 93A8001F */  lbu   $t0, 0x1f($sp)
/* 08C798 802D1798 00055100 */  sll   $t2, $a1, 4
/* 08C79C 802D179C 008A5821 */  addu  $t3, $a0, $t2
/* 08C7A0 802D17A0 A168000C */  sb    $t0, 0xc($t3)
/* 08C7A4 802D17A4 93AC0023 */  lbu   $t4, 0x23($sp)
/* 08C7A8 802D17A8 00057100 */  sll   $t6, $a1, 4
/* 08C7AC 802D17AC 008E6821 */  addu  $t5, $a0, $t6
/* 08C7B0 802D17B0 A1AC000D */  sb    $t4, 0xd($t5)
/* 08C7B4 802D17B4 93AF0027 */  lbu   $t7, 0x27($sp)
/* 08C7B8 802D17B8 0005C900 */  sll   $t9, $a1, 4
/* 08C7BC 802D17BC 0099C021 */  addu  $t8, $a0, $t9
/* 08C7C0 802D17C0 A30F000E */  sb    $t7, 0xe($t8)
/* 08C7C4 802D17C4 93A9002B */  lbu   $t1, 0x2b($sp)
/* 08C7C8 802D17C8 00055100 */  sll   $t2, $a1, 4
/* 08C7CC 802D17CC 008A4021 */  addu  $t0, $a0, $t2
/* 08C7D0 802D17D0 A109000F */  sb    $t1, 0xf($t0)
/* 08C7D4 802D17D4 03E00008 */  jr    $ra
/* 08C7D8 802D17D8 00000000 */   nop   

/* 08C7DC 802D17DC 03E00008 */  jr    $ra
/* 08C7E0 802D17E0 00000000 */   nop   

glabel func_802D17E4
/* 08C7E4 802D17E4 44803800 */  mtc1  $zero, $f7
/* 08C7E8 802D17E8 44803000 */  mtc1  $zero, $f6
/* 08C7EC 802D17EC 46006121 */  cvt.d.s $f4, $f12
/* 08C7F0 802D17F0 4624303E */  c.le.d $f6, $f4
/* 08C7F4 802D17F4 00000000 */  nop   
/* 08C7F8 802D17F8 45000010 */  bc1f  .L802D183C
/* 08C7FC 802D17FC 00000000 */   nop   
/* 08C800 802D1800 3C013FE0 */  li    $at, 0x3FE00000 # 1.750000
/* 08C804 802D1804 44815800 */  mtc1  $at, $f11
/* 08C808 802D1808 44805000 */  mtc1  $zero, $f10
/* 08C80C 802D180C 46006221 */  cvt.d.s $f8, $f12
/* 08C810 802D1810 462A4400 */  add.d $f16, $f8, $f10
/* 08C814 802D1814 4620848D */  trunc.w.d $f18, $f16
/* 08C818 802D1818 44029000 */  mfc1  $v0, $f18
/* 08C81C 802D181C 00000000 */  nop   
/* 08C820 802D1820 00027C00 */  sll   $t7, $v0, 0x10
/* 08C824 802D1824 01E01025 */  move  $v0, $t7
/* 08C828 802D1828 0002C403 */  sra   $t8, $v0, 0x10
/* 08C82C 802D182C 03E00008 */  jr    $ra
/* 08C830 802D1830 03001025 */   move  $v0, $t8

/* 08C834 802D1834 1000000E */  b     .L802D1870
/* 08C838 802D1838 00000000 */   nop   
.L802D183C:
/* 08C83C 802D183C 3C013FE0 */  li    $at, 0x3FE00000 # 1.750000
/* 08C840 802D1840 44813800 */  mtc1  $at, $f7
/* 08C844 802D1844 44803000 */  mtc1  $zero, $f6
/* 08C848 802D1848 46006121 */  cvt.d.s $f4, $f12
/* 08C84C 802D184C 46262201 */  sub.d $f8, $f4, $f6
/* 08C850 802D1850 4620428D */  trunc.w.d $f10, $f8
/* 08C854 802D1854 44025000 */  mfc1  $v0, $f10
/* 08C858 802D1858 00000000 */  nop   
/* 08C85C 802D185C 00024400 */  sll   $t0, $v0, 0x10
/* 08C860 802D1860 01001025 */  move  $v0, $t0
/* 08C864 802D1864 00024C03 */  sra   $t1, $v0, 0x10
/* 08C868 802D1868 03E00008 */  jr    $ra
/* 08C86C 802D186C 01201025 */   move  $v0, $t1

.L802D1870:
/* 08C870 802D1870 03E00008 */  jr    $ra
/* 08C874 802D1874 00000000 */   nop   

/* 08C878 802D1878 03E00008 */  jr    $ra
/* 08C87C 802D187C 00000000 */   nop   

glabel Geo18_802D2360
/* 08C880 802D1880 27BDFFD0 */  addiu $sp, $sp, -0x30
/* 08C884 802D1884 AFBF0014 */  sw    $ra, 0x14($sp)
/* 08C888 802D1888 AFA40030 */  sw    $a0, 0x30($sp)
/* 08C88C 802D188C AFA50034 */  sw    $a1, 0x34($sp)
/* 08C890 802D1890 AFA60038 */  sw    $a2, 0x38($sp)
/* 08C894 802D1894 AFA00024 */  sw    $zero, 0x24($sp)
/* 08C898 802D1898 AFA00020 */  sw    $zero, 0x20($sp)
/* 08C89C 802D189C 8FAE0030 */  lw    $t6, 0x30($sp)
/* 08C8A0 802D18A0 24010001 */  li    $at, 1
/* 08C8A4 802D18A4 15C10032 */  bne   $t6, $at, .L802D1970
/* 08C8A8 802D18A8 00000000 */   nop   
/* 08C8AC 802D18AC 0C09E6EF */  jal   save_file_get_flags
/* 08C8B0 802D18B0 00000000 */   nop   
/* 08C8B4 802D18B4 AFA2002C */  sw    $v0, 0x2c($sp)
/* 08C8B8 802D18B8 3C0F8034 */  lui   $t7, %hi(D_80339EF4) # $t7, 0x8034
/* 08C8BC 802D18BC 85EF9EF4 */  lh    $t7, %lo(D_80339EF4)($t7)
/* 08C8C0 802D18C0 29E1000A */  slti  $at, $t7, 0xa
/* 08C8C4 802D18C4 1420002A */  bnez  $at, .L802D1970
/* 08C8C8 802D18C8 00000000 */   nop   
/* 08C8CC 802D18CC 8FB8002C */  lw    $t8, 0x2c($sp)
/* 08C8D0 802D18D0 33190002 */  andi  $t9, $t8, 2
/* 08C8D4 802D18D4 17200026 */  bnez  $t9, .L802D1970
/* 08C8D8 802D18D8 00000000 */   nop   
/* 08C8DC 802D18DC 0C09E25F */  jal   func_8027897C
/* 08C8E0 802D18E0 24040010 */   li    $a0, 16
/* 08C8E4 802D18E4 AFA20020 */  sw    $v0, 0x20($sp)
/* 08C8E8 802D18E8 8FA80020 */  lw    $t0, 0x20($sp)
/* 08C8EC 802D18EC 15000005 */  bnez  $t0, .L802D1904
/* 08C8F0 802D18F0 00000000 */   nop   
/* 08C8F4 802D18F4 10000022 */  b     .L802D1980
/* 08C8F8 802D18F8 00001025 */   move  $v0, $zero
/* 08C8FC 802D18FC 10000003 */  b     .L802D190C
/* 08C900 802D1900 00000000 */   nop   
.L802D1904:
/* 08C904 802D1904 8FA90020 */  lw    $t1, 0x20($sp)
/* 08C908 802D1908 AFA90024 */  sw    $t1, 0x24($sp)
.L802D190C:
/* 08C90C 802D190C 8FAA0034 */  lw    $t2, 0x34($sp)
/* 08C910 802D1910 AFAA0028 */  sw    $t2, 0x28($sp)
/* 08C914 802D1914 8FAB0028 */  lw    $t3, 0x28($sp)
/* 08C918 802D1918 856C0002 */  lh    $t4, 2($t3)
/* 08C91C 802D191C 318D00FF */  andi  $t5, $t4, 0xff
/* 08C920 802D1920 35AE0500 */  ori   $t6, $t5, 0x500
/* 08C924 802D1924 A56E0002 */  sh    $t6, 2($t3)
/* 08C928 802D1928 8FAF0024 */  lw    $t7, 0x24($sp)
/* 08C92C 802D192C 25F80008 */  addiu $t8, $t7, 8
/* 08C930 802D1930 AFB80024 */  sw    $t8, 0x24($sp)
/* 08C934 802D1934 AFAF001C */  sw    $t7, 0x1c($sp)
/* 08C938 802D1938 8FA8001C */  lw    $t0, 0x1c($sp)
/* 08C93C 802D193C 3C190600 */  lui   $t9, 0x600
/* 08C940 802D1940 AD190000 */  sw    $t9, ($t0)
/* 08C944 802D1944 8FAA001C */  lw    $t2, 0x1c($sp)
/* 08C948 802D1948 3C090703 */  lui   $t1, %hi(D_0702A880) # $t1, 0x703
/* 08C94C 802D194C 2529A880 */  addiu $t1, %lo(D_0702A880) # addiu $t1, $t1, -0x5780
/* 08C950 802D1950 AD490004 */  sw    $t1, 4($t2)
/* 08C954 802D1954 8FAC0024 */  lw    $t4, 0x24($sp)
/* 08C958 802D1958 AFAC0018 */  sw    $t4, 0x18($sp)
/* 08C95C 802D195C 8FAE0018 */  lw    $t6, 0x18($sp)
/* 08C960 802D1960 3C0DB800 */  lui   $t5, 0xb800
/* 08C964 802D1964 ADCD0000 */  sw    $t5, ($t6)
/* 08C968 802D1968 8FAB0018 */  lw    $t3, 0x18($sp)
/* 08C96C 802D196C AD600004 */  sw    $zero, 4($t3)
.L802D1970:
/* 08C970 802D1970 10000003 */  b     .L802D1980
/* 08C974 802D1974 8FA20020 */   lw    $v0, 0x20($sp)
/* 08C978 802D1978 10000001 */  b     .L802D1980
/* 08C97C 802D197C 00000000 */   nop   
.L802D1980:
/* 08C980 802D1980 8FBF0014 */  lw    $ra, 0x14($sp)
/* 08C984 802D1984 27BD0030 */  addiu $sp, $sp, 0x30
/* 08C988 802D1988 03E00008 */  jr    $ra
/* 08C98C 802D198C 00000000 */   nop   

glabel Geo18_802D2470
/* 08C990 802D1990 AFA50004 */  sw    $a1, 4($sp)
/* 08C994 802D1994 AFA60008 */  sw    $a2, 8($sp)
/* 08C998 802D1998 24010001 */  li    $at, 1
/* 08C99C 802D199C 1081000F */  beq   $a0, $at, .L802D19DC
/* 08C9A0 802D19A0 00000000 */   nop   
/* 08C9A4 802D19A4 3C018033 */  lui   $at, %hi(D_80330398) # $at, 0x8033
/* 08C9A8 802D19A8 A4200398 */  sh    $zero, %lo(D_80330398)($at)
/* 08C9AC 802D19AC 3C0E8033 */  lui   $t6, %hi(D_8032CFA8) # $t6, 0x8033
/* 08C9B0 802D19B0 95CECFA8 */  lhu   $t6, %lo(D_8032CFA8)($t6)
/* 08C9B4 802D19B4 3C018033 */  lui   $at, %hi(D_80330394) # $at, 0x8033
/* 08C9B8 802D19B8 25CFFFFF */  addiu $t7, $t6, -1
/* 08C9BC 802D19BC A42F0394 */  sh    $t7, %lo(D_80330394)($at)
/* 08C9C0 802D19C0 3C188033 */  lui   $t8, %hi(D_8032CFA8) # $t8, 0x8033
/* 08C9C4 802D19C4 9718CFA8 */  lhu   $t8, %lo(D_8032CFA8)($t8)
/* 08C9C8 802D19C8 3C018033 */  lui   $at, %hi(D_80330390) # $at, 0x8033
/* 08C9CC 802D19CC A4380390 */  sh    $t8, %lo(D_80330390)($at)
/* 08C9D0 802D19D0 3C018036 */  lui   $at, %hi(D_8035FF80) # $at, 0x8036
/* 08C9D4 802D19D4 10000014 */  b     .L802D1A28
/* 08C9D8 802D19D8 A020FF80 */   sb    $zero, %lo(D_8035FF80)($at)
.L802D19DC:
/* 08C9DC 802D19DC 3C198033 */  lui   $t9, %hi(D_80330390) # $t9, 0x8033
/* 08C9E0 802D19E0 87390390 */  lh    $t9, %lo(D_80330390)($t9)
/* 08C9E4 802D19E4 3C018033 */  lui   $at, %hi(D_80330394) # $at, 0x8033
/* 08C9E8 802D19E8 A4390394 */  sh    $t9, %lo(D_80330394)($at)
/* 08C9EC 802D19EC 3C088033 */  lui   $t0, %hi(D_8032CFA8) # $t0, 0x8033
/* 08C9F0 802D19F0 9508CFA8 */  lhu   $t0, %lo(D_8032CFA8)($t0)
/* 08C9F4 802D19F4 3C018033 */  lui   $at, %hi(D_80330390) # $at, 0x8033
/* 08C9F8 802D19F8 A4280390 */  sh    $t0, %lo(D_80330390)($at)
/* 08C9FC 802D19FC 3C098033 */  lui   $t1, %hi(D_80330394) # $t1, 0x8033
/* 08CA00 802D1A00 3C0A8033 */  lui   $t2, %hi(D_80330390) # $t2, 0x8033
/* 08CA04 802D1A04 854A0390 */  lh    $t2, %lo(D_80330390)($t2)
/* 08CA08 802D1A08 85290394 */  lh    $t1, %lo(D_80330394)($t1)
/* 08CA0C 802D1A0C 112A0006 */  beq   $t1, $t2, .L802D1A28
/* 08CA10 802D1A10 00000000 */   nop   
/* 08CA14 802D1A14 3C0B8033 */  lui   $t3, %hi(D_80330398) # $t3, 0x8033
/* 08CA18 802D1A18 856B0398 */  lh    $t3, %lo(D_80330398)($t3)
/* 08CA1C 802D1A1C 3C018033 */  lui   $at, %hi(D_80330398) # $at, 0x8033
/* 08CA20 802D1A20 256C0400 */  addiu $t4, $t3, 0x400
/* 08CA24 802D1A24 A42C0398 */  sh    $t4, %lo(D_80330398)($at)
.L802D1A28:
/* 08CA28 802D1A28 10000003 */  b     .L802D1A38
/* 08CA2C 802D1A2C 00001025 */   move  $v0, $zero
/* 08CA30 802D1A30 10000001 */  b     .L802D1A38
/* 08CA34 802D1A34 00000000 */   nop   
.L802D1A38:
/* 08CA38 802D1A38 03E00008 */  jr    $ra
/* 08CA3C 802D1A3C 00000000 */   nop   

glabel Geo18_802D2520
/* 08CA40 802D1A40 27BDFF80 */  addiu $sp, $sp, -0x80
/* 08CA44 802D1A44 AFBF0034 */  sw    $ra, 0x34($sp)
/* 08CA48 802D1A48 AFA40080 */  sw    $a0, 0x80($sp)
/* 08CA4C 802D1A4C AFA50084 */  sw    $a1, 0x84($sp)
/* 08CA50 802D1A50 AFA60088 */  sw    $a2, 0x88($sp)
/* 08CA54 802D1A54 8FAE0084 */  lw    $t6, 0x84($sp)
/* 08CA58 802D1A58 AFAE0068 */  sw    $t6, 0x68($sp)
/* 08CA5C 802D1A5C 3C040702 */  lui   $a0, %hi(D_07019248) # $a0, 0x702
/* 08CA60 802D1A60 0C09DE68 */  jal   SegmentedToVirtual
/* 08CA64 802D1A64 24849248 */   addiu $a0, %lo(D_07019248) # addiu $a0, $a0, -0x6db8
/* 08CA68 802D1A68 AFA20064 */  sw    $v0, 0x64($sp)
/* 08CA6C 802D1A6C AFA00060 */  sw    $zero, 0x60($sp)
/* 08CA70 802D1A70 AFA0005C */  sw    $zero, 0x5c($sp)
/* 08CA74 802D1A74 8FAF0080 */  lw    $t7, 0x80($sp)
/* 08CA78 802D1A78 24010001 */  li    $at, 1
/* 08CA7C 802D1A7C 15E100D3 */  bne   $t7, $at, .L802D1DCC
/* 08CA80 802D1A80 00000000 */   nop   
/* 08CA84 802D1A84 0C09E25F */  jal   func_8027897C
/* 08CA88 802D1A88 24040150 */   li    $a0, 336
/* 08CA8C 802D1A8C AFA2006C */  sw    $v0, 0x6c($sp)
/* 08CA90 802D1A90 0C09E25F */  jal   func_8027897C
/* 08CA94 802D1A94 24040038 */   li    $a0, 56
/* 08CA98 802D1A98 AFA20060 */  sw    $v0, 0x60($sp)
/* 08CA9C 802D1A9C 8FB80060 */  lw    $t8, 0x60($sp)
/* 08CAA0 802D1AA0 AFB8005C */  sw    $t8, 0x5c($sp)
/* 08CAA4 802D1AA4 8FB9006C */  lw    $t9, 0x6c($sp)
/* 08CAA8 802D1AA8 13200004 */  beqz  $t9, .L802D1ABC
/* 08CAAC 802D1AAC 00000000 */   nop   
/* 08CAB0 802D1AB0 8FA80060 */  lw    $t0, 0x60($sp)
/* 08CAB4 802D1AB4 15000003 */  bnez  $t0, .L802D1AC4
/* 08CAB8 802D1AB8 00000000 */   nop   
.L802D1ABC:
/* 08CABC 802D1ABC 100000C7 */  b     .L802D1DDC
/* 08CAC0 802D1AC0 00001025 */   move  $v0, $zero
.L802D1AC4:
/* 08CAC4 802D1AC4 8FA90068 */  lw    $t1, 0x68($sp)
/* 08CAC8 802D1AC8 852A0002 */  lh    $t2, 2($t1)
/* 08CACC 802D1ACC 314B00FF */  andi  $t3, $t2, 0xff
/* 08CAD0 802D1AD0 356C0100 */  ori   $t4, $t3, 0x100
/* 08CAD4 802D1AD4 A52C0002 */  sh    $t4, 2($t1)
/* 08CAD8 802D1AD8 A7A0007E */  sh    $zero, 0x7e($sp)
.L802D1ADC:
/* 08CADC 802D1ADC 87AD007E */  lh    $t5, 0x7e($sp)
/* 08CAE0 802D1AE0 24010003 */  li    $at, 3
/* 08CAE4 802D1AE4 01A1001A */  div   $zero, $t5, $at
/* 08CAE8 802D1AE8 00007012 */  mflo  $t6
/* 08CAEC 802D1AEC A7AE007C */  sh    $t6, 0x7c($sp)
/* 08CAF0 802D1AF0 00000000 */  nop   
/* 08CAF4 802D1AF4 87AF007E */  lh    $t7, 0x7e($sp)
/* 08CAF8 802D1AF8 24010003 */  li    $at, 3
/* 08CAFC 802D1AFC 01E1001A */  div   $zero, $t7, $at
/* 08CB00 802D1B00 0000C010 */  mfhi  $t8
/* 08CB04 802D1B04 A7B8007A */  sh    $t8, 0x7a($sp)
/* 08CB08 802D1B08 00000000 */  nop   
/* 08CB0C 802D1B0C 87A8007E */  lh    $t0, 0x7e($sp)
/* 08CB10 802D1B10 8FB90064 */  lw    $t9, 0x64($sp)
/* 08CB14 802D1B14 00085080 */  sll   $t2, $t0, 2
/* 08CB18 802D1B18 000A5840 */  sll   $t3, $t2, 1
/* 08CB1C 802D1B1C 032B6021 */  addu  $t4, $t9, $t3
/* 08CB20 802D1B20 85890000 */  lh    $t1, ($t4)
/* 08CB24 802D1B24 A7A90078 */  sh    $t1, 0x78($sp)
/* 08CB28 802D1B28 87AE007C */  lh    $t6, 0x7c($sp)
/* 08CB2C 802D1B2C 3C0D8033 */  lui   $t5, %hi(D_80330398) # $t5, 0x8033
/* 08CB30 802D1B30 85AD0398 */  lh    $t5, %lo(D_80330398)($t5)
/* 08CB34 802D1B34 87A8007A */  lh    $t0, 0x7a($sp)
/* 08CB38 802D1B38 000E7B00 */  sll   $t7, $t6, 0xc
/* 08CB3C 802D1B3C 01AFC021 */  addu  $t8, $t5, $t7
/* 08CB40 802D1B40 00085380 */  sll   $t2, $t0, 0xe
/* 08CB44 802D1B44 030AC821 */  addu  $t9, $t8, $t2
/* 08CB48 802D1B48 332BFFFF */  andi  $t3, $t9, 0xffff
/* 08CB4C 802D1B4C 000B6103 */  sra   $t4, $t3, 4
/* 08CB50 802D1B50 000C4880 */  sll   $t1, $t4, 2
/* 08CB54 802D1B54 3C018038 */  li    $at, 0x80380000
/* 08CB58 802D1B58 00290821 */  addu  $at, $at, $t1
/* 08CB5C 802D1B5C C4246000 */  lwc1  $f4, 0x6000($at)
/* 08CB60 802D1B60 3C014034 */  li    $at, 0x40340000 # 2.812500
/* 08CB64 802D1B64 44814800 */  mtc1  $at, $f9
/* 08CB68 802D1B68 44804000 */  mtc1  $zero, $f8
/* 08CB6C 802D1B6C 460021A1 */  cvt.d.s $f6, $f4
/* 08CB70 802D1B70 46283282 */  mul.d $f10, $f6, $f8
/* 08CB74 802D1B74 0C0B45F9 */  jal   func_802D17E4
/* 08CB78 802D1B78 46205320 */   cvt.s.d $f12, $f10
/* 08CB7C 802D1B7C A7A20076 */  sh    $v0, 0x76($sp)
/* 08CB80 802D1B80 87AD007E */  lh    $t5, 0x7e($sp)
/* 08CB84 802D1B84 8FAE0064 */  lw    $t6, 0x64($sp)
/* 08CB88 802D1B88 000D7880 */  sll   $t7, $t5, 2
/* 08CB8C 802D1B8C 000F4040 */  sll   $t0, $t7, 1
/* 08CB90 802D1B90 01C8C021 */  addu  $t8, $t6, $t0
/* 08CB94 802D1B94 870A0002 */  lh    $t2, 2($t8)
/* 08CB98 802D1B98 A7AA0074 */  sh    $t2, 0x74($sp)
/* 08CB9C 802D1B9C 87AB007E */  lh    $t3, 0x7e($sp)
/* 08CBA0 802D1BA0 8FB90064 */  lw    $t9, 0x64($sp)
/* 08CBA4 802D1BA4 000B6080 */  sll   $t4, $t3, 2
/* 08CBA8 802D1BA8 000C4840 */  sll   $t1, $t4, 1
/* 08CBAC 802D1BAC 03296821 */  addu  $t5, $t9, $t1
/* 08CBB0 802D1BB0 85AF0004 */  lh    $t7, 4($t5)
/* 08CBB4 802D1BB4 A7AF0072 */  sh    $t7, 0x72($sp)
/* 08CBB8 802D1BB8 87A8007E */  lh    $t0, 0x7e($sp)
/* 08CBBC 802D1BBC 8FAE0064 */  lw    $t6, 0x64($sp)
/* 08CBC0 802D1BC0 0008C080 */  sll   $t8, $t0, 2
/* 08CBC4 802D1BC4 00185040 */  sll   $t2, $t8, 1
/* 08CBC8 802D1BC8 01CA5821 */  addu  $t3, $t6, $t2
/* 08CBCC 802D1BCC 856C0006 */  lh    $t4, 6($t3)
/* 08CBD0 802D1BD0 A7AC0070 */  sh    $t4, 0x70($sp)
/* 08CBD4 802D1BD4 87B90074 */  lh    $t9, 0x74($sp)
/* 08CBD8 802D1BD8 87A90072 */  lh    $t1, 0x72($sp)
/* 08CBDC 802D1BDC 87AD0070 */  lh    $t5, 0x70($sp)
/* 08CBE0 802D1BE0 240F007F */  li    $t7, 127
/* 08CBE4 802D1BE4 240800FF */  li    $t0, 255
/* 08CBE8 802D1BE8 AFA80028 */  sw    $t0, 0x28($sp)
/* 08CBEC 802D1BEC AFAF0020 */  sw    $t7, 0x20($sp)
/* 08CBF0 802D1BF0 8FA4006C */  lw    $a0, 0x6c($sp)
/* 08CBF4 802D1BF4 87A5007E */  lh    $a1, 0x7e($sp)
/* 08CBF8 802D1BF8 87A60078 */  lh    $a2, 0x78($sp)
/* 08CBFC 802D1BFC 87A70076 */  lh    $a3, 0x76($sp)
/* 08CC00 802D1C00 AFA0001C */  sw    $zero, 0x1c($sp)
/* 08CC04 802D1C04 AFA00024 */  sw    $zero, 0x24($sp)
/* 08CC08 802D1C08 AFB90010 */  sw    $t9, 0x10($sp)
/* 08CC0C 802D1C0C AFA90014 */  sw    $t1, 0x14($sp)
/* 08CC10 802D1C10 0C0B45CC */  jal   func_802D1730
/* 08CC14 802D1C14 AFAD0018 */   sw    $t5, 0x18($sp)
/* 08CC18 802D1C18 87B8007E */  lh    $t8, 0x7e($sp)
/* 08CC1C 802D1C1C 270E0001 */  addiu $t6, $t8, 1
/* 08CC20 802D1C20 000E5400 */  sll   $t2, $t6, 0x10
/* 08CC24 802D1C24 000A5C03 */  sra   $t3, $t2, 0x10
/* 08CC28 802D1C28 29610015 */  slti  $at, $t3, 0x15
/* 08CC2C 802D1C2C 1420FFAB */  bnez  $at, .L802D1ADC
/* 08CC30 802D1C30 A7AE007E */   sh    $t6, 0x7e($sp)
/* 08CC34 802D1C34 8FAC005C */  lw    $t4, 0x5c($sp)
/* 08CC38 802D1C38 25990008 */  addiu $t9, $t4, 8
/* 08CC3C 802D1C3C AFB9005C */  sw    $t9, 0x5c($sp)
/* 08CC40 802D1C40 AFAC0054 */  sw    $t4, 0x54($sp)
/* 08CC44 802D1C44 8FAD0054 */  lw    $t5, 0x54($sp)
/* 08CC48 802D1C48 3C090600 */  lui   $t1, 0x600
/* 08CC4C 802D1C4C ADA90000 */  sw    $t1, ($t5)
/* 08CC50 802D1C50 8FA80054 */  lw    $t0, 0x54($sp)
/* 08CC54 802D1C54 3C0F0702 */  lui   $t7, %hi(D_070192F0) # $t7, 0x702
/* 08CC58 802D1C58 25EF92F0 */  addiu $t7, %lo(D_070192F0) # addiu $t7, $t7, -0x6d10
/* 08CC5C 802D1C5C AD0F0004 */  sw    $t7, 4($t0)
/* 08CC60 802D1C60 8FB8005C */  lw    $t8, 0x5c($sp)
/* 08CC64 802D1C64 270E0008 */  addiu $t6, $t8, 8
/* 08CC68 802D1C68 AFAE005C */  sw    $t6, 0x5c($sp)
/* 08CC6C 802D1C6C AFB80050 */  sw    $t8, 0x50($sp)
/* 08CC70 802D1C70 8FAB0050 */  lw    $t3, 0x50($sp)
/* 08CC74 802D1C74 3C0A04B0 */  lui   $t2, (0x04B000C0 >> 16) # lui $t2, 0x4b0
/* 08CC78 802D1C78 354A00C0 */  ori   $t2, (0x04B000C0 & 0xFFFF) # ori $t2, $t2, 0xc0
/* 08CC7C 802D1C7C AD6A0000 */  sw    $t2, ($t3)
/* 08CC80 802D1C80 8FAC006C */  lw    $t4, 0x6c($sp)
/* 08CC84 802D1C84 8FB90050 */  lw    $t9, 0x50($sp)
/* 08CC88 802D1C88 AF2C0004 */  sw    $t4, 4($t9)
/* 08CC8C 802D1C8C 8FA9005C */  lw    $t1, 0x5c($sp)
/* 08CC90 802D1C90 252D0008 */  addiu $t5, $t1, 8
/* 08CC94 802D1C94 AFAD005C */  sw    $t5, 0x5c($sp)
/* 08CC98 802D1C98 AFA9004C */  sw    $t1, 0x4c($sp)
/* 08CC9C 802D1C9C 8FA8004C */  lw    $t0, 0x4c($sp)
/* 08CCA0 802D1CA0 3C0F0600 */  lui   $t7, 0x600
/* 08CCA4 802D1CA4 AD0F0000 */  sw    $t7, ($t0)
/* 08CCA8 802D1CA8 8FAE004C */  lw    $t6, 0x4c($sp)
/* 08CCAC 802D1CAC 3C180702 */  lui   $t8, %hi(D_07019360) # $t8, 0x702
/* 08CCB0 802D1CB0 27189360 */  addiu $t8, %lo(D_07019360) # addiu $t8, $t8, -0x6ca0
/* 08CCB4 802D1CB4 ADD80004 */  sw    $t8, 4($t6)
/* 08CCB8 802D1CB8 8FAA005C */  lw    $t2, 0x5c($sp)
/* 08CCBC 802D1CBC 254B0008 */  addiu $t3, $t2, 8
/* 08CCC0 802D1CC0 AFAB005C */  sw    $t3, 0x5c($sp)
/* 08CCC4 802D1CC4 AFAA0048 */  sw    $t2, 0x48($sp)
/* 08CCC8 802D1CC8 8FB90048 */  lw    $t9, 0x48($sp)
/* 08CCCC 802D1CCC 3C0C04B0 */  lui   $t4, (0x04B000C0 >> 16) # lui $t4, 0x4b0
/* 08CCD0 802D1CD0 358C00C0 */  ori   $t4, (0x04B000C0 & 0xFFFF) # ori $t4, $t4, 0xc0
/* 08CCD4 802D1CD4 AF2C0000 */  sw    $t4, ($t9)
/* 08CCD8 802D1CD8 8FA9006C */  lw    $t1, 0x6c($sp)
/* 08CCDC 802D1CDC 8FAF0048 */  lw    $t7, 0x48($sp)
/* 08CCE0 802D1CE0 252D0090 */  addiu $t5, $t1, 0x90
/* 08CCE4 802D1CE4 ADED0004 */  sw    $t5, 4($t7)
/* 08CCE8 802D1CE8 8FA8005C */  lw    $t0, 0x5c($sp)
/* 08CCEC 802D1CEC 25180008 */  addiu $t8, $t0, 8
/* 08CCF0 802D1CF0 AFB8005C */  sw    $t8, 0x5c($sp)
/* 08CCF4 802D1CF4 AFA80044 */  sw    $t0, 0x44($sp)
/* 08CCF8 802D1CF8 8FAA0044 */  lw    $t2, 0x44($sp)
/* 08CCFC 802D1CFC 3C0E0600 */  lui   $t6, 0x600
/* 08CD00 802D1D00 AD4E0000 */  sw    $t6, ($t2)
/* 08CD04 802D1D04 8FAC0044 */  lw    $t4, 0x44($sp)
/* 08CD08 802D1D08 3C0B0702 */  lui   $t3, %hi(D_07019360) # $t3, 0x702
/* 08CD0C 802D1D0C 256B9360 */  addiu $t3, %lo(D_07019360) # addiu $t3, $t3, -0x6ca0
/* 08CD10 802D1D10 AD8B0004 */  sw    $t3, 4($t4)
/* 08CD14 802D1D14 8FB9005C */  lw    $t9, 0x5c($sp)
/* 08CD18 802D1D18 27290008 */  addiu $t1, $t9, 8
/* 08CD1C 802D1D1C AFA9005C */  sw    $t1, 0x5c($sp)
/* 08CD20 802D1D20 AFB90040 */  sw    $t9, 0x40($sp)
/* 08CD24 802D1D24 8FAF0040 */  lw    $t7, 0x40($sp)
/* 08CD28 802D1D28 3C0D0600 */  lui   $t5, 0x600
/* 08CD2C 802D1D2C ADED0000 */  sw    $t5, ($t7)
/* 08CD30 802D1D30 8FB80040 */  lw    $t8, 0x40($sp)
/* 08CD34 802D1D34 3C080702 */  lui   $t0, %hi(D_070193C8) # $t0, 0x702
/* 08CD38 802D1D38 250893C8 */  addiu $t0, %lo(D_070193C8) # addiu $t0, $t0, -0x6c38
/* 08CD3C 802D1D3C AF080004 */  sw    $t0, 4($t8)
/* 08CD40 802D1D40 8FAE005C */  lw    $t6, 0x5c($sp)
/* 08CD44 802D1D44 AFAE003C */  sw    $t6, 0x3c($sp)
/* 08CD48 802D1D48 8FAB003C */  lw    $t3, 0x3c($sp)
/* 08CD4C 802D1D4C 3C0AB800 */  lui   $t2, 0xb800
/* 08CD50 802D1D50 AD6A0000 */  sw    $t2, ($t3)
/* 08CD54 802D1D54 8FAC003C */  lw    $t4, 0x3c($sp)
/* 08CD58 802D1D58 AD800004 */  sw    $zero, 4($t4)
/* 08CD5C 802D1D5C 3C198033 */  lui   $t9, %hi(D_8032CFA0) # $t9, 0x8033
/* 08CD60 802D1D60 8F39CFA0 */  lw    $t9, %lo(D_8032CFA0)($t9)
/* 08CD64 802D1D64 AFB90058 */  sw    $t9, 0x58($sp)
/* 08CD68 802D1D68 3C098036 */  li    $t1, 0x80360000 # 0.000000
/* 08CD6C 802D1D6C 8D29FDE8 */  lw    $t1, %lo(gMarioObject)($t1)
/* 08CD70 802D1D70 8FAF0058 */  lw    $t7, 0x58($sp)
/* 08CD74 802D1D74 8D2D0214 */  lw    $t5, 0x214($t1)
/* 08CD78 802D1D78 15AF0005 */  bne   $t5, $t7, .L802D1D90
/* 08CD7C 802D1D7C 00000000 */   nop   
/* 08CD80 802D1D80 24080002 */  li    $t0, 2
/* 08CD84 802D1D84 3C018036 */  li    $at, 0x80360000
/* 08CD88 802D1D88 10000010 */  b     .L802D1DCC
/* 08CD8C 802D1D8C A028FF80 */   sb    $t0, %lo(D_8035FF80)($at)
.L802D1D90:
/* 08CD90 802D1D90 8FB80058 */  lw    $t8, 0x58($sp)
/* 08CD94 802D1D94 44802800 */  mtc1  $zero, $f5
/* 08CD98 802D1D98 44802000 */  mtc1  $zero, $f4
/* 08CD9C 802D1D9C C71000B8 */  lwc1  $f16, 0xb8($t8)
/* 08CDA0 802D1DA0 460084A1 */  cvt.d.s $f18, $f16
/* 08CDA4 802D1DA4 46249032 */  c.eq.d $f18, $f4
/* 08CDA8 802D1DA8 00000000 */  nop   
/* 08CDAC 802D1DAC 45010005 */  bc1t  .L802D1DC4
/* 08CDB0 802D1DB0 00000000 */   nop   
/* 08CDB4 802D1DB4 240E0001 */  li    $t6, 1
/* 08CDB8 802D1DB8 3C018036 */  lui   $at, %hi(D_8035FF80) # $at, 0x8036
/* 08CDBC 802D1DBC 10000003 */  b     .L802D1DCC
/* 08CDC0 802D1DC0 A02EFF80 */   sb    $t6, %lo(D_8035FF80)($at)
.L802D1DC4:
/* 08CDC4 802D1DC4 3C018036 */  lui   $at, %hi(D_8035FF80) # $at, 0x8036
/* 08CDC8 802D1DC8 A020FF80 */  sb    $zero, %lo(D_8035FF80)($at)
.L802D1DCC:
/* 08CDCC 802D1DCC 10000003 */  b     .L802D1DDC
/* 08CDD0 802D1DD0 8FA20060 */   lw    $v0, 0x60($sp)
/* 08CDD4 802D1DD4 10000001 */  b     .L802D1DDC
/* 08CDD8 802D1DD8 00000000 */   nop   
.L802D1DDC:
/* 08CDDC 802D1DDC 8FBF0034 */  lw    $ra, 0x34($sp)
/* 08CDE0 802D1DE0 27BD0080 */  addiu $sp, $sp, 0x80
/* 08CDE4 802D1DE4 03E00008 */  jr    $ra
/* 08CDE8 802D1DE8 00000000 */   nop   

glabel Geo18_802D28CC
/* 08CDEC 802D1DEC 27BDFFD0 */  addiu $sp, $sp, -0x30
/* 08CDF0 802D1DF0 AFBF0014 */  sw    $ra, 0x14($sp)
/* 08CDF4 802D1DF4 AFA40030 */  sw    $a0, 0x30($sp)
/* 08CDF8 802D1DF8 AFA50034 */  sw    $a1, 0x34($sp)
/* 08CDFC 802D1DFC AFA60038 */  sw    $a2, 0x38($sp)
/* 08CE00 802D1E00 8FAE0034 */  lw    $t6, 0x34($sp)
/* 08CE04 802D1E04 AFAE002C */  sw    $t6, 0x2c($sp)
/* 08CE08 802D1E08 AFA00028 */  sw    $zero, 0x28($sp)
/* 08CE0C 802D1E0C AFA00024 */  sw    $zero, 0x24($sp)
/* 08CE10 802D1E10 8FAF0030 */  lw    $t7, 0x30($sp)
/* 08CE14 802D1E14 24010001 */  li    $at, 1
/* 08CE18 802D1E18 15E10028 */  bne   $t7, $at, .L802D1EBC
/* 08CE1C 802D1E1C 00000000 */   nop   
/* 08CE20 802D1E20 0C09E25F */  jal   func_8027897C
/* 08CE24 802D1E24 24040018 */   li    $a0, 24
/* 08CE28 802D1E28 AFA20028 */  sw    $v0, 0x28($sp)
/* 08CE2C 802D1E2C 8FB80028 */  lw    $t8, 0x28($sp)
/* 08CE30 802D1E30 AFB80024 */  sw    $t8, 0x24($sp)
/* 08CE34 802D1E34 8FB9002C */  lw    $t9, 0x2c($sp)
/* 08CE38 802D1E38 87280002 */  lh    $t0, 2($t9)
/* 08CE3C 802D1E3C 310900FF */  andi  $t1, $t0, 0xff
/* 08CE40 802D1E40 352A0100 */  ori   $t2, $t1, 0x100
/* 08CE44 802D1E44 A72A0002 */  sh    $t2, 2($t9)
/* 08CE48 802D1E48 8FAB0024 */  lw    $t3, 0x24($sp)
/* 08CE4C 802D1E4C 256C0008 */  addiu $t4, $t3, 8
/* 08CE50 802D1E50 AFAC0024 */  sw    $t4, 0x24($sp)
/* 08CE54 802D1E54 AFAB0020 */  sw    $t3, 0x20($sp)
/* 08CE58 802D1E58 8FAE0020 */  lw    $t6, 0x20($sp)
/* 08CE5C 802D1E5C 3C0D0600 */  lui   $t5, 0x600
/* 08CE60 802D1E60 ADCD0000 */  sw    $t5, ($t6)
/* 08CE64 802D1E64 8FB80020 */  lw    $t8, 0x20($sp)
/* 08CE68 802D1E68 3C0F0201 */  lui   $t7, %hi(D_02014660) # $t7, 0x201
/* 08CE6C 802D1E6C 25EF4660 */  addiu $t7, %lo(D_02014660) # addiu $t7, $t7, 0x4660
/* 08CE70 802D1E70 AF0F0004 */  sw    $t7, 4($t8)
/* 08CE74 802D1E74 8FA80024 */  lw    $t0, 0x24($sp)
/* 08CE78 802D1E78 25090008 */  addiu $t1, $t0, 8
/* 08CE7C 802D1E7C AFA90024 */  sw    $t1, 0x24($sp)
/* 08CE80 802D1E80 AFA8001C */  sw    $t0, 0x1c($sp)
/* 08CE84 802D1E84 8FB9001C */  lw    $t9, 0x1c($sp)
/* 08CE88 802D1E88 3C0A0600 */  lui   $t2, 0x600
/* 08CE8C 802D1E8C AF2A0000 */  sw    $t2, ($t9)
/* 08CE90 802D1E90 8FAC001C */  lw    $t4, 0x1c($sp)
/* 08CE94 802D1E94 3C0B0702 */  lui   $t3, %hi(D_07026400) # $t3, 0x702
/* 08CE98 802D1E98 256B6400 */  addiu $t3, %lo(D_07026400) # addiu $t3, $t3, 0x6400
/* 08CE9C 802D1E9C AD8B0004 */  sw    $t3, 4($t4)
/* 08CEA0 802D1EA0 8FAD0024 */  lw    $t5, 0x24($sp)
/* 08CEA4 802D1EA4 AFAD0018 */  sw    $t5, 0x18($sp)
/* 08CEA8 802D1EA8 8FAF0018 */  lw    $t7, 0x18($sp)
/* 08CEAC 802D1EAC 3C0EB800 */  lui   $t6, 0xb800
/* 08CEB0 802D1EB0 ADEE0000 */  sw    $t6, ($t7)
/* 08CEB4 802D1EB4 8FB80018 */  lw    $t8, 0x18($sp)
/* 08CEB8 802D1EB8 AF000004 */  sw    $zero, 4($t8)
.L802D1EBC:
/* 08CEBC 802D1EBC 10000003 */  b     .L802D1ECC
/* 08CEC0 802D1EC0 8FA20028 */   lw    $v0, 0x28($sp)
/* 08CEC4 802D1EC4 10000001 */  b     .L802D1ECC
/* 08CEC8 802D1EC8 00000000 */   nop   
.L802D1ECC:
/* 08CECC 802D1ECC 8FBF0014 */  lw    $ra, 0x14($sp)
/* 08CED0 802D1ED0 27BD0030 */  addiu $sp, $sp, 0x30
/* 08CED4 802D1ED4 03E00008 */  jr    $ra
/* 08CED8 802D1ED8 00000000 */   nop   

/* 08CEDC 802D1EDC 00000000 */  nop   
