# generated by n64split
.section .rodata
.include "macros.inc"
.include "ultra64/gbi.inc"

initbinid
actor bowser_flame
actor impact_ring
actor yellow_sphere
actor bowser
actor bomb
actor impact_smoke
