# generated by n64split
.section .rodata
.include "macros.inc"
.include "geo_commands.inc"
.include "ultra64/gbi.inc"

initbinid
actor bubba
actor wiggler
actor lakitu_enemy
actor spiny_egg
actor spiny
