# generated by n64split
.section .rodata
.include "macros.inc"
.include "ultra64/gbi.inc"
.include "special_presets.inc"

bowser_3_seg7_texture_07000000: # 0x07000000 - 0x07000800
.incbin "levels/bowser_3/0.rgba16"

bowser_3_seg7_texture_07000800: # 0x07000800 - 0x07001000
.incbin "levels/bowser_3/1.rgba16"

bowser_3_seg7_texture_07001000: # 0x07001000 - 0x07002000
.incbin "levels/bowser_3/2.rgba16"

bowser_3_seg7_light_07002000: # 0x07002000 - 0x07002008
.byte 0x22, 0x22, 0x22, 0x00, 0x22, 0x22, 0x22, 0x00

bowser_3_seg7_light_07002008: # 0x07002008 - 0x07002018
.byte 0x89, 0x89, 0x8A, 0x00, 0x89, 0x89, 0x8A, 0x00
.byte 0x28, 0x28, 0x28, 0x00, 0x00, 0x00, 0x00, 0x00

bowser_3_seg7_light_07002018: # 0x07002018 - 0x07002020
.byte 0x3F, 0x3F, 0x3F, 0x00, 0x3F, 0x3F, 0x3F, 0x00

bowser_3_seg7_light_07002020: # 0x07002020 - 0x07002030
.byte 0xFF, 0xFF, 0xFF, 0x00, 0xFF, 0xFF, 0xFF, 0x00
.byte 0x28, 0x28, 0x28, 0x00, 0x00, 0x00, 0x00, 0x00

bowser_3_seg7_vertex_07002030: # 0x07002030 - 0x07002090
vertex  -1945,  -1340,  -2661,   5282,    786,  0xC4, 0x99, 0xD7, 0xFF
vertex  -2364,  -1852,   -787,   3412,   1202,  0xC4, 0x99, 0xD7, 0xFF
vertex  -3071,  -1340,  -1023,   3648,   1908,  0xC4, 0x99, 0xD7, 0xFF
vertex  -1945,  -1340,  -2661,   5282,    786,  0xD6, 0x90, 0xD8, 0xFF
vertex   -787,  -2364,  -1024,   3648,   -370,  0xD6, 0x90, 0xD8, 0xFF
vertex  -2364,  -1852,   -787,   3412,   1202,  0xD6, 0x90, 0xD8, 0xFF

bowser_3_seg7_vertex_07002090: # 0x07002090 - 0x070020D0
vertex  -3071,    307,  -1023,  -1052,  -1872,  0x00, 0x7F, 0x00, 0xFF
vertex   -787,    307,  -1024,    466,  -1872,  0x00, 0x7F, 0x00, 0xFF
vertex  -1945,    307,  -2661,   -302,  -2962,  0x00, 0x7F, 0x00, 0xFF
vertex  -2364,    307,   -787,   -582,  -1714,  0x00, 0x7F, 0x00, 0xFF

bowser_3_seg7_vertex_070020D0: # 0x070020D0 - 0x070021D0
vertex  -1945,  -1340,  -2661,    990,   2012,  0x67, 0x00, 0xB7, 0xFF
vertex  -1945,    307,  -2661,    990,      0,  0x67, 0x00, 0xB7, 0xFF
vertex   -787,  -2364,  -1024,  -1010,   2012,  0x67, 0x00, 0xB7, 0xFF
vertex  -2364,    307,   -787,    494,      0,  0xD8, 0x00, 0x78, 0xFF
vertex  -3071,    307,  -1023,    990,      0,  0xD8, 0x00, 0x78, 0xFF
vertex  -3071,  -1340,  -1023,    990,   2012,  0xD8, 0x00, 0x78, 0xFF
vertex  -2364,  -1852,   -787,    494,   2012,  0xD8, 0x00, 0x78, 0xFF
vertex   -787,  -2364,  -1024,   -504,   2012,  0x12, 0x00, 0x7D, 0xFF
vertex   -787,    307,  -1024,   -506,      0,  0x12, 0x00, 0x7D, 0xFF
vertex  -2364,  -1852,   -787,   1048,   2012,  0x12, 0x00, 0x7D, 0xFF
vertex  -2364,    307,   -787,   1046,      0,  0x12, 0x00, 0x7D, 0xFF
vertex  -3071,  -1340,  -1023,  14512,   1816,  0x98, 0x00, 0xB9, 0xFF
vertex  -3071,    307,  -1023,  14512,    172,  0x98, 0x00, 0xB9, 0xFF
vertex  -1945,  -1340,  -2661,  13006,   1816,  0x98, 0x00, 0xB9, 0xFF
vertex  -1945,    307,  -2661,  13006,    172,  0x98, 0x00, 0xB9, 0xFF
vertex   -787,    307,  -1024,  -1010,      0,  0x67, 0x00, 0xB7, 0xFF

bowser_3_seg7_dl_070021D0: # 0x070021D0 - 0x07002240
gsDPSetTextureImage G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, bowser_3_seg7_texture_07000800
gsDPLoadSync
gsDPLoadBlock 7, 0, 0, 0x3FF, 0x100
gsSPLight bowser_3_seg7_light_07002008, 1
gsSPLight bowser_3_seg7_light_07002000, 2
gsSPVertex bowser_3_seg7_vertex_07002030, 6, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  3,  4,  5, 0x0
gsSPLight bowser_3_seg7_light_07002020, 1
gsSPLight bowser_3_seg7_light_07002018, 2
gsSPVertex bowser_3_seg7_vertex_07002090, 4, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  0,  3,  1, 0x0
gsSPEndDisplayList

bowser_3_seg7_dl_07002240: # 0x07002240 - 0x070022A8
gsDPSetTextureImage G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, bowser_3_seg7_texture_07001000
gsDPLoadSync
gsDPLoadBlock 7, 0, 0, 0x7FF, 0x100
gsSPVertex bowser_3_seg7_vertex_070020D0, 16, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  3,  4,  5, 0x0
gsSP1Triangle  3,  5,  6, 0x0
gsSP1Triangle  7,  8,  9, 0x0
gsSP1Triangle  8, 10,  9, 0x0
gsSP1Triangle 11, 12, 13, 0x0
gsSP1Triangle 12, 14, 13, 0x0
gsSP1Triangle  1, 15,  2, 0x0
gsSPEndDisplayList

glabel bowser_3_seg7_dl_070022A8 # 0x070022A8 - 0x07002338
gsDPPipeSync
gsDPSetCombineMode G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsSPClearGeometryMode G_SHADING_SMOOTH
gsDPSetTile G_IM_FMT_RGBA, G_IM_SIZ_16b, 0, 0, G_TX_LOADTILE, 0, G_TX_WRAP | G_TX_NOMIRROR, G_TX_NOMASK, G_TX_NOLOD, G_TX_WRAP | G_TX_NOMIRROR, G_TX_NOMASK, G_TX_NOLOD
gsSPTexture -1, -1, 0, 0, 1
gsDPTileSync
gsDPSetTile G_IM_FMT_RGBA, G_IM_SIZ_16b, 8, 0, G_TX_RENDERTILE, 0, G_TX_WRAP | G_TX_NOMIRROR, 5, G_TX_NOLOD, G_TX_WRAP | G_TX_NOMIRROR, 5, G_TX_NOLOD
gsDPSetTileSize 0, 0, 0, 124, 124
gsSPDisplayList bowser_3_seg7_dl_070021D0
gsDPTileSync
gsDPSetTile G_IM_FMT_RGBA, G_IM_SIZ_16b, 8, 0, G_TX_RENDERTILE, 0, G_TX_WRAP | G_TX_NOMIRROR, 6, G_TX_NOLOD, G_TX_WRAP | G_TX_NOMIRROR, 5, G_TX_NOLOD
gsDPSetTileSize 0, 0, 0, 124, 252
gsSPDisplayList bowser_3_seg7_dl_07002240
gsSPTexture -1, -1, 0, 0, 0
gsDPPipeSync
gsDPSetCombineMode G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsSPSetGeometryMode G_SHADING_SMOOTH
gsSPEndDisplayList

bowser_3_seg7_light_07002338: # 0x07002338 - 0x07002340
.byte 0x22, 0x22, 0x22, 0x00, 0x22, 0x22, 0x22, 0x00

bowser_3_seg7_light_07002340: # 0x07002340 - 0x07002350
.byte 0x89, 0x89, 0x8A, 0x00, 0x89, 0x89, 0x8A, 0x00
.byte 0x28, 0x28, 0x28, 0x00, 0x00, 0x00, 0x00, 0x00

bowser_3_seg7_light_07002350: # 0x07002350 - 0x07002358
.byte 0x3F, 0x3F, 0x3F, 0x00, 0x3F, 0x3F, 0x3F, 0x00

bowser_3_seg7_light_07002358: # 0x07002358 - 0x07002368
.byte 0xFF, 0xFF, 0xFF, 0x00, 0xFF, 0xFF, 0xFF, 0x00
.byte 0x28, 0x28, 0x28, 0x00, 0x00, 0x00, 0x00, 0x00

bowser_3_seg7_vertex_07002368: # 0x07002368 - 0x070023C8
vertex  -2364,  -1852,   -787,   3412,   1202,  0xB6, 0x9A, 0x00, 0xFF
vertex  -3071,  -1340,   1024,   1604,   1908,  0xB6, 0x9A, 0x00, 0xFF
vertex  -3071,  -1340,  -1023,   3648,   1908,  0xB6, 0x9A, 0x00, 0xFF
vertex  -2364,  -1852,   -787,   3412,   1202,  0xC7, 0x90, 0x09, 0xFF
vertex  -1182,  -2364,    394,   2232,     24,  0xC7, 0x90, 0x09, 0xFF
vertex  -3071,  -1340,   1024,   1604,   1908,  0xC7, 0x90, 0x09, 0xFF

bowser_3_seg7_vertex_070023C8: # 0x070023C8 - 0x07002408
vertex  -3071,    307,   1024,  -1052,   -508,  0x00, 0x7F, 0x00, 0xFF
vertex  -1182,    307,    394,    204,   -928,  0x00, 0x7F, 0x00, 0xFF
vertex  -2364,    307,   -787,   -582,  -1714,  0x00, 0x7F, 0x00, 0xFF
vertex  -3071,    307,  -1023,  -1052,  -1872,  0x00, 0x7F, 0x00, 0xFF

bowser_3_seg7_vertex_07002408: # 0x07002408 - 0x07002508
vertex  -1182,  -2364,    394,   -996,   2012,  0x28, 0x00, 0x78, 0xFF
vertex  -3071,    307,   1024,    990,      0,  0x28, 0x00, 0x78, 0xFF
vertex  -3071,  -1340,   1024,    990,   2012,  0x28, 0x00, 0x78, 0xFF
vertex  -3071,  -1340,   1024,  16084,   1816,  0x81, 0x00, 0x00, 0xFF
vertex  -3071,    307,  -1023,  14512,    172,  0x81, 0x00, 0x00, 0xFF
vertex  -3071,  -1340,  -1023,  14512,   1816,  0x81, 0x00, 0x00, 0xFF
vertex  -3071,    307,   1024,  16084,    172,  0x81, 0x00, 0x00, 0xFF
vertex  -3071,  -1340,  -1023,    990,   2012,  0x28, 0x00, 0x88, 0xFF
vertex  -3071,    307,  -1023,    990,      0,  0x28, 0x00, 0x88, 0xFF
vertex  -2364,    307,   -787,    246,      0,  0x28, 0x00, 0x88, 0xFF
vertex  -2364,  -1852,   -787,    246,   2012,  0x28, 0x00, 0x88, 0xFF
vertex  -2364,    307,   -787,   -678,      0,  0x59, 0x00, 0xA7, 0xFF
vertex  -1182,  -2364,    394,    990,   2012,  0x59, 0x00, 0xA7, 0xFF
vertex  -2364,  -1852,   -787,   -678,   2012,  0x59, 0x00, 0xA7, 0xFF
vertex  -1182,    307,    394,    990,      0,  0x59, 0x00, 0xA7, 0xFF
vertex  -1182,    307,    394,   -996,      0,  0x28, 0x00, 0x78, 0xFF

bowser_3_seg7_dl_07002508: # 0x07002508 - 0x07002578
gsDPSetTextureImage G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, bowser_3_seg7_texture_07000800
gsDPLoadSync
gsDPLoadBlock 7, 0, 0, 0x3FF, 0x100
gsSPLight bowser_3_seg7_light_07002340, 1
gsSPLight bowser_3_seg7_light_07002338, 2
gsSPVertex bowser_3_seg7_vertex_07002368, 6, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  3,  4,  5, 0x0
gsSPLight bowser_3_seg7_light_07002358, 1
gsSPLight bowser_3_seg7_light_07002350, 2
gsSPVertex bowser_3_seg7_vertex_070023C8, 4, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  0,  2,  3, 0x0
gsSPEndDisplayList

bowser_3_seg7_dl_07002578: # 0x07002578 - 0x070025E0
gsDPSetTextureImage G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, bowser_3_seg7_texture_07001000
gsDPLoadSync
gsDPLoadBlock 7, 0, 0, 0x7FF, 0x100
gsSPVertex bowser_3_seg7_vertex_07002408, 16, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  3,  4,  5, 0x0
gsSP1Triangle  3,  6,  4, 0x0
gsSP1Triangle  7,  8,  9, 0x0
gsSP1Triangle  7,  9, 10, 0x0
gsSP1Triangle 11, 12, 13, 0x0
gsSP1Triangle 11, 14, 12, 0x0
gsSP1Triangle  0, 15,  1, 0x0
gsSPEndDisplayList

glabel bowser_3_seg7_dl_070025E0 # 0x070025E0 - 0x07002670
gsDPPipeSync
gsDPSetCombineMode G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsSPClearGeometryMode G_SHADING_SMOOTH
gsDPSetTile G_IM_FMT_RGBA, G_IM_SIZ_16b, 0, 0, G_TX_LOADTILE, 0, G_TX_WRAP | G_TX_NOMIRROR, G_TX_NOMASK, G_TX_NOLOD, G_TX_WRAP | G_TX_NOMIRROR, G_TX_NOMASK, G_TX_NOLOD
gsSPTexture -1, -1, 0, 0, 1
gsDPTileSync
gsDPSetTile G_IM_FMT_RGBA, G_IM_SIZ_16b, 8, 0, G_TX_RENDERTILE, 0, G_TX_WRAP | G_TX_NOMIRROR, 5, G_TX_NOLOD, G_TX_WRAP | G_TX_NOMIRROR, 5, G_TX_NOLOD
gsDPSetTileSize 0, 0, 0, 124, 124
gsSPDisplayList bowser_3_seg7_dl_07002508
gsDPTileSync
gsDPSetTile G_IM_FMT_RGBA, G_IM_SIZ_16b, 8, 0, G_TX_RENDERTILE, 0, G_TX_WRAP | G_TX_NOMIRROR, 6, G_TX_NOLOD, G_TX_WRAP | G_TX_NOMIRROR, 5, G_TX_NOLOD
gsDPSetTileSize 0, 0, 0, 124, 252
gsSPDisplayList bowser_3_seg7_dl_07002578
gsSPTexture -1, -1, 0, 0, 0
gsDPPipeSync
gsDPSetCombineMode G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsSPSetGeometryMode G_SHADING_SMOOTH
gsSPEndDisplayList

bowser_3_seg7_light_07002670: # 0x07002670 - 0x07002678
.byte 0x22, 0x22, 0x22, 0x00, 0x22, 0x22, 0x22, 0x00

bowser_3_seg7_light_07002678: # 0x07002678 - 0x07002688
.byte 0x89, 0x89, 0x8A, 0x00, 0x89, 0x89, 0x8A, 0x00
.byte 0x28, 0x28, 0x28, 0x00, 0x00, 0x00, 0x00, 0x00

bowser_3_seg7_light_07002688: # 0x07002688 - 0x07002690
.byte 0x3F, 0x3F, 0x3F, 0x00, 0x3F, 0x3F, 0x3F, 0x00

bowser_3_seg7_light_07002690: # 0x07002690 - 0x070026A0
.byte 0xFF, 0xFF, 0xFF, 0x00, 0xFF, 0xFF, 0xFF, 0x00
.byte 0x28, 0x28, 0x28, 0x00, 0x00, 0x00, 0x00, 0x00

bowser_3_seg7_vertex_070026A0: # 0x070026A0 - 0x07002700
vertex  -3071,  -1340,   1024,   1604,   1908,  0xC4, 0x99, 0x29, 0xFF
vertex  -1497,  -1852,   2050,    580,    338,  0xC4, 0x99, 0x29, 0xFF
vertex  -1945,  -1340,   2662,      0,    786,  0xC4, 0x99, 0x29, 0xFF
vertex  -3071,  -1340,   1024,   1604,   1908,  0xCC, 0x90, 0x18, 0xFF
vertex  -1182,  -2364,    394,   2232,     24,  0xCC, 0x90, 0x18, 0xFF
vertex  -1497,  -1852,   2050,    580,    338,  0xCC, 0x90, 0x18, 0xFF

bowser_3_seg7_vertex_07002700: # 0x07002700 - 0x07002740
vertex  -3071,    307,   1024,  -1052,   -508,  0x00, 0x7F, 0x00, 0xFF
vertex  -1497,    307,   2050,     -6,    174,  0x00, 0x7F, 0x00, 0xFF
vertex  -1182,    307,    394,    204,   -928,  0x00, 0x7F, 0x00, 0xFF
vertex  -1945,    307,   2662,   -302,    582,  0x00, 0x7F, 0x00, 0xFF

bowser_3_seg7_vertex_07002740: # 0x07002740 - 0x07002840
vertex  -3071,  -1340,   1024,   -996,   2012,  0xD8, 0x00, 0x88, 0xFF
vertex  -1182,    307,    394,    990,      0,  0xD8, 0x00, 0x88, 0xFF
vertex  -1182,  -2364,    394,    990,   2012,  0xD8, 0x00, 0x88, 0xFF
vertex  -1945,  -1340,   2662,   2260,   1816,  0x98, 0x00, 0x47, 0xFF
vertex  -1945,    307,   2662,   2260,    172,  0x98, 0x00, 0x47, 0xFF
vertex  -3071,    307,   1024,    754,    172,  0x98, 0x00, 0x47, 0xFF
vertex  -3071,  -1340,   1024,    754,   1816,  0x98, 0x00, 0x47, 0xFF
vertex  -1182,  -2364,    394,   -690,   2012,  0x7C, 0x00, 0x17, 0xFF
vertex  -1497,    307,   2050,    990,      0,  0x7C, 0x00, 0x17, 0xFF
vertex  -1497,  -1852,   2050,    990,   2012,  0x7C, 0x00, 0x17, 0xFF
vertex  -1182,    307,    394,   -690,      0,  0x7C, 0x00, 0x17, 0xFF
vertex  -1497,    307,   2050,    234,      0,  0x66, 0x00, 0x4B, 0xFF
vertex  -1945,  -1340,   2662,    990,   2012,  0x66, 0x00, 0x4B, 0xFF
vertex  -1497,  -1852,   2050,    234,   2012,  0x66, 0x00, 0x4B, 0xFF
vertex  -1945,    307,   2662,    990,      0,  0x66, 0x00, 0x4B, 0xFF
vertex  -3071,    307,   1024,   -996,      0,  0xD8, 0x00, 0x88, 0xFF

bowser_3_seg7_dl_07002840: # 0x07002840 - 0x070028B0
gsDPSetTextureImage G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, bowser_3_seg7_texture_07000800
gsDPLoadSync
gsDPLoadBlock 7, 0, 0, 0x3FF, 0x100
gsSPLight bowser_3_seg7_light_07002678, 1
gsSPLight bowser_3_seg7_light_07002670, 2
gsSPVertex bowser_3_seg7_vertex_070026A0, 6, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  3,  4,  5, 0x0
gsSPLight bowser_3_seg7_light_07002690, 1
gsSPLight bowser_3_seg7_light_07002688, 2
gsSPVertex bowser_3_seg7_vertex_07002700, 4, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  0,  3,  1, 0x0
gsSPEndDisplayList

bowser_3_seg7_dl_070028B0: # 0x070028B0 - 0x07002918
gsDPSetTextureImage G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, bowser_3_seg7_texture_07001000
gsDPLoadSync
gsDPLoadBlock 7, 0, 0, 0x7FF, 0x100
gsSPVertex bowser_3_seg7_vertex_07002740, 16, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  3,  4,  5, 0x0
gsSP1Triangle  3,  5,  6, 0x0
gsSP1Triangle  7,  8,  9, 0x0
gsSP1Triangle  7, 10,  8, 0x0
gsSP1Triangle 11, 12, 13, 0x0
gsSP1Triangle 11, 14, 12, 0x0
gsSP1Triangle  0, 15,  1, 0x0
gsSPEndDisplayList

glabel bowser_3_seg7_dl_07002918 # 0x07002918 - 0x070029A8
gsDPPipeSync
gsDPSetCombineMode G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsSPClearGeometryMode G_SHADING_SMOOTH
gsDPSetTile G_IM_FMT_RGBA, G_IM_SIZ_16b, 0, 0, G_TX_LOADTILE, 0, G_TX_WRAP | G_TX_NOMIRROR, G_TX_NOMASK, G_TX_NOLOD, G_TX_WRAP | G_TX_NOMIRROR, G_TX_NOMASK, G_TX_NOLOD
gsSPTexture -1, -1, 0, 0, 1
gsDPTileSync
gsDPSetTile G_IM_FMT_RGBA, G_IM_SIZ_16b, 8, 0, G_TX_RENDERTILE, 0, G_TX_WRAP | G_TX_NOMIRROR, 5, G_TX_NOLOD, G_TX_WRAP | G_TX_NOMIRROR, 5, G_TX_NOLOD
gsDPSetTileSize 0, 0, 0, 124, 124
gsSPDisplayList bowser_3_seg7_dl_07002840
gsDPTileSync
gsDPSetTile G_IM_FMT_RGBA, G_IM_SIZ_16b, 8, 0, G_TX_RENDERTILE, 0, G_TX_WRAP | G_TX_NOMIRROR, 6, G_TX_NOLOD, G_TX_WRAP | G_TX_NOMIRROR, 5, G_TX_NOLOD
gsDPSetTileSize 0, 0, 0, 124, 252
gsSPDisplayList bowser_3_seg7_dl_070028B0
gsSPTexture -1, -1, 0, 0, 0
gsDPPipeSync
gsDPSetCombineMode G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsSPSetGeometryMode G_SHADING_SMOOTH
gsSPEndDisplayList

bowser_3_seg7_light_070029A8: # 0x070029A8 - 0x070029B0
.byte 0x22, 0x22, 0x22, 0x00, 0x22, 0x22, 0x22, 0x00

bowser_3_seg7_light_070029B0: # 0x070029B0 - 0x070029C0
.byte 0x89, 0x89, 0x8A, 0x00, 0x89, 0x89, 0x8A, 0x00
.byte 0x28, 0x28, 0x28, 0x00, 0x00, 0x00, 0x00, 0x00

bowser_3_seg7_light_070029C0: # 0x070029C0 - 0x070029C8
.byte 0x3F, 0x3F, 0x3F, 0x00, 0x3F, 0x3F, 0x3F, 0x00

bowser_3_seg7_light_070029C8: # 0x070029C8 - 0x070029D8
.byte 0xFF, 0xFF, 0xFF, 0x00, 0xFF, 0xFF, 0xFF, 0x00
.byte 0x28, 0x28, 0x28, 0x00, 0x00, 0x00, 0x00, 0x00

bowser_3_seg7_vertex_070029D8: # 0x070029D8 - 0x07002A38
vertex  -1497,  -1852,   2050,    580,    338,  0xF8, 0x90, 0x39, 0xFF
vertex      0,  -2364,   1262,   1366,  -1156,  0xF8, 0x90, 0x39, 0xFF
vertex      0,  -1340,   3277,   -644,  -1156,  0xF8, 0x90, 0x39, 0xFF
vertex  -1497,  -1852,   2050,    580,    338,  0xEA, 0x99, 0x46, 0xFF
vertex      0,  -1340,   3277,   -644,  -1156,  0xEA, 0x99, 0x46, 0xFF
vertex  -1945,  -1340,   2662,      0,    786,  0xEA, 0x99, 0x46, 0xFF

bowser_3_seg7_vertex_07002A38: # 0x07002A38 - 0x07002A78
vertex  -1945,    307,   2662,   -302,    582,  0x00, 0x7F, 0x00, 0xFF
vertex      0,    307,   3277,    990,    990,  0x00, 0x7F, 0x00, 0xFF
vertex      0,    307,   1262,    990,   -350,  0x00, 0x7F, 0x00, 0xFF
vertex  -1497,    307,   2050,     -6,    174,  0x00, 0x7F, 0x00, 0xFF

bowser_3_seg7_vertex_07002A78: # 0x07002A78 - 0x07002B78
vertex      0,  -2364,   1262,  -1020,   2012,  0x7F, 0x00, 0x00, 0xFF
vertex      0,    307,   1262,  -1020,      0,  0x7F, 0x00, 0x00, 0xFF
vertex      0,  -1340,   3277,    990,   2012,  0x7F, 0x00, 0x00, 0xFF
vertex      0,  -1340,   3277,   3800,   1816,  0xDA, 0x00, 0x79, 0xFF
vertex  -1945,    307,   2662,   2260,    172,  0xDA, 0x00, 0x79, 0xFF
vertex  -1945,  -1340,   2662,   2260,   1816,  0xDA, 0x00, 0x79, 0xFF
vertex      0,    307,   3277,   3800,    172,  0xDA, 0x00, 0x79, 0xFF
vertex  -1945,    307,   2662,    234,      0,  0x9A, 0x00, 0xB5, 0xFF
vertex  -1497,    307,   2050,    990,      0,  0x9A, 0x00, 0xB5, 0xFF
vertex  -1497,  -1852,   2050,    990,   2012,  0x9A, 0x00, 0xB5, 0xFF
vertex  -1945,  -1340,   2662,    234,   2012,  0x9A, 0x00, 0xB5, 0xFF
vertex  -1497,    307,   2050,   -698,      0,  0xC5, 0x00, 0x90, 0xFF
vertex      0,  -2364,   1262,    990,   2012,  0xC5, 0x00, 0x90, 0xFF
vertex  -1497,  -1852,   2050,   -698,   2012,  0xC5, 0x00, 0x90, 0xFF
vertex      0,    307,   1262,    990,      0,  0xC5, 0x00, 0x90, 0xFF
vertex      0,    307,   3277,    990,      0,  0x7F, 0x00, 0x00, 0xFF

bowser_3_seg7_dl_07002B78: # 0x07002B78 - 0x07002BE8
gsDPSetTextureImage G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, bowser_3_seg7_texture_07000800
gsDPLoadSync
gsDPLoadBlock 7, 0, 0, 0x3FF, 0x100
gsSPLight bowser_3_seg7_light_070029B0, 1
gsSPLight bowser_3_seg7_light_070029A8, 2
gsSPVertex bowser_3_seg7_vertex_070029D8, 6, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  3,  4,  5, 0x0
gsSPLight bowser_3_seg7_light_070029C8, 1
gsSPLight bowser_3_seg7_light_070029C0, 2
gsSPVertex bowser_3_seg7_vertex_07002A38, 4, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  0,  2,  3, 0x0
gsSPEndDisplayList

bowser_3_seg7_dl_07002BE8: # 0x07002BE8 - 0x07002C50
gsDPSetTextureImage G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, bowser_3_seg7_texture_07001000
gsDPLoadSync
gsDPLoadBlock 7, 0, 0, 0x7FF, 0x100
gsSPVertex bowser_3_seg7_vertex_07002A78, 16, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  3,  4,  5, 0x0
gsSP1Triangle  3,  6,  4, 0x0
gsSP1Triangle  7,  8,  9, 0x0
gsSP1Triangle 10,  7,  9, 0x0
gsSP1Triangle 11, 12, 13, 0x0
gsSP1Triangle 11, 14, 12, 0x0
gsSP1Triangle  1, 15,  2, 0x0
gsSPEndDisplayList

glabel bowser_3_seg7_dl_07002C50 # 0x07002C50 - 0x07002CE0
gsDPPipeSync
gsDPSetCombineMode G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsSPClearGeometryMode G_SHADING_SMOOTH
gsDPSetTile G_IM_FMT_RGBA, G_IM_SIZ_16b, 0, 0, G_TX_LOADTILE, 0, G_TX_WRAP | G_TX_NOMIRROR, G_TX_NOMASK, G_TX_NOLOD, G_TX_WRAP | G_TX_NOMIRROR, G_TX_NOMASK, G_TX_NOLOD
gsSPTexture -1, -1, 0, 0, 1
gsDPTileSync
gsDPSetTile G_IM_FMT_RGBA, G_IM_SIZ_16b, 8, 0, G_TX_RENDERTILE, 0, G_TX_WRAP | G_TX_NOMIRROR, 5, G_TX_NOLOD, G_TX_WRAP | G_TX_NOMIRROR, 5, G_TX_NOLOD
gsDPSetTileSize 0, 0, 0, 124, 124
gsSPDisplayList bowser_3_seg7_dl_07002B78
gsDPTileSync
gsDPSetTile G_IM_FMT_RGBA, G_IM_SIZ_16b, 8, 0, G_TX_RENDERTILE, 0, G_TX_WRAP | G_TX_NOMIRROR, 6, G_TX_NOLOD, G_TX_WRAP | G_TX_NOMIRROR, 5, G_TX_NOLOD
gsDPSetTileSize 0, 0, 0, 124, 252
gsSPDisplayList bowser_3_seg7_dl_07002BE8
gsSPTexture -1, -1, 0, 0, 0
gsDPPipeSync
gsDPSetCombineMode G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsSPSetGeometryMode G_SHADING_SMOOTH
gsSPEndDisplayList

bowser_3_seg7_light_07002CE0: # 0x07002CE0 - 0x07002CE8
.byte 0x22, 0x22, 0x22, 0x00, 0x22, 0x22, 0x22, 0x00

bowser_3_seg7_light_07002CE8: # 0x07002CE8 - 0x07002CF8
.byte 0x89, 0x89, 0x8A, 0x00, 0x89, 0x89, 0x8A, 0x00
.byte 0x28, 0x28, 0x28, 0x00, 0x00, 0x00, 0x00, 0x00

bowser_3_seg7_light_07002CF8: # 0x07002CF8 - 0x07002D00
.byte 0x3F, 0x3F, 0x3F, 0x00, 0x3F, 0x3F, 0x3F, 0x00

bowser_3_seg7_light_07002D00: # 0x07002D00 - 0x07002D10
.byte 0xFF, 0xFF, 0xFF, 0x00, 0xFF, 0xFF, 0xFF, 0x00
.byte 0x28, 0x28, 0x28, 0x00, 0x00, 0x00, 0x00, 0x00

bowser_3_seg7_vertex_07002D10: # 0x07002D10 - 0x07002D70
vertex      0,  -2364,   1262,   1366,  -1156,  0x08, 0x90, 0x39, 0xFF
vertex   1498,  -1852,   2050,    580,  -2652,  0x08, 0x90, 0x39, 0xFF
vertex      0,  -1340,   3277,   -644,  -1156,  0x08, 0x90, 0x39, 0xFF
vertex   1498,  -1852,   2050,    580,  -2652,  0x16, 0x99, 0x46, 0xFF
vertex   1946,  -1340,   2662,      0,  -3098,  0x16, 0x99, 0x46, 0xFF
vertex      0,  -1340,   3277,   -644,  -1156,  0x16, 0x99, 0x46, 0xFF

bowser_3_seg7_vertex_07002D70: # 0x07002D70 - 0x07002DB0
vertex      0,    307,   3277,    990,    990,  0x00, 0x7F, 0x00, 0xFF
vertex   1946,    307,   2662,   2284,    582,  0x00, 0x7F, 0x00, 0xFF
vertex   1498,    307,   2050,   1986,    174,  0x00, 0x7F, 0x00, 0xFF
vertex      0,    307,   1262,    990,   -350,  0x00, 0x7F, 0x00, 0xFF

bowser_3_seg7_vertex_07002DB0: # 0x07002DB0 - 0x07002EB0
vertex      0,  -1340,   3277,    958,   2012,  0x81, 0x00, 0x00, 0xFF
vertex      0,    307,   3277,    990,      0,  0x81, 0x00, 0x00, 0xFF
vertex      0,  -2364,   1262,  -1052,   2012,  0x81, 0x00, 0x00, 0xFF
vertex   1498,    307,   2050,    234,      0,  0x66, 0x00, 0xB5, 0xFF
vertex   1946,    307,   2662,    990,      0,  0x66, 0x00, 0xB5, 0xFF
vertex   1946,  -1340,   2662,    990,   2012,  0x66, 0x00, 0xB5, 0xFF
vertex   1498,  -1852,   2050,    234,   2012,  0x66, 0x00, 0xB5, 0xFF
vertex      0,  -2364,   1262,    990,   2012,  0x3B, 0x00, 0x90, 0xFF
vertex      0,    307,   1262,    990,      0,  0x3B, 0x00, 0x90, 0xFF
vertex   1498,    307,   2050,   -698,      0,  0x3B, 0x00, 0x90, 0xFF
vertex   1498,  -1852,   2050,   -698,   2012,  0x3B, 0x00, 0x90, 0xFF
vertex   1946,  -1340,   2662,   5340,   1816,  0x26, 0x00, 0x79, 0xFF
vertex      0,    307,   3277,   3800,    172,  0x26, 0x00, 0x79, 0xFF
vertex      0,  -1340,   3277,   3800,   1816,  0x26, 0x00, 0x79, 0xFF
vertex   1946,    307,   2662,   5340,    172,  0x26, 0x00, 0x79, 0xFF
vertex      0,    307,   1262,  -1020,      0,  0x81, 0x00, 0x00, 0xFF

bowser_3_seg7_dl_07002EB0: # 0x07002EB0 - 0x07002F20
gsDPSetTextureImage G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, bowser_3_seg7_texture_07000800
gsDPLoadSync
gsDPLoadBlock 7, 0, 0, 0x3FF, 0x100
gsSPLight bowser_3_seg7_light_07002CE8, 1
gsSPLight bowser_3_seg7_light_07002CE0, 2
gsSPVertex bowser_3_seg7_vertex_07002D10, 6, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  3,  4,  5, 0x0
gsSPLight bowser_3_seg7_light_07002D00, 1
gsSPLight bowser_3_seg7_light_07002CF8, 2
gsSPVertex bowser_3_seg7_vertex_07002D70, 4, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  0,  2,  3, 0x0
gsSPEndDisplayList

bowser_3_seg7_dl_07002F20: # 0x07002F20 - 0x07002F88
gsDPSetTextureImage G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, bowser_3_seg7_texture_07001000
gsDPLoadSync
gsDPLoadBlock 7, 0, 0, 0x7FF, 0x100
gsSPVertex bowser_3_seg7_vertex_07002DB0, 16, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  3,  4,  5, 0x0
gsSP1Triangle  3,  5,  6, 0x0
gsSP1Triangle  7,  8,  9, 0x0
gsSP1Triangle  7,  9, 10, 0x0
gsSP1Triangle 11, 12, 13, 0x0
gsSP1Triangle 11, 14, 12, 0x0
gsSP1Triangle  1, 15,  2, 0x0
gsSPEndDisplayList

glabel bowser_3_seg7_dl_07002F88 # 0x07002F88 - 0x07003018
gsDPPipeSync
gsDPSetCombineMode G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsSPClearGeometryMode G_SHADING_SMOOTH
gsDPSetTile G_IM_FMT_RGBA, G_IM_SIZ_16b, 0, 0, G_TX_LOADTILE, 0, G_TX_WRAP | G_TX_NOMIRROR, G_TX_NOMASK, G_TX_NOLOD, G_TX_WRAP | G_TX_NOMIRROR, G_TX_NOMASK, G_TX_NOLOD
gsSPTexture -1, -1, 0, 0, 1
gsDPTileSync
gsDPSetTile G_IM_FMT_RGBA, G_IM_SIZ_16b, 8, 0, G_TX_RENDERTILE, 0, G_TX_WRAP | G_TX_NOMIRROR, 5, G_TX_NOLOD, G_TX_WRAP | G_TX_NOMIRROR, 5, G_TX_NOLOD
gsDPSetTileSize 0, 0, 0, 124, 124
gsSPDisplayList bowser_3_seg7_dl_07002EB0
gsDPTileSync
gsDPSetTile G_IM_FMT_RGBA, G_IM_SIZ_16b, 8, 0, G_TX_RENDERTILE, 0, G_TX_WRAP | G_TX_NOMIRROR, 6, G_TX_NOLOD, G_TX_WRAP | G_TX_NOMIRROR, 5, G_TX_NOLOD
gsDPSetTileSize 0, 0, 0, 124, 252
gsSPDisplayList bowser_3_seg7_dl_07002F20
gsSPTexture -1, -1, 0, 0, 0
gsDPPipeSync
gsDPSetCombineMode G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsSPSetGeometryMode G_SHADING_SMOOTH
gsSPEndDisplayList

bowser_3_seg7_light_07003018: # 0x07003018 - 0x07003020
.byte 0x22, 0x22, 0x22, 0x00, 0x22, 0x22, 0x22, 0x00

bowser_3_seg7_light_07003020: # 0x07003020 - 0x07003030
.byte 0x89, 0x89, 0x8A, 0x00, 0x89, 0x89, 0x8A, 0x00
.byte 0x28, 0x28, 0x28, 0x00, 0x00, 0x00, 0x00, 0x00

bowser_3_seg7_light_07003030: # 0x07003030 - 0x07003038
.byte 0x3F, 0x3F, 0x3F, 0x00, 0x3F, 0x3F, 0x3F, 0x00

bowser_3_seg7_light_07003038: # 0x07003038 - 0x07003048
.byte 0xFF, 0xFF, 0xFF, 0x00, 0xFF, 0xFF, 0xFF, 0x00
.byte 0x28, 0x28, 0x28, 0x00, 0x00, 0x00, 0x00, 0x00

bowser_3_seg7_vertex_07003048: # 0x07003048 - 0x070030A8
vertex   1183,  -2364,    394,   2232,  -2336,  0x34, 0x90, 0x18, 0xFF
vertex   3072,  -1340,   1024,   1604,  -4222,  0x34, 0x90, 0x18, 0xFF
vertex   1498,  -1852,   2050,    580,  -2652,  0x34, 0x90, 0x18, 0xFF
vertex   3072,  -1340,   1024,   1604,  -4222,  0x3C, 0x99, 0x29, 0xFF
vertex   1946,  -1340,   2662,      0,  -3098,  0x3C, 0x99, 0x29, 0xFF
vertex   1498,  -1852,   2050,    580,  -2652,  0x3C, 0x99, 0x29, 0xFF

bowser_3_seg7_vertex_070030A8: # 0x070030A8 - 0x070030E8
vertex   3072,    307,   1024,   3034,   -508,  0x00, 0x7F, 0x00, 0xFF
vertex   1183,    307,    394,   1776,   -928,  0x00, 0x7F, 0x00, 0xFF
vertex   1498,    307,   2050,   1986,    174,  0x00, 0x7F, 0x00, 0xFF
vertex   1946,    307,   2662,   2284,    582,  0x00, 0x7F, 0x00, 0xFF

bowser_3_seg7_vertex_070030E8: # 0x070030E8 - 0x070031E8
vertex   1183,  -2364,    394,   -996,   2012,  0x28, 0x00, 0x88, 0xFF
vertex   3072,    307,   1024,    990,      0,  0x28, 0x00, 0x88, 0xFF
vertex   3072,  -1340,   1024,    990,   2012,  0x28, 0x00, 0x88, 0xFF
vertex   3072,  -1340,   1024,   6848,   1816,  0x68, 0x00, 0x47, 0xFF
vertex   1946,    307,   2662,   5340,    172,  0x68, 0x00, 0x47, 0xFF
vertex   1946,  -1340,   2662,   5340,   1816,  0x68, 0x00, 0x47, 0xFF
vertex   3072,    307,   1024,   6848,    172,  0x68, 0x00, 0x47, 0xFF
vertex   1946,  -1340,   2662,    990,   2012,  0x9A, 0x00, 0x4B, 0xFF
vertex   1946,    307,   2662,    990,      0,  0x9A, 0x00, 0x4B, 0xFF
vertex   1498,    307,   2050,    234,      0,  0x9A, 0x00, 0x4B, 0xFF
vertex   1498,  -1852,   2050,    234,   2012,  0x9A, 0x00, 0x4B, 0xFF
vertex   1498,    307,   2050,   -690,      0,  0x84, 0x00, 0x17, 0xFF
vertex   1183,    307,    394,    990,      0,  0x84, 0x00, 0x17, 0xFF
vertex   1498,  -1852,   2050,   -690,   2012,  0x84, 0x00, 0x17, 0xFF
vertex   1183,  -2364,    394,    990,   2012,  0x84, 0x00, 0x17, 0xFF
vertex   1183,    307,    394,   -996,      0,  0x28, 0x00, 0x88, 0xFF

bowser_3_seg7_dl_070031E8: # 0x070031E8 - 0x07003258
gsDPSetTextureImage G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, bowser_3_seg7_texture_07000800
gsDPLoadSync
gsDPLoadBlock 7, 0, 0, 0x3FF, 0x100
gsSPLight bowser_3_seg7_light_07003020, 1
gsSPLight bowser_3_seg7_light_07003018, 2
gsSPVertex bowser_3_seg7_vertex_07003048, 6, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  3,  4,  5, 0x0
gsSPLight bowser_3_seg7_light_07003038, 1
gsSPLight bowser_3_seg7_light_07003030, 2
gsSPVertex bowser_3_seg7_vertex_070030A8, 4, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  0,  2,  3, 0x0
gsSPEndDisplayList

bowser_3_seg7_dl_07003258: # 0x07003258 - 0x070032C0
gsDPSetTextureImage G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, bowser_3_seg7_texture_07001000
gsDPLoadSync
gsDPLoadBlock 7, 0, 0, 0x7FF, 0x100
gsSPVertex bowser_3_seg7_vertex_070030E8, 16, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  3,  4,  5, 0x0
gsSP1Triangle  3,  6,  4, 0x0
gsSP1Triangle  7,  8,  9, 0x0
gsSP1Triangle  7,  9, 10, 0x0
gsSP1Triangle 11, 12, 13, 0x0
gsSP1Triangle 12, 14, 13, 0x0
gsSP1Triangle  0, 15,  1, 0x0
gsSPEndDisplayList

glabel bowser_3_seg7_dl_070032C0 # 0x070032C0 - 0x07003350
gsDPPipeSync
gsDPSetCombineMode G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsSPClearGeometryMode G_SHADING_SMOOTH
gsDPSetTile G_IM_FMT_RGBA, G_IM_SIZ_16b, 0, 0, G_TX_LOADTILE, 0, G_TX_WRAP | G_TX_NOMIRROR, G_TX_NOMASK, G_TX_NOLOD, G_TX_WRAP | G_TX_NOMIRROR, G_TX_NOMASK, G_TX_NOLOD
gsSPTexture -1, -1, 0, 0, 1
gsDPTileSync
gsDPSetTile G_IM_FMT_RGBA, G_IM_SIZ_16b, 8, 0, G_TX_RENDERTILE, 0, G_TX_WRAP | G_TX_NOMIRROR, 5, G_TX_NOLOD, G_TX_WRAP | G_TX_NOMIRROR, 5, G_TX_NOLOD
gsDPSetTileSize 0, 0, 0, 124, 124
gsSPDisplayList bowser_3_seg7_dl_070031E8
gsDPTileSync
gsDPSetTile G_IM_FMT_RGBA, G_IM_SIZ_16b, 8, 0, G_TX_RENDERTILE, 0, G_TX_WRAP | G_TX_NOMIRROR, 6, G_TX_NOLOD, G_TX_WRAP | G_TX_NOMIRROR, 5, G_TX_NOLOD
gsDPSetTileSize 0, 0, 0, 124, 252
gsSPDisplayList bowser_3_seg7_dl_07003258
gsSPTexture -1, -1, 0, 0, 0
gsDPPipeSync
gsDPSetCombineMode G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsSPSetGeometryMode G_SHADING_SMOOTH
gsSPEndDisplayList

bowser_3_seg7_light_07003350: # 0x07003350 - 0x07003358
.byte 0x22, 0x22, 0x22, 0x00, 0x22, 0x22, 0x22, 0x00

bowser_3_seg7_light_07003358: # 0x07003358 - 0x07003368
.byte 0x89, 0x89, 0x8A, 0x00, 0x89, 0x89, 0x8A, 0x00
.byte 0x28, 0x28, 0x28, 0x00, 0x00, 0x00, 0x00, 0x00

bowser_3_seg7_light_07003368: # 0x07003368 - 0x07003370
.byte 0x3F, 0x3F, 0x3F, 0x00, 0x3F, 0x3F, 0x3F, 0x00

bowser_3_seg7_light_07003370: # 0x07003370 - 0x07003380
.byte 0xFF, 0xFF, 0xFF, 0x00, 0xFF, 0xFF, 0xFF, 0x00
.byte 0x28, 0x28, 0x28, 0x00, 0x00, 0x00, 0x00, 0x00

bowser_3_seg7_vertex_07003380: # 0x07003380 - 0x070033E0
vertex   3072,  -1340,   1024,   1604,  -4222,  0x39, 0x90, 0x09, 0xFF
vertex   1183,  -2364,    394,   2232,  -2336,  0x39, 0x90, 0x09, 0xFF
vertex   2365,  -1852,   -787,   3412,  -3518,  0x39, 0x90, 0x09, 0xFF
vertex   3072,  -1340,   1024,   1604,  -4222,  0x4A, 0x9A, 0x00, 0xFF
vertex   2365,  -1852,   -787,   3412,  -3518,  0x4A, 0x9A, 0x00, 0xFF
vertex   3072,  -1340,  -1023,   3648,  -4222,  0x4A, 0x9A, 0x00, 0xFF

bowser_3_seg7_vertex_070033E0: # 0x070033E0 - 0x07003420
vertex   3072,    307,   1024,   3034,   -508,  0x00, 0x7F, 0x00, 0xFF
vertex   2365,    307,   -787,   2564,  -1714,  0x00, 0x7F, 0x00, 0xFF
vertex   1183,    307,    394,   1776,   -928,  0x00, 0x7F, 0x00, 0xFF
vertex   3072,    307,  -1023,   3034,  -1872,  0x00, 0x7F, 0x00, 0xFF

bowser_3_seg7_vertex_07003420: # 0x07003420 - 0x07003520
vertex   3072,  -1340,   1024,    990,   2012,  0xD8, 0x00, 0x78, 0xFF
vertex   1183,    307,    394,   -996,      0,  0xD8, 0x00, 0x78, 0xFF
vertex   1183,  -2364,    394,   -996,   2012,  0xD8, 0x00, 0x78, 0xFF
vertex   2365,    307,   -787,    246,      0,  0xD8, 0x00, 0x88, 0xFF
vertex   3072,    307,  -1023,    990,      0,  0xD8, 0x00, 0x88, 0xFF
vertex   3072,  -1340,  -1023,    990,   2012,  0xD8, 0x00, 0x88, 0xFF
vertex   2365,  -1852,   -787,    246,   2012,  0xD8, 0x00, 0x88, 0xFF
vertex   1183,  -2364,    394,   -678,   2012,  0xA7, 0x00, 0xA7, 0xFF
vertex   2365,    307,   -787,    990,      0,  0xA7, 0x00, 0xA7, 0xFF
vertex   2365,  -1852,   -787,    990,   2012,  0xA7, 0x00, 0xA7, 0xFF
vertex   1183,    307,    394,   -678,      0,  0xA7, 0x00, 0xA7, 0xFF
vertex   3072,  -1340,  -1023,   8418,   1816,  0x7F, 0x00, 0x00, 0xFF
vertex   3072,    307,   1024,   6848,    172,  0x7F, 0x00, 0x00, 0xFF
vertex   3072,  -1340,   1024,   6848,   1816,  0x7F, 0x00, 0x00, 0xFF
vertex   3072,    307,  -1023,   8418,    172,  0x7F, 0x00, 0x00, 0xFF
vertex   3072,    307,   1024,    990,      0,  0xD8, 0x00, 0x78, 0xFF

bowser_3_seg7_dl_07003520: # 0x07003520 - 0x07003590
gsDPSetTextureImage G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, bowser_3_seg7_texture_07000800
gsDPLoadSync
gsDPLoadBlock 7, 0, 0, 0x3FF, 0x100
gsSPLight bowser_3_seg7_light_07003358, 1
gsSPLight bowser_3_seg7_light_07003350, 2
gsSPVertex bowser_3_seg7_vertex_07003380, 6, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  3,  4,  5, 0x0
gsSPLight bowser_3_seg7_light_07003370, 1
gsSPLight bowser_3_seg7_light_07003368, 2
gsSPVertex bowser_3_seg7_vertex_070033E0, 4, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  0,  3,  1, 0x0
gsSPEndDisplayList

bowser_3_seg7_dl_07003590: # 0x07003590 - 0x070035F8
gsDPSetTextureImage G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, bowser_3_seg7_texture_07001000
gsDPLoadSync
gsDPLoadBlock 7, 0, 0, 0x7FF, 0x100
gsSPVertex bowser_3_seg7_vertex_07003420, 16, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  3,  4,  5, 0x0
gsSP1Triangle  3,  5,  6, 0x0
gsSP1Triangle  7,  8,  9, 0x0
gsSP1Triangle  7, 10,  8, 0x0
gsSP1Triangle 11, 12, 13, 0x0
gsSP1Triangle 11, 14, 12, 0x0
gsSP1Triangle  0, 15,  1, 0x0
gsSPEndDisplayList

glabel bowser_3_seg7_dl_070035F8 # 0x070035F8 - 0x07003688
gsDPPipeSync
gsDPSetCombineMode G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsSPClearGeometryMode G_SHADING_SMOOTH
gsDPSetTile G_IM_FMT_RGBA, G_IM_SIZ_16b, 0, 0, G_TX_LOADTILE, 0, G_TX_WRAP | G_TX_NOMIRROR, G_TX_NOMASK, G_TX_NOLOD, G_TX_WRAP | G_TX_NOMIRROR, G_TX_NOMASK, G_TX_NOLOD
gsSPTexture -1, -1, 0, 0, 1
gsDPTileSync
gsDPSetTile G_IM_FMT_RGBA, G_IM_SIZ_16b, 8, 0, G_TX_RENDERTILE, 0, G_TX_WRAP | G_TX_NOMIRROR, 5, G_TX_NOLOD, G_TX_WRAP | G_TX_NOMIRROR, 5, G_TX_NOLOD
gsDPSetTileSize 0, 0, 0, 124, 124
gsSPDisplayList bowser_3_seg7_dl_07003520
gsDPTileSync
gsDPSetTile G_IM_FMT_RGBA, G_IM_SIZ_16b, 8, 0, G_TX_RENDERTILE, 0, G_TX_WRAP | G_TX_NOMIRROR, 6, G_TX_NOLOD, G_TX_WRAP | G_TX_NOMIRROR, 5, G_TX_NOLOD
gsDPSetTileSize 0, 0, 0, 124, 252
gsSPDisplayList bowser_3_seg7_dl_07003590
gsSPTexture -1, -1, 0, 0, 0
gsDPPipeSync
gsDPSetCombineMode G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsSPSetGeometryMode G_SHADING_SMOOTH
gsSPEndDisplayList

bowser_3_seg7_light_07003688: # 0x07003688 - 0x07003690
.byte 0x22, 0x22, 0x22, 0x00, 0x22, 0x22, 0x22, 0x00

bowser_3_seg7_light_07003690: # 0x07003690 - 0x070036A0
.byte 0x89, 0x89, 0x8A, 0x00, 0x89, 0x89, 0x8A, 0x00
.byte 0x28, 0x28, 0x28, 0x00, 0x00, 0x00, 0x00, 0x00

bowser_3_seg7_light_070036A0: # 0x070036A0 - 0x070036A8
.byte 0x3F, 0x3F, 0x3F, 0x00, 0x3F, 0x3F, 0x3F, 0x00

bowser_3_seg7_light_070036A8: # 0x070036A8 - 0x070036B8
.byte 0xFF, 0xFF, 0xFF, 0x00, 0xFF, 0xFF, 0xFF, 0x00
.byte 0x28, 0x28, 0x28, 0x00, 0x00, 0x00, 0x00, 0x00

bowser_3_seg7_vertex_070036B8: # 0x070036B8 - 0x07003718
vertex   2365,  -1852,   -787,   3412,  -3518,  0x3C, 0x99, 0xD7, 0xFF
vertex   1946,  -1340,  -2661,   5282,  -3098,  0x3C, 0x99, 0xD7, 0xFF
vertex   3072,  -1340,  -1023,   3648,  -4222,  0x3C, 0x99, 0xD7, 0xFF
vertex   2365,  -1852,   -787,   3412,  -3518,  0x2A, 0x90, 0xD8, 0xFF
vertex    788,  -2364,  -1024,   3648,  -1944,  0x2A, 0x90, 0xD8, 0xFF
vertex   1946,  -1340,  -2661,   5282,  -3098,  0x2A, 0x90, 0xD8, 0xFF

bowser_3_seg7_vertex_07003718: # 0x07003718 - 0x07003758
vertex    788,    307,  -1024,   1514,  -1872,  0x00, 0x7F, 0x00, 0xFF
vertex   3072,    307,  -1023,   3034,  -1872,  0x00, 0x7F, 0x00, 0xFF
vertex   1946,    307,  -2661,   2284,  -2962,  0x00, 0x7F, 0x00, 0xFF
vertex   2365,    307,   -787,   2564,  -1714,  0x00, 0x7F, 0x00, 0xFF

bowser_3_seg7_vertex_07003758: # 0x07003758 - 0x07003858
vertex    788,  -2364,  -1024,  -1010,   2012,  0x99, 0x00, 0xB7, 0xFF
vertex   1946,    307,  -2661,    990,      0,  0x99, 0x00, 0xB7, 0xFF
vertex   1946,  -1340,  -2661,    990,   2012,  0x99, 0x00, 0xB7, 0xFF
vertex   1946,  -1340,  -2661,   9926,   1816,  0x68, 0x00, 0xB9, 0xFF
vertex   1946,    307,  -2661,   9926,    172,  0x68, 0x00, 0xB9, 0xFF
vertex   3072,    307,  -1023,   8418,    172,  0x68, 0x00, 0xB9, 0xFF
vertex   3072,  -1340,  -1023,   8418,   1816,  0x68, 0x00, 0xB9, 0xFF
vertex   3072,  -1340,  -1023,    990,   2012,  0x28, 0x00, 0x78, 0xFF
vertex   2365,    307,   -787,    246,      0,  0x28, 0x00, 0x78, 0xFF
vertex   2365,  -1852,   -787,    246,   2012,  0x28, 0x00, 0x78, 0xFF
vertex   3072,    307,  -1023,    990,      0,  0x28, 0x00, 0x78, 0xFF
vertex   2365,    307,   -787,    990,      0,  0xEE, 0x00, 0x7D, 0xFF
vertex    788,    307,  -1024,   -600,      0,  0xEE, 0x00, 0x7D, 0xFF
vertex   2365,  -1852,   -787,    990,   2012,  0xEE, 0x00, 0x7D, 0xFF
vertex    788,  -2364,  -1024,   -600,   2012,  0xEE, 0x00, 0x7D, 0xFF
vertex    788,    307,  -1024,  -1010,      0,  0x99, 0x00, 0xB7, 0xFF

bowser_3_seg7_dl_07003858: # 0x07003858 - 0x070038C8
gsDPSetTextureImage G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, bowser_3_seg7_texture_07000800
gsDPLoadSync
gsDPLoadBlock 7, 0, 0, 0x3FF, 0x100
gsSPLight bowser_3_seg7_light_07003690, 1
gsSPLight bowser_3_seg7_light_07003688, 2
gsSPVertex bowser_3_seg7_vertex_070036B8, 6, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  3,  4,  5, 0x0
gsSPLight bowser_3_seg7_light_070036A8, 1
gsSPLight bowser_3_seg7_light_070036A0, 2
gsSPVertex bowser_3_seg7_vertex_07003718, 4, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  0,  3,  1, 0x0
gsSPEndDisplayList

bowser_3_seg7_dl_070038C8: # 0x070038C8 - 0x07003930
gsDPSetTextureImage G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, bowser_3_seg7_texture_07001000
gsDPLoadSync
gsDPLoadBlock 7, 0, 0, 0x7FF, 0x100
gsSPVertex bowser_3_seg7_vertex_07003758, 16, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  3,  4,  5, 0x0
gsSP1Triangle  3,  5,  6, 0x0
gsSP1Triangle  7,  8,  9, 0x0
gsSP1Triangle  7, 10,  8, 0x0
gsSP1Triangle 11, 12, 13, 0x0
gsSP1Triangle 12, 14, 13, 0x0
gsSP1Triangle  0, 15,  1, 0x0
gsSPEndDisplayList

glabel bowser_3_seg7_dl_07003930 # 0x07003930 - 0x070039C0
gsDPPipeSync
gsDPSetCombineMode G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsSPClearGeometryMode G_SHADING_SMOOTH
gsDPSetTile G_IM_FMT_RGBA, G_IM_SIZ_16b, 0, 0, G_TX_LOADTILE, 0, G_TX_WRAP | G_TX_NOMIRROR, G_TX_NOMASK, G_TX_NOLOD, G_TX_WRAP | G_TX_NOMIRROR, G_TX_NOMASK, G_TX_NOLOD
gsSPTexture -1, -1, 0, 0, 1
gsDPTileSync
gsDPSetTile G_IM_FMT_RGBA, G_IM_SIZ_16b, 8, 0, G_TX_RENDERTILE, 0, G_TX_WRAP | G_TX_NOMIRROR, 5, G_TX_NOLOD, G_TX_WRAP | G_TX_NOMIRROR, 5, G_TX_NOLOD
gsDPSetTileSize 0, 0, 0, 124, 124
gsSPDisplayList bowser_3_seg7_dl_07003858
gsDPTileSync
gsDPSetTile G_IM_FMT_RGBA, G_IM_SIZ_16b, 8, 0, G_TX_RENDERTILE, 0, G_TX_WRAP | G_TX_NOMIRROR, 6, G_TX_NOLOD, G_TX_WRAP | G_TX_NOMIRROR, 5, G_TX_NOLOD
gsDPSetTileSize 0, 0, 0, 124, 252
gsSPDisplayList bowser_3_seg7_dl_070038C8
gsSPTexture -1, -1, 0, 0, 0
gsDPPipeSync
gsDPSetCombineMode G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsSPSetGeometryMode G_SHADING_SMOOTH
gsSPEndDisplayList

bowser_3_seg7_light_070039C0: # 0x070039C0 - 0x070039C8
.byte 0x22, 0x22, 0x22, 0x00, 0x22, 0x22, 0x22, 0x00

bowser_3_seg7_light_070039C8: # 0x070039C8 - 0x070039D8
.byte 0x89, 0x89, 0x8A, 0x00, 0x89, 0x89, 0x8A, 0x00
.byte 0x28, 0x28, 0x28, 0x00, 0x00, 0x00, 0x00, 0x00

bowser_3_seg7_light_070039D8: # 0x070039D8 - 0x070039E0
.byte 0x3F, 0x3F, 0x3F, 0x00, 0x3F, 0x3F, 0x3F, 0x00

bowser_3_seg7_light_070039E0: # 0x070039E0 - 0x070039F0
.byte 0xFF, 0xFF, 0xFF, 0x00, 0xFF, 0xFF, 0xFF, 0x00
.byte 0x28, 0x28, 0x28, 0x00, 0x00, 0x00, 0x00, 0x00

bowser_3_seg7_vertex_070039F0: # 0x070039F0 - 0x07003A50
vertex    788,  -2364,  -1024,   3648,  -1944,  0x19, 0x90, 0xCC, 0xFF
vertex      0,  -1852,  -2522,   5144,  -1156,  0x19, 0x90, 0xCC, 0xFF
vertex   1946,  -1340,  -2661,   5282,  -3098,  0x19, 0x90, 0xCC, 0xFF
vertex      0,  -1852,  -2522,   5144,  -1156,  0x16, 0x99, 0xBA, 0xFF
vertex      0,  -1340,  -3276,   5896,  -1156,  0x16, 0x99, 0xBA, 0xFF
vertex   1946,  -1340,  -2661,   5282,  -3098,  0x16, 0x99, 0xBA, 0xFF

bowser_3_seg7_vertex_07003A50: # 0x07003A50 - 0x07003A90
vertex      0,    307,  -3276,    990,  -3370,  0x00, 0x7F, 0x00, 0xFF
vertex      0,    307,  -2522,    990,  -2870,  0x00, 0x7F, 0x00, 0xFF
vertex    788,    307,  -1024,   1514,  -1872,  0x00, 0x7F, 0x00, 0xFF
vertex   1946,    307,  -2661,   2284,  -2962,  0x00, 0x7F, 0x00, 0xFF

bowser_3_seg7_vertex_07003A90: # 0x07003A90 - 0x07003B90
vertex   1946,  -1340,  -2661,    990,   2012,  0x67, 0x00, 0x49, 0xFF
vertex    788,    307,  -1024,  -1010,      0,  0x67, 0x00, 0x49, 0xFF
vertex    788,  -2364,  -1024,  -1010,   2012,  0x67, 0x00, 0x49, 0xFF
vertex      0,    307,  -3276,    990,      0,  0x81, 0x00, 0x00, 0xFF
vertex      0,  -1340,  -3276,    990,   2012,  0x81, 0x00, 0x00, 0xFF
vertex      0,  -1852,  -2522,    238,   2012,  0x81, 0x00, 0x00, 0xFF
vertex      0,    307,  -2522,    238,      0,  0x81, 0x00, 0x00, 0xFF
vertex    788,    307,  -1024,   -698,      0,  0x90, 0x00, 0x3B, 0xFF
vertex      0,    307,  -2522,    990,      0,  0x90, 0x00, 0x3B, 0xFF
vertex      0,  -1852,  -2522,    990,   2012,  0x90, 0x00, 0x3B, 0xFF
vertex    788,  -2364,  -1024,   -698,   2012,  0x90, 0x00, 0x3B, 0xFF
vertex      0,  -1340,  -3276,  -1044,   2012,  0x26, 0x00, 0x87, 0xFF
vertex   1946,    307,  -2661,    990,      0,  0x26, 0x00, 0x87, 0xFF
vertex   1946,  -1340,  -2661,    990,   2012,  0x26, 0x00, 0x87, 0xFF
vertex      0,    307,  -3276,  -1044,      0,  0x26, 0x00, 0x87, 0xFF
vertex   1946,    307,  -2661,    990,      0,  0x67, 0x00, 0x49, 0xFF

bowser_3_seg7_dl_07003B90: # 0x07003B90 - 0x07003C00
gsDPSetTextureImage G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, bowser_3_seg7_texture_07000800
gsDPLoadSync
gsDPLoadBlock 7, 0, 0, 0x3FF, 0x100
gsSPLight bowser_3_seg7_light_070039C8, 1
gsSPLight bowser_3_seg7_light_070039C0, 2
gsSPVertex bowser_3_seg7_vertex_070039F0, 6, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  3,  4,  5, 0x0
gsSPLight bowser_3_seg7_light_070039E0, 1
gsSPLight bowser_3_seg7_light_070039D8, 2
gsSPVertex bowser_3_seg7_vertex_07003A50, 4, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  0,  2,  3, 0x0
gsSPEndDisplayList

bowser_3_seg7_dl_07003C00: # 0x07003C00 - 0x07003C68
gsDPSetTextureImage G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, bowser_3_seg7_texture_07001000
gsDPLoadSync
gsDPLoadBlock 7, 0, 0, 0x7FF, 0x100
gsSPVertex bowser_3_seg7_vertex_07003A90, 16, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  3,  4,  5, 0x0
gsSP1Triangle  6,  3,  5, 0x0
gsSP1Triangle  7,  8,  9, 0x0
gsSP1Triangle 10,  7,  9, 0x0
gsSP1Triangle 11, 12, 13, 0x0
gsSP1Triangle 11, 14, 12, 0x0
gsSP1Triangle  0, 15,  1, 0x0
gsSPEndDisplayList

glabel bowser_3_seg7_dl_07003C68 # 0x07003C68 - 0x07003CF8
gsDPPipeSync
gsDPSetCombineMode G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsSPClearGeometryMode G_SHADING_SMOOTH
gsDPSetTile G_IM_FMT_RGBA, G_IM_SIZ_16b, 0, 0, G_TX_LOADTILE, 0, G_TX_WRAP | G_TX_NOMIRROR, G_TX_NOMASK, G_TX_NOLOD, G_TX_WRAP | G_TX_NOMIRROR, G_TX_NOMASK, G_TX_NOLOD
gsSPTexture -1, -1, 0, 0, 1
gsDPTileSync
gsDPSetTile G_IM_FMT_RGBA, G_IM_SIZ_16b, 8, 0, G_TX_RENDERTILE, 0, G_TX_WRAP | G_TX_NOMIRROR, 5, G_TX_NOLOD, G_TX_WRAP | G_TX_NOMIRROR, 5, G_TX_NOLOD
gsDPSetTileSize 0, 0, 0, 124, 124
gsSPDisplayList bowser_3_seg7_dl_07003B90
gsDPTileSync
gsDPSetTile G_IM_FMT_RGBA, G_IM_SIZ_16b, 8, 0, G_TX_RENDERTILE, 0, G_TX_WRAP | G_TX_NOMIRROR, 6, G_TX_NOLOD, G_TX_WRAP | G_TX_NOMIRROR, 5, G_TX_NOLOD
gsDPSetTileSize 0, 0, 0, 124, 252
gsSPDisplayList bowser_3_seg7_dl_07003C00
gsSPTexture -1, -1, 0, 0, 0
gsDPPipeSync
gsDPSetCombineMode G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsSPSetGeometryMode G_SHADING_SMOOTH
gsSPEndDisplayList

bowser_3_seg7_light_07003CF8: # 0x07003CF8 - 0x07003D00
.byte 0x22, 0x22, 0x22, 0x00, 0x22, 0x22, 0x22, 0x00

bowser_3_seg7_light_07003D00: # 0x07003D00 - 0x07003D10
.byte 0x89, 0x89, 0x8A, 0x00, 0x89, 0x89, 0x8A, 0x00
.byte 0x28, 0x28, 0x28, 0x00, 0x00, 0x00, 0x00, 0x00

bowser_3_seg7_light_07003D10: # 0x07003D10 - 0x07003D18
.byte 0x3F, 0x3F, 0x3F, 0x00, 0x3F, 0x3F, 0x3F, 0x00

bowser_3_seg7_light_07003D18: # 0x07003D18 - 0x07003D28
.byte 0xFF, 0xFF, 0xFF, 0x00, 0xFF, 0xFF, 0xFF, 0x00
.byte 0x28, 0x28, 0x28, 0x00, 0x00, 0x00, 0x00, 0x00

bowser_3_seg7_vertex_07003D28: # 0x07003D28 - 0x07003D88
vertex      0,  -1340,  -3276,   5896,  -1156,  0xEA, 0x99, 0xBA, 0xFF
vertex      0,  -1852,  -2522,   5144,  -1156,  0xEA, 0x99, 0xBA, 0xFF
vertex  -1945,  -1340,  -2661,   5282,    786,  0xEA, 0x99, 0xBA, 0xFF
vertex      0,  -1852,  -2522,   5144,  -1156,  0xE7, 0x90, 0xCC, 0xFF
vertex   -787,  -2364,  -1024,   3648,   -370,  0xE7, 0x90, 0xCC, 0xFF
vertex  -1945,  -1340,  -2661,   5282,    786,  0xE7, 0x90, 0xCC, 0xFF

bowser_3_seg7_vertex_07003D88: # 0x07003D88 - 0x07003DC8
vertex   -787,    307,  -1024,    466,  -1872,  0x00, 0x7F, 0x00, 0xFF
vertex      0,    307,  -2522,    990,  -2870,  0x00, 0x7F, 0x00, 0xFF
vertex      0,    307,  -3276,    990,  -3370,  0x00, 0x7F, 0x00, 0xFF
vertex  -1945,    307,  -2661,   -302,  -2962,  0x00, 0x7F, 0x00, 0xFF

bowser_3_seg7_vertex_07003DC8: # 0x07003DC8 - 0x07003EC8
vertex   -787,  -2364,  -1024,  -1010,   2012,  0x99, 0x00, 0x49, 0xFF
vertex   -787,    307,  -1024,  -1010,      0,  0x99, 0x00, 0x49, 0xFF
vertex  -1945,  -1340,  -2661,    990,   2012,  0x99, 0x00, 0x49, 0xFF
vertex  -1945,  -1340,  -2661,  13006,   1816,  0xDA, 0x00, 0x87, 0xFF
vertex      0,    307,  -3276,  11466,    172,  0xDA, 0x00, 0x87, 0xFF
vertex      0,  -1340,  -3276,  11466,   1816,  0xDA, 0x00, 0x87, 0xFF
vertex  -1945,    307,  -2661,  13006,    172,  0xDA, 0x00, 0x87, 0xFF
vertex      0,  -1340,  -3276,    990,   2012,  0x7F, 0x00, 0x00, 0xFF
vertex      0,    307,  -3276,    990,      0,  0x7F, 0x00, 0x00, 0xFF
vertex      0,    307,  -2522,    238,      0,  0x7F, 0x00, 0x00, 0xFF
vertex      0,  -1852,  -2522,    238,   2012,  0x7F, 0x00, 0x00, 0xFF
vertex      0,    307,  -2522,   -698,      0,  0x70, 0x00, 0x3B, 0xFF
vertex   -787,  -2364,  -1024,    990,   2012,  0x70, 0x00, 0x3B, 0xFF
vertex      0,  -1852,  -2522,   -698,   2012,  0x70, 0x00, 0x3B, 0xFF
vertex   -787,    307,  -1024,    990,      0,  0x70, 0x00, 0x3B, 0xFF
vertex  -1945,    307,  -2661,    990,      0,  0x99, 0x00, 0x49, 0xFF

bowser_3_seg7_dl_07003EC8: # 0x07003EC8 - 0x07003F38
gsDPSetTextureImage G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, bowser_3_seg7_texture_07000800
gsDPLoadSync
gsDPLoadBlock 7, 0, 0, 0x3FF, 0x100
gsSPLight bowser_3_seg7_light_07003D00, 1
gsSPLight bowser_3_seg7_light_07003CF8, 2
gsSPVertex bowser_3_seg7_vertex_07003D28, 6, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  3,  4,  5, 0x0
gsSPLight bowser_3_seg7_light_07003D18, 1
gsSPLight bowser_3_seg7_light_07003D10, 2
gsSPVertex bowser_3_seg7_vertex_07003D88, 4, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  0,  2,  3, 0x0
gsSPEndDisplayList

bowser_3_seg7_dl_07003F38: # 0x07003F38 - 0x07003FA0
gsDPSetTextureImage G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, bowser_3_seg7_texture_07001000
gsDPLoadSync
gsDPLoadBlock 7, 0, 0, 0x7FF, 0x100
gsSPVertex bowser_3_seg7_vertex_07003DC8, 16, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  3,  4,  5, 0x0
gsSP1Triangle  3,  6,  4, 0x0
gsSP1Triangle  7,  8,  9, 0x0
gsSP1Triangle  7,  9, 10, 0x0
gsSP1Triangle 11, 12, 13, 0x0
gsSP1Triangle 11, 14, 12, 0x0
gsSP1Triangle  1, 15,  2, 0x0
gsSPEndDisplayList

glabel bowser_3_seg7_dl_07003FA0 # 0x07003FA0 - 0x07004030
gsDPPipeSync
gsDPSetCombineMode G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsSPClearGeometryMode G_SHADING_SMOOTH
gsDPSetTile G_IM_FMT_RGBA, G_IM_SIZ_16b, 0, 0, G_TX_LOADTILE, 0, G_TX_WRAP | G_TX_NOMIRROR, G_TX_NOMASK, G_TX_NOLOD, G_TX_WRAP | G_TX_NOMIRROR, G_TX_NOMASK, G_TX_NOLOD
gsSPTexture -1, -1, 0, 0, 1
gsDPTileSync
gsDPSetTile G_IM_FMT_RGBA, G_IM_SIZ_16b, 8, 0, G_TX_RENDERTILE, 0, G_TX_WRAP | G_TX_NOMIRROR, 5, G_TX_NOLOD, G_TX_WRAP | G_TX_NOMIRROR, 5, G_TX_NOLOD
gsDPSetTileSize 0, 0, 0, 124, 124
gsSPDisplayList bowser_3_seg7_dl_07003EC8
gsDPTileSync
gsDPSetTile G_IM_FMT_RGBA, G_IM_SIZ_16b, 8, 0, G_TX_RENDERTILE, 0, G_TX_WRAP | G_TX_NOMIRROR, 6, G_TX_NOLOD, G_TX_WRAP | G_TX_NOMIRROR, 5, G_TX_NOLOD
gsDPSetTileSize 0, 0, 0, 124, 252
gsSPDisplayList bowser_3_seg7_dl_07003F38
gsSPTexture -1, -1, 0, 0, 0
gsDPPipeSync
gsDPSetCombineMode G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsSPSetGeometryMode G_SHADING_SMOOTH
gsSPEndDisplayList

bowser_3_seg7_light_07004030: # 0x07004030 - 0x07004038
.byte 0x22, 0x22, 0x22, 0x00, 0x22, 0x22, 0x22, 0x00

bowser_3_seg7_light_07004038: # 0x07004038 - 0x07004048
.byte 0x89, 0x89, 0x8A, 0x00, 0x89, 0x89, 0x8A, 0x00
.byte 0x28, 0x28, 0x28, 0x00, 0x00, 0x00, 0x00, 0x00

bowser_3_seg7_light_07004048: # 0x07004048 - 0x07004050
.byte 0x3F, 0x3F, 0x3F, 0x00, 0x3F, 0x3F, 0x3F, 0x00

bowser_3_seg7_light_07004050: # 0x07004050 - 0x07004060
.byte 0xFF, 0xFF, 0xFF, 0x00, 0xFF, 0xFF, 0xFF, 0x00
.byte 0x28, 0x28, 0x28, 0x00, 0x00, 0x00, 0x00, 0x00

bowser_3_seg7_vertex_07004060: # 0x07004060 - 0x07004160
vertex  -1182,  -2364,    394,   2232,     24,  0xD8, 0x89, 0xF5, 0xFF
vertex  -2364,  -1852,   -787,   3412,   1202,  0xD8, 0x89, 0xF5, 0xFF
vertex   -787,  -2364,  -1024,   3648,   -370,  0xD8, 0x89, 0xF5, 0xFF
vertex  -1182,  -2364,    394,   2232,     24,  0xE9, 0x88, 0x20, 0xFF
vertex      0,  -2364,   1262,   1366,  -1156,  0xE9, 0x88, 0x20, 0xFF
vertex  -1497,  -1852,   2050,    580,    338,  0xE9, 0x88, 0x20, 0xFF
vertex      0,  -2364,   1262,   1366,  -1156,  0x00, 0x81, 0x00, 0xFF
vertex  -1182,  -2364,    394,   2232,     24,  0x00, 0x81, 0x00, 0xFF
vertex   -787,  -2364,  -1024,   3648,   -370,  0x00, 0x81, 0x00, 0xFF
vertex   -787,  -2364,  -1024,   3648,   -370,  0x00, 0x88, 0xD7, 0xFF
vertex      0,  -1852,  -2522,   5144,  -1156,  0x00, 0x88, 0xD7, 0xFF
vertex    788,  -2364,  -1024,   3648,  -1944,  0x00, 0x88, 0xD7, 0xFF
vertex    788,  -2364,  -1024,   3648,  -1944,  0x00, 0x81, 0x00, 0xFF
vertex   1498,  -1852,   2050,    580,  -2652,  0x17, 0x88, 0x20, 0xFF
vertex      0,  -2364,   1262,   1366,  -1156,  0x17, 0x88, 0x20, 0xFF
vertex   1183,  -2364,    394,   2232,  -2336,  0x17, 0x88, 0x20, 0xFF

bowser_3_seg7_vertex_07004160: # 0x07004160 - 0x070041C0
vertex      0,  -2364,   1262,   1366,  -1156,  0x00, 0x81, 0x00, 0xFF
vertex    788,  -2364,  -1024,   3648,  -1944,  0x00, 0x81, 0x00, 0xFF
vertex   1183,  -2364,    394,   2232,  -2336,  0x00, 0x81, 0x00, 0xFF
vertex   1183,  -2364,    394,   2232,  -2336,  0x28, 0x89, 0xF5, 0xFF
vertex    788,  -2364,  -1024,   3648,  -1944,  0x28, 0x89, 0xF5, 0xFF
vertex   2365,  -1852,   -787,   3412,  -3518,  0x28, 0x89, 0xF5, 0xFF

bowser_3_seg7_vertex_070041C0: # 0x070041C0 - 0x07004260
vertex  -2364,    307,   -787,   -582,  -1714,  0x00, 0x7F, 0x00, 0xFF
vertex  -1182,    307,    394,    204,   -928,  0x00, 0x7F, 0x00, 0xFF
vertex   -787,    307,  -1024,    466,  -1872,  0x00, 0x7F, 0x00, 0xFF
vertex      0,    307,   1262,    990,   -350,  0x00, 0x7F, 0x00, 0xFF
vertex  -1497,    307,   2050,     -6,    174,  0x00, 0x7F, 0x00, 0xFF
vertex   1183,    307,    394,   1776,   -928,  0x00, 0x7F, 0x00, 0xFF
vertex    788,    307,  -1024,   1514,  -1872,  0x00, 0x7F, 0x00, 0xFF
vertex      0,    307,  -2522,    990,  -2870,  0x00, 0x7F, 0x00, 0xFF
vertex   1498,    307,   2050,   1986,    174,  0x00, 0x7F, 0x00, 0xFF
vertex   2365,    307,   -787,   2564,  -1714,  0x00, 0x7F, 0x00, 0xFF

bowser_3_seg7_vertex_07004260: # 0x07004260 - 0x07004350
vertex      0,  -1852,  -2522,    990,   2012,  0x70, 0x00, 0xC5, 0xFF
vertex      0,    307,  -2522,    990,      0,  0x70, 0x00, 0xC5, 0xFF
vertex    788,  -2364,  -1024,   -698,   2012,  0x70, 0x00, 0xC5, 0xFF
vertex   2365,  -1852,   -787,    990,   2012,  0x59, 0x00, 0x59, 0xFF
vertex   1183,    307,    394,   -678,      0,  0x59, 0x00, 0x59, 0xFF
vertex   1183,  -2364,    394,   -678,   2012,  0x59, 0x00, 0x59, 0xFF
vertex   2365,    307,   -787,    990,      0,  0x59, 0x00, 0x59, 0xFF
vertex   1183,  -2364,    394,   -690,   2012,  0x7C, 0x00, 0xE9, 0xFF
vertex   1498,    307,   2050,    990,      0,  0x7C, 0x00, 0xE9, 0xFF
vertex   1498,  -1852,   2050,    990,   2012,  0x7C, 0x00, 0xE9, 0xFF
vertex   1183,    307,    394,   -690,      0,  0x7C, 0x00, 0xE9, 0xFF
vertex   -787,  -2364,  -1024,   -698,   2012,  0x90, 0x00, 0xC5, 0xFF
vertex   -787,    307,  -1024,   -698,      0,  0x90, 0x00, 0xC5, 0xFF
vertex      0,    307,  -2522,    990,      0,  0x90, 0x00, 0xC5, 0xFF
vertex      0,  -1852,  -2522,    990,   2012,  0x90, 0x00, 0xC5, 0xFF

bowser_3_seg7_vertex_07004350: # 0x07004350 - 0x07004440
vertex   1498,  -1852,   2050,    990,   2012,  0xC5, 0x00, 0x70, 0xFF
vertex   1498,    307,   2050,    990,      0,  0xC5, 0x00, 0x70, 0xFF
vertex      0,    307,   1262,   -698,      0,  0xC5, 0x00, 0x70, 0xFF
vertex      0,    307,  -2522,    990,      0,  0x70, 0x00, 0xC5, 0xFF
vertex    788,    307,  -1024,   -698,      0,  0x70, 0x00, 0xC5, 0xFF
vertex    788,  -2364,  -1024,   -698,   2012,  0x70, 0x00, 0xC5, 0xFF
vertex  -2364,    307,   -787,    990,      0,  0xEE, 0x00, 0x83, 0xFF
vertex   -787,    307,  -1024,   -600,      0,  0xEE, 0x00, 0x83, 0xFF
vertex   -787,  -2364,  -1024,   -600,   2012,  0xEE, 0x00, 0x83, 0xFF
vertex  -2364,  -1852,   -787,    990,   2012,  0xEE, 0x00, 0x83, 0xFF
vertex    788,  -2364,  -1024,   -600,   2012,  0x12, 0x00, 0x83, 0xFF
vertex   2365,    307,   -787,    990,      0,  0x12, 0x00, 0x83, 0xFF
vertex   2365,  -1852,   -787,    990,   2012,  0x12, 0x00, 0x83, 0xFF
vertex    788,    307,  -1024,   -600,      0,  0x12, 0x00, 0x83, 0xFF
vertex      0,  -2364,   1262,   -698,   2012,  0xC5, 0x00, 0x70, 0xFF

bowser_3_seg7_vertex_07004440: # 0x07004440 - 0x07004500
vertex      0,  -2364,   1262,   -698,   2012,  0x3B, 0x00, 0x70, 0xFF
vertex      0,    307,   1262,   -698,      0,  0x3B, 0x00, 0x70, 0xFF
vertex  -1497,    307,   2050,    990,      0,  0x3B, 0x00, 0x70, 0xFF
vertex  -1497,  -1852,   2050,    990,   2012,  0x3B, 0x00, 0x70, 0xFF
vertex  -1497,  -1852,   2050,    990,   2012,  0x84, 0x00, 0xE9, 0xFF
vertex  -1497,    307,   2050,    990,      0,  0x84, 0x00, 0xE9, 0xFF
vertex  -1182,    307,    394,   -690,      0,  0x84, 0x00, 0xE9, 0xFF
vertex  -1182,  -2364,    394,   -690,   2012,  0x84, 0x00, 0xE9, 0xFF
vertex  -1182,  -2364,    394,   -678,   2012,  0xA7, 0x00, 0x59, 0xFF
vertex  -2364,    307,   -787,    990,      0,  0xA7, 0x00, 0x59, 0xFF
vertex  -2364,  -1852,   -787,    990,   2012,  0xA7, 0x00, 0x59, 0xFF
vertex  -1182,    307,    394,   -678,      0,  0xA7, 0x00, 0x59, 0xFF

bowser_3_seg7_dl_07004500: # 0x07004500 - 0x070045D8
gsDPSetTextureImage G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, bowser_3_seg7_texture_07000800
gsDPLoadSync
gsDPLoadBlock 7, 0, 0, 0x3FF, 0x100
gsSPLight bowser_3_seg7_light_07004038, 1
gsSPLight bowser_3_seg7_light_07004030, 2
gsSPVertex bowser_3_seg7_vertex_07004060, 16, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  3,  4,  5, 0x0
gsSP1Triangle  6,  7,  8, 0x0
gsSP1Triangle  9, 10, 11, 0x0
gsSP1Triangle  6,  8, 12, 0x0
gsSP1Triangle 13, 14, 15, 0x0
gsSPVertex bowser_3_seg7_vertex_07004160, 6, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  3,  4,  5, 0x0
gsSPLight bowser_3_seg7_light_07004050, 1
gsSPLight bowser_3_seg7_light_07004048, 2
gsSPVertex bowser_3_seg7_vertex_070041C0, 10, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  2,  1,  3, 0x0
gsSP1Triangle  1,  4,  3, 0x0
gsSP1Triangle  2,  3,  5, 0x0
gsSP1Triangle  2,  5,  6, 0x0
gsSP1Triangle  6,  7,  2, 0x0
gsSP1Triangle  3,  8,  5, 0x0
gsSP1Triangle  5,  9,  6, 0x0
gsSPEndDisplayList

bowser_3_seg7_dl_070045D8: # 0x070045D8 - 0x070046B0
gsDPSetTextureImage G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, bowser_3_seg7_texture_07001000
gsDPLoadSync
gsDPLoadBlock 7, 0, 0, 0x7FF, 0x100
gsSPVertex bowser_3_seg7_vertex_07004260, 15, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  3,  4,  5, 0x0
gsSP1Triangle  3,  6,  4, 0x0
gsSP1Triangle  7,  8,  9, 0x0
gsSP1Triangle  7, 10,  8, 0x0
gsSP1Triangle 11, 12, 13, 0x0
gsSP1Triangle 11, 13, 14, 0x0
gsSPVertex bowser_3_seg7_vertex_07004350, 15, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  3,  4,  5, 0x0
gsSP1Triangle  6,  7,  8, 0x0
gsSP1Triangle  9,  6,  8, 0x0
gsSP1Triangle 10, 11, 12, 0x0
gsSP1Triangle 10, 13, 11, 0x0
gsSP1Triangle  0,  2, 14, 0x0
gsSPVertex bowser_3_seg7_vertex_07004440, 12, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  0,  2,  3, 0x0
gsSP1Triangle  4,  5,  6, 0x0
gsSP1Triangle  4,  6,  7, 0x0
gsSP1Triangle  8,  9, 10, 0x0
gsSP1Triangle  8, 11,  9, 0x0
gsSPEndDisplayList

glabel bowser_3_seg7_dl_070046B0 # 0x070046B0 - 0x07004740
gsDPPipeSync
gsDPSetCombineMode G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsSPClearGeometryMode G_SHADING_SMOOTH
gsDPSetTile G_IM_FMT_RGBA, G_IM_SIZ_16b, 0, 0, G_TX_LOADTILE, 0, G_TX_WRAP | G_TX_NOMIRROR, G_TX_NOMASK, G_TX_NOLOD, G_TX_WRAP | G_TX_NOMIRROR, G_TX_NOMASK, G_TX_NOLOD
gsSPTexture -1, -1, 0, 0, 1
gsDPTileSync
gsDPSetTile G_IM_FMT_RGBA, G_IM_SIZ_16b, 8, 0, G_TX_RENDERTILE, 0, G_TX_WRAP | G_TX_NOMIRROR, 5, G_TX_NOLOD, G_TX_WRAP | G_TX_NOMIRROR, 5, G_TX_NOLOD
gsDPSetTileSize 0, 0, 0, 124, 124
gsSPDisplayList bowser_3_seg7_dl_07004500
gsDPTileSync
gsDPSetTile G_IM_FMT_RGBA, G_IM_SIZ_16b, 8, 0, G_TX_RENDERTILE, 0, G_TX_WRAP | G_TX_NOMIRROR, 6, G_TX_NOLOD, G_TX_WRAP | G_TX_NOMIRROR, 5, G_TX_NOLOD
gsDPSetTileSize 0, 0, 0, 124, 252
gsSPDisplayList bowser_3_seg7_dl_070045D8
gsSPTexture -1, -1, 0, 0, 0
gsDPPipeSync
gsDPSetCombineMode G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsSPSetGeometryMode G_SHADING_SMOOTH
gsSPEndDisplayList

bowser_3_seg7_light_07004740: # 0x07004740 - 0x07004748
.byte 0x3F, 0x3F, 0x3F, 0x00, 0x3F, 0x3F, 0x3F, 0x00

bowser_3_seg7_light_07004748: # 0x07004748 - 0x07004758
.byte 0xFF, 0xFF, 0xFF, 0x00, 0xFF, 0xFF, 0xFF, 0x00
.byte 0x28, 0x28, 0x28, 0x00, 0x00, 0x00, 0x00, 0x00

bowser_3_seg7_vertex_07004758: # 0x07004758 - 0x07004848
vertex    205,    256,      0,    478,    478,  0x4D, 0x3E, 0xB2, 0xFF
vertex      0,    256,   -204,    734,    478,  0x4D, 0x3E, 0xB2, 0xFF
vertex      0,    512,      0,    606,      0,  0x4D, 0x3E, 0xB2, 0xFF
vertex      0,    256,    205,    224,    480,  0x4E, 0x3E, 0x4E, 0xFF
vertex    205,    256,      0,    478,    478,  0x4E, 0x3E, 0x4E, 0xFF
vertex      0,    512,      0,    352,      0,  0x4E, 0x3E, 0x4E, 0xFF
vertex    205,    256,      0,    478,    478,  0x4E, 0xC2, 0x4E, 0xFF
vertex      0,    256,    205,    224,    480,  0x4E, 0xC2, 0x4E, 0xFF
vertex      0,      0,      0,    352,    990,  0x4E, 0xC2, 0x4E, 0xFF
vertex      0,    256,   -204,    734,    478,  0x4D, 0xC2, 0xB2, 0xFF
vertex    205,    256,      0,    478,    478,  0x4D, 0xC2, 0xB2, 0xFF
vertex      0,      0,      0,    606,    990,  0x4D, 0xC2, 0xB2, 0xFF
vertex   -204,    256,      0,      0,    480,  0xB2, 0x3E, 0x4D, 0xFF
vertex      0,    256,    205,    224,    480,  0xB2, 0x3E, 0x4D, 0xFF
vertex      0,    512,      0,     96,      0,  0xB2, 0x3E, 0x4D, 0xFF

bowser_3_seg7_vertex_07004848: # 0x07004848 - 0x070048D8
vertex      0,    256,    205,    224,    480,  0xB2, 0xC2, 0x4D, 0xFF
vertex   -204,    256,      0,      0,    480,  0xB2, 0xC2, 0x4D, 0xFF
vertex      0,      0,      0,     96,    990,  0xB2, 0xC2, 0x4D, 0xFF
vertex      0,    256,   -204,    734,    478,  0xB2, 0x3E, 0xB2, 0xFF
vertex   -204,    256,      0,    990,    480,  0xB2, 0x3E, 0xB2, 0xFF
vertex      0,    512,      0,    862,      0,  0xB2, 0x3E, 0xB2, 0xFF
vertex   -204,    256,      0,    990,    480,  0xB2, 0xC2, 0xB2, 0xFF
vertex      0,    256,   -204,    734,    478,  0xB2, 0xC2, 0xB2, 0xFF
vertex      0,      0,      0,    862,    990,  0xB2, 0xC2, 0xB2, 0xFF

bowser_3_seg7_dl_070048D8: # 0x070048D8 - 0x07004958
gsDPSetTextureImage G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, bowser_3_seg7_texture_07000000
gsDPLoadSync
gsDPLoadBlock 7, 0, 0, 0x3FF, 0x100
gsSPLight bowser_3_seg7_light_07004748, 1
gsSPLight bowser_3_seg7_light_07004740, 2
gsSPVertex bowser_3_seg7_vertex_07004758, 15, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  3,  4,  5, 0x0
gsSP1Triangle  6,  7,  8, 0x0
gsSP1Triangle  9, 10, 11, 0x0
gsSP1Triangle 12, 13, 14, 0x0
gsSPVertex bowser_3_seg7_vertex_07004848, 9, 0
gsSP1Triangle  0,  1,  2, 0x0
gsSP1Triangle  3,  4,  5, 0x0
gsSP1Triangle  6,  7,  8, 0x0
gsSPEndDisplayList

glabel bowser_3_seg7_dl_07004958 # 0x07004958 - 0x070049C8
gsDPPipeSync
gsDPSetCombineMode G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsSPClearGeometryMode G_SHADING_SMOOTH
gsDPSetTile G_IM_FMT_RGBA, G_IM_SIZ_16b, 0, 0, G_TX_LOADTILE, 0, G_TX_WRAP | G_TX_NOMIRROR, G_TX_NOMASK, G_TX_NOLOD, G_TX_WRAP | G_TX_NOMIRROR, G_TX_NOMASK, G_TX_NOLOD
gsSPTexture -1, -1, 0, 0, 1
gsDPTileSync
gsDPSetTile G_IM_FMT_RGBA, G_IM_SIZ_16b, 8, 0, G_TX_RENDERTILE, 0, G_TX_WRAP | G_TX_NOMIRROR, 5, G_TX_NOLOD, G_TX_WRAP | G_TX_NOMIRROR, 5, G_TX_NOLOD
gsDPSetTileSize 0, 0, 0, 124, 124
gsSPDisplayList bowser_3_seg7_dl_070048D8
gsSPTexture -1, -1, 0, 0, 0
gsDPPipeSync
gsDPSetCombineMode G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsSPSetGeometryMode G_SHADING_SMOOTH
gsSPEndDisplayList

glabel bowser_3_seg7_collision_level # 0x070049C8 - 0x07004B94
# collision vertices
.hword 0x0040, 0x0018
.hword -8191, -6143,  8192
.hword  8192, -6143,  8192
.hword  8192, -6143, -8191
.hword -8191, -6143, -8191
.hword -1182, -2364,   394
.hword -1182,   307,   394
.hword -2364,   307,  -787
.hword -2364, -1852,  -787
.hword  -787,   307, -1024
.hword  -787, -2364, -1024
.hword -1497, -1852,  2050
.hword -1497,   307,  2050
.hword     0,   307,  1262
.hword   788,   307, -1024
.hword     0,   307, -2522
.hword  1183,   307,   394
.hword  1498, -1852,  2050
.hword  1498,   307,  2050
.hword     0, -2364,  1262
.hword  2365,   307,  -787
.hword  2365, -1852,  -787
.hword  1183, -2364,   394
.hword   788, -2364, -1024
.hword     0, -1852, -2522
# collision 0x00 normal
.hword 0x0000,   36
.hword    4,   18,   10
.hword    4,    5,    6
.hword    4,    6,    7
.hword    6,    5,    8
.hword    6,    8,    9
.hword    7,    6,    9
.hword   10,    5,    4
.hword   10,   11,    5
.hword    5,   11,   12
.hword    8,    5,   12
.hword   13,   14,    8
.hword    8,   12,   15
.hword    8,   15,   13
.hword    9,    8,   14
.hword   16,   17,   12
.hword   16,   12,   18
.hword   18,   12,   11
.hword   12,   17,   15
.hword   18,   11,   10
.hword   18,    4,    9
.hword    4,    7,    9
.hword    9,   23,   22
.hword   15,   19,   13
.hword   20,   19,   15
.hword   20,   15,   21
.hword   21,   15,   17
.hword   22,   13,   19
.hword   14,   13,   22
.hword   23,   14,   22
.hword    9,   14,   23
.hword   22,   19,   20
.hword   21,   17,   16
.hword   21,   22,   20
.hword   18,   22,   21
.hword   16,   18,   21
.hword   18,    9,   22
# collision 0x0A deathfloor
.hword 0x000A,    2
.hword    0,    1,    2
.hword    0,    2,    3
.hword 0x0041
# special objects 0x43
.hword 0x0043,    7 # add 7 special objects
special_object_10_byte /*preset*/ special_null_start,   /*pos*/     0,   307,     0, /*yaw*/  128 # unused, probably an early way to set intial position
special_object_8_byte  /*preset*/ special_bowser,       /*pos*/    13,   307, -1024
special_object_10_byte /*preset*/ special_level_geo_03, /*pos*/ -3362,  -204,  1121, /*yaw*/    0
special_object_10_byte /*preset*/ special_level_geo_03, /*pos*/     0,  -204,  3584, /*yaw*/    0
special_object_10_byte /*preset*/ special_level_geo_03, /*pos*/  3362,  -204,  1126, /*yaw*/    0
special_object_10_byte /*preset*/ special_level_geo_03, /*pos*/  2123,  -204, -2912, /*yaw*/    0
special_object_10_byte /*preset*/ special_level_geo_03, /*pos*/ -2122,  -204, -2912, /*yaw*/    0
.hword 0x0042

glabel bowser_3_seg7_collision_07004B94 # 0x07004B94 - 0x07004C18
# collision vertices
.hword 0x0040, 0x0008
.hword -3071,   307, -1023
.hword -2364,   307,  -787
.hword  -787,   307, -1024
.hword -3071, -1340, -1023
.hword -2364, -1852,  -787
.hword -1945,   307, -2661
.hword -1945, -1340, -2661
.hword  -787, -2364, -1024
# collision 0x00 normal
.hword 0x0000,   12
.hword    0,    1,    2
.hword    1,    0,    3
.hword    1,    3,    4
.hword    2,    1,    4
.hword    0,    2,    5
.hword    0,    5,    6
.hword    3,    0,    6
.hword    6,    4,    3
.hword    6,    7,    4
.hword    7,    2,    4
.hword    5,    2,    7
.hword    6,    5,    7
.hword 0x0041
.hword 0x0042

glabel bowser_3_seg7_collision_07004C18 # 0x07004C18 - 0x07004C9C
# collision vertices
.hword 0x0040, 0x0008
.hword -1182, -2364,   394
.hword -1182,   307,   394
.hword -3071,   307,  1024
.hword -3071, -1340,  1024
.hword -2364,   307,  -787
.hword -3071,   307, -1023
.hword -2364, -1852,  -787
.hword -3071, -1340, -1023
# collision 0x00 normal
.hword 0x0000,   12
.hword    0,    1,    2
.hword    0,    2,    3
.hword    2,    1,    4
.hword    2,    4,    5
.hword    3,    2,    5
.hword    4,    1,    0
.hword    4,    0,    6
.hword    7,    5,    4
.hword    7,    4,    6
.hword    3,    5,    7
.hword    6,    0,    3
.hword    6,    3,    7
.hword 0x0041
.hword 0x0042

glabel bowser_3_seg7_collision_07004C9C # 0x07004C9C - 0x07004D20
# collision vertices
.hword 0x0040, 0x0008
.hword -1497,   307,  2050
.hword -1945, -1340,  2662
.hword -1497, -1852,  2050
.hword -3071, -1340,  1024
.hword -1945,   307,  2662
.hword -3071,   307,  1024
.hword -1182,   307,   394
.hword -1182, -2364,   394
# collision 0x00 normal
.hword 0x0000,   12
.hword    0,    1,    2
.hword    3,    2,    1
.hword    0,    4,    1
.hword    1,    4,    5
.hword    1,    5,    3
.hword    5,    4,    0
.hword    3,    5,    6
.hword    5,    0,    6
.hword    3,    6,    7
.hword    3,    7,    2
.hword    7,    6,    0
.hword    7,    0,    2
.hword 0x0041
.hword 0x0042

glabel bowser_3_seg7_collision_07004D20 # 0x07004D20 - 0x07004DA4
# collision vertices
.hword 0x0040, 0x0008
.hword -1945,   307,  2662
.hword     0,   307,  3277
.hword     0,   307,  1262
.hword -1497,   307,  2050
.hword     0, -1340,  3277
.hword -1945, -1340,  2662
.hword -1497, -1852,  2050
.hword     0, -2364,  1262
# collision 0x00 normal
.hword 0x0000,   12
.hword    0,    1,    2
.hword    0,    2,    3
.hword    4,    1,    0
.hword    4,    0,    5
.hword    0,    3,    6
.hword    5,    0,    6
.hword    2,    1,    4
.hword    7,    2,    4
.hword    3,    2,    7
.hword    3,    7,    6
.hword    6,    4,    5
.hword    6,    7,    4
.hword 0x0041
.hword 0x0042

glabel bowser_3_seg7_collision_07004DA4 # 0x07004DA4 - 0x07004E28
# collision vertices
.hword 0x0040, 0x0008
.hword  1498,   307,  2050
.hword  1946,   307,  2662
.hword  1946, -1340,  2662
.hword  1498, -1852,  2050
.hword     0, -2364,  1262
.hword     0,   307,  1262
.hword     0,   307,  3277
.hword     0, -1340,  3277
# collision 0x00 normal
.hword 0x0000,   12
.hword    0,    1,    2
.hword    0,    2,    3
.hword    4,    5,    0
.hword    4,    0,    3
.hword    6,    1,    0
.hword    6,    0,    5
.hword    2,    1,    6
.hword    2,    6,    7
.hword    3,    2,    7
.hword    4,    3,    7
.hword    6,    5,    4
.hword    7,    6,    4
.hword 0x0041
.hword 0x0042

glabel bowser_3_seg7_collision_07004E28 # 0x07004E28 - 0x07004EAC
# collision vertices
.hword 0x0040, 0x0008
.hword  1183, -2364,   394
.hword  1183,   307,   394
.hword  3072,   307,  1024
.hword  3072, -1340,  1024
.hword  1498,   307,  2050
.hword  1946,   307,  2662
.hword  1498, -1852,  2050
.hword  1946, -1340,  2662
# collision 0x00 normal
.hword 0x0000,   12
.hword    0,    1,    2
.hword    0,    2,    3
.hword    2,    1,    4
.hword    2,    4,    5
.hword    3,    2,    5
.hword    4,    1,    6
.hword    1,    0,    6
.hword    7,    5,    4
.hword    7,    4,    6
.hword    3,    5,    7
.hword    0,    3,    6
.hword    3,    7,    6
.hword 0x0041
.hword 0x0042

glabel bowser_3_seg7_collision_07004EAC # 0x07004EAC - 0x07004F30
# collision vertices
.hword 0x0040, 0x0008
.hword  3072,   307,  1024
.hword  2365,   307,  -787
.hword  1183,   307,   394
.hword  3072,   307, -1023
.hword  3072, -1340, -1023
.hword  2365, -1852,  -787
.hword  1183, -2364,   394
.hword  3072, -1340,  1024
# collision 0x00 normal
.hword 0x0000,   12
.hword    0,    1,    2
.hword    0,    3,    1
.hword    1,    3,    4
.hword    1,    4,    5
.hword    6,    2,    1
.hword    6,    1,    5
.hword    4,    3,    0
.hword    7,    5,    4
.hword    4,    0,    7
.hword    7,    6,    5
.hword    7,    2,    6
.hword    7,    0,    2
.hword 0x0041
.hword 0x0042

glabel bowser_3_seg7_collision_07004F30 # 0x07004F30 - 0x07004FB4
# collision vertices
.hword 0x0040, 0x0008
.hword   788, -2364, -1024
.hword  1946,   307, -2661
.hword  1946, -1340, -2661
.hword  2365, -1852,  -787
.hword  3072, -1340, -1023
.hword  3072,   307, -1023
.hword   788,   307, -1024
.hword  2365,   307,  -787
# collision 0x00 normal
.hword 0x0000,   12
.hword    0,    1,    2
.hword    3,    0,    2
.hword    3,    2,    4
.hword    2,    1,    5
.hword    2,    5,    4
.hword    0,    6,    1
.hword    6,    5,    1
.hword    6,    7,    5
.hword    4,    5,    7
.hword    4,    7,    3
.hword    7,    6,    3
.hword    6,    0,    3
.hword 0x0041
.hword 0x0042

glabel bowser_3_seg7_collision_07004FB4 # 0x07004FB4 - 0x07005038
# collision vertices
.hword 0x0040, 0x0008
.hword     0, -1340, -3276
.hword     0,   307, -3276
.hword  1946,   307, -2661
.hword     0, -1852, -2522
.hword     0,   307, -2522
.hword   788,   307, -1024
.hword  1946, -1340, -2661
.hword   788, -2364, -1024
# collision 0x00 normal
.hword 0x0000,   12
.hword    0,    1,    2
.hword    1,    0,    3
.hword    4,    1,    3
.hword    1,    4,    5
.hword    1,    5,    2
.hword    0,    2,    6
.hword    3,    0,    6
.hword    7,    3,    6
.hword    5,    4,    3
.hword    7,    5,    3
.hword    6,    2,    5
.hword    6,    5,    7
.hword 0x0041
.hword 0x0042

glabel bowser_3_seg7_collision_07005038 # 0x07005038 - 0x070050BC
# collision vertices
.hword 0x0040, 0x0008
.hword  -787,   307, -1024
.hword -1945,   307, -2661
.hword -1945, -1340, -2661
.hword  -787, -2364, -1024
.hword     0,   307, -2522
.hword     0,   307, -3276
.hword     0, -1852, -2522
.hword     0, -1340, -3276
# collision 0x00 normal
.hword 0x0000,   12
.hword    0,    1,    2
.hword    3,    0,    2
.hword    4,    0,    3
.hword    0,    4,    5
.hword    0,    5,    1
.hword    4,    3,    6
.hword    7,    5,    4
.hword    7,    4,    6
.hword    2,    1,    5
.hword    2,    5,    7
.hword    7,    6,    2
.hword    6,    3,    2
.hword 0x0041
.hword 0x0042

