#ifndef _OBJ_BEHAVIORS_H
#define _OBJ_BEHAVIORS_H

#include "types.h"

extern s8 D_80331508;
extern s8 D_80331500;
extern struct Surface *D_803600E0;
extern s16 D_80331504;
extern s8 D_8033150C;
extern s8 D_80331510;
extern s32 D_80331514; /* most likely some sort of struct or array */
extern s32 D_80331524;
extern s32 D_80331534;
extern s32 D_80331544;
extern s16 D_803600B0[10];
extern s32 D_80331554;

struct Struct802E2F58
{
    s32 unk0[2];
    s32 unk8[2];
    u8 filler10[0x8];
};

/*

struct UnknownWhirpoolData
{
    s8 filler[2];
    Vec3s unk2;

    Vec3s unk8;

    s16 unkE;
    s16 unk10;
    s16 unk12;
};

*/

// extern ? D_80331564;
// extern ? D_80331574;
// extern ? D_80331584;
// extern ? D_80331594;
// extern ? D_803315A4;
// extern ? D_07011530;
// extern ? D_070170A0;
// extern ? D_070115C4;
// extern ? D_803315B4;
// extern ? D_80331608;
// extern ? D_80331654;
// extern ? D_070165A8;
// extern ? D_80331664;
// extern ? D_80331674;
// extern ? D_80331684;
// extern ? D_80331694;
// extern ? D_80331698;
// extern ? D_803316EC;
// extern ? D_803316A8;
// extern ? D_803316FC;
// extern ? D_8033170C;
// extern ? D_07079068;
// extern ? D_8033171C;

void func_802E2F40(void);
struct Struct802E2F58 *func_802E2F58(s32 arg0, struct Object *arg1, UNUSED s32 arg2); /* likely unused */
float func_802E3058(f32 f);
void TurnObjAwayFromSurface(f32 objVelX, f32 objVelZ, f32 nX, UNUSED f32 nY, f32 nZ, f32 *objYawX, f32 *objYawZ);
s32 ObjFindWall(f32 objNewX, f32 objY, f32 objNewZ, f32 objVelX, f32 objVelZ);
s32 TurnObjAwayFromAwkwardFloor(struct Surface *objFloor, f32 floorY, f32 objVelX, f32 objVelZ);
void ObjOrientGraph(struct Object *obj, f32 normalX, f32 normalY, f32 normalZ);
void CalcObjGroundFVelMultiplier(f32 *objGroundFVelMultPtr, f32 floor_nY);
void CalcNewObjVelAndPosY(struct Surface* objFloor, f32 objFloorY, f32 objVelX, f32 arg3);
void CalcNewObjVelAndPosYUnderwater(struct Surface* objFloor, f32 floorY, f32 objVelX, f32 objVelZ, f32 waterY);
void ObjUpdatePosVelXZ(void);
void ObjSplash(s32 waterY, s32 objY);
s16 ObjectStep(void);
s16 func_802E4204(void);
void func_802E4250(struct Object* obj);
s32 IsPointCloseToMario(f32 x, f32 y, f32 z, s32 dist);
s32 IsPointCloseToObject(struct Object* obj, f32 x, f32 y, f32 z, s32 dist);
void SetObjectVisibility(struct Object* obj, s32 arg1);
s32 ObjLeaveIfMarioIsHome(struct Object* obj, f32 arg1, f32 arg2, f32 arg3, s32 arg4);
void func_802E45A0(struct Object* obj, f32 arg1, UNUSED f32 arg2, f32 arg3, s32 arg4);
s32 func_802E46C0(u32 arg0, u32 arg1, s16 arg2);
s32 func_802E478C(Vec3f dist, f32 x, f32 y, f32 z, f32 arg4);
void func_802E4850(struct Object *obj, s32 arg1);
s32 ObjFlickerAndDisappear(struct Object *obj, s16 arg1);
s8 func_802E49A4(s16 arg0);
s16 func_802E4A38(s32 *arg0, s16 arg1, f32 arg2, s32 arg3);
void ObjCheckFloorDeath(s16 collisionFlags, struct Surface *floor);
s32 func_802E4C08(void);
void func_802E4D5C(s8 arg0, s16 arg1, s16 arg2, s16 arg3);
s32 Unknown802E4DF4(s16 *arg0);
s32 CoinStep(s16 *collisionFlagsPtr);
void MovingCoinBlinkingLoop(void);
void CoinCollected(void);
void BehMovingYellowCoinInit(void);
void BehMovingYellowCoinLoop(void);
void BehMovingBlueCoinInit(void);
void BehMovingBlueCoinLoop(void);
void BehBlueCoinSlidingJumpingInit(void);
void func_802E540C(void); /* likely unused */
void func_802E54DC(void); /* likely unused */
void BehBlueCoinSlidingLoop(void); /* likely unused */
void BehBlueCoinJumpingLoop(void); /* likely unused */
void BehSeaweedInit(void);
void BehSeaweedBundleInit(void);
void BehBobombInit(void);
void func_802E5B7C(void);
void BobombExplodeLoop(void);
void CheckBobombInteractions(void);
void BobombPatrolLoop(void);
void BobombChaseMarioLoop(void);
void BobombActThrownLoop(void);
void GenericBobombFreeLoop(void);
void StationaryBobombFreeLoop(void);
void BobombFreeLoop(void);
void BobombHeldLoop(void);
void BobombDroppedLoop(void);
void BobombHeldThrownLoop(void);
void ObjRandomBlink(s32 *blinkTimer);
void BehBobombLoop(void);
void BehBobombFuseSmokeInit(void);
void BehBobombBuddyInit(void);
void BobombBuddyIdleLoop(void);
void BobombBuddyCannonLoop(s16 arg0, s16 arg1);
void BobombBuddyTalkLoop(void);
void BobombBuddyTurnToTalkLoop(void);
void BobombBuddyActionLoop(void);
void BehBobombBuddyLoop(void);
void BehCannonTrapDoorInit(void);
void CannonTrapDoorOpeningLoop(void);
void BehCannonTrapDoorLoop(void);
void BehWhirlpoolInit(void);
void func_802E70A8(void);
void WhirlpoolOrientGraph(void);
void BehWhirlpoolLoop(void);
void BehJetStreamLoop(void);
void BehAmpHomingInit(void);
void CheckAmpAttack(void);
void AmpHomingAppearLoop(void);
void AmpHomingChaseLoop(void);
void AmpHomingGiveUpLoop(void);
void AmpAttackCooldownLoop(void);
void BehAmpHomingLoop(void);
void BehAmpInit(void);
void FixedAmpIdleLoop(void);
void AmpIdleLoop(void);
void BehAmpLoop(void);
void BehButterflyInit(void);
void ButterflyStep(s32 speed);
void CalculateButterflyAngle(void);
void ButterflyRestingLoop(void);
void ButterflyFollowMarioLoop(void);
void ButterflyReturnHomeLoop(void);
void BehButterflyLoop(void);
void BehHootInit(void);
f32 func_802E88EC(s32 **arg0, f32 arg1);
// extern ? func_802E89B0(?);
// extern ? func_802E8B3C(?);
// extern ? func_802E8DE4(?);
// extern ? func_802E8E88(?);
// extern ? func_802E9050(?);
// extern ? func_802E9234(?);
// extern ? func_802E9348(?);
// extern ? func_802E94E0(?);
// extern ? func_802E95DC(?);
// extern ? BehHootLoop(?);
// extern ? BehBetaGreenShellInit(?);
// extern ? func_802E97E8(?);
// extern ? func_802E984C(?);
// extern ? BehBetaGreenShellLoop(?);
// extern ? BehDirtInit(?);
// extern ? BehDirtLoop(?);
// extern ? BehWaterWaveInit(?);
// extern ? BehWaterWaveLoop(?);
// extern ? BehExplosionInit(?);
// extern ? BehExplosionLoop(?);
// extern ? BehLargeWhiteSmokeCloundInit(?);
// extern ? BehWhiteParticleWaterDropInit(?);
// extern ? BehWhiteParticleWaterDropLoop(?);
// extern ? BehBreakableBoxBackupLoop(?);
extern void func_802EA074(s32 arg0, void *behavior, s32 arg2);
// extern ? BehSmallBullyInit(?);
// extern ? BehBullyBossInit(?);
// extern ? func_802EA2B0(?);
// extern ? func_802EA378(?);
// extern ? func_802EA4E0(?);
// extern ? func_802EA600(?);
// extern ? func_802EA6B4(?);
// extern ? func_802EA720(?);
// extern ? func_802EA834(?);
// extern ? func_802EA8D0(?);
// extern ? func_802EA9A0(?);
// extern ? BehBullyCommonLoop(?);
// extern ? func_802EAC64(?);
// extern ? BehBullyInit(?);
// extern ? func_802EAD78(?);
// extern ? BehBullyLoop(?);
// extern ? func_802EB060(?);
// extern ? func_802EB120(?);
// extern ? BehAirBubbleWaterRingsInit(?);
// extern ? func_802EB2F0(?);
// extern ? func_802EB4A8(?);
// extern ? func_802EB5B8(?);
// extern ? func_802EB674(?);
// extern ? BehAirBubbleWaterRingsLoop(?);
// extern ? Unknown802EB8A4(?);
// extern ? func_802EB8F0(?);
// extern ? BehMantaRingsGeneratorLoop(?);
// extern ? BehAirBubbleWaterRingsUnderwaterInit(?);
// extern ? func_802EBAC8(?);
// extern ? BehAirBubbleWaterRingsUnderwaterLoop(?);
// extern ? BehBowserBombLoop(?);
// extern ? BehSpikeyBombExplosion1Loop(?);
// extern ? BehSpikeyBombExplosion2Loop(?);
// extern ? BehStarCelebrationStarInit(?);
// extern ? func_802EC164(?);
// extern ? func_802EC2E4(?);
// extern ? BehStarCelebrationStarLoop(?);
// extern ? BehKeyGrabSparklesLoop(?);
// extern ? BehSomeWhitePuffLoop(?);
// extern ? BehBasculeBridgeLoop(?);
// extern ? BehLllTiltingBridgeLoop(?);
// extern ? BehRockFormationEyesInit(?);
// extern ? BehRockFormationEyesLoop(?);
// extern ? BehLargeRockEyesInit(?);
// extern ? BehLargeRockEyesLoop(?);
// extern ? BehSlidingBrickPlatform2Init(?);
// extern ? BehSlidingBrickPlatform2Loop(?);
// extern ? BehMoneybagTransformingInit(?);
// extern ? func_802ED1A8(?);
// extern ? func_802ED270(?);
// extern ? func_802ED474(?);
// extern ? func_802ED5A0(?);
// extern ? func_802ED724(?);
// extern ? func_802ED774(?);
// extern ? BehMoneybagTransformingLoop(?);
// extern ? BehMoneybagLoop(?);
// extern ? BehTinyMetalBallInit(?);
// extern ? func_802EDA14(?);
// extern ? func_802EDA6C(?);
// extern ? func_802EDB54(?);
// extern ? func_802EDCA8(?);
// extern ? BehTinyMetalBallLoop(?);
// extern ? BehMetalBallGeneratorInit(?);
// extern ? BehMetalBallGeneratorLoop(?);
// extern ? BehMiniMetalBallGeneratorLoop(?);
// extern ? BehRollingBallInit(?);
// extern ? BehRollingBallLoop(?);
// extern ? BehRollingMetalBallInit(?);
// extern ? func_802EE3E4(?);
// extern ? BehRollingMetalBallLoop(?);
// extern ? BehFlappingWingInit(?);
// extern ? BehFlappingWingLoop(?);
// extern ? BehSpindelInit(?);
// extern ? BehSpindelLoop(?);
// extern ? BehMovingUpAndDownInit(?);
// extern ? BehMovingUpAndDownLoop(?);
// extern ? BehPyramidElevatorInit(?);
// extern ? BehPyramidElevatorLoop(?);
// extern ? BehPyramidElevatorMetalBallsLoop(?);
// extern ? BehPyramidTopInit(?);
// extern ? func_802EF238(?);
// extern ? func_802EF450(?);
// extern ? BehPyramidTopLoop(?);
// extern ? BehPyramidTopExplosionInit(?);
// extern ? BehPyramidTopExplosionLoop(?);
// extern ? BehCollisionBoxSubBehaviorLoop(?);
// extern ? BehWaterfallSoundLoop(?);
// extern ? BehVolcanoSoundLoop(?);
// extern ? BehCastleFlagWavingInit(?);
// extern ? BehBirdsSoundLoop(?);
// extern ? BehAmbiantSoundsInit(?);
// extern ? BehSandSoundLoop(?);
// extern ? BehHiddenAt120StarsInit(?);
// extern ? BehSnowmansBottomInit(?);
// extern ? func_802EFB2C(?);
// extern ? func_802EFB84(?);
// extern ? func_802EFC44(?);
// extern ? func_802EFDA0(?);
// extern ? func_802EFF58(?);
// extern ? BehSnowmansBottomLoop(?);
// extern ? BehSnowmansHeadInit(?);
// extern ? BehSnowmansHeadLoop(?);
// extern ? BehSnowmansBodyCheckpointLoop(?);
// extern ? BehBigBoulderInit(?);
// extern ? func_802F05DC(?);
// extern ? BehBigBoulderLoop(?);
// extern ? BehBigBoulderGeneratorLoop(?);
// extern ? func_802F0904(?);
// extern ? func_802F0978(?);
// extern ? func_802F09C0(?);
// extern ? func_802F0B68(?);
// extern ? BehWingCapInit(?);
// extern ? func_802F0D70(?);
// extern ? func_802F0E0C(?);
// extern ? BehWingVanishCapLoop(?);
// extern ? BehMetalCapInit(?);
// extern ? func_802F0FE0(?);
// extern ? BehMetalCapLoop(?);
// extern ? BehNormalCapInit(?);
// extern ? func_802F1190(?);
// extern ? func_802F1234(?);
// extern ? BehNormalCapLoop(?);
// extern ? BehVanishCapInit(?);
// extern ? BehCollectStarInit(?);
// extern ? BehCollectStarLoop(?);
// extern ? BehStarSpawnInit(?);
// extern ? BehStarSpawnLoop(?);
// extern ? func_802F1A50(?);
extern void CreateStar(f32, f32, f32);
// extern ? func_802F1B84(?);
// extern ? func_802F1BD4(?);
// extern ? BehHiddenRedCoinStarInit(?);
// extern ? BehHiddenRedCoinStarLoop(?);
// extern ? BehRedCoinInit(?);
// extern ? BehRedCoinLoop(?);
// extern ? BehHiddenStarInit(?);
// extern ? BehHiddenStarLoop(?);
// extern ? BehCheckpointLoop(?);
// extern ? BehBowserCourseRedCoinStarLoop(?);
// extern ? BehPitoune2Init(?);
// extern ? func_802F238C(?);
// extern ? BehPitouneLoop(?);
// extern ? func_802F2820(?);
// extern ? func_802F2924(?);
// extern ? BehFallingWhenMarioNearLoop(?);
// extern ? BehPitouneInit(?);
// extern ? func_802F2BC4(?);
// extern ? Beh1UpCommonInit(?);
// extern ? Beh1UpInit(?);
// extern ? func_802F2D40(?);
// extern ? func_802F2E18(?);
// extern ? func_802F2F8C(?);
// extern ? Beh1UpWalkingLoop(?);
// extern ? Beh1UpRunningAwayLoop(?);
// extern ? func_802F3328(?);
// extern ? Beh1UpSlidingLoop(?);
// extern ? Beh1UpLoop(?);
// extern ? Beh1UpJumpOnApproachLoop(?);
// extern ? Beh1UpHiddenLoop(?);
// extern ? Beh1UpHiddenTriggerLoop(?);
// extern ? Beh1UpHiddenTreePoleLoop(?);
// extern ? Beh1UpHiddenTreePoleTriggerLoop(?);
// extern ? Beh1UpHiddenInTreeLoop(?);
// extern ? func_802F3BD8(?);
// extern ? func_802F3C50(?);
// extern ? BehControllablePlatformSubLoop(?);
// extern ? BehControllablePlatformInit(?);
// extern ? func_802F3F80(?);
// extern ? func_802F3FD8(?);
// extern ? func_802F4230(?);
// extern ? func_802F43EC(?);
// extern ? BehControllablePlatformLoop(?);
// extern ? BehBreakableBox2Init(?);
// extern ? func_802F4CE8(?);
// extern ? func_802F4DB4(?);
// extern ? func_802F4EB8(?);
// extern ? func_802F4F84(?);
// extern ? func_802F5048(?);
// extern ? func_802F50C0(?);
// extern ? BehBreakableBox2Loop(?);
// extern ? BehSlidingSnowMoundLoop(?);
// extern ? BehSnowMoundSpawnLoop(?);
// extern ? func_802F54F8(?);
// extern ? func_802F55CC(?);
// extern ? BehFloatingPlatformLoop(?);
// extern ? func_802F59B4(?);
// extern ? func_802F5A9C(?);
// extern ? BehArrowLiftLoop(?);
// extern ? BehOrangeNumberInit(?);
// extern ? BehOrangeNumberLoop(?);
// extern ? BehMantaRayInit(?);
// extern ? func_802F5E20(?);
// extern ? func_802F5FD8(?);
// extern ? BehMantaRayLoop(?);
// extern ? BehFallingPillarInit(?);
// extern ? func_802F6308(?);
// extern ? func_802F6388(?);
// extern ? BehFallingPillarLoop(?);
// extern ? BehSomeSubobjectFallingPillarLoop(?);
// extern ? BehJrbFloatingBoxLoop(?);
// extern ? BehOscillatingPendulumInit(?);
// extern ? BehOscillatingPendulumLoop(?);
// extern ? BehTreasureChestTopLoop(?);
// extern ? BehTreasureChestBottomInit(?);
// extern ? BehTreasureChestBottomLoop(?);
// extern ? func_802F6E8C(?);
// extern ? BehTreasureChestShipInit(?);
// extern ? BehTreasureChestShipLoop(?);
// extern ? BehTreasureChestJrbInit(?);
// extern ? BehTreasureChestJrbLoop(?);
// extern ? BehTreasureChestInit(?);
// extern ? BehTreasureChestLoop(?);
// extern ? BehMipsInit(?);
// extern ? func_802F7528(?);
// extern ? func_802F76A8(?);
// extern ? func_802F7750(?);
// extern ? func_802F788C(?);
// extern ? func_802F78D8(?);
// extern ? func_802F7984(?);
// extern ? func_802F7A04(?);
// extern ? func_802F7AA4(?);
// extern ? func_802F7BC4(?);
// extern ? func_802F7C48(?);
// extern ? BehMipsLoop(?);
// extern ? BehYoshiInit(?);
// extern ? func_802F7E58(?);
// extern ? func_802F7FA4(?);
// extern ? func_802F818C(?);
// extern ? func_802F82F8(?);
// extern ? func_802F8450(?);
// extern ? func_802F84FC(?);
// extern ? BehYoshiLoop(?);

#endif /* _OBJ_BEHAVIORS_H */
